IF OBJECT_ID (N'dbo.SP_ADMIN_SELECT_SAMPLE_GROUP_LIST_BY_SAMPLE_ORDER', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_ADMIN_SELECT_SAMPLE_GROUP_LIST_BY_SAMPLE_ORDER
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_ADMIN_SELECT_SAMPLE_GROUP_LIST_BY_SAMPLE_ORDER]
	-- Add the parameters for the stored procedure here
	@p_order_seq int
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	SELECT 
	CM.*,
	SGM.TITLE as PROD_TITLE,
	SGM.DESCRIPTION,
	STUFF(
			(
				SELECT ',' + CAST(ISGIM.PROD_SEQ AS NVARCHAR)
				FROM SAMPLE_GROUP_ITEM_MST ISGIM
				WHERE ISGIM.SAMPLE_GROUP_SEQ = SGM.SAMPLE_GROUP_SEQ 
				ORDER BY ISGIM.PROD_SEQ ASC
				FOR XML PATH('')
			)
		, 1, 1, '') AS PROD_SEQ_LIST,
	STUFF(
			(
				SELECT ',' + IPM.PROD_CODE
				FROM SAMPLE_GROUP_ITEM_MST ISGIM
				LEFT JOIN PROD_MST IPM ON ISGIM.PROD_SEQ = IPM.PROD_SEQ
				WHERE ISGIM.SAMPLE_GROUP_SEQ = SGM.SAMPLE_GROUP_SEQ 
				ORDER BY ISGIM.PROD_SEQ ASC
				FOR XML PATH('')
			)
		, 1, 1, '') AS PROD_CODE_LIST,
	STUFF(
			(
				SELECT ',' + IPM.PROD_TITLE
				FROM SAMPLE_GROUP_ITEM_MST ISGIM
				LEFT JOIN PROD_MST IPM ON ISGIM.PROD_SEQ = IPM.PROD_SEQ
				WHERE ISGIM.SAMPLE_GROUP_SEQ = SGM.SAMPLE_GROUP_SEQ 
				ORDER BY ISGIM.PROD_SEQ ASC
				FOR XML PATH('')
			)
		, 1, 1, '') AS PROD_TITLE_LIST
	FROM CART_MST CM
	LEFT JOIN SAMPLE_GROUP_MST SGM ON CM.PROD_SEQ = SGM.SAMPLE_GROUP_SEQ
	WHERE CM.ORDER_SEQ = @p_order_seq
	AND CM.CART_TYPE_CODE = '111002'
	ORDER BY CM.CART_SEQ ASC;
END

GO
