IF OBJECT_ID (N'dbo.SP_ADMIN_SELECT_PRODUCT_DETAIL', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_ADMIN_SELECT_PRODUCT_DETAIL
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_ADMIN_SELECT_PRODUCT_DETAIL]
	-- Add the parameters for the stored procedure here
	@p_prod_seq int
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	SELECT 
	PM.* 
	,PG.GROUP_CODE
	,CATEGORY_CC.DTL_NAME as CATEGORY_NAME
    ,COLOR_CC.DTL_NAME as COLOR_NAME
    ,COLOR_CC.DTL_DESC as COLOR_RGB
    ,KIND_CC.DTL_NAME as KIND_NAME
    ,PRICE_TERM_CC.DTL_NAME as PRICE_TERM_NAME
    ,PRINT_CC.DTL_NAME as PRINT_NAME
    ,SIZE_CC.DTL_NAME as SIZE_NAME
    ,FORMAT_CC.DTL_NAME as FORMAT_NAME
	FROM PROD_MST PM
	LEFT JOIN PROD_GROUP PG ON PM.PROD_SEQ = PG.PROD_SEQ AND PG.TYPE_CODE = '117002'
	LEFT JOIN COMMON_CODE CATEGORY_CC ON CATEGORY_CC.CMMN_CODE = PM.CATEGORY_TYPE_CODE
    LEFT JOIN COMMON_CODE COLOR_CC ON COLOR_CC.CMMN_CODE = PM.COLOR_TYPE_CODE
    LEFT JOIN COMMON_CODE KIND_CC ON KIND_CC.CMMN_CODE = PM.KIND_CODE
    LEFT JOIN COMMON_CODE PRICE_TERM_CC ON PRICE_TERM_CC.CMMN_CODE = PM.PRICE_TERM_TYPE_CODE
    LEFT JOIN COMMON_CODE PRINT_CC ON PRINT_CC.CMMN_CODE = PM.PRINT_TYPE_CODE
    LEFT JOIN COMMON_CODE SIZE_CC ON SIZE_CC.CMMN_CODE = PM.PROD_SIZE_TYPE_CODE
    LEFT JOIN COMMON_CODE FORMAT_CC ON FORMAT_CC.CMMN_CODE = PM.FORMAT_TYPE_CODE
	WHERE PM.PROD_SEQ = @p_prod_seq;
END
GO
