IF OBJECT_ID (N'dbo.SP_SELECT_ORDER_LIST_BY_USER_ID', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_ORDER_LIST_BY_USER_ID
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_SELECT_ORDER_LIST_BY_USER_ID]
	-- Add the parameters for the stored procedure here
	@p_user_id nvarchar(255),
	@p_order_type_code nvarchar(6) = '110001'
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	
	IF(@p_order_type_code IS NULL)
		SET @p_order_type_code = '110001'

    -- Insert statements for procedure here
	SELECT 	
	VOM.*
	,ORDER_STATUS_CC.DTL_NAME AS ORDER_STATUS_TYPE_NAME
	,SHIPPING_TYPE_CC.DTL_NAME AS SHIPPING_TYPE_NAME
	,PAYMENT_TYPE_CC.DTL_NAME AS PAYMENT_TYPE_NAME
	,PAYMENT_STATUS_CC.DTL_NAME AS PAYMENT_STATUS_TYPE_NAME
	FROM
	VW_ORDER_MST VOM
	LEFT JOIN USER_MST UM ON VOM.USER_SEQ = UM.USER_SEQ
	LEFT JOIN COMMON_CODE ORDER_STATUS_CC ON ORDER_STATUS_CC.CMMN_CODE = VOM.ORDER_STATUS_TYPE_CODE
	LEFT JOIN COMMON_CODE SHIPPING_TYPE_CC ON SHIPPING_TYPE_CC.CMMN_CODE = VOM.SHIPPING_TYPE_CODE
	LEFT JOIN COMMON_CODE PAYMENT_TYPE_CC ON PAYMENT_TYPE_CC.CMMN_CODE = VOM.PAYMENT_TYPE_CODE
	LEFT JOIN COMMON_CODE PAYMENT_STATUS_CC ON PAYMENT_STATUS_CC.CMMN_CODE = VOM.PAYMENT_STATUS_CODE
	WHERE UM.USER_ID = @p_user_id AND VOM.ORDER_TYPE_CODE = @p_order_type_code
	ORDER BY VOM.ORDER_DATE DESC;
END


GO
