IF OBJECT_ID (N'dbo.SP_SELECT_ORDER_DETAIL', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_ORDER_DETAIL
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_SELECT_ORDER_DETAIL]
	-- Add the parameters for the stored procedure here
	@p_seq int
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    SELECT 
    VOM.*
	,ORDER_STATUS_CC.DTL_NAME AS ORDER_STATUS_TYPE_NAME
	,SHIPPING_TYPE_CC.DTL_NAME AS SHIPPING_TYPE_NAME
	,PAYMENT_TYPE_CC.DTL_NAME AS PAYMENT_TYPE_NAME
	,PAYMENT_STATUS_CC.DTL_NAME AS PAYMENT_STATUS_TYPE_NAME
    FROM
    VW_ORDER_MST VOM
    LEFT JOIN USER_MST UM ON VOM.USER_SEQ = UM.USER_SEQ
	LEFT JOIN COMMON_CODE ORDER_STATUS_CC ON ORDER_STATUS_CC.CMMN_CODE = VOM.ORDER_STATUS_TYPE_CODE
	LEFT JOIN COMMON_CODE SHIPPING_TYPE_CC ON SHIPPING_TYPE_CC.CMMN_CODE = VOM.SHIPPING_TYPE_CODE
	LEFT JOIN COMMON_CODE PAYMENT_TYPE_CC ON PAYMENT_TYPE_CC.CMMN_CODE = VOM.PAYMENT_TYPE_CODE
	LEFT JOIN COMMON_CODE PAYMENT_STATUS_CC ON PAYMENT_STATUS_CC.CMMN_CODE = VOM.PAYMENT_STATUS_CODE
	WHERE VOM.ORDER_SEQ = @p_seq;
END


GO
