IF OBJECT_ID (N'dbo.SP_SELECT_PRODUCT_DETAIL', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_PRODUCT_DETAIL
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_SELECT_PRODUCT_DETAIL]
	-- Add the parameters for the stored procedure here
	@p_prod_code nvarchar(15)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	
	SELECT 
	PM.*
	,CATEGORY_CC.DTL_NAME AS CATEGORY_NAME,
	KIND_CC.DTL_NAME AS KIND_NAME,
	PRINT_TYPE_CC.DTL_NAME AS PRINT_TYPE_NAME,
	TYPE_CC.DTL_NAME AS TYPE_NAME,
	THEME_CC.DTL_NAME AS THEME_NAME,
	PRICE_TERM_CC.DTL_NAME AS PRICE_TERM_NAME,
	SIZE_CC.DTL_NAME AS SIZE_NAME,
	COLOR_CC.DTL_NAME AS COLOR_NAME,
	COLOR_CC.DTL_DESC AS RGB_VALUE
	FROM PROD_MST PM
	LEFT JOIN COMMON_CODE CATEGORY_CC ON CATEGORY_CC.CMMN_CODE = PM.CATEGORY_TYPE_CODE
	LEFT JOIN COMMON_CODE TYPE_CC ON TYPE_CC.CMMN_CODE = PM.TYPE_CODE
	LEFT JOIN COMMON_CODE KIND_CC ON KIND_CC.CMMN_CODE = PM.KIND_CODE
	LEFT JOIN COMMON_CODE PRINT_TYPE_CC ON PRINT_TYPE_CC.CMMN_CODE = PM.PRINT_TYPE_CODE
	LEFT JOIN COMMON_CODE THEME_CC ON THEME_CC.CMMN_CODE = PM.THEME_TYPE_CODE
	LEFT JOIN COMMON_CODE PRICE_TERM_CC ON PRICE_TERM_CC.CMMN_CODE = PM.PRICE_TERM_TYPE_CODE
	LEFT JOIN COMMON_CODE SIZE_CC ON SIZE_CC.CMMN_CODE = PM.PROD_SIZE_TYPE_CODE
	LEFT JOIN COMMON_CODE COLOR_CC ON COLOR_CC.CMMN_CODE = PM.COLOR_TYPE_CODE
	LEFT JOIN PROD_GROUP PG ON PM.PROD_SEQ = PG.PROD_SEQ AND PG.TYPE_CODE = '117002'
	
	WHERE PM.PROD_CODE = @p_prod_code;
	
END

GO
