IF OBJECT_ID (N'dbo.SP_T_USER_ORDER_AUTO_PRODUCTION_DELETE', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_T_USER_ORDER_AUTO_PRODUCTION_DELETE
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_T_USER_ORDER_AUTO_PRODUCTION_DELETE]
/***************************************************************
작성자	:	표수현
작성일	:	2020-02-15
DESCRIPTION	:	제작중인 전체 주문건중에서 주문일이 30일이 지나면 매일 10분단위로 자동 삭제
SPECIAL LOGIC	:
******************************************************************
MODIFICATION
******************************************************************
수정일           작업자                DESCRIPTION
==================================================================
******************************************************************/
 @ORDER_ID INT = NULL
AS

 SET NOCOUNT ON
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 

  --DROP TABLE #THIRTY_PLUSDAY_LIST
	
 DECLARE @삭제할제작중주문건 INT

 SELECT * INTO 	#THIRTY_PLUSDAY_LIST
 FROM
	 (
			SELECT	ORDER_ID = A.ORDER_ID,
					--ORDER_CODE = A.ORDER_CODE, 
					--A.REGIST_DATETIME,
					--THIRTY_PLUSDAY = DATEADD(DAY, 30, A.REGIST_DATETIME) ,
					----MINUTE_VALUE =  DATEDIFF(MINUTE, DATEADD(DAY, 30, A.REGIST_DATETIME) ,'2021-12-18 10:14:06.640')
					MINUTE_VALUE =  DATEDIFF(MINUTE, DATEADD(DAY, 30, A.REGIST_DATETIME) , GETDATE())--'2021-12-18 10:14:06.640')
			FROM	BARUNSON.DBO.TB_ORDER A INNER JOIN 
					BARUNSON.DBO.VW_USER B ON A.USER_ID = B.USER_ID INNER JOIN 
					BARUNSON.DBO.TB_ORDER_PRODUCT C ON A.ORDER_ID = C.ORDER_ID  INNER JOIN 
					BARUNSON.DBO.TB_PRODUCT D ON C.PRODUCT_ID = D.PRODUCT_ID  INNER JOIN 
					BARUNSON.DBO.TB_TEMPLATE E ON D.TEMPLATE_ID = E.TEMPLATE_ID  INNER JOIN 
					BARUNSON.DBO.TB_COMMON_CODE F ON D.PRODUCT_CATEGORY_CODE = F.CODE  INNER JOIN 
					BARUNSON.DBO.TB_INVITATION G ON A.ORDER_ID = G.ORDER_ID  LEFT JOIN 
					BARUNSON.DBO.TB_INVITATION_DETAIL K ON G.INVITATION_ID =  K.INVITATION_ID
					/*BARUNSON.DBO.TB_COMMON_CODE H ON A.PAYMENT_STATUS_CODE = H.CODE INNER JOIN   
					--BARUNSON.DBO.TB_INVITATION_DETAIL K ON G.INVITATION_ID =  K.INVITATION_ID --INNER JOIN*/ 
					--BARUNSON.DBO.TB_COMMON_CODE P ON A.PAYMENT_METHOD_CODE = P.CODE

			WHERE	--A.USER_ID = 'VYRUDAKS8888' AND
					F.CODE_GROUP = 'PRODUCT_CATEGORY_CODE' AND
					A.ORDER_STATUS_CODE = 'OSC01' AND  --주문완료
					A.PAYMENT_STATUS_CODE = 'PSC01' AND --결제대기 
					A.PAYMENT_METHOD_CODE IS NULL
			GROUP BY A.ORDER_ID, A.ORDER_CODE, F.CODE_NAME, D.PRODUCT_CODE,
					 D.PRODUCT_NAME,  A.REGIST_DATETIME, A.ORDER_PRICE, D.PREVIEW_IMAGE_URL,
					 D.MAIN_IMAGE_URL, C.PRODUCT_ID , A.REGIST_DATETIME, G.INVITATION_ID , F.CODE, A.FINANCE_NAME, --K.INVITATION_DISPLAY_YN,
					 /*H.CODE,K.WEDDINGYY , K.WEDDINGMM, K.WEDDINGDD*/  A.ACCOUNT_NUMBER, A.ORDER_DATETIME, K.MONEYGIFT_REMIT_USE_YN
	 ) TB
 WHERE TB.MINUTE_VALUE > 0

 SELECT @삭제할제작중주문건 = COUNT(1)
 FROM #THIRTY_PLUSDAY_LIST
		
 IF @삭제할제작중주문건 > 0 BEGIN 

 	 UPDATE TB_ORDER  
	 SET TB_ORDER.ORDER_STATUS_CODE= 'OSC02', --주문취소
		 TB_ORDER.UPDATE_DATETIME = GETDATE()
	 WHERE TB_ORDER.ORDER_ID IN (SELECT ORDER_ID FROM  #THIRTY_PLUSDAY_LIST)

 END 
GO
