IF OBJECT_ID (N'dbo.SP_S_USER_PRODUCT_LIST', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_S_USER_PRODUCT_LIST
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_S_USER_PRODUCT_LIST]
/***************************************************************
작성자	:	표수현
작성일	:	2020-02-15
DESCRIPTION	:	프런트 - 상품 리스트 정보 
SPECIAL LOGIC	: SP_S_USER_PRODUCT_LIST  @USER_ID = 'vyrudaks80', @CATEGORY_ID = 97, @SORT_GUBUN = 0
******************************************************************
MODIFICATION 
******************************************************************
수정일           작업자                DESCRIPTION
==================================================================
******************************************************************/
 @USER_ID VARCHAR(50) = NULL,
 @CATEGORY_ID	INT = NULL,
 @SORT_GUBUN INT = NULL,
 @SEARCHBRAND_CODE VARCHAR(10) = NULL
AS

 SET NOCOUNT ON
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

 DECLARE @CONDITION1 INT = 0

 IF @SEARCHBRAND_CODE IS NOT NULL BEGIN  
	SET @CONDITION1 = 1
 END

 -- SELECT * 
 -- FROM (
	--	SELECT	
		
	--	UPDATE_DATETIME = max(B.UPDATE_DATETIME), 
	--			PRICE = max(B.PRICE),
	--			CODE_NAME = max(C.CODE_NAME), 
	--			PRODUCT_BRAND_CODE = max(B.PRODUCT_BRAND_CODE), 
	--			CATEGORY_ID = max(A.CATEGORY_ID), 
	--			PRODUCT_ID = A.PRODUCT_ID, 
	--			MAIN_IMAGE_URL = max(B.MAIN_IMAGE_URL), 
	--			PRODUCT_NAME = max(B.PRODUCT_NAME), 
	--			PRODUCT_CODE = max(B.PRODUCT_CODE),
	--			WISHCNT = (SELECT COUNT(*) FROM TB_WISH_LIST WHERE PRODUCT_ID = max(A.PRODUCT_ID) AND USER_ID = @USER_ID),
	--			TOTALSALE = (SELECT COUNT(*) FROM TB_ORDER P INNER JOIN TB_ORDER_PRODUCT Q ON P.ORDER_ID = Q.ORDER_ID WHERE Q.PRODUCT_ID = max(A.PRODUCT_ID)),
	--			SORT = max(A.SORT)
	--	FROM	TB_PRODUCT_CATEGORY A INNER JOIN 
	--			TB_PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID INNER JOIN 
	--			TB_COMMON_CODE C ON B.PRODUCT_BRAND_CODE = C.CODE
	--	WHERE CATEGORY_ID IN (SELECT CATEGORY_ID FROM TB_CATEGORY WHERE CATEGORY_ID = @CATEGORY_ID OR PARENT_CATEGORY_ID =  @CATEGORY_ID ) AND
	--		  C.CODE= (CASE WHEN @CONDITION1 = 1 THEN @SEARCHBRAND_CODE ELSE C.CODE END) 
	--	group by A.PRODUCT_ID

	--  ) TB
 --ORDER BY   CASE WHEN @SORT_GUBUN = 0  THEN TB.SORT END ASC,  
	--		CASE WHEN @SORT_GUBUN = 1  THEN TB.UPDATE_DATETIME END ASC,  
	--		CASE WHEN @SORT_GUBUN = 2 THEN TB.TOTALSALE  END ASC  ,
	--		CASE WHEN @SORT_GUBUN = 3  THEN TB.PRICE END ASC  ,
	--		CASE WHEN @SORT_GUBUN = 4  THEN TB.PRICE  END DESC 

  SELECT * 
  FROM (
		SELECT	B.UPDATE_DATETIME, 
				B.PRICE,
				C.CODE_NAME, B.PRODUCT_BRAND_CODE, A.CATEGORY_ID, A.PRODUCT_ID, 
				B.MAIN_IMAGE_URL, 
				B.PRODUCT_NAME, 
				B.PRODUCT_CODE,
				WISHCNT = (SELECT COUNT(*) FROM TB_WISH_LIST WHERE PRODUCT_ID = A.PRODUCT_ID AND USER_ID = @USER_ID),
				TOTALSALE = (SELECT COUNT(*) FROM TB_ORDER P INNER JOIN TB_ORDER_PRODUCT Q ON P.ORDER_ID = Q.ORDER_ID WHERE Q.PRODUCT_ID = A.PRODUCT_ID),
				SORT = A.SORT
		FROM	TB_PRODUCT_CATEGORY A INNER JOIN 
				TB_PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID INNER JOIN 
				TB_COMMON_CODE C ON B.PRODUCT_BRAND_CODE = C.CODE
		WHERE CATEGORY_ID IN (SELECT CATEGORY_ID FROM TB_CATEGORY WHERE CATEGORY_ID = @CATEGORY_ID OR PARENT_CATEGORY_ID =  @CATEGORY_ID ) AND
			  C.CODE= (CASE WHEN @CONDITION1 = 1 THEN @SEARCHBRAND_CODE ELSE C.CODE END)
	  ) TB
 ORDER BY   CASE WHEN @SORT_GUBUN = 0  THEN TB.SORT END ASC,  
			CASE WHEN @SORT_GUBUN = 1  THEN TB.UPDATE_DATETIME END ASC,  
			CASE WHEN @SORT_GUBUN = 2 THEN TB.TOTALSALE  END ASC  ,
			CASE WHEN @SORT_GUBUN = 3  THEN TB.PRICE END ASC  ,
			CASE WHEN @SORT_GUBUN = 4  THEN TB.PRICE  END DESC 
			

/**** 아이콘 리스트 *************/
 SELECT	A.Product_ID,ICON_URL FROM 
		TB_PRODUCT_ICON A INNER JOIN 
		TB_ICON B ON A.ICON_ID = B.ICON_ID
 WHERE A.PRODUCT_ID IN(

SELECT	A.PRODUCT_ID
FROM	TB_PRODUCT_CATEGORY A INNER JOIN 
	TB_PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID INNER JOIN 
	TB_COMMON_CODE C ON B.PRODUCT_BRAND_CODE = C.CODE
WHERE CATEGORY_ID IN (SELECT CATEGORY_ID FROM TB_CATEGORY WHERE CATEGORY_ID = @CATEGORY_ID OR PARENT_CATEGORY_ID =  @CATEGORY_ID ) AND
C.CODE= (CASE WHEN @CONDITION1 = 1 THEN @SEARCHBRAND_CODE ELSE C.CODE END)
	)
GO
