IF OBJECT_ID (N'dbo.SP_S_USER_PAY_STATUS', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_S_USER_PAY_STATUS
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_S_USER_PAY_STATUS]
/***************************************************************
작성자	:	표수현
작성일	:	2020-02-15
DESCRIPTION	:	마이페이지 - 제작중 / 제작완료 정보 조회
SPECIAL LOGIC	: SP_S_USER_PAY_STATUS 'U',3, 'VYRUDAKS00'
******************************************************************
MODIFICATION
******************************************************************
수정일           작업자                DESCRIPTION
==================================================================
******************************************************************/
 @GUBUN CHAR(1) = 'U',  -- U : 회원 / G : 비회원
 @GUBUN2 INT = 1,		-- 1: 제작중 / 2: 제작완료 / 3: 취소/환불
 @USER_ID VARCHAR(50) = NULL,
 @USER_NAME VARCHAR(100) = NULL,
 @USER_EMAIL VARCHAR(100) = NULL
AS

 SET NOCOUNT ON
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

 /* 임시 */
 --UPDATE BARUNSON.DBO.TB_ORDER
 --SET PG_ID = ORDER_CODE
 --WHERE USER_ID = @USER_ID
 
-- insert tb_test22(GUBUN,
--GUBUN2,
--USER_ID,
--USER_NAME,
--USER_EMAIL)
--values (@GUBUN, @GUBUN2, @USER_ID, @USER_NAME, @USER_EMAIL)


 IF @GUBUN = 'U' BEGIN
 

	IF @GUBUN2 = 1 BEGIN 

	-- 마이페이지(회원) - 제작중  리스트 
		SELECT	ORDER_ID = A.ORDER_ID,
				ORDER_CODE = A.ORDER_CODE, 
				PRODUCT_CATEGORY = F.CODE_NAME,
				PRODUCT_CODE = D.PRODUCT_CODE,
				PRODUCT_NAME = D.PRODUCT_NAME,
				REGIST_DATETIME = A.REGIST_DATETIME,
				ORDER_PRICE = A.ORDER_PRICE,
				PREVIEW_IMAGE_URL = D.PREVIEW_IMAGE_URL,
				MAIN_IMAGE_URL = D.MAIN_IMAGE_URL,
				PRODUCT_ID = C.PRODUCT_ID,
				PRODUCT_CODE2 = CASE  F.CODE  WHEN 'PCC01' THEN 'MCARD' WHEN 'PCC02'  THEN 'MTHANKS' END ,
				INVITATION_ID = G.INVITATION_ID,
				FINANCE_NAME = A.FINANCE_NAME,
				INVITATION_DISPLAY_YN = 'Y', --K.INVITATION_DISPLAY_YN,
				PAYMENT_STATUS_CODE = '',--,H.CODE,
				WeddingYY = '',--K.WeddingYY,
				WeddingMM = '',--K.WeddingMM,
				WeddingDD = '',--K.WeddingDD,
				Payment_Method_Name = '',
				Account_Number = A.Account_Number,
				Order_DateTime = A.Order_DateTime,
				Account_Count = (select count(1) from TB_Account where Invitation_ID = G.Invitation_ID),
				MoneyGift_Remit_Use_YN = ISNULL(K.MoneyGift_Remit_Use_YN, 'N')
		FROM	BARUNSON.DBO.TB_ORDER A INNER JOIN 
				BARUNSON.DBO.VW_USER B ON A.USER_ID = B.USER_ID INNER JOIN 
				BARUNSON.DBO.TB_ORDER_PRODUCT C ON A.ORDER_ID = C.ORDER_ID  INNER JOIN 
				BARUNSON.DBO.TB_PRODUCT D ON C.PRODUCT_ID = D.PRODUCT_ID  INNER JOIN 
				BARUNSON.DBO.TB_TEMPLATE E ON D.TEMPLATE_ID = E.TEMPLATE_ID  INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE F ON D.PRODUCT_CATEGORY_CODE = F.CODE  INNER JOIN 
				BARUNSON.DBO.TB_INVITATION G ON A.ORDER_ID = G.ORDER_ID  LEFT JOIN 
				BARUNSON.DBO.TB_Invitation_Detail K ON G.Invitation_ID =  K.Invitation_ID
				/*BARUNSON.DBO.TB_COMMON_CODE H ON A.PAYMENT_STATUS_CODE = H.CODE INNER JOIN   
				--BARUNSON.DBO.TB_Invitation_Detail K ON G.Invitation_ID =  K.Invitation_ID --INNER JOIN*/ 
				--BARUNSON.DBO.TB_COMMON_CODE P on A.Payment_Method_Code = P.Code

		WHERE	A.USER_ID = @USER_ID  -- AND A.NAME = @USER_NAME 
				AND
				F.CODE_GROUP = 'PRODUCT_CATEGORY_CODE' AND
				A.ORDER_STATUS_CODE = 'OSC01' AND  --주문완료
				A.PAYMENT_STATUS_CODE = 'PSC01' --and --결제대기 AND
				--P.Code_Group = 'Payment_Method_Code'  
		GROUP BY A.ORDER_ID, A.ORDER_CODE, F.CODE_NAME, D.PRODUCT_CODE,
				 D.PRODUCT_NAME,  A.REGIST_DATETIME, A.ORDER_PRICE, D.PREVIEW_IMAGE_URL,
				 D.MAIN_IMAGE_URL, C.PRODUCT_ID , A.REGIST_DATETIME, G.INVITATION_ID , F.CODE, A.FINANCE_NAME, --K.INVITATION_DISPLAY_YN,
				 /*H.CODE,K.WeddingYY , K.WeddingMM, K.WeddingDD*/  A.Account_Number, A.Order_DateTime, K.MoneyGift_Remit_Use_YN
		ORDER BY A.REGIST_DATETIME DESC

	END ELSE IF @GUBUN2 = 2 BEGIN 

		-- 마이페이지(회원) - 제작완료  리스트 
		SELECT	ORDER_ID = A.ORDER_ID,
				ORDER_CODE = A.ORDER_CODE, 
				PRODUCT_CATEGORY = F.CODE_NAME,
				PRODUCT_CODE = D.PRODUCT_CODE,
				PRODUCT_NAME = D.PRODUCT_NAME,
				REGIST_DATETIME = A.REGIST_DATETIME,
				ORDER_PRICE = ISNULL(A.PAYMENT_PRICE, 0),
				PREVIEW_IMAGE_URL = D.PREVIEW_IMAGE_URL,
				MAIN_IMAGE_URL = D.MAIN_IMAGE_URL,
				PRODUCT_ID = C.PRODUCT_ID,
				PRODUCT_CODE2 = CASE  F.CODE  WHEN 'PCC01' THEN 'MCARD' WHEN 'PCC02'  THEN 'MTHANKS' END ,
				INVITATION_ID = G.INVITATION_ID,
				FINANCE_NAME = A.FINANCE_NAME,
				INVITATION_DISPLAY_YN = K.INVITATION_DISPLAY_YN,
				WeddingYY = K.WeddingYY,
				WeddingMM = K.WeddingMM,
				WeddingDD = K.WeddingDD,
				PAYMENT_STATUS_CODE = H.CODE,
				Payment_Method_Name = P.Code_Name,
				Account_Number = A.Account_Number,
				Order_DateTime = A.Order_DateTime,
				Account_Count = (select count(1) from TB_Account where Invitation_ID = G.Invitation_ID),
				K.MoneyGift_Remit_Use_YN
		FROM	BARUNSON.DBO.TB_ORDER A INNER JOIN 
				BARUNSON.DBO.VW_USER B ON A.USER_ID = B.USER_ID  INNER JOIN 
				BARUNSON.DBO.TB_ORDER_PRODUCT C ON A.ORDER_ID = C.ORDER_ID  INNER JOIN 
				BARUNSON.DBO.TB_PRODUCT D ON C.PRODUCT_ID = D.PRODUCT_ID  INNER JOIN 
				BARUNSON.DBO.TB_TEMPLATE E ON D.TEMPLATE_ID = E.TEMPLATE_ID INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE F ON D.PRODUCT_CATEGORY_CODE = F.CODE INNER JOIN 
				BARUNSON.DBO.TB_INVITATION G ON A.ORDER_ID = G.ORDER_ID  INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE H ON A.PAYMENT_STATUS_CODE = H.CODE INNER JOIN   
				BARUNSON.DBO.TB_Invitation_Detail K ON G.Invitation_ID =  K.Invitation_ID INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE P on A.Payment_Method_Code = P.Code
		WHERE	A.USER_ID = @USER_ID  -- AND A.NAME = @USER_NAME
				AND 
				A.ORDER_STATUS_CODE = 'OSC01' AND  --주문완료
				A.PAYMENT_STATUS_CODE IN ('PSC02' , 'PSC04') and --결제완료 / 입금대기 
				P.Code_Group = 'Payment_Method_Code'
		GROUP BY A.ORDER_ID, A.ORDER_CODE, F.CODE_NAME, D.PRODUCT_CODE,
				 D.PRODUCT_NAME,  A.REGIST_DATETIME, A.PAYMENT_PRICE, D.PREVIEW_IMAGE_URL,
				 D.MAIN_IMAGE_URL, C.PRODUCT_ID, A.REGIST_DATETIME,G.INVITATION_ID  , F.CODE, A.FINANCE_NAME , K.INVITATION_DISPLAY_YN,
				 H.CODE, K.WeddingYY , K.WeddingMM, K.WeddingDD, P.Code_Name, A.Account_Number, A.Order_DateTime, K.MoneyGift_Remit_Use_YN
		ORDER BY A.REGIST_DATETIME DESC

	END ELSE BEGIN 
		
		-- 마이페이지(회원) - 취소/환불

		SELECT	ORDER_ID = A.ORDER_ID,
				ORDER_CODE = A.ORDER_CODE, 
				PRODUCT_CATEGORY = F.CODE_NAME,
				PRODUCT_CODE = D.PRODUCT_CODE,
				PRODUCT_NAME = D.PRODUCT_NAME,
				REGIST_DATETIME = A.REGIST_DATETIME,
				ORDER_PRICE = case H.CODE when 'RTC04' then 0
							 else ISNULL(A.PAYMENT_PRICE, A.ORDER_PRICE) end,
				
				
				PREVIEW_IMAGE_URL = D.PREVIEW_IMAGE_URL,
				MAIN_IMAGE_URL = D.MAIN_IMAGE_URL,
				PRODUCT_ID = C.PRODUCT_ID,
				INVITATION_ID = I.INVITATION_ID,
				REFUND_REGIST_DATETIME = G.REGIST_DATETIME,
				PAY_CODE = H.CODE,
				FINANCE_NAME = A.FINANCE_NAME,
				INVITATION_DISPLAY_YN = K.INVITATION_DISPLAY_YN,
				PAYMENT_STATUS_CODE =J.CODE,
				WeddingYY = K.WeddingYY,
				WeddingMM = K.WeddingMM,
				WeddingDD = K.WeddingDD,
				Payment_Method_Name = P.Code_Name,
				Account_Number = A.Account_Number,
				Order_DateTime = A.Order_DateTime,
				Q.Code,
				Q.Code_Name,
				Account_Count = 0,
				MoneyGift_Remit_Use_YN = 'N'
		FROM	BARUNSON.DBO.TB_ORDER A INNER JOIN 
				BARUNSON.DBO.VW_USER B ON A.USER_ID = B.USER_ID  INNER JOIN 
				BARUNSON.DBO.TB_ORDER_PRODUCT C ON A.ORDER_ID = C.ORDER_ID  INNER JOIN 
				BARUNSON.DBO.TB_PRODUCT D ON C.PRODUCT_ID = D.PRODUCT_ID  INNER JOIN 
				BARUNSON.DBO.TB_TEMPLATE E ON D.TEMPLATE_ID = E.TEMPLATE_ID INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE F ON D.PRODUCT_CATEGORY_CODE = F.CODE  INNER JOIN 
				BARUNSON.DBO.TB_REFUND_INFO G ON A.ORDER_ID = G.ORDER_ID  INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE H ON G.REFUND_TYPE_CODE = H.CODE INNER JOIN 
				BARUNSON.DBO.TB_INVITATION I ON A.ORDER_ID = I.ORDER_ID INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE J ON A.PAYMENT_STATUS_CODE = J.CODE INNER JOIN   
				BARUNSON.DBO.TB_Invitation_Detail K ON I.Invitation_ID =  K.Invitation_ID INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE P on A.Payment_Method_Code = P.Code INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE Q ON G.REFUND_STATUS_CODE = Q.CODE 

		WHERE	A.USER_ID = @USER_ID   --AND A.NAME = @USER_NAME
				AND 
				(
					G.REFUND_STATUS_CODE = 'RSC01' OR  --환불신청
					G.REFUND_STATUS_CODE ='RSC02' OR  --환불완료
					G.REFUND_STATUS_CODE = 'RSC04' OR--취소완료
					G.REFUND_STATUS_CODE = 'RSC05' --입금대기취소완료
				) and
				P.Code_Group = 'Payment_Method_Code'
		GROUP BY A.ORDER_ID, A.ORDER_CODE, F.CODE_NAME, D.PRODUCT_CODE,
				 D.PRODUCT_NAME,  A.ORDER_DATETIME, A.PAYMENT_PRICE,
				 D.PREVIEW_IMAGE_URL, D.MAIN_IMAGE_URL,  C.PRODUCT_ID,
				 G.REGIST_DATETIME,  H.CODE, A.ORDER_PRICE, A.REGIST_DATETIME, I.INVITATION_ID, A.FINANCE_NAME , K.INVITATION_DISPLAY_YN,
				 J.CODE, K.WeddingYY , K.WeddingMM, K.WeddingDD, P.Code_Name, A.Account_Number,  Q.Code,Q.Code_Name
		ORDER BY A.REGIST_DATETIME DESC	 

	END 

	--SELECT	COUNT(CASE  WHEN PAYMENT_STATUS_CODE = 'PSC01' /*OR PAYMENT_STATUS_CODE = 'PSC05'*/ THEN 1 END) AS 제작중,
	--		COUNT(CASE  WHEN PAYMENT_STATUS_CODE = 'PSC02' OR PAYMENT_STATUS_CODE = 'PSC04' /*OR PAYMENT_STATUS_CODE = 'PSC04'*/ THEN 1 END) AS 완료
	--FROM	BARUNSON.DBO.TB_ORDER A INNER JOIN 
	--		BARUNSON.DBO.VW_USER B ON A.USER_ID = B.USER_ID INNER JOIN 
	--		BARUNSON.DBO.TB_ORDER_PRODUCT C ON A.ORDER_ID = C.ORDER_ID  INNER JOIN 
	--		BARUNSON.DBO.TB_PRODUCT D ON C.PRODUCT_ID = D.PRODUCT_ID  INNER JOIN 
	--		BARUNSON.DBO.TB_TEMPLATE E ON D.TEMPLATE_ID = E.TEMPLATE_ID  INNER JOIN 
	--		BARUNSON.DBO.TB_COMMON_CODE F ON D.PRODUCT_CATEGORY_CODE = F.CODE 
	--WHERE	A.USER_ID = @USER_ID

	--SELECT	COUNT(CASE  WHEN G.REFUND_STATUS_CODE = 'RSC01' OR G.REFUND_STATUS_CODE ='RSC02' OR G.REFUND_STATUS_CODE = 'RSC04' THEN 1 END) AS 취소환불
	--FROM	BARUNSON.DBO.TB_ORDER A INNER JOIN 
	--		BARUNSON.DBO.VW_USER B ON A.USER_ID = B.USER_ID INNER JOIN 
	--		BARUNSON.DBO.TB_ORDER_PRODUCT C ON A.ORDER_ID = C.ORDER_ID  INNER JOIN 
	--		BARUNSON.DBO.TB_PRODUCT D ON C.PRODUCT_ID = D.PRODUCT_ID  INNER JOIN 
	--		BARUNSON.DBO.TB_TEMPLATE E ON D.TEMPLATE_ID = E.TEMPLATE_ID  INNER JOIN 
	--		BARUNSON.DBO.TB_COMMON_CODE F ON D.PRODUCT_CATEGORY_CODE = F.CODE  INNER JOIN 
	--		BARUNSON.DBO.TB_REFUND_INFO G ON A.ORDER_ID = G.ORDER_ID
	--WHERE	A.USER_ID = @USER_ID

	
 END ELSE BEGIN

	IF @GUBUN2 = 1 BEGIN 
		
		-- 마이페이지(비회원) - 제작중  리스트
		SELECT	ORDER_ID = A.ORDER_ID,
				ORDER_CODE = A.ORDER_CODE, 
				PRODUCT_CATEGORY = F.CODE_NAME,
				PRODUCT_CODE = D.PRODUCT_CODE,
				PRODUCT_NAME = D.PRODUCT_NAME,
				REGIST_DATETIME = A.REGIST_DATETIME,
				ORDER_PRICE = A.ORDER_PRICE,
				PREVIEW_IMAGE_URL = D.PREVIEW_IMAGE_URL,
				MAIN_IMAGE_URL = D.MAIN_IMAGE_URL,
				PRODUCT_ID = C.PRODUCT_ID,
				INVITATION_ID = G.INVITATION_ID,
				FINANCE_NAME = A.FINANCE_NAME,
				PRODUCT_CODE2 = CASE  F.CODE  WHEN 'PCC01' THEN 'MCARD' WHEN 'PCC02'  THEN 'MTHANKS' END ,
				INVITATION_DISPLAY_YN = 'Y', --K.INVITATION_DISPLAY_YN,
				PAYMENT_STATUS_CODE = '',--J.CODE,
				WeddingYY = '', --K.WeddingYY,
				WeddingMM = '', --K.WeddingMM,
				WeddingDD = '', --K.WeddingDD,
				Payment_Method_Name = '',
				Account_Number = A.Account_Number,
				Payment_Method_Name = '',
				Order_DateTime = A.Order_DateTime,
				Account_Count = (select count(1) from TB_Account where Invitation_ID = G.Invitation_ID),
				MoneyGift_Remit_Use_YN = ISNULL(K.MoneyGift_Remit_Use_YN, 'N')
		FROM	BARUNSON.DBO.TB_ORDER A  INNER JOIN 
				BARUNSON.DBO.TB_ORDER_PRODUCT C ON A.ORDER_ID = C.ORDER_ID  INNER JOIN 
				BARUNSON.DBO.TB_PRODUCT D ON C.PRODUCT_ID = D.PRODUCT_ID  INNER JOIN 
				BARUNSON.DBO.TB_TEMPLATE E ON D.TEMPLATE_ID = E.TEMPLATE_ID INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE F ON D.PRODUCT_CATEGORY_CODE = F.CODE  INNER JOIN 
				BARUNSON.DBO.TB_INVITATION G ON A.ORDER_ID = G.ORDER_ID LEFT JOIN
				BARUNSON.DBO.TB_Invitation_Detail K ON G.Invitation_ID =  K.Invitation_ID
				--BARUNSON.DBO.TB_COMMON_CODE J ON A.PAYMENT_STATUS_CODE = J.CODE INNER JOIN   
				--BARUNSON.DBO.TB_Invitation_Detail K ON G.Invitation_ID =  K.Invitation_ID -- INNER JOIN 
				--BARUNSON.DBO.TB_COMMON_CODE P on A.Payment_Method_Code = P.Code
		WHERE	NAME = @USER_NAME AND 
				F.CODE_GROUP = 'PRODUCT_CATEGORY_CODE' AND
				EMAIL = @USER_EMAIL AND
				ORDER_STATUS_CODE = 'OSC01' AND  --주문완료	
				PAYMENT_STATUS_CODE = 'PSC01' --결제대기
				and (A.User_ID = '' OR A.User_ID is null)
		GROUP BY A.ORDER_ID, A.ORDER_CODE, F.CODE_NAME, D.PRODUCT_CODE,
				 D.PRODUCT_NAME,  A.REGIST_DATETIME, A.ORDER_PRICE, D.PREVIEW_IMAGE_URL,
				 D.MAIN_IMAGE_URL, C.PRODUCT_ID, A.REGIST_DATETIME, G.INVITATION_ID  , F.CODE, A.FINANCE_NAME, --K.INVITATION_DISPLAY_YN,
				 /*J.CODE,  K.WeddingYY , K.WeddingMM, K.WeddingDD*/ A.Account_Number,  A.Order_DateTime, K.MoneyGift_Remit_Use_YN
		ORDER BY A.REGIST_DATETIME DESC

	END ELSE IF  @GUBUN2 = 2 BEGIN 
	
		-- 마이페이지(비회원) - 제작완료  리스트 
		SELECT	ORDER_ID = A.ORDER_ID,
				ORDER_CODE = A.ORDER_CODE, 
				PRODUCT_CATEGORY = F.CODE_NAME,
				PRODUCT_CODE = D.PRODUCT_CODE,
				PRODUCT_NAME = D.PRODUCT_NAME,
				REGIST_DATETIME = A.REGIST_DATETIME,
				ORDER_PRICE = ISNULL(A.PAYMENT_PRICE,0),
				PREVIEW_IMAGE_URL = D.PREVIEW_IMAGE_URL,
				MAIN_IMAGE_URL = D.MAIN_IMAGE_URL,
				PRODUCT_ID = C.PRODUCT_ID,
				INVITATION_ID = G.INVITATION_ID,
				PRODUCT_CODE2 = CASE  F.CODE  WHEN 'PCC01' THEN 'MCARD' WHEN 'PCC02'  THEN 'MTHANKS' END ,
				FINANCE_NAME = A.FINANCE_NAME,
				INVITATION_DISPLAY_YN = K.INVITATION_DISPLAY_YN,
				PAYMENT_STATUS_CODE =J.CODE,
				WeddingYY = K.WeddingYY,
				WeddingMM = K.WeddingMM,
				WeddingDD = K.WeddingDD,
				Payment_Method_Name = P.Code_Name,
				Account_Number = A.Account_Number,
				Order_DateTime = A.Order_DateTime,
				Account_Count = (select count(1) from TB_Account where Invitation_ID = G.Invitation_ID),
				K.MoneyGift_Remit_Use_YN
		FROM	BARUNSON.DBO.TB_ORDER  A  INNER JOIN 
				BARUNSON.DBO.TB_ORDER_PRODUCT C ON A.ORDER_ID = C.ORDER_ID  INNER JOIN 
				BARUNSON.DBO.TB_PRODUCT D ON C.PRODUCT_ID = D.PRODUCT_ID  INNER JOIN 
				BARUNSON.DBO.TB_TEMPLATE E ON D.TEMPLATE_ID = E.TEMPLATE_ID INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE F ON D.PRODUCT_CATEGORY_CODE = F.CODE INNER JOIN 
				BARUNSON.DBO.TB_INVITATION G ON A.ORDER_ID = G.ORDER_ID  INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE J ON A.PAYMENT_STATUS_CODE = J.CODE INNER JOIN   
				BARUNSON.DBO.TB_Invitation_Detail K ON G.Invitation_ID =  K.Invitation_ID INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE P on A.Payment_Method_Code = P.Code

		WHERE	NAME = @USER_NAME AND 
				EMAIL = @USER_EMAIL AND
				ORDER_STATUS_CODE = 'OSC01' AND  --주문완료
				PAYMENT_STATUS_CODE IN ('PSC02' , 'PSC04') and--결제완료 / 입금대기 
				P.Code_Group = 'Payment_Method_Code'
				and (A.User_ID = '' OR A.User_ID is null)
		GROUP BY A.ORDER_ID, A.ORDER_CODE, F.CODE_NAME, D.PRODUCT_CODE,
				 D.PRODUCT_NAME,  A.REGIST_DATETIME, A.ORDER_PRICE, D.PREVIEW_IMAGE_URL,
				 D.MAIN_IMAGE_URL, C.PRODUCT_ID, A.REGIST_DATETIME, G.INVITATION_ID  , F.CODE, A.FINANCE_NAME, K.INVITATION_DISPLAY_YN,
				 J.CODE, K.WeddingYY , K.WeddingMM, K.WeddingDD, P.Code_Name, A.Account_Number,A.Order_DateTime ,A.PAYMENT_PRICE, K.MoneyGift_Remit_Use_YN
		ORDER BY A.REGIST_DATETIME DESC

	END ELSE BEGIN 

	  -- 마이페이지(비회원) - 취소/환불

	  		SELECT	ORDER_ID = A.ORDER_ID,
				ORDER_CODE = A.ORDER_CODE, 
				PRODUCT_CATEGORY = F.CODE_NAME,
				PRODUCT_CODE = D.PRODUCT_CODE,
				PRODUCT_NAME = D.PRODUCT_NAME,
				REGIST_DATETIME = A.REGIST_DATETIME,
				ORDER_PRICE = CASE H.CODE WHEN 'RTC04' THEN 0 ELSE ISNULL(A.PAYMENT_PRICE, A.ORDER_PRICE) END,
				--ORDER_PRICE = ISNULL(A.PAYMENT_PRICE, A.ORDER_PRICE),
				IMAGE_URL = D.PREVIEW_IMAGE_URL, --E.PREVIEW_IMAGE_URL 
				PREVIEW_IMAGE_URL = D.PREVIEW_IMAGE_URL,
				MAIN_IMAGE_URL = D.MAIN_IMAGE_URL,
				PRODUCT_ID = C.PRODUCT_ID,
				REFUND_REGIST_DATETIME = G.REGIST_DATETIME,
				PAY_CODE = H.CODE,
				INVITATION_ID = I.INVITATION_ID,
				FINANCE_NAME = A.FINANCE_NAME,
				INVITATION_DISPLAY_YN = K.INVITATION_DISPLAY_YN,
				PAYMENT_STATUS_CODE =J.CODE,
				WeddingYY = K.WeddingYY,
				WeddingMM = K.WeddingMM,
				WeddingDD = K.WeddingDD,
				Payment_Method_Name = P.Code_Name,
				Account_Number = A.Account_Number,
				Order_DateTime = A.Order_DateTime,
				Q.Code,
				Q.Code_Name,
				Account_Count = 0,
				MoneyGift_Remit_Use_YN = 'N'
		FROM	BARUNSON.DBO.TB_ORDER  A  INNER JOIN 
				BARUNSON.DBO.TB_ORDER_PRODUCT C ON A.ORDER_ID = C.ORDER_ID  INNER JOIN 
				BARUNSON.DBO.TB_PRODUCT D ON C.PRODUCT_ID = D.PRODUCT_ID  INNER JOIN 
				BARUNSON.DBO.TB_TEMPLATE E ON D.TEMPLATE_ID = E.TEMPLATE_ID INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE F ON D.PRODUCT_CATEGORY_CODE = F.CODE INNER JOIN 
				BARUNSON.DBO.TB_REFUND_INFO G ON A.ORDER_ID = G.ORDER_ID  INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE H ON G.REFUND_TYPE_CODE = H.CODE INNER JOIN 
				BARUNSON.DBO.TB_INVITATION I ON A.ORDER_ID = I.ORDER_ID  INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE J ON A.PAYMENT_STATUS_CODE = J.CODE INNER JOIN   
				BARUNSON.DBO.TB_Invitation_Detail K ON I.Invitation_ID =  K.Invitation_ID INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE P on A.Payment_Method_Code = P.Code INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE Q ON G.REFUND_STATUS_CODE = Q.CODE 
		WHERE	NAME = @USER_NAME AND 
				EMAIL = @USER_EMAIL AND
				(
					G.REFUND_STATUS_CODE = 'RSC01' OR  --환불신청
					G.REFUND_STATUS_CODE ='RSC02' OR  --환불완료
					G.REFUND_STATUS_CODE = 'RSC04' OR --취소완료
					G.REFUND_STATUS_CODE = 'RSC05' --입금대기취소완료
				) and P.Code_Group = 'Payment_Method_Code'
				and (A.User_ID = '' OR A.User_ID is null)
		GROUP BY A.ORDER_ID, A.ORDER_CODE, F.CODE_NAME, D.PRODUCT_CODE,
				 D.PRODUCT_NAME,  A.ORDER_DATETIME, A.PAYMENT_PRICE,
				 D.PREVIEW_IMAGE_URL, D.MAIN_IMAGE_URL,  C.PRODUCT_ID,
				 A.REGIST_DATETIME, H.CODE, G.REGIST_DATETIME, A.ORDER_PRICE , A.REGIST_DATETIME, I.INVITATION_ID, A.FINANCE_NAME, K.INVITATION_DISPLAY_YN,
				 J.CODE, K.WeddingYY , K.WeddingMM, K.WeddingDD, P.Code_Name, A.Account_Number,	Q.Code,
				Q.Code_Name
		ORDER BY A.REGIST_DATETIME DESC

	END 
 

 END 

GO
