IF OBJECT_ID (N'dbo.SP_S_USER_Order_List', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_S_USER_Order_List
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_S_USER_Order_List]
/***************************************************************
작성자	:	표수현
작성일	:	2020-02-15
DESCRIPTION	:	1대1 문의 - 주문완료리스트 조회 
SPECIAL LOGIC	: SP_S_USER_PAY_STATUS 'U',1, 'VYRUDAKS9876'
******************************************************************
MODIFICATION
******************************************************************
수정일           작업자                DESCRIPTION
==================================================================
******************************************************************/
 @GUBUN CHAR(1) = 'U',  -- U : 회원 / G : 비회원
 --@GUBUN2 INT = 1,		-- 1: 제작중 / 2: 제작완료 / 3: 취소/환불
 @USER_ID VARCHAR(50) = NULL,
 @USER_NAME VARCHAR(100) = NULL,
 @USER_EMAIL VARCHAR(100) = NULL,
 @ORDER_CODE VARCHAR(20) = ''
AS

 SET NOCOUNT ON
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

 /* 임시 */
 --UPDATE BARUNSON.DBO.TB_ORDER
 --SET PG_ID = ORDER_CODE
 --WHERE USER_ID = @USER_ID


 IF @GUBUN = 'U' BEGIN
 
	IF @ORDER_CODE <> '' BEGIN 
		-- 마이페이지(회원) - 제작완료  리스트 
		SELECT	ORDER_ID = A.ORDER_ID,
			ORDER_CODE = A.ORDER_CODE, 
			PRODUCT_CATEGORY = F.CODE_NAME,
			PRODUCT_CODE = D.PRODUCT_CODE,
			PRODUCT_NAME = D.PRODUCT_NAME,
			REGIST_DATETIME = A.REGIST_DATETIME,
			ORDER_PRICE = isnull(A.PAYMENT_PRICE, 0),
			PREVIEW_IMAGE_URL = D.PREVIEW_IMAGE_URL,
			MAIN_IMAGE_URL = D.MAIN_IMAGE_URL,
			PRODUCT_ID = C.PRODUCT_ID,
			PRODUCT_CODE2 = CASE  F.CODE  WHEN 'PCC01' THEN 'MCARD' WHEN 'PCC02'  THEN 'MTHANKS' END ,
			INVITATION_ID = G.INVITATION_ID,
			FINANCE_NAME = A.FINANCE_NAME,
			INVITATION_DISPLAY_YN = K.INVITATION_DISPLAY_YN,
			WEDDINGYY = K.WEDDINGYY,
			WEDDINGMM = K.WEDDINGMM,
			WEDDINGDD = K.WEDDINGDD,
			PAYMENT_STATUS_CODE = H.CODE,
			PAYMENT_METHOD_NAME = P.CODE_NAME,
			ACCOUNT_NUMBER = A.ACCOUNT_NUMBER,
			ORDER_DATETIME = A.ORDER_DATETIME
	FROM	BARUNSON.DBO.TB_ORDER A INNER JOIN 
			BARUNSON.DBO.VW_USER B ON A.USER_ID = B.USER_ID  INNER JOIN 
			BARUNSON.DBO.TB_ORDER_PRODUCT C ON A.ORDER_ID = C.ORDER_ID  INNER JOIN 
			BARUNSON.DBO.TB_PRODUCT D ON C.PRODUCT_ID = D.PRODUCT_ID  INNER JOIN 
			BARUNSON.DBO.TB_TEMPLATE E ON D.TEMPLATE_ID = E.TEMPLATE_ID INNER JOIN 
			BARUNSON.DBO.TB_COMMON_CODE F ON D.PRODUCT_CATEGORY_CODE = F.CODE INNER JOIN 
			BARUNSON.DBO.TB_INVITATION G ON A.ORDER_ID = G.ORDER_ID  INNER JOIN 
			BARUNSON.DBO.TB_COMMON_CODE H ON A.PAYMENT_STATUS_CODE = H.CODE INNER JOIN   
			BARUNSON.DBO.TB_INVITATION_DETAIL K ON G.INVITATION_ID =  K.INVITATION_ID INNER JOIN 
			BARUNSON.DBO.TB_COMMON_CODE P ON A.PAYMENT_METHOD_CODE = P.CODE
	WHERE	A.USER_ID = @USER_ID AND 
			A.ORDER_STATUS_CODE = 'OSC01' AND  --주문완료
			A.PAYMENT_STATUS_CODE IN ('PSC02' , 'PSC04') AND --결제완료 / 입금대기 
			P.CODE_GROUP = 'PAYMENT_METHOD_CODE'  AND
			A.ORDER_CODE LIKE '%' + @ORDER_CODE + '%'
	GROUP BY A.ORDER_ID, A.ORDER_CODE, F.CODE_NAME, D.PRODUCT_CODE,
				D.PRODUCT_NAME,  A.REGIST_DATETIME, A.PAYMENT_PRICE, D.PREVIEW_IMAGE_URL,
				D.MAIN_IMAGE_URL, C.PRODUCT_ID, A.REGIST_DATETIME,G.INVITATION_ID  , F.CODE, A.FINANCE_NAME , K.INVITATION_DISPLAY_YN,
				H.CODE, K.WEDDINGYY , K.WEDDINGMM, K.WEDDINGDD, P.CODE_NAME, A.ACCOUNT_NUMBER, A.ORDER_DATETIME
	ORDER BY A.REGIST_DATETIME DESC
	
	END ELSE BEGIN 
		-- 마이페이지(회원) - 제작완료  리스트 
		SELECT	ORDER_ID = A.ORDER_ID,
				ORDER_CODE = A.ORDER_CODE, 
				PRODUCT_CATEGORY = F.CODE_NAME,
				PRODUCT_CODE = D.PRODUCT_CODE,
				PRODUCT_NAME = D.PRODUCT_NAME,
				REGIST_DATETIME = A.REGIST_DATETIME,
				ORDER_PRICE = isnull(A.PAYMENT_PRICE, 0),
				PREVIEW_IMAGE_URL = D.PREVIEW_IMAGE_URL,
				MAIN_IMAGE_URL = D.MAIN_IMAGE_URL,
				PRODUCT_ID = C.PRODUCT_ID,
				PRODUCT_CODE2 = CASE  F.CODE  WHEN 'PCC01' THEN 'MCARD' WHEN 'PCC02'  THEN 'MTHANKS' END ,
				INVITATION_ID = G.INVITATION_ID,
				FINANCE_NAME = A.FINANCE_NAME,
				INVITATION_DISPLAY_YN = K.INVITATION_DISPLAY_YN,
				WEDDINGYY = K.WEDDINGYY,
				WEDDINGMM = K.WEDDINGMM,
				WEDDINGDD = K.WEDDINGDD,
				PAYMENT_STATUS_CODE = H.CODE,
				PAYMENT_METHOD_NAME = P.CODE_NAME,
				ACCOUNT_NUMBER = A.ACCOUNT_NUMBER,
				ORDER_DATETIME = A.ORDER_DATETIME
		FROM	BARUNSON.DBO.TB_ORDER A INNER JOIN 
				BARUNSON.DBO.VW_USER B ON A.USER_ID = B.USER_ID  INNER JOIN 
				BARUNSON.DBO.TB_ORDER_PRODUCT C ON A.ORDER_ID = C.ORDER_ID  INNER JOIN 
				BARUNSON.DBO.TB_PRODUCT D ON C.PRODUCT_ID = D.PRODUCT_ID  INNER JOIN 
				BARUNSON.DBO.TB_TEMPLATE E ON D.TEMPLATE_ID = E.TEMPLATE_ID INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE F ON D.PRODUCT_CATEGORY_CODE = F.CODE INNER JOIN 
				BARUNSON.DBO.TB_INVITATION G ON A.ORDER_ID = G.ORDER_ID  INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE H ON A.PAYMENT_STATUS_CODE = H.CODE INNER JOIN   
				BARUNSON.DBO.TB_INVITATION_DETAIL K ON G.INVITATION_ID =  K.INVITATION_ID INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE P ON A.PAYMENT_METHOD_CODE = P.CODE
		WHERE	A.USER_ID = @USER_ID AND 
				A.ORDER_STATUS_CODE = 'OSC01' AND  --주문완료
				A.PAYMENT_STATUS_CODE IN ('PSC02') AND --결제완료 / 입금대기 
				P.CODE_GROUP = 'PAYMENT_METHOD_CODE'
		GROUP BY A.ORDER_ID, A.ORDER_CODE, F.CODE_NAME, D.PRODUCT_CODE,
					D.PRODUCT_NAME,  A.REGIST_DATETIME, A.PAYMENT_PRICE, D.PREVIEW_IMAGE_URL,
					D.MAIN_IMAGE_URL, C.PRODUCT_ID, A.REGIST_DATETIME,G.INVITATION_ID  , F.CODE, A.FINANCE_NAME , K.INVITATION_DISPLAY_YN,
					H.CODE, K.WEDDINGYY , K.WEDDINGMM, K.WEDDINGDD, P.CODE_NAME, A.ACCOUNT_NUMBER, A.ORDER_DATETIME
		ORDER BY A.REGIST_DATETIME DESC

	END 


 END ELSE BEGIN 
	
	
	IF @ORDER_CODE <> '' BEGIN 
	
		-- 마이페이지(비회원) - 제작완료  리스트 
		SELECT	ORDER_ID = A.ORDER_ID,
				ORDER_CODE = A.ORDER_CODE, 
				PRODUCT_CATEGORY = F.CODE_NAME,
				PRODUCT_CODE = D.PRODUCT_CODE,
				PRODUCT_NAME = D.PRODUCT_NAME,
				REGIST_DATETIME = A.REGIST_DATETIME,
				ORDER_PRICE = isnull(A.PAYMENT_PRICE, 0),
				PREVIEW_IMAGE_URL = D.PREVIEW_IMAGE_URL,
				MAIN_IMAGE_URL = D.MAIN_IMAGE_URL,
				PRODUCT_ID = C.PRODUCT_ID,
				INVITATION_ID = G.INVITATION_ID,
				PRODUCT_CODE2 = CASE  F.CODE  WHEN 'PCC01' THEN 'MCARD' WHEN 'PCC02'  THEN 'MTHANKS' END ,
				FINANCE_NAME = A.FINANCE_NAME,
				INVITATION_DISPLAY_YN = K.INVITATION_DISPLAY_YN,
				PAYMENT_STATUS_CODE =J.CODE,
				WEDDINGYY = K.WEDDINGYY,
				WEDDINGMM = K.WEDDINGMM,
				WEDDINGDD = K.WEDDINGDD,
				PAYMENT_METHOD_NAME = P.CODE_NAME,
				ACCOUNT_NUMBER = A.ACCOUNT_NUMBER,
				ORDER_DATETIME = A.ORDER_DATETIME
		FROM	BARUNSON.DBO.TB_ORDER  A  INNER JOIN 
				BARUNSON.DBO.TB_ORDER_PRODUCT C ON A.ORDER_ID = C.ORDER_ID  INNER JOIN 
				BARUNSON.DBO.TB_PRODUCT D ON C.PRODUCT_ID = D.PRODUCT_ID  INNER JOIN 
				BARUNSON.DBO.TB_TEMPLATE E ON D.TEMPLATE_ID = E.TEMPLATE_ID INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE F ON D.PRODUCT_CATEGORY_CODE = F.CODE INNER JOIN 
				BARUNSON.DBO.TB_INVITATION G ON A.ORDER_ID = G.ORDER_ID  INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE J ON A.PAYMENT_STATUS_CODE = J.CODE INNER JOIN   
				BARUNSON.DBO.TB_INVITATION_DETAIL K ON G.INVITATION_ID =  K.INVITATION_ID INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE P ON A.PAYMENT_METHOD_CODE = P.CODE
		WHERE	NAME = @USER_NAME AND 
				EMAIL = @USER_EMAIL AND
				ORDER_STATUS_CODE = 'OSC01' AND  --주문완료
				PAYMENT_STATUS_CODE IN ('PSC02') AND--결제완료 / 입금대기 
				P.CODE_GROUP = 'PAYMENT_METHOD_CODE'  AND
				A.ORDER_CODE LIKE '%' + @ORDER_CODE + '%'
		GROUP BY A.ORDER_ID, A.ORDER_CODE, F.CODE_NAME, D.PRODUCT_CODE,
				D.PRODUCT_NAME,  A.REGIST_DATETIME, A.ORDER_PRICE, D.PREVIEW_IMAGE_URL,
				D.MAIN_IMAGE_URL, C.PRODUCT_ID, A.REGIST_DATETIME, G.INVITATION_ID  , F.CODE, A.FINANCE_NAME, K.INVITATION_DISPLAY_YN,
				J.CODE, K.WEDDINGYY , K.WEDDINGMM, K.WEDDINGDD, P.CODE_NAME, A.ACCOUNT_NUMBER,A.ORDER_DATETIME ,A.PAYMENT_PRICE
		ORDER BY A.REGIST_DATETIME DESC

	END ELSE  BEGIN 
	
		-- 마이페이지(비회원) - 제작완료  리스트 
		SELECT	ORDER_ID = A.ORDER_ID,
				ORDER_CODE = A.ORDER_CODE, 
				PRODUCT_CATEGORY = F.CODE_NAME,
				PRODUCT_CODE = D.PRODUCT_CODE,
				PRODUCT_NAME = D.PRODUCT_NAME,
				REGIST_DATETIME = A.REGIST_DATETIME,
				ORDER_PRICE = isnull(A.PAYMENT_PRICE, 0),
				PREVIEW_IMAGE_URL = D.PREVIEW_IMAGE_URL,
				MAIN_IMAGE_URL = D.MAIN_IMAGE_URL,
				PRODUCT_ID = C.PRODUCT_ID,
				INVITATION_ID = G.INVITATION_ID,
				PRODUCT_CODE2 = CASE  F.CODE  WHEN 'PCC01' THEN 'MCARD' WHEN 'PCC02'  THEN 'MTHANKS' END ,
				FINANCE_NAME = A.FINANCE_NAME,
				INVITATION_DISPLAY_YN = K.INVITATION_DISPLAY_YN,
				PAYMENT_STATUS_CODE =J.CODE,
				WEDDINGYY = K.WEDDINGYY,
				WEDDINGMM = K.WEDDINGMM,
				WEDDINGDD = K.WEDDINGDD,
				PAYMENT_METHOD_NAME = P.CODE_NAME,
				ACCOUNT_NUMBER = A.ACCOUNT_NUMBER,
				ORDER_DATETIME = A.ORDER_DATETIME
		FROM	BARUNSON.DBO.TB_ORDER  A  INNER JOIN 
				BARUNSON.DBO.TB_ORDER_PRODUCT C ON A.ORDER_ID = C.ORDER_ID  INNER JOIN 
				BARUNSON.DBO.TB_PRODUCT D ON C.PRODUCT_ID = D.PRODUCT_ID  INNER JOIN 
				BARUNSON.DBO.TB_TEMPLATE E ON D.TEMPLATE_ID = E.TEMPLATE_ID INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE F ON D.PRODUCT_CATEGORY_CODE = F.CODE INNER JOIN 
				BARUNSON.DBO.TB_INVITATION G ON A.ORDER_ID = G.ORDER_ID  INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE J ON A.PAYMENT_STATUS_CODE = J.CODE INNER JOIN   
				BARUNSON.DBO.TB_INVITATION_DETAIL K ON G.INVITATION_ID =  K.INVITATION_ID INNER JOIN 
				BARUNSON.DBO.TB_COMMON_CODE P ON A.PAYMENT_METHOD_CODE = P.CODE
		WHERE	NAME = @USER_NAME AND 
				EMAIL = @USER_EMAIL AND
				ORDER_STATUS_CODE = 'OSC01' AND  --주문완료
				PAYMENT_STATUS_CODE IN ('PSC02') AND--결제완료 / 입금대기 
				P.CODE_GROUP = 'PAYMENT_METHOD_CODE'
		GROUP BY A.ORDER_ID, A.ORDER_CODE, F.CODE_NAME, D.PRODUCT_CODE,
				D.PRODUCT_NAME,  A.REGIST_DATETIME, A.ORDER_PRICE, D.PREVIEW_IMAGE_URL,
				D.MAIN_IMAGE_URL, C.PRODUCT_ID, A.REGIST_DATETIME, G.INVITATION_ID  , F.CODE, A.FINANCE_NAME, K.INVITATION_DISPLAY_YN,
				J.CODE, K.WEDDINGYY , K.WEDDINGMM, K.WEDDINGDD, P.CODE_NAME, A.ACCOUNT_NUMBER,A.ORDER_DATETIME ,A.PAYMENT_PRICE
		ORDER BY A.REGIST_DATETIME DESC

	END

 END 
GO
