IF OBJECT_ID (N'dbo.SP_S_USER_ORDER_INFO', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_S_USER_ORDER_INFO
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_S_USER_ORDER_INFO]
/***************************************************************
작성자	:	표수현
작성일	:	2020-02-15
DESCRIPTION	:	프런트 - 특정 주문건 정보 조회 & 발급받은 쿠폰 조회
SPECIAL LOGIC	:  SP_S_USER_ORDER_INFO 1, 111
******************************************************************
MODIFICATION
******************************************************************
수정일           작업자                DESCRIPTION
==================================================================
******************************************************************/
 @GUBUN		INT = 1,		--  1 : 주문정보 조회 / 2 : 발급받은 쿠폰 조회
 @ORDER_ID	INT = 1
AS

 SET NOCOUNT ON
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

 IF @GUBUN = 1 BEGIN  -- 주문건 정보 조회 
	
	SELECT	ORDER_ID = A.ORDER_ID,
			PG_ID = A.PG_ID,
			ORDER_CODE = A.ORDER_CODE ,  
			ORDER_DATETIME = A.ORDER_DATETIME , 
			REGIST_DATETIME = A.REGIST_DATETIME,
			PRODUCT_CODE = C.PRODUCT_CODE,
			PRODUCT_NAME = C.PRODUCT_NAME,
			PRODUCT_PRICE =  ISNULL(C.PRICE, 0),
			TOTAL_PRICE = ISNULL(B.TOTAL_PRICE, 0),
			COUPON_PRICE = ISNULL(A.COUPON_PRICE, 0),
			EMAIL = A.EMAIL,
			COUPO_CNT = (
							SELECT COUNT(*) FROM TB_COUPON_PUBLISH F INNER JOIN 
												VW_USER Q ON F.USER_ID = Q.USER_ID INNER JOIN 
												TB_ORDER_COUPON_USE S ON F.COUPON_PUBLISH_ID = S.COUPON_PUBLISH_ID
							WHERE F.USER_ID = A.USER_ID AND F.USE_YN = 'Y' AND S.ORDER_ID = A.ORDER_ID
						),
			INVITATION_DISPLAY_YN = K.INVITATION_DISPLAY_YN,
			PRODUCT_CODE2 = CASE  F.CODE  WHEN 'PCC01' THEN 'MCARD' WHEN 'PCC02'  THEN 'MTHANKS' END ,
			PRODUCT_CATEGORY_NAME = F.CODE_NAME,
			PREVIEW_IMAGE_URL =  C.PREVIEW_IMAGE_URL,
			MAIN_IMAGE_URL = C.MAIN_IMAGE_URL,
			PAYMENT_PRICE = ISNULL(A.PAYMENT_PRICE, 0),
			INVITATION_URL = 'https://www.barunsonmcard.com/m/' + K.INVITATION_URL,
			CELLPHONE_NUMBER = A.CELLPHONE_NUMBER,
			INVITATION_ID = G.INVITATION_ID,
			PAYMENT_METHOD_NAME = P.CODE_NAME,
			PAYMENT_METHOD_CODE = P.CODE,
			ACCOUNT_NUMBER = A.ACCOUNT_NUMBER,
			FINANCE_NAME = A.FINANCE_NAME,
			TRADING_NUMBER = A.TRADING_NUMBER,
			DEPOSIT_DEADLINE_DATETIME = ISNULL(A.DEPOSIT_DEADLINE_DATETIME, DATEADD(HH, 72, A.ORDER_DATETIME)) ,
			DEADLINE_DATETIME =  DATEDIFF(HOUR, GETDATE(), ISNULL(A.DEPOSIT_DEADLINE_DATETIME, DATEADD(HH, 72, A.ORDER_DATETIME))),
			PAY_CANCEL_YN = CASE WHEN  DATEDIFF(HOUR, GETDATE(), ISNULL(A.DEPOSIT_DEADLINE_DATETIME, DATEADD(HH, 72, A.ORDER_DATETIME))) < 0 THEN 'N'
			ELSE 'Y' END, 
			ACCOUNT_COUNT = (
								SELECT COUNT(1) 
								FROM TB_ACCOUNT A INNER JOIN 
									 TB_REMIT B ON A.INVITATION_ID = B.INVITATION_ID
								WHERE A.INVITATION_ID = Q.INVITATION_ID and
									  ISNULL(B.TOTAL_PRICE, 0) >= 10000
							)
	FROM	TB_ORDER A INNER JOIN 
			TB_ORDER_PRODUCT B ON A.ORDER_ID = B.ORDER_ID INNER JOIN 
			TB_PRODUCT C ON B.PRODUCT_ID = C.PRODUCT_ID INNER JOIN 
			BARUNSON.DBO.TB_INVITATION G ON A.ORDER_ID = G.ORDER_ID  INNER JOIN 
			BARUNSON.DBO.TB_COMMON_CODE F ON C.PRODUCT_CATEGORY_CODE = F.CODE INNER JOIN   
			BARUNSON.DBO.TB_INVITATION_DETAIL K ON G.INVITATION_ID =  K.INVITATION_ID INNER JOIN 
			BARUNSON.DBO.TB_COMMON_CODE P ON A.PAYMENT_METHOD_CODE = P.CODE INNER JOIN 
			BARUNSON.DBO.TB_INVITATION Q ON A.ORDER_ID = Q.ORDER_ID  
	WHERE	A.ORDER_ID = @ORDER_ID AND P.CODE_GROUP = 'PAYMENT_METHOD_CODE'
	

 END ELSE BEGIN  -- 발급받은 쿠폰 조회
	
	DECLARE @USER_ID VARCHAR(100)

	SELECT @USER_ID 
	FROM TB_ORDER
	WHERE ORDER_ID = @ORDER_ID
		
	SELECT	DISTINCT(A.COUPON_NAME)
	FROM	TB_COUPON A INNER JOIN TB_COUPON_PUBLISH B ON A.COUPON_ID = B.COUPON_ID  
	WHERE	B.USER_ID =  @USER_ID

 END
GO
