IF OBJECT_ID (N'dbo.SP_S_ADMIN_MEMBER_DETAIL_TEST', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_S_ADMIN_MEMBER_DETAIL_TEST
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_S_ADMIN_MEMBER_DETAIL_TEST]
/***************************************************************
작성자	:	표수현
작성일	:	2020-02-15
DESCRIPTION	:	ADMIN - 회원상세 
SPECIAL LOGIC	: SP_S_ADMIN_MEMBER_DETAIL_TEST 'M', 377

SP_S_ADMIN_MEMBER_DETAIL 'T', 3

******************************************************************
MODIFICATION
******************************************************************
수정일           작업자                DESCRIPTION
==================================================================
******************************************************************/
 @GUBUN CHAR(1) = 1, --  M : 회원 / F : 비회원
 @ORDER_ID INT = NULL
AS

 SET NOCOUNT ON
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

 DECLARE @USER_NAME VARCHAR(10)
 DECLARE @USER_ID VARCHAR(10)
 DECLARE @USER_EMAIL VARCHAR(100)
 

 IF @GUBUN = 'M' BEGIN 

	SELECT USER_NAME = MAX(A.NAME),
		   USER_ID = MAX(A.USER_ID),
		   USER_EMAIL = MAX(A.EMAIL)
	FROM  TB_ORDER A INNER JOIN 
		  VW_USER B ON A.USER_ID = B.USER_ID
	WHERE A.ORDER_ID = @ORDER_ID

	-- 1. 기본정보(이름, 아이디, 연락처, 이메일, 예식일, 회원가입일) 

	SELECT @USER_NAME
	
	SELECT @USER_ID
	
	SELECT @USER_EMAIL


	select @ORDER_ID
	SELECT  USER_NAME = @USER_NAME,
			USER_ID = @USER_ID,
			USER_HP = MAX(A.CELLPHONE_NUMBER),
			USER_EMAIL = @USER_EMAIL, 
			WEDDING_DATE = MAX(B.WEDDING_DATE), 
			REGIST_DATETIME = MAX(B.REGIST_DATETIME) 
	 FROM	TB_ORDER A INNER JOIN VW_USER B ON A.USER_ID = B.USER_ID
	 WHERE	A.ORDER_ID = @ORDER_ID


	-- 2. 주문정보(주문번호, 상품코드, 주문금액, 쿠폰사용금액, 결재금액, 결재수단, 결재일자, 결제취소, 모초 바로가기 URL)
	-- 그중에 결재일자, 결재취소날짜 여부 알수 없음 

	 SELECT ORDER_CODE = A.ORDER_CODE, 
			ORDER_ID = A.ORDER_ID, 
			PRODUCT_CODE= C.PRODUCT_CODE,
			ORDER_PRICE = A.ORDER_PRICE,
			쿠폰사용금액 =(SELECT DISCOUNT_PRICE FROM TB_ORDER_COUPON_USE WHERE ORDER_ID = A.ORDER_ID), 
			A.PAYMENT_PRICE,
			PAYMENT_METHOD_CODE = A.PAYMENT_METHOD_CODE, 
			CODE_NAME1 = D.CODE_NAME, 
			CODE_NAME2 = E.CODE_NAME,
			REG_DATE = A.REGIST_DATETIME,
			CANCEL_DATE = (CASE WHEN E.CODE_NAME = '결제취소' THEN A.UPDATE_DATETIME ELSE NULL END)
			--INVITATION_URL = (SELECT INVITATION_URL FROM TB_ORDER_DETAIL  WHERE INVITATION_ID =  F.INVITATION_ID)
		FROM TB_ORDER A INNER JOIN TB_ORDER_PRODUCT B ON A.ORDER_ID = B.ORDER_ID INNER JOIN 
			TB_PRODUCT C ON B.PRODUCT_ID = C.PRODUCT_ID INNER JOIN 
			TB_COMMON_CODE D ON A.PAYMENT_METHOD_CODE = D.CODE AND D.CODE_GROUP = 'PAYMENT_METHOD_CODE' INNER JOIN 
			TB_COMMON_CODE E ON A.PAYMENT_STATUS_CODE = E.CODE AND E.CODE_GROUP = 'PAYMENT_STATUS_CODE' INNER JOIN 
			TB_ORDER_PRODUCT F ON A.ORDER_ID = F.ORDER_ID
			-- INNER JOIN 
		--TB_INVITATION F ON A.ORDER_ID = F.ORDER_ID   INNER JOIN 
		--TB_ORDER_DETAIL G ON F.INVITATION_ID = G.INVITATION_ID  
		WHERE A.USER_ID = @USER_ID


	-- 3. 쿠폰 정보 

	 SELECT D.COUPON_NAME,  
			D.COUPON_ID, 
			C.USE_YN, 
			D.DISCOUNT_PRICE, 
			C.USE_DATETIME, 
			D.REGIST_DATETIME,
			C.RETRIEVE_DATETIME 
	 FROM TB_ORDER A INNER JOIN 
		  TB_ORDER_COUPON_USE B ON A.ORDER_ID = B.ORDER_ID INNER JOIN
		  TB_COUPON_PUBLISH C ON B.COUPON_PUBLISH_ID = C.COUPON_PUBLISH_ID INNER JOIN 
		  TB_COUPON D ON C.COUPON_ID = D.COUPON_ID
	 WHERE A.USER_ID = @USER_ID 


	-- 4. 결재 환불 정보 

	SELECT	주문번호 = A.ORDER_ID , 
			주문코드 = A.ORDER_CODE,
			결재금액 = A.PAYMENT_PRICE ,결제수단 = C.CODE_NAME,
			결제기관명 = A.FINANCE_NAME,
			계좌정보 = A.ACCOUNT_NUMBER,
			결제일 = A.UPDATE_DATETIME,
			환불금액 = (SELECT REFUND_PRICE FROM TB_REFUND_INFO WHERE ORDER_ID = A.ORDER_ID),
			환불날짜= (SELECT REFUND_DATETIME FROM TB_REFUND_INFO WHERE ORDER_ID = A.ORDER_ID)
	FROM	TB_ORDER A INNER JOIN 
			TB_COMMON_CODE C ON A.PAYMENT_METHOD_CODE = C.CODE AND C.CODE_GROUP = 'PAYMENT_METHOD_CODE' 
	WHERE	A.USER_ID = @USER_ID

	--SELECT 주문번호 = A.ORDER_ID , 결재금액 = A.PAYMENT_PRICE ,결제수단 = C.CODE_NAME,
	--	   결재상세 = B.ACCOUNTNUMBER, 환불금액 = B.REFUND_PRICE, 환불상태= B.REFUND_DATETIME
	--FROM TB_ORDER A INNER JOIN 
	--	 TB_REFUND_INFO B ON A.ORDER_ID = B.ORDER_ID INNER JOIN 
	--	 TB_COMMON_CODE C ON A.PAYMENT_STATUS_CODE = C.CODE AND C.CODE_GROUP = 'PAYMENT_METHOD_CODE' 
	--WHERE  A.USER_ID = @USER_ID


	-- 5. 고객 상담
	SELECT * 
	FROM VW_USER_QNA A INNER JOIN 
		 TB_ORDER B ON A.ORDER_ID = B.ORDER_ID
	WHERE  B.USER_ID = @USER_ID


 END ELSE BEGIN

	SELECT @USER_NAME = NAME,
		   @USER_ID = USER_ID,
		   @USER_EMAIL = EMAIL
	FROM  TB_ORDER
	WHERE ORDER_ID = @ORDER_ID

	
	--SELECT @USER_NAME
	
	--SELECT @USER_ID
	
	--SELECT @USER_EMAIL

	SELECT  USER_NAME = @USER_NAME,
			USER_ID = @USER_ID,
			USER_HP = CELLPHONE_NUMBER,
			USER_EMAIL = @USER_EMAIL, 
			WEDDING_DATE = '',
			REGIST_DATETIME = ''
	FROM TB_ORDER 
	WHERE ORDER_ID = @ORDER_ID

	
	-- 2. 주문정보(주문번호, 상품코드, 주문금액, 쿠폰사용금액, 결재금액, 결재수단, 결재일자, 결제취소, 모초 바로가기 URL)
	-- 그중에 결재일자, 결재취소날짜 여부 알수 없음 

	 SELECT ORDER_CODE = A.ORDER_CODE, 
			ORDER_ID = A.ORDER_ID, 
			PRODUCT_CODE= C.PRODUCT_CODE,
			ORDER_PRICE = A.ORDER_PRICE,
			쿠폰사용금액 =(SELECT DISCOUNT_PRICE FROM TB_ORDER_COUPON_USE WHERE ORDER_ID = A.ORDER_ID ), 
			A.PAYMENT_PRICE,
			PAYMENT_METHOD_CODE = A.PAYMENT_METHOD_CODE, 
			CODE_NAME1 = D.CODE_NAME, 
			CODE_NAME2 = E.CODE_NAME,
			REG_DATE = F.REGIST_DATETIME,
			CANCEL_DATE = (CASE WHEN E.CODE_NAME = '결제취소' THEN A.UPDATE_DATETIME ELSE NULL END)
			--INVITATION_URL = (SELECT INVITATION_URL FROM TB_ORDER_DETAIL  WHERE INVITATION_ID =  F.INVITATION_ID)
		FROM TB_ORDER A INNER JOIN TB_ORDER_PRODUCT B ON A.ORDER_ID = B.ORDER_ID INNER JOIN 
			TB_PRODUCT C ON B.PRODUCT_ID = C.PRODUCT_ID INNER JOIN 
			TB_COMMON_CODE D ON A.PAYMENT_METHOD_CODE = D.CODE AND D.CODE_GROUP = 'PAYMENT_METHOD_CODE' INNER JOIN 
			TB_COMMON_CODE E ON A.PAYMENT_STATUS_CODE = E.CODE AND E.CODE_GROUP = 'PAYMENT_STATUS_CODE' INNER JOIN 
			TB_ORDER_PRODUCT F ON A.ORDER_ID = F.ORDER_ID
			-- INNER JOIN 
		--TB_INVITATION F ON A.ORDER_ID = F.ORDER_ID   INNER JOIN 
		--TB_ORDER_DETAIL G ON F.INVITATION_ID = G.INVITATION_ID  
		WHERE A.EMAIL = @USER_EMAIL AND A.NAME = @USER_NAME


	-- 3. 쿠폰 정보 

	 SELECT D.COUPON_NAME,  
			D.COUPON_ID, 
			C.USE_YN, 
			D.DISCOUNT_PRICE, 
			C.USE_DATETIME, 
			D.REGIST_DATETIME,
			C.RETRIEVE_DATETIME 
	 FROM TB_ORDER A INNER JOIN 
		  TB_ORDER_COUPON_USE B ON A.ORDER_ID = B.ORDER_ID INNER JOIN
		  TB_COUPON_PUBLISH C ON B.COUPON_PUBLISH_ID = C.COUPON_PUBLISH_ID INNER JOIN 
		  TB_COUPON D ON C.COUPON_ID = D.COUPON_ID
	 WHERE A.EMAIL = @USER_EMAIL AND A.NAME = @USER_NAME


	-- 4. 결재 환불 정보 

	
	SELECT	주문번호 = A.ORDER_ID , 
			주문코드 = A.ORDER_CODE,
			결재금액 = A.PAYMENT_PRICE ,결제수단 = C.CODE_NAME,
			결제기관명 = A.FINANCE_NAME,
			계좌정보 = A.ACCOUNT_NUMBER,
			결제일 = A.UPDATE_DATETIME,
			환불금액 = (SELECT REFUND_PRICE FROM TB_REFUND_INFO WHERE ORDER_ID = A.ORDER_ID),
			환불날짜= (SELECT REFUND_DATETIME FROM TB_REFUND_INFO WHERE ORDER_ID = A.ORDER_ID)
	FROM	TB_ORDER A INNER JOIN 
			TB_COMMON_CODE C ON A.PAYMENT_METHOD_CODE = C.CODE AND C.CODE_GROUP = 'PAYMENT_METHOD_CODE' 
	WHERE	A.EMAIL = @USER_EMAIL AND A.NAME = @USER_NAME


	--SELECT 주문번호 = A.ORDER_ID , 결재금액 = A.PAYMENT_PRICE ,결제수단 = C.CODE_NAME,
	--	   결재상세 = B.ACCOUNTNUMBER, 환불금액 = B.REFUND_PRICE, 환불상태= B.REFUND_DATETIME
	--FROM TB_ORDER A INNER JOIN 
	--	 TB_REFUND_INFO B ON A.ORDER_ID = B.ORDER_ID INNER JOIN 
	--	 TB_COMMON_CODE C ON A.PAYMENT_STATUS_CODE = C.CODE AND C.CODE_GROUP = 'PAYMENT_METHOD_CODE' 
	--WHERE A.EMAIL = @USER_EMAIL AND A.NAME = @USER_NAME


	-- 5. 고객 상담

	SELECT * 
	FROM VW_USER_QNA A INNER JOIN 
		 TB_ORDER B ON A.ORDER_ID = B.ORDER_ID
	WHERE B.EMAIL = @USER_EMAIL AND A.NAME = @USER_NAME

 END 

	-- 6. 관리자 메모 
	SELECT A.MEMO_ID, A.CONTENT,  A.REGIST_USER_ID, A.REGIST_DATETIME, B.ADMIN_NAME
	FROM TB_ADMIN_MEMO A INNER JOIN 
		 VW_ADMIN B ON A.REGIST_USER_ID = B.ADMIN_ID
	ORDER BY A.REGIST_DATETIME DESC

GO
