IF OBJECT_ID (N'dbo.SP_T_USER_COUPON_PAY_MO', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_T_USER_COUPON_PAY_MO
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_T_USER_COUPON_PAY_MO]
/***************************************************************
작성자	:	표수현
작성일	:	2020-02-15
DESCRIPTION	:	쿠폰 전액 결재 처리 (모바일)
SPECIAL LOGIC	:
******************************************************************
MODIFICATION
******************************************************************
수정일           작업자                DESCRIPTION
==================================================================
******************************************************************/
 @GUBUN CHAR(1) = NULL, --I -> 쿠폰전액결제 | P --> 쿠폰부분결제
 @ORDER_CODE VARCHAR(20) = NULL,
 @USER_ID VARCHAR(50) = NULL,
 @IP	  VARCHAR(50) = NULL,
 @PAYMENT_PRICE  INT = NULL,
 @COUPON_PRICE INT = NULL,
 @COUPON_PUBLISH_ID INT = NULL,
 @COUPON_ID INT = NULL
AS

 SET NOCOUNT ON
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 
 
 DECLARE @ORDER_ID INT = NULL

 SELECT @ORDER_ID = ORDER_ID
 FROM TB_ORDER
 WHERE ORDER_CODE = @ORDER_CODE

 IF @GUBUN = 'I' BEGIN  -- 쿠폰전액결제 

	  --1. TB_ORDER 업데이트 
	 UPDATE TB_ORDER
	 SET	PAYMENT_METHOD_CODE = 'PMC04',
			PAYMENT_STATUS_CODE = 'PSC02',
			UPDATE_DATETIME = GETDATE(),
			ORDER_DATETIME = GETDATE(),
			UPDATE_USER_ID = @USER_ID,
			UPDATE_IP = @IP,
			--PAYMENT_PRICE = @PAYMENT_PRICE,
			COUPON_PRICE = @COUPON_PRICE
	 WHERE	ORDER_ID = @ORDER_ID

 END ELSE BEGIN -- 쿠폰부분결제 

	 -- 1. TB_ORDER 업데이트 
	 UPDATE TB_ORDER
	 SET	--PAYMENT_METHOD_CODE = 'PMC04',
			--PAYMENT_STATUS_CODE = 'PSC02',
			UPDATE_DATETIME = GETDATE(),
			ORDER_DATETIME = GETDATE(),
			UPDATE_USER_ID = @USER_ID,
			UPDATE_IP = @IP,
			--PAYMENT_PRICE = @PAYMENT_PRICE,
			COUPON_PRICE = @COUPON_PRICE
	 WHERE	ORDER_ID = @ORDER_ID
 END 



IF(ISNULL(@COUPON_ID,0) > 100000)
 BEGIN
	 --2. TB_COUPON_PUBLISH USE_YN값을 Y로 업데이트 
	 UPDATE TB_SERIAL_COUPON_PUBLISH
	 SET USE_YN = 'Y', USE_DATETIME = GETDATE()
	 WHERE COUPON_PUBLISH_ID = @COUPON_PUBLISH_ID

	 --3. TB_ORDER_COUPON_USE 인서트 
	 IF NOT Exists(Select * From TB_ORDER_SERIAL_COUPON_USE Where ORDER_ID = @ORDER_ID)
	 BEGIN
		INSERT TB_ORDER_SERIAL_COUPON_USE(ORDER_ID, COUPON_PUBLISH_ID, DISCOUNT_PRICE, REGIST_USER_ID, REGIST_DATETIME, REGIST_IP, UPDATE_USER_ID, UPDATE_DATETIME, UPDATE_IP)
		VALUES (@ORDER_ID, @COUPON_PUBLISH_ID, @COUPON_PRICE, @USER_ID, GETDATE(), @IP, @USER_ID, GETDATE(),   @IP)
	 END
 END
 ELSE
 BEGIN
	 --2. TB_COUPON_PUBLISH USE_YN값을 Y로 업데이트 
	 UPDATE TB_COUPON_PUBLISH
	 SET USE_YN = 'Y', USE_DATETIME = GETDATE()
	 WHERE COUPON_PUBLISH_ID = @COUPON_PUBLISH_ID

	 --3. TB_ORDER_COUPON_USE 인서트 
	 IF NOT Exists(Select * From TB_ORDER_COUPON_USE Where ORDER_ID = @ORDER_ID)
	 BEGIN
		INSERT TB_ORDER_COUPON_USE(ORDER_ID, COUPON_PUBLISH_ID, DISCOUNT_PRICE, REGIST_USER_ID, REGIST_DATETIME, REGIST_IP, UPDATE_USER_ID, UPDATE_DATETIME, UPDATE_IP)
		VALUES (@ORDER_ID, @COUPON_PUBLISH_ID, @COUPON_PRICE, @USER_ID, GETDATE(), @IP, @USER_ID, GETDATE(),   @IP)
	 END
	
 END



GO
