IF OBJECT_ID (N'dbo.SP_T_COUPON_APPLY_PRODUCT_INSERT', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_T_COUPON_APPLY_PRODUCT_INSERT
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_T_COUPON_APPLY_PRODUCT_INSERT]
/***************************************************************
작성자	:	표수현
작성일	:	2020-02-15
DESCRIPTION	: 어드민 - 쿠폰 적용 / 미적용할 상품 저장 / 삭제 
SPECIAL LOGIC	: SP_T_COUPON_APPLY_PRODUCT_INSERT 'I', 'MC1201'
******************************************************************
MODIFICATION
******************************************************************
수정일           작업자                DESCRIPTION
==================================================================
******************************************************************/
 @GUBUN CHAR(1) = 'I', -- I -> 신규 / U -> 삭제
 @PRODUCT_CODE VARCHAR(50) = NULL,
 @PRODUCT_APPLY_ID INT = NULL
AS 

 SET NOCOUNT ON
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 

 DECLARE @ORDER_CODE INT
 DECLARE @상품중복카운트 INT 

 IF @GUBUN = 'I' BEGIN  

	 IF @PRODUCT_APPLY_ID = 0 OR @PRODUCT_APPLY_ID = NULL BEGIN 

		INSERT TB_COUPON_APPLY_PRODUCT(COUPON_ID)
		VALUES(NULL)

		DECLARE @NEW_PRODUCT_APPLY_ID INT = @@IDENTITY

		INSERT TB_APPLY_PRODUCT(PRODUCT_APPLY_ID, PRODUCT_CODE)
		VALUES (@NEW_PRODUCT_APPLY_ID, @PRODUCT_CODE)  -- 저장 

		 SELECT PRODUCT_APPLY_ID = @NEW_PRODUCT_APPLY_ID

	 END ELSE BEGIN 

		SELECT @상품중복카운트 = COUNT(1) 
		FROM TB_APPLY_PRODUCT
		WHERE PRODUCT_APPLY_ID = @PRODUCT_APPLY_ID 
			  AND PRODUCT_CODE = @PRODUCT_CODE

		IF @상품중복카운트 = 0 BEGIN 

	 		INSERT TB_APPLY_PRODUCT(PRODUCT_APPLY_ID, PRODUCT_CODE)
			VALUES (@PRODUCT_APPLY_ID, @PRODUCT_CODE)  -- 저장 
		END 

		SELECT PRODUCT_APPLY_ID = @PRODUCT_APPLY_ID

	 END 

 END ELSE BEGIN 

	DELETE 
	FROM TB_APPLY_PRODUCT
	WHERE PRODUCT_APPLY_ID = @PRODUCT_APPLY_ID
		  AND PRODUCT_CODE = @PRODUCT_CODE


	SELECT @상품중복카운트 = COUNT(1)
	FROM TB_APPLY_PRODUCT
	WHERE PRODUCT_APPLY_ID = @PRODUCT_APPLY_ID
	
		IF @상품중복카운트 = 0 BEGIN 

			DELETE 
			FROM TB_COUPON_APPLY_PRODUCT
			WHERE PRODUCT_APPLY_ID = @PRODUCT_APPLY_ID

			UPDATE TB_COUPON 
			SET COUPON_APPLY_PRODUCT_ID = NULL
			WHERE COUPON_APPLY_PRODUCT_ID = @PRODUCT_APPLY_ID

			SELECT PRODUCT_APPLY_ID = 0

		END ELSE BEGIN 

			SELECT PRODUCT_APPLY_ID = @PRODUCT_APPLY_ID

		END 

 END 

 
GO
