IF OBJECT_ID (N'dbo.SP_S_ADMIN_COUPON_PUBLISH_MEMBER_LIST', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_S_ADMIN_COUPON_PUBLISH_MEMBER_LIST
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_S_ADMIN_COUPON_PUBLISH_MEMBER_LIST]
	@COUPONID INT,
	@USEYN VARCHAR(4) = '',
	@SEARCHKEYWORD VARCHAR(20) =''

AS
 BEGIN
	SET NOCOUNT ON;

	SELECT 
			CP.COUPON_ID,
			CP.COUPON_PUBLISH_ID,
			CASE WHEN U.USER_ID IS NOT NULL THEN U.NAME ELSE '탈퇴회원' END NAME,
			CP.USER_ID,
			CASE WHEN U.USER_ID IS NOT NULL THEN U.EMAIL ELSE '-' END EMAIL,
			CASE WHEN U.USER_ID IS NOT NULL THEN U.PHONE_NUMBER ELSE '-' END PHONE_NUMBER,
			CONVERT(VARCHAR(20), CP.REGIST_DATETIME, 120) REGIST_DATETIME,
			CASE WHEN CP.EXPIRATION_DATE IS NOT NULL THEN CP.EXPIRATION_DATE ELSE '무제한' END EXPIRATION_DATE,
			CP.USE_YN,
			CONVERT(VARCHAR(20), CP.USE_DATETIME, 120) USE_DATETIME,
			CONVERT(VARCHAR(20), CP.RETRIEVE_DATETIME, 120) RETRIEVE_DATETIME
	FROM TB_COUPON_PUBLISH AS CP LEFT JOIN 
			 VW_USER AS U ON CP.USER_ID = U.USER_ID
	WHERE CP.COUPON_ID = @COUPONID AND 
		 (CP.USER_ID LIKE '%'+@SEARCHKEYWORD+'%' OR U.NAME LIKE '%'+@SEARCHKEYWORD+'%') AND 
		 --CP.USE_YN = (CASE WHEN @USEYN <> '' THEN @USEYN ELSE  CP.USE_YN END)

		 (@USEYN <> 'Y' OR CP.USE_YN = 'Y') AND 
		 (@USEYN <> 'N' OR CP.USE_YN = 'N')
	
	ORDER BY CP.REGIST_DATETIME DESC
 END

GO
