IF OBJECT_ID (N'dbo.SP_T_USER_PAYCHANGE_COUPON', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_T_USER_PAYCHANGE_COUPON
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_T_USER_PAYCHANGE_COUPON]
/***************************************************************
작성자	:	표수현
작성일	:	2020-02-15
DESCRIPTION	:	어드민에서 수동으로 무통장 입금대기 주문건을 쿠폰 전액 결제로 처리 
SPECIAL LOGIC	:
******************************************************************
MODIFICATION
******************************************************************
수정일           작업자                DESCRIPTION
==================================================================
******************************************************************/
 @ORDER_ID INT = NULL
AS

 SET NOCOUNT ON
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 
 
 DECLARE @USER_ID VARCHAR(50) = '';
 DECLARE @COUPON_PUBLISH_ID INT 
 DECLARE @COUPON_PRICE  INT 
 DECLARE @IP   VARCHAR(50)

 SELECT @USER_ID = USER_ID , 
		@COUPON_PRICE = PAYMENT_PRICE
 FROM TB_ORDER
 WHERE ORDER_ID = @ORDER_ID AND
		PAYMENT_STATUS_CODE = 'PSC04'

--DROP TABLE #COUPON

		
 SELECT * INTO #COUPON
		FROM (
				SELECT	A.COUPON_ID ,
						만료일 = CASE A.PERIOD_METHOD_CODE 
									WHEN 'PMC01' THEN CONVERT(VARCHAR(10), A.PUBLISH_END_DATE , 120) -- 날짜 지정 
									WHEN 'PMC02' THEN 
									(
										-- 발행일로부터
										SELECT CONVERT(VARCHAR(10), DATEADD(DD, CONVERT(INT,CODE_NAME), GETDATE()) , 120) 
										FROM TB_COMMON_CODE 
										WHERE CODE_GROUP = 'PUBLISH_PERIOD_CODE' AND
												CODE = A.PUBLISH_PERIOD_CODE 

									)
								--ELSE '무제한' 
								END ,
							--A.PERIOD_METHOD_CODE,
							--A.PUBLISH_PERIOD_CODE
							A.DISCOUNT_METHOD_CODE
					FROM TB_COUPON A INNER JOIN 
						 TB_COMMON_CODE B ON A.DISCOUNT_METHOD_CODE = B.CODE 
					WHERE B.CODE_GROUP = 'DISCOUNT_METHOD_CODE' AND 
						  A.DISCOUNT_METHOD_CODE = 'DMC03' 
						
			)  TB
 WHERE CONVERT(VARCHAR(10), ISNULL(TB.만료일, CONVERT(VARCHAR(10),GETDATE(), 120)), 120) >=  CONVERT(VARCHAR(10), GETDATE(), 120)
	AND TB.DISCOUNT_METHOD_CODE = 'DMC03'

 --SELECT TOP 1 * INTO #COUPON
	--	FROM (
	--			SELECT	A.COUPON_ID ,
	--					만료일 = CASE A.PERIOD_METHOD_CODE 
	--								WHEN 'PMC01' THEN CONVERT(VARCHAR(10), A.PUBLISH_END_DATE , 120) -- 날짜 지정 
	--								WHEN 'PMC02' THEN 
	--								(
	--									-- 발행일로부터
	--									SELECT CONVERT(VARCHAR(10), DATEADD(DD, CONVERT(INT,CODE_NAME), GETDATE()) , 120) 
	--									FROM TB_COMMON_CODE 
	--									WHERE CODE_GROUP = 'PUBLISH_PERIOD_CODE' AND
	--											CODE = A.PUBLISH_PERIOD_CODE 

	--								)
	--							--ELSE '무제한' 
	--							END ,
	--						--A.PERIOD_METHOD_CODE,
	--						--A.PUBLISH_PERIOD_CODE
	--						A.DISCOUNT_METHOD_CODE
	--				FROM TB_COUPON A INNER JOIN 
	--					 TB_COMMON_CODE B ON A.PUBLISH_METHOD_CODE = B.CODE  INNER JOIN 
	--					 TB_COMMON_CODE C ON A.PUBLISH_TARGET_CODE = C.CODE
	--				WHERE B.CODE_GROUP = 'PUBLISH_METHOD_CODE' AND 
	--					  A.PUBLISH_METHOD_CODE = 'PMC01' AND -- 자동발행
	--					  C.CODE_GROUP = 'PUBLISH_TARGET_CODE'  AND 
	--					  A.PUBLISH_TARGET_CODE = 'PTC01' -- 청첩장 결제완료 + 고객 컨펌 완료 
						
	--		)  TB
 --WHERE CONVERT(VARCHAR(10), ISNULL(TB.만료일, CONVERT(VARCHAR(10),GETDATE(), 120)), 120) >=  CONVERT(VARCHAR(10), GETDATE(), 120)
	--AND TB.DISCOUNT_METHOD_CODE = 'DMC03'
			


 SELECT @COUPON_PUBLISH_ID = T.COUPON_PUBLISH_ID -- #COUPON.COUPON_ID, T.COUPON_PUBLISH_ID
 FROM #COUPON 
		INNER JOIN (
						SELECT COUPON_ID, COUPON_PUBLISH_ID
						FROM [TB_COUPON_PUBLISH] 
						WHERE (([USER_ID] = @USER_ID) AND 
						([RETRIEVE_DATETIME] IS NULL OR 
						(CONVERT(VARCHAR(100), RETRIEVE_DATETIME) = ''))) AND (USE_YN = 'N')
				   ) T ON #COUPON.[COUPON_ID] = T.COUPON_ID


 IF @COUPON_PUBLISH_ID > 0 AND @USER_ID <> '' BEGIN 

  --1. TB_ORDER 업데이트   
	UPDATE	TB_ORDER  
	SET		PAYMENT_METHOD_CODE = 'PMC04', --기타(쿠폰)  
			PAYMENT_STATUS_CODE = 'PSC02',  --결제완료
			ORDER_STATUS_CODE = 'OSC01',  --주문완료
			UPDATE_DATETIME = GETDATE(),  
			--ORDER_DATETIME = GETDATE(),    
			PAYMENT_DATETIME = GETDATE(),  
			PAYMENT_PRICE = NULL,
			COUPON_PRICE = PAYMENT_PRICE,
			FINANCE_NAME = NULL,
			PAYER_NAME = NULL,
			ESCROW_YN = NULL,
			ACCOUNT_NUMBER = NULL,
			TRADING_NUMBER = NULL,
			CANCEL_DATETIME = NULL,
			CANCEL_TIME = NULL,
			DEPOSIT_DEADLINE_DATETIME = NULL,
			ORDER_PATH = 'PC',  
			PAYMENT_PATH = 'PC'
	WHERE ORDER_ID = @ORDER_ID  

--2. TB_COUPON_PUBLISH USE_YN값을 Y로 업데이트 
 UPDATE TB_COUPON_PUBLISH  
 SET	USE_YN = 'Y',   
		USE_DATETIME = GETDATE()  
 WHERE COUPON_PUBLISH_ID = @COUPON_PUBLISH_ID  
  

 --3. TB_ORDER_COUPON_USE 인서트   
 INSERT TB_ORDER_COUPON_USE(ORDER_ID, COUPON_PUBLISH_ID, DISCOUNT_PRICE, REGIST_USER_ID, REGIST_DATETIME, REGIST_IP, UPDATE_USER_ID, UPDATE_DATETIME, UPDATE_IP)  
 VALUES (@ORDER_ID, @COUPON_PUBLISH_ID, @COUPON_PRICE, @USER_ID, GETDATE(), @IP, @USER_ID, GETDATE(),   @IP)  
 
	SELECT 결과 = 'T'

 END ELSE BEGIN 

	SELECT  결과 = 'F'

 END
GO
