IF OBJECT_ID (N'dbo.SP_S_ADMIN_ORDER_MEMBER', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_S_ADMIN_ORDER_MEMBER
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_S_ADMIN_ORDER_MEMBER]
/***************************************************************
작성자	:	표수현
작성일	:	2021-05-26
DESCRIPTION	:	ADMIN - 회원관리 - 주문한 회원목록 
SPECIAL LOGIC	: SP_S_ADMIN_ORDER_MEMBER '2021-05-19', '2021-05-26' , 'ALL', NULL
SP_S_ADMIN_ORDER_MEMBER '2021-05-19', '2021-05-26' , 'ALL',	'브'
******************************************************************
MODIFICATION
******************************************************************
수정일           작업자                DESCRIPTION
==================================================================
******************************************************************/
 @START_DATE VARCHAR(10) = NULL,
 @END_DATE VARCHAR(10) = NULL,
 @MEMBER_TYPE CHAR(3) = NULL,
 @SEARCHTXT VARCHAR(100) = NULL -- 검색어 
AS

 SET NOCOUNT ON
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

 IF @MEMBER_TYPE = 'ALL' OR  @MEMBER_TYPE IS NULL BEGIN SET @MEMBER_TYPE = '' END

 IF @SEARCHTXT IS NOT NULL AND @SEARCHTXT <> '' BEGIN 
	
	IF @START_DATE IS NOT NULL AND @END_DATE IS NOT NULL BEGIN
		
		--	DROP TABLE #TEMP
			SELECT * 
			INTO #TEMP
			FROM 
			(
				
					SELECT	ORDER_ID = MAX(ORDER_ID),
							[USER_NAME] = A.NAME,
							[USER_ID] = A.USER_ID,
							CARD_CODE = B.CARD_CODE,
							JOIN_TYPE = B.REFERER_SALES_GUBUN, 
							WEDDING_DATE = MAX(B.WEDDING_DATE), 
							REGIST_DATETIME = MAX(B.REGIST_DATETIME),
							ORDER_DATE = MAX(A.REGIST_DATETIME),
							MEMBER_TYPE = 'M'
					FROM	BARUNSON.DBO.TB_ORDER A INNER JOIN 
							BARUNSON.DBO.VW_USER_TEST B ON A.USER_ID = B.USER_ID 
					GROUP BY A.NAME, A.USER_ID, B.CARD_CODE, B.REFERER_SALES_GUBUN--,
							 --B.WEDDING_DATE, B.REGIST_DATETIME, A.REGIST_DATETIME
			) TEMP

		SELECT	ORDER_ID,
				[USER_NAME],
				[USER_ID],
				CARD_CODE,
				JOIN_TYPE, 
				WEDDING_DATE, 
				REGIST_DATETIME,
				ORDER_DATE,
				MEMBER_TYPE
		FROM (
				-- 회원
				SELECT	ORDER_ID = MAX(ORDER_ID), 
						[USER_NAME], 
						[USER_ID], 
						CARD_CODE = max(CARD_CODE), 
						JOIN_TYPE,
						WEDDING_DATE, 
						REGIST_DATETIME = max(REGIST_DATETIME), 
						ORDER_DATE = max(ORDER_DATE), 
						MEMBER_TYPE
				FROM	#TEMP
				GROUP BY USER_NAME, USER_ID, --CARD_CODE, 
						 JOIN_TYPE, WEDDING_DATE,--REGIST_DATETIME,  REGIST_DATETIME , ORDER_DATE, 
						 MEMBER_TYPE
				UNION
		
				-- 비회원
				SELECT  ORDER_ID = MAX(ORDER_ID),
						[USER_NAME] = NAME, 
						NULL, NULL, NULL, NULL, max(REGIST_DATETIME),  max(Order_DateTime), 'F'
				FROM	TB_ORDER 
				WHERE	USER_ID = '' 
				GROUP BY NAME--, REGIST_DATETIME
		) TB
		WHERE (TB.[USER_NAME] LIKE  '%' + @SEARCHTXT + '%' OR  TB.[USER_ID] LIKE  '%' + @SEARCHTXT + '%') AND
		ORDER_DATE BETWEEN @START_DATE AND  @END_DATE AND
		(MEMBER_TYPE =  (CASE WHEN @MEMBER_TYPE <> '' THEN @MEMBER_TYPE ELSE MEMBER_TYPE END))

		--SELECT	ORDER_ID,
		--		[USER_NAME],
		--		[USER_ID],
		--		CARD_CODE,
		--		JOIN_TYPE, 
		--		WEDDING_DATE, 
		--		REGIST_DATETIME,
		--		ORDER_DATE,
		--		MEMBER_TYPE
		--FROM (
		--		-- 회원
			
		--		SELECT ORDER_ID = MAX(ORDER_ID),
		--			   [USER_NAME] = A.NAME,
		--			   [USER_ID] = A.USER_ID,
		--			   CARD_CODE = B.CARD_CODE,
		--			   JOIN_TYPE = B.REFERER_SALES_GUBUN, 
		--			   WEDDING_DATE = B.WEDDING_DATE, 
		--			   REGIST_DATETIME = B.REGIST_DATETIME,
		--			   ORDER_DATE = A.REGIST_DATETIME,
		--			   MEMBER_TYPE = 'M'
		--		FROM BARUNSON.DBO.TB_ORDER A INNER JOIN 
		--			 BARUNSON.DBO.VW_USER_TEST B ON A.USER_ID = B.USER_ID 
		--		GROUP BY A.NAME, A.USER_ID, B.CARD_CODE, B.REFERER_SALES_GUBUN,
		--				 B.WEDDING_DATE, B.REGIST_DATETIME, A.REGIST_DATETIME

		--		UNION
			
		--		-- 비회원

		--		SELECT  ORDER_ID = MAX(ORDER_ID),
		--				[USER_NAME] = NAME, 
		--				NULL, NULL, NULL, NULL, NULL, REGIST_DATETIME, 'F'
		--		FROM TB_ORDER 
		--		WHERE USER_ID = '' 
		--		GROUP BY NAME, REGIST_DATETIME

		--	) TB
		--WHERE (TB.[USER_NAME] LIKE  '%' + @SEARCHTXT + '%' OR  TB.[USER_ID] LIKE  '%' + @SEARCHTXT + '%') AND
		--	   ORDER_DATE BETWEEN @START_DATE AND  @END_DATE AND
		--	  (MEMBER_TYPE =  (CASE WHEN @MEMBER_TYPE <> '' THEN @MEMBER_TYPE ELSE MEMBER_TYPE END))

	END ELSE BEGIN

		SELECT	ORDER_ID,
				[USER_NAME],
				[USER_ID],
				CARD_CODE,
				JOIN_TYPE, 
				WEDDING_DATE, 
				REGIST_DATETIME,
				ORDER_DATE,
				MEMBER_TYPE
		FROM (
				-- 회원
			
				SELECT ORDER_ID = MAX(ORDER_ID), 
					   [USER_NAME] = A.NAME,
					   [USER_ID] = A.USER_ID,
					   CARD_CODE = B.CARD_CODE,
					   JOIN_TYPE = B.REFERER_SALES_GUBUN, 
					   WEDDING_DATE = B.WEDDING_DATE, 
					   REGIST_DATETIME = B.REGIST_DATETIME,
					   ORDER_DATE = A.REGIST_DATETIME,
					   MEMBER_TYPE = 'M'
				FROM BARUNSON.DBO.TB_ORDER A INNER JOIN 
					 BARUNSON.DBO.VW_USER_TEST B ON A.USER_ID = B.USER_ID
				GROUP BY A.NAME, A.USER_ID, B.CARD_CODE, B.REFERER_SALES_GUBUN,
						 B.WEDDING_DATE, B.REGIST_DATETIME, A.REGIST_DATETIME

				UNION
			
				-- 비회원

				SELECT ORDER_ID = MAX(ORDER_ID), [USER_NAME] = NAME, NULL, NULL, NULL, NULL, NULL, REGIST_DATETIME, 'F'
				FROM TB_ORDER 
				WHERE USER_ID = '' 
				GROUP BY NAME, REGIST_DATETIME

			) TB
		WHERE (TB.[USER_NAME] LIKE  '%' + @SEARCHTXT + '%' OR  TB.[USER_ID] LIKE  '%' + @SEARCHTXT + '%') AND
			  (MEMBER_TYPE =  (CASE WHEN @MEMBER_TYPE <> '' THEN @MEMBER_TYPE ELSE MEMBER_TYPE END))

	END 
	



 END ELSE BEGIN

	IF @START_DATE IS NOT NULL AND @END_DATE IS NOT NULL BEGIN

		SELECT ORDER_ID,
			   [USER_NAME],
			   [USER_ID],
			   CARD_CODE,
			   JOIN_TYPE, 
			   WEDDING_DATE, 
			   REGIST_DATETIME,
			   ORDER_DATE,
			   MEMBER_TYPE
		FROM (
				-- 회원
			
				SELECT ORDER_ID = MAX(ORDER_ID), 
					   [USER_NAME] = A.NAME,
					   [USER_ID] = A.USER_ID,
					   CARD_CODE = B.CARD_CODE,
					   JOIN_TYPE = B.REFERER_SALES_GUBUN, 
					   WEDDING_DATE = B.WEDDING_DATE, 
					   REGIST_DATETIME = B.REGIST_DATETIME,
					   ORDER_DATE = A.REGIST_DATETIME,
					   MEMBER_TYPE = 'M'
				FROM BARUNSON.DBO.TB_ORDER A INNER JOIN 
					 BARUNSON.DBO.VW_USER_TEST B ON A.USER_ID = B.USER_ID
				GROUP BY A.NAME, A.USER_ID, B.CARD_CODE, B.REFERER_SALES_GUBUN,
						 B.WEDDING_DATE, B.REGIST_DATETIME, A.REGIST_DATETIME

				UNION
			
				-- 비회원

				SELECT  ORDER_ID = MAX(ORDER_ID), 
						[USER_NAME] = NAME, 
						NULL, 
						NULL, 
						NULL, 
						NULL, 
						NULL, 
						REGIST_DATETIME, 
						'F'
				FROM TB_ORDER 
				WHERE USER_ID = '' 
				GROUP BY NAME, REGIST_DATETIME

			) TB
		WHERE ORDER_DATE BETWEEN @START_DATE AND  @END_DATE AND
			  (MEMBER_TYPE =  (CASE WHEN @MEMBER_TYPE <> '' THEN @MEMBER_TYPE ELSE MEMBER_TYPE END))

	END ELSE BEGIN 

		SELECT ORDER_ID,
			   [USER_NAME],
			   [USER_ID],
			   CARD_CODE,
			   JOIN_TYPE, 
			   WEDDING_DATE, 
			   REGIST_DATETIME,
			   ORDER_DATE,
			   MEMBER_TYPE
		FROM (
				-- 회원
			
				SELECT ORDER_ID = MAX(ORDER_ID), 
					   [USER_NAME] = A.NAME,
					   [USER_ID] = A.USER_ID,
					   CARD_CODE = B.CARD_CODE,
					   JOIN_TYPE = B.REFERER_SALES_GUBUN, 
					   WEDDING_DATE = B.WEDDING_DATE, 
					   REGIST_DATETIME = B.REGIST_DATETIME,
					   ORDER_DATE = A.REGIST_DATETIME,
					   MEMBER_TYPE = 'M'
				FROM BARUNSON.DBO.TB_ORDER A INNER JOIN 
					 BARUNSON.DBO.VW_USER_TEST B ON A.USER_ID = B.USER_ID
				GROUP BY A.NAME, A.USER_ID, B.CARD_CODE, B.REFERER_SALES_GUBUN,
						 B.WEDDING_DATE, B.REGIST_DATETIME, A.REGIST_DATETIME


				UNION
			
				-- 비회원

				SELECT  ORDER_ID = MAX(ORDER_ID), 
						[USER_NAME] = NAME, 
						NULL, 
						NULL, 
						NULL, 
						NULL, 
						NULL, 
						REGIST_DATETIME, 
						'F'
				FROM TB_ORDER 
				WHERE USER_ID = '' 
				GROUP BY NAME, REGIST_DATETIME

			) TB
			WHERE MEMBER_TYPE =  (CASE WHEN @MEMBER_TYPE <> '' THEN @MEMBER_TYPE ELSE MEMBER_TYPE END)

	END 
	

 END
GO
