IF OBJECT_ID (N'dbo.SP_T_ADMIN_MENU', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_T_ADMIN_MENU
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_T_ADMIN_MENU]
/***************************************************************
작성자	:	표수현
작성일	:	2020-02-15
DESCRIPTION	:	ADMIN - 메뉴 저장
SPECIAL LOGIC	:
******************************************************************
MODIFICATION
******************************************************************
수정일           작업자                DESCRIPTION
==================================================================
******************************************************************/
 @GUBUN				CHAR(1) = 'I',			--  I(대문자 I) : 저장 / U : 수정 / D : 삭제 
 @MENU_TYPE_CODE	VARCHAR(50) = NULL,		-- 분류_구분_코드 (메인 CTC01 / 카테고리 CTC02)
 @MENU_NAME1		VARCHAR(100) = NULL,	-- 대분류명
 @MENU_STEP1		CHAR(1) = NULL,			-- 
 @MENU_URL1			VARCHAR(1000) = NULL,	-- 
 @SORT				INT = NULL,				-- 분류순서
 @IMAGE_URL1		VARCHAR(1000) = NULL,	--
 @DEPTH2_YN			INT = 0,				-- 중분류 존재 여부 
 @DEL_UP_MENU_ID	INT = NULL,				-- 삭제하거나 수정할 대분류 카테고리ID
 @DEPTH2			MENU_DEPTHLISTTYPE READONLY,
 @ID				OBJECTTYPE READONLY		-- 테이블 반환 매개변수 
AS

--select * from TB_COMMON_MENU
 SET NOCOUNT ON
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

 -- 순서 업데이트  
 UPDATE TB_COMMON_MENU
 SET TB_COMMON_MENU.SORT = B.ID2
 FROM TB_COMMON_MENU A INNER JOIN @ID B ON A.MENU_ID = B.ID
 WHERE A.MENU_TYPE_CODE = @MENU_TYPE_CODE

 IF @GUBUN = 'I' BEGIN
	
	DECLARE @CATEGORY_ID  INT
	DECLARE @PARENT_MENU_ID  INT

	/* 대분류 정보를 저장하므로 PARENT_CATEGORY_ID는 NULL값이 들어감 */
	INSERT INTO DBO.TB_COMMON_MENU (PARENT_MENU_ID, MENU_NAME, MENU_TYPE_CODE, MENU_URL, MENU_STEP, SORT, DISPLAY_YN) 
	VALUES (NULL, @MENU_NAME1, @MENU_TYPE_CODE, @MENU_URL1, @MENU_STEP1, @SORT, 'Y')
	
	IF @DEPTH2_YN > 0 BEGIN 

		SET @PARENT_MENU_ID = @@IDENTITY

		SELECT @PARENT_MENU_ID = ISNULL(MAX(MENU_ID), 0) 
		FROM DBO.TB_COMMON_MENU
	
		INSERT INTO DBO.TB_COMMON_MENU (PARENT_MENU_ID, MENU_NAME, MENU_TYPE_CODE, MENU_URL, MENU_STEP, SORT,IMAGE_URL) 
		SELECT  @PARENT_MENU_ID, MENU_NAME, MENU_TYPE_CODE, MENU_URL, MENU_STEP, SORT,IMAGE_URL
		FROM	@DEPTH2

	END 
	
 END ELSE IF @GUBUN = 'U' BEGIN 
		
		UPDATE TB_COMMON_MENU
		SET MENU_NAME = @MENU_NAME1,
			MENU_TYPE_CODE = @MENU_TYPE_CODE,
			MENU_URL = @MENU_URL1,
			IMAGE_URL = @IMAGE_URL1
		WHERE MENU_ID = @DEL_UP_MENU_ID

		UPDATE TB_COMMON_MENU
		SET TB_COMMON_MENU.MENU_NAME = B.MENU_NAME,
			TB_COMMON_MENU.MENU_TYPE_CODE = B.MENU_TYPE_CODE,
			TB_COMMON_MENU.MENU_URL  = B.MENU_URL,
			TB_COMMON_MENU.IMAGE_URL = B.IMAGE_URL
		FROM TB_COMMON_MENU A INNER JOIN 
			@DEPTH2 B ON A.Menu_ID = B.Menu_ID

 END

GO
