IF OBJECT_ID (N'dbo.SP_T_ADMIN_POPUP', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_T_ADMIN_POPUP
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_T_ADMIN_POPUP]
/***************************************************************
작성자	:	표수현
작성일	:	2020-02-15
DESCRIPTION	:	ADMIN - @GUBUN - D1 -> 배너 삭제
						@GUBUN - D2 -> 배너 분류 삭제
						@GUBUN - S ->  배너 등록
SPECIAL LOGIC	:
******************************************************************
MODIFICATION
******************************************************************
수정일           작업자                DESCRIPTION
==================================================================
******************************************************************/
 @GUBUN			CHAR(2) = NULL,
 @ID OBJECTTYPE READONLY, -- 테이블 반환 매개변수 
 @POPUP_TITLE VARCHAR(200) = NULL, 
 @POPUP_PC_YN CHAR(1) = NULL, 
 @POPUP_MOBILE_YN CHAR(1) = NULL, 
 @POPUP_LOCATION_TOP INT = NULL,
 @POPUP_LOCATION_LEFT INT = NULL,
 @POPUP_HEIGHT INT = NULL,
 @POPUP_WIDTH INT = NULL, 
 @REGIST_USER_ID VARCHAR(50) = NULL, 
 @REGIST_IP VARCHAR(15) = NULL,  
 @UPDATE_USER_ID VARCHAR(50) = NULL, 
 @UPDATE_IP VARCHAR(15) = NULL, 
 
 @POPUP_TYPE_CODE VARCHAR(50) = NULL, 
 @IMAGE_URL VARCHAR(1000) = NULL, 
 @LINK_URL VARCHAR(1000) = NULL, 
 @PERIOD_TYPE_CODE VARCHAR(50) = NULL, 
 @START_DATE VARCHAR(10) = NULL, 
 @START_TIME VARCHAR(2) = NULL, 
 @END_DATE VARCHAR(10) = NULL, 
 @END_TIME VARCHAR(2) = NULL
AS

 SET NOCOUNT ON
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 

 IF @GUBUN = 'D' BEGIN

	-- 배너만 삭제 
	 DELETE FROM DBO.TB_POPUP_ITEM
			FROM DBO.TB_POPUP_ITEM A INNER JOIN 
			@ID B ON A.POPUP_ID = B.ID

	DELETE FROM DBO.TB_POPUP
			FROM DBO.TB_POPUP A INNER JOIN 
			@ID B ON A.POPUP_ID = B.ID

 END ELSE IF @GUBUN = 'S' BEGIN 

		INSERT 	DBO.TB_POPUP (POPUP_TITLE, POPUP_PC_YN, POPUP_MOBILE_YN, POPUP_LOCATION_TOP, POPUP_LOCATION_LEFT, POPUP_HEIGHT, POPUP_WIDTH,
							REGIST_USER_ID, REGIST_DATETIME, REGIST_IP, UPDATE_USER_ID, UPDATE_DATETIME, UPDATE_IP)
		VALUES (@POPUP_TITLE, @POPUP_PC_YN, @POPUP_MOBILE_YN, @POPUP_LOCATION_TOP, @POPUP_LOCATION_LEFT, @POPUP_HEIGHT, @POPUP_WIDTH,
				@REGIST_USER_ID, GETDATE(), @REGIST_IP, @UPDATE_USER_ID, GETDATE(), @UPDATE_IP)

		DECLARE @PARENT_POPUP_ID INT = @@IDENTITY

		INSERT DBO.TB_POPUP_ITEM  (POPUP_ID, POPUP_TYPE_CODE, IMAGE_URL, LINK_URL, PERIOD_TYPE_CODE, START_DATE, START_TIME, END_DATE, END_TIME,
								REGIST_USER_ID, REGIST_DATETIME, REGIST_IP, UPDATE_USER_ID, UPDATE_DATETIME, UPDATE_IP)
		VALUES (@PARENT_POPUP_ID, @POPUP_TYPE_CODE, @IMAGE_URL, @LINK_URL, @PERIOD_TYPE_CODE, @START_DATE, @START_TIME, @END_DATE, @END_TIME,
								@REGIST_USER_ID, GETDATE(), @REGIST_IP, @UPDATE_USER_ID,  GETDATE(), @UPDATE_IP)


 END 
GO
