IF OBJECT_ID (N'dbo.SP_T_SEND_ORDER_BIZTALK_HR', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_T_SEND_ORDER_BIZTALK_HR
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_T_SEND_ORDER_BIZTALK_HR] 
/***************************************************************
작성자	:	표수현
작성일	:	2020-02-15
DESCRIPTION	:	결재 완료시 SMS 보내기 
SPECIAL LOGIC	:
/*  
SP_MAILSEND_ORDER 2538241,'시스템테스트','010-9484-4697','DEVELOPER@BARUNN.NET','','2017-09-22 오후 4:58:00','SA','초대장주문',''  


EXEC SP_T_SEND_ORDER_BIZTALK_HR 'M2108160010'
TB_ORDER
청첩장주문 - 초대장주문
M2108100002

@ORDER_CDOE 
*/  
******************************************************************
MODIFICATION
******************************************************************
수정일           작업자                DESCRIPTION
==================================================================
******************************************************************/
 @ORDER_CDOE VARCHAR(25)
AS  

	/* 20201123 추가 START */
	DECLARE	@ERRNUM INT,
			@ERRSEV INT, 
			@ERRSTATE INT, 
			@ERRPROC VARCHAR(50), 
			@ERRLINE INT, 
			@ERRMSG VARCHAR(2000)
	/* 20201123 추가 END */

	DECLARE      @SMS_PHONE     [VARCHAR](20)  
	DECLARE      @SMS_MSG       [VARCHAR](200)  
	DECLARE      @EMAIL         [VARCHAR](100)  
	DECLARE      @EMAIL_SENDER  [VARCHAR](50)  
	DECLARE      @EMAIL_TITLE   [VARCHAR](50)  
	DECLARE      @EMAIL_MSG     [VARCHAR](8000)   
	DECLARE      @SMS_NEW_MSG   [VARCHAR](200)
	DECLARE      @COMPANY_SEQ   AS INT   

	DECLARE @DATE DATETIME
	 
    --########## 알림톡 시작 ############ 
    DECLARE @CONTENT VARCHAR(800) 
    DECLARE @TEMPLATE_CODE VARCHAR(30)
    DECLARE @SENDER_KEY VARCHAR(40)
    DECLARE @MSG_TYPE INT 
    DECLARE @KKO_BTN_TYPE CHAR(1)
    DECLARE @KKO_BTN_INFO VARCHAR(4000)
    DECLARE @CALLBACK VARCHAR(15)
    DECLARE @LMS_SUBJECT VARCHAR(200)
	DECLARE @SALES_GUBUN  VARCHAR(2) = 'BM'
	DECLARE @DIV VARCHAR(20) = '결제완료'

	DECLARE @CARD_NAME VARCHAR(20)  
    DECLARE @BANK_NAME VARCHAR(200)  
    DECLARE @BANK_ACCOUNT VARCHAR(100)  
    DECLARE @LAST_TOTAL_PRICE INT 
    DECLARE @SETTLE_METHOD VARCHAR(50) 
	DECLARE @SETTLE_METHOD_CODE VARCHAR(10)  
    DECLARE @SETTLE_PRICE INT   
    DECLARE @TARGET_DT VARCHAR(10)  
	DECLARE @ORDER_SEQ INT
	DECLARE @ORDER_NAME NVARCHAR(100)
	DECLARE @ORDER_HPHONE VARCHAR(20)  

	
    -- 결제정보
	SELECT	@CARD_NAME = F.PRODUCT_NAME,
			@ORDER_SEQ = A.ORDER_ID , 
			@ORDER_NAME = A.[NAME],
			@LAST_TOTAL_PRICE = A.ORDER_PRICE,
			@SETTLE_PRICE = A.PAYMENT_PRICE ,
			@SETTLE_METHOD = C.CODE_NAME,
			@ORDER_HPHONE = CELLPHONE_NUMBER,
			@SETTLE_METHOD_CODE   = C.CODE,
			@BANK_NAME = A.FINANCE_NAME,
			@BANK_ACCOUNT = A.ACCOUNT_NUMBER
	FROM  BARUNSON.DBO.TB_ORDER A INNER JOIN 
			BARUNSON.DBO.TB_COMMON_CODE C ON A.PAYMENT_METHOD_CODE = C.CODE AND C.CODE_GROUP = 'PAYMENT_METHOD_CODE' INNER JOIN 
			BARUNSON.DBO.TB_COMMON_CODE D ON A.PAYMENT_STATUS_CODE = D.CODE AND D.CODE_GROUP = 'PAYMENT_STATUS_CODE' INNER JOIN 
			BARUNSON.DBO.TB_ORDER_PRODUCT E ON A.ORDER_ID = E.ORDER_ID  INNER JOIN 
			BARUNSON.DBO.TB_PRODUCT F ON E.PRODUCT_ID = F.PRODUCT_ID
	WHERE	A.ORDER_CODE = @ORDER_CDOE

	
	IF @SETTLE_METHOD_CODE = 'PMC02' BEGIN 
		SET @DIV = '무통장결제요청'
	END ELSE BEGIN 
		SET @DIV = '결제완료'
	END 

    -- 알림톡 컨텐츠 가져오기
    SELECT	@CONTENT = CONTENT , 
			@MSG_TYPE = MSG_TYPE,
			@SENDER_KEY = SENDER_KEY,
			@TEMPLATE_CODE = TEMPLATE_CODE,
			@KKO_BTN_TYPE = KKO_BTN_TYPE,
			@KKO_BTN_INFO = KKO_BTN_INFO,
			@CALLBACK = CALLBACK,
			@LMS_SUBJECT = LMS_SUBJECT,
			@COMPANY_SEQ = COMPANY_SEQ
    FROM	BAR_SHOP1.DBO.WEDD_BIZTALK    
    WHERE   SALES_GUBUN = @SALES_GUBUN AND
			DIV = @DIV AND 
			USE_YORN = 'Y'  


        -- 변수세팅
        IF @TARGET_DT <> '' AND CHARINDEX('#{0000-00-00}',@CONTENT) > 0
        BEGIN 
            SET @CONTENT = REPLACE(@CONTENT, '#{0000-00-00}', @TARGET_DT) -- 초안등록
        END

        IF @ORDER_NAME <> '' AND CHARINDEX('#{NAME}',@CONTENT) > 0
        BEGIN  
            SET @CONTENT = REPLACE(@CONTENT, '#{NAME}', @ORDER_NAME)
        END

        IF @ORDER_SEQ <> '' AND (CHARINDEX('#{0000000}',@CONTENT) > 0 OR CHARINDEX('#{주문번호}',@CONTENT) > 0)
        BEGIN
            SET @CONTENT = REPLACE(@CONTENT, '#{0000000}', @ORDER_CDOE)
            SET @CONTENT = REPLACE(@CONTENT, '#{주문번호}', @ORDER_CDOE)
        END

        IF @CARD_NAME <> '' AND CHARINDEX('#{상품명}',@CONTENT) > 0
        BEGIN
            SET @CONTENT = REPLACE(@CONTENT, '#{상품명}', @CARD_NAME)
        END
 
        IF @BANK_NAME <> '' AND CHARINDEX('#{입금은행명}',@CONTENT) > 0
        BEGIN
            SET @CONTENT = REPLACE(@CONTENT, '#{입금은행명}', @BANK_NAME)
        END

        IF @BANK_ACCOUNT <> '' AND CHARINDEX('#{가상계좌번호}',@CONTENT) > 0
        BEGIN
			SET @CONTENT = REPLACE(@CONTENT, '#{가상계좌번호}', @BANK_ACCOUNT)
        END

        IF @SETTLE_PRICE /*@LAST_TOTAL_PRICE*/ >= 0  AND CHARINDEX('#{입금금액}',@CONTENT) > 0
        BEGIN
            SET @CONTENT = REPLACE(@CONTENT, '#{입금금액}', @SETTLE_PRICE /*@LAST_TOTAL_PRICE*/)
		END

        IF @SETTLE_PRICE >= 0  AND (CHARINDEX('#{결제금액}',@CONTENT) > 0 OR CHARINDEX('#{금액}',@CONTENT) > 0) 
        BEGIN
            SET @CONTENT = REPLACE(@CONTENT, '#{결제금액}', @SETTLE_PRICE)
            SET @CONTENT = REPLACE(@CONTENT, '#{금액}', @SETTLE_PRICE) -- 더카드는 금액으로 들어감.
        END

        IF @SETTLE_METHOD <> '' AND (CHARINDEX('#{결제카드정보}',@CONTENT) > 0 OR CHARINDEX('#{결제수단}',@CONTENT) > 0)
        BEGIN
            SET @CONTENT = REPLACE(@CONTENT, '#{결제카드정보}', @SETTLE_METHOD)
            SET @CONTENT = REPLACE(@CONTENT, '#{결제수단}', @SETTLE_METHOD)
        END

	
		SELECT LMS_SUBJECT = @LMS_SUBJECT
			SELECT CONTENT = @CONTENT
	SELECT  CALLBACK  = @CALLBACK 
	SELECT ORDER_HPHONE  =  @ORDER_HPHONE 
	 SELECT MSG_TYPE = @MSG_TYPE
		SELECT SENDER_KEY =   @SENDER_KEY
	SELECT  TEMPLATE_CODE = @TEMPLATE_CODE
	SELECT   KKO_BTN_TYPE  = @KKO_BTN_TYPE 
	SELECT  KKO_BTN_INFO = @KKO_BTN_INFO
	SELECT   SALES_GUBUN =  @SALES_GUBUN
				                   
	SELECT  COMPANY_SEQ	=  @COMPANY_SEQ	

        INSERT INTO BAR_SHOP1.DBO.ATA_MMT_TRAN 
		(
			DATE_CLIENT_REQ, SUBJECT, CONTENT, CALLBACK, MSG_STATUS, RECIPIENT_NUM, MSG_TYPE,   
			SENDER_KEY, TEMPLATE_CODE, KKO_BTN_TYPE, KKO_BTN_INFO, 
			ETC_TEXT_1,-- SALES_GUBUN
			ETC_TEXT_2,	-- 호출프로시저
			ETC_NUM_1	-- COMPANY_SEQ 
		) 
		VALUES 
		(
			GETDATE(), @LMS_SUBJECT, @CONTENT, @CALLBACK, '1', '010-9484-4697', @MSG_TYPE,
			@SENDER_KEY, @TEMPLATE_CODE, @KKO_BTN_TYPE, @KKO_BTN_INFO, 
			@SALES_GUBUN,   
			'BARUNSON.DBO.SP_T_SEND_ORDER_BIZTALK',
			@COMPANY_SEQ	
		)
		
		--insert SMS_Log(ORDER_CDOE, regdate, CONTENT, ORDER_HPHONE)
		--values (@ORDER_CDOE, getdate(), @CONTENT, @ORDER_HPHONE)

GO
