IF OBJECT_ID (N'dbo.SP_S_USER_PRODUCT_Search', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_S_USER_PRODUCT_Search
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_S_USER_PRODUCT_Search]
/***************************************************************
작성자	:	표수현
작성일	:	2020-02-15
DESCRIPTION	:	프런트 - 상품 리스트 정보 
SPECIAL LOGIC	:  SP_S_USER_PRODUCT_SEARCH @SEARCH_KEYWORD = 'MC'
******************************************************************
MODIFICATION
******************************************************************
수정일           작업자                DESCRIPTION
==================================================================
******************************************************************/
 @USER_ID VARCHAR(50) = NULL,
 --@CATEGORY_ID	INT = NULL,
 @SORT_GUBUN INT = NULL,
 @SEARCH_KEYWORD VARCHAR(10) = NULL
AS

 SET NOCOUNT ON
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

 SELECT * 
 FROM (

		SELECT	A.REGIST_DATETIME,
				A.DISPLAY_YN,
				A.UPDATE_DATETIME, 
				A.PRICE,
				B.CODE_NAME, A.PRODUCT_BRAND_CODE, A.PRODUCT_ID, 
				A.MAIN_IMAGE_URL, 
				A.PRODUCT_NAME, 
				A.PRODUCT_CODE,
				WISHCNT = CASE WHEN @USER_ID is null then 0 Else (SELECT COUNT(*) FROM TB_WISH_LIST WHERE PRODUCT_ID = A.PRODUCT_ID AND USER_ID = @USER_ID) End,
				TOTALSALE = CASE WHEN @SORT_GUBUN = 2 Then (SELECT COUNT(*) FROM TB_ORDER P INNER JOIN TB_ORDER_PRODUCT Q ON P.ORDER_ID = Q.ORDER_ID WHERE Q.PRODUCT_ID = A.PRODUCT_ID) Else 0 End
		FROM	TB_PRODUCT A INNER JOIN  TB_COMMON_CODE B ON A.PRODUCT_BRAND_CODE = B.CODE
		WHERE   (A.PRODUCT_CODE LIKE '%' + @SEARCH_KEYWORD + '%' OR A.PRODUCT_NAME LIKE '%' + @SEARCH_KEYWORD + '%')
				AND A.DISPLAY_YN = 'Y'

	  ) TB
	   ORDER BY   
			CASE WHEN @SORT_GUBUN = 0  THEN TB.REGIST_DATETIME END DESC,  
			CASE WHEN @SORT_GUBUN = 1  THEN TB.REGIST_DATETIME END DESC,  
			CASE WHEN @SORT_GUBUN = 2 THEN TB.TOTALSALE  END ASC  ,
			CASE WHEN @SORT_GUBUN = 3  THEN TB.PRICE END ASC  ,
			CASE WHEN @SORT_GUBUN = 4  THEN TB.PRICE  END DESC 


GO
