IF OBJECT_ID (N'dbo.SP_S_ADMIN_CATEGORY_DISPLAYCNT', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_S_ADMIN_CATEGORY_DISPLAYCNT
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_S_ADMIN_CATEGORY_DISPLAYCNT]
/***************************************************************
작성자	:	표수현
작성일	:	2020-02-15
DESCRIPTION	:	ADMIN - 중분류 카테고리별로 진열되어 있는 상품카운트까지 같이 노출
SPECIAL LOGIC	: SP_S_ADMIN_CATEGORY_DISPLAYCNT 'CTC02'
******************************************************************
MODIFICATION
******************************************************************
수정일           작업자                DESCRIPTION
==================================================================
******************************************************************/
 @CATEGORY_TYPE_CODE VARCHAR(100) = 'CTC02'	--   CTC01 : 메인 / CTC02 : 카테고리 
AS

 SET NOCOUNT ON
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

 IF @CATEGORY_TYPE_CODE = 'CTC01' BEGIN -- 메인, 즉 대분류만 노출 

	 SELECT	CATEGORY_ID, PARENT_CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE_CODE, CATEGORY_NAME_TYPE_CODE,
			CATEGORY_NAME_PC, CATEGORY_NAME_PC_URL = ISNULL(CATEGORY_NAME_PC_URL, ''), CATEGORY_NAME_MOBILE, CATEGORY_NAME_MOBILE_URL = ISNULL(CATEGORY_NAME_MOBILE_URL, ''), 
			CATEGORY_STEP = ISNULL(CATEGORY_STEP,1), SORT = ISNULL(SORT, 1), DISPLAY_YN = ISNULL(DISPLAY_YN, 'Y'), 
			CNT = (
						SELECT COUNT(*) FROM TB_PRODUCT_CATEGORY B  INNER JOIN TB_PRODUCT C ON B.PRODUCT_ID = C.PRODUCT_ID 
						WHERE C.DISPLAY_YN = 'Y' AND  B.CATEGORY_ID = A.CATEGORY_ID
				  )
	 FROM	TB_CATEGORY A
	 WHERE	CATEGORY_TYPE_CODE = @CATEGORY_TYPE_CODE 
			ORDER BY SORT ASC

 END ELSE BEGIN -- 카테고리, 즉 중분류만 노출 

	SELECT	CATEGORY_ID, PARENT_CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE_CODE, CATEGORY_NAME_TYPE_CODE,
			CATEGORY_NAME_PC, CATEGORY_NAME_PC_URL = ISNULL(CATEGORY_NAME_PC_URL, ''), CATEGORY_NAME_MOBILE, CATEGORY_NAME_MOBILE_URL = ISNULL(CATEGORY_NAME_MOBILE_URL, ''), 
			CATEGORY_STEP = ISNULL(CATEGORY_STEP,1), SORT = ISNULL(SORT, 1), DISPLAY_YN = ISNULL(DISPLAY_YN, 'Y'), 
			CNT =(
						SELECT COUNT(*) FROM TB_PRODUCT_CATEGORY B  INNER JOIN TB_PRODUCT C ON B.PRODUCT_ID = C.PRODUCT_ID 
						WHERE C.DISPLAY_YN = 'Y' AND  B.CATEGORY_ID = A.CATEGORY_ID
				 )
			--CNT = (SELECT COUNT(*) FROM TB_PRODUCT_CATEGORY B WHERE B.CATEGORY_ID = A.CATEGORY_ID)
	 FROM	TB_CATEGORY A
	 WHERE	CATEGORY_TYPE_CODE = @CATEGORY_TYPE_CODE
			ORDER BY SORT ASC, CATEGORY_STEP ASC
			--PARENT_CATEGORY_ID IS NULL 
			--PARENT_CATEGORY_ID IS NOT NULL 
 END 
GO
