IF OBJECT_ID (N'dbo.SP_S_ADMIN_CATEGORY', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_S_ADMIN_CATEGORY
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_S_ADMIN_CATEGORY]
/***************************************************************
작성자	:	표수현
작성일	:	2020-02-15
DESCRIPTION	:	ADMIN - 카테고리 전체 리스트 
SPECIAL LOGIC	:  SP_S_ADMIN_CATEGORY 2, 'N', NULL, NULL
******************************************************************
MODIFICATION
******************************************************************
수정일           작업자                DESCRIPTION
==================================================================
******************************************************************/
 @GUBUN					INT = 1,		--  1 : 메인대분류 / 2 : 카테고리대분류  / 3 : 카테고리중분류 
 @DETAILVIEW_YN			CHAR(1) = 'N', 	--  카테고리 상세 리스트 디스플레이 Y/N
 @PARENT_CATEGORY_ID	INT = NULL,		-- 상위 대분류 카테고리번호 
 @CATEGORY_ID			INT = NULL		-- 선택한 카테고리의 번호 
AS

 SET NOCOUNT ON
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

 IF @GUBUN = 1 BEGIN  -- 메인대분류 

	IF @DETAILVIEW_YN = 'Y' BEGIN 
			
		SELECT	CATEGORY_ID, PARENT_CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE_CODE, CATEGORY_NAME_TYPE_CODE,
  				CATEGORY_NAME_PC, CATEGORY_NAME_PC_URL, CATEGORY_NAME_MOBILE, CATEGORY_NAME_MOBILE_URL, CATEGORY_STEP,
				SORT = ISNULL(SORT, 1), DISPLAY_YN  = ISNULL(DISPLAY_YN, 'Y')
		FROM	TB_CATEGORY  
		WHERE	CATEGORY_TYPE_CODE = 'CTC01' AND 
				PARENT_CATEGORY_ID IS NULL AND
				CATEGORY_ID = @CATEGORY_ID
				ORDER BY SORT

	END ELSE BEGIN 

		
		SELECT	CATEGORY_ID, PARENT_CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE_CODE, CATEGORY_NAME_TYPE_CODE,
  				CATEGORY_NAME_PC, CATEGORY_NAME_PC_URL, CATEGORY_NAME_MOBILE, CATEGORY_NAME_MOBILE_URL, CATEGORY_STEP,
				SORT = ISNULL(SORT, 1), DISPLAY_YN  = ISNULL(DISPLAY_YN, 'Y')
		FROM	TB_CATEGORY  
		WHERE	CATEGORY_TYPE_CODE = 'CTC01' AND 
				PARENT_CATEGORY_ID IS NULL 
				ORDER BY SORT

	END
	

 END ELSE IF  @GUBUN = 2 BEGIN   -- 카테고리대분류 
 
	IF @DETAILVIEW_YN = 'Y' BEGIN 
	
		 SELECT	CATEGORY_ID, PARENT_CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE_CODE, CATEGORY_NAME_TYPE_CODE,
  				CATEGORY_NAME_PC, CATEGORY_NAME_PC_URL, --CATEGORY_NAME_MOBILE, CATEGORY_NAME_MOBILE_URL, 
				CATEGORY_STEP,
				SORT = ISNULL(SORT, 1), DISPLAY_YN  = ISNULL(DISPLAY_YN, 'Y')
		 FROM	TB_CATEGORY  
		 WHERE	CATEGORY_TYPE_CODE = 'CTC02' AND 
				--ISNULL(PARENT_CATEGORY_ID, '') = ISNULL(@PARENT_CATEGORY_ID, '') AND 
				--PARENT_CATEGORY_ID = @PARENT_CATEGORY_ID AND
				CATEGORY_ID = @CATEGORY_ID OR PARENT_CATEGORY_ID = @CATEGORY_ID
				ORDER BY SORT

	END ELSE BEGIN 
		
		 SELECT	CATEGORY_ID, PARENT_CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE_CODE, CATEGORY_NAME_TYPE_CODE,
  				CATEGORY_NAME_PC, CATEGORY_NAME_PC_URL, --CATEGORY_NAME_MOBILE, CATEGORY_NAME_MOBILE_URL, 
				CATEGORY_STEP,
				SORT = ISNULL(SORT, 1), DISPLAY_YN  = ISNULL(DISPLAY_YN, 'Y')
		 FROM	TB_CATEGORY  
		 WHERE	CATEGORY_TYPE_CODE = 'CTC02' AND 
				PARENT_CATEGORY_ID IS NULL
				--ISNULL(PARENT_CATEGORY_ID, '') = ISNULL(@PARENT_CATEGORY_ID, '') 
				--ISNULL(PARENT_CATEGORY_ID, '') = (CASE WHEN @PARENT_CATEGORY_ID IS NOT NULL THEN @PARENT_CATEGORY_ID ELSE ISNULL(PARENT_CATEGORY_ID, '') END)
				ORDER BY SORT

	END

 END ELSE BEGIN --카테고리중분류

		 SELECT	CATEGORY_ID, PARENT_CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE_CODE, CATEGORY_NAME_TYPE_CODE,
  				CATEGORY_NAME_PC, CATEGORY_NAME_PC_URL, CATEGORY_NAME_MOBILE, CATEGORY_NAME_MOBILE_URL, CATEGORY_STEP,
				SORT = ISNULL(SORT, 1), DISPLAY_YN  = ISNULL(DISPLAY_YN, 'Y')
		 FROM	TB_CATEGORY  
		 WHERE	CATEGORY_TYPE_CODE = 'CTC02' AND 
				PARENT_CATEGORY_ID = @PARENT_CATEGORY_ID
				--ISNULL(PARENT_CATEGORY_ID, '') = ISNULL(@PARENT_CATEGORY_ID, '') 
				--ISNULL(PARENT_CATEGORY_ID, '') = (CASE WHEN @PARENT_CATEGORY_ID IS NOT NULL THEN @PARENT_CATEGORY_ID ELSE ISNULL(PARENT_CATEGORY_ID, '') END)
				ORDER BY SORT

 END

GO
