IF OBJECT_ID (N'dbo.SP_S_ADMIN_COUPON_PUBLISH_MEMBER', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_S_ADMIN_COUPON_PUBLISH_MEMBER
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_S_ADMIN_COUPON_PUBLISH_MEMBER]
/***************************************************************
작성자	:	표수현
작성일	:	2021-05-15
DESCRIPTION	:	
@GUBUN 1 -> 쿠폰이 기발급된 주문자 리스트 정보 
@GUBUN 2 -> 쿠폰을 발급할 전체 주문자 리스트 정보 
SPECIAL LOGIC	: SP_S_ADMIN_COUPON_PUBLISH_MEMBER 1 , 2, NULL, NULL
******************************************************************
MODIFICATION
******************************************************************
수정일           작업자                DESCRIPTION
==================================================================
******************************************************************/
 @GUBUN INT = 1,
 @COUPONID INT = NULL,
 @SEARCHTXT VARCHAR(100) = NULL, -- 검색어 
 @USEYN VARCHAR(2) = NULL
AS

 SET NOCOUNT ON
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

 DECLARE @COUPON_NAME VARCHAR(200)

 SELECT @COUPON_NAME = COUPON_NAME 
 FROM BARUNSON.DBO.TB_COUPON
 WHERE COUPON_ID = @COUPONID

 IF @USEYN = 'ALL' BEGIN SET @USEYN = '' END

 IF @GUBUN = 1 BEGIN

	--  쿠폰이 기발급된 주문자 리스트 정보 

	IF @SEARCHTXT IS NOT NULL AND @SEARCHTXT <> '' BEGIN 
		
		SELECT	COUPON_PUBLISH_ID = C.COUPON_PUBLISH_ID,
				USER_ID = A.USER_ID, 
				USER_NAME = A.NAME, 
				PHONE_NUMBER = A.CELLPHONE_NUMBER, 
				WEDDING_DATE = A.WEDDING_DATE, 
				JOIN_DATETIME = A.JOIN_DATETIME,
				--사용일
				USEDATE = C.USE_DATETIME, 
				
				--사용여부
				USE_YN = C.USE_YN,
				
				--회수일
				COLLECTIONDATE = C.RETRIEVE_DATETIME,

				-- 유효기간 
				PUBLISH_END_DATE = C.EXPIRATION_DATE,

				-- 발급일(회원한테 쿠폰을 발급한 날짜)
				REGIST_DATETIME = C.REGIST_DATETIME

		FROM	BARUNSON.DBO.VW_USER A INNER JOIN 
				BARUNSON.DBO.TB_COUPON_PUBLISH C ON A.USER_ID = C.USER_ID INNER JOIN 
				BARUNSON.DBO.TB_COUPON D ON C.COUPON_ID = D.COUPON_ID
		WHERE C.COUPON_ID = @COUPONID AND
				(A.NAME LIKE  '%' + @SEARCHTXT + '%' OR  A.USER_ID LIKE  '%' + @SEARCHTXT + '%') AND
				(C.USE_YN =  (CASE WHEN @USEYN <> '' THEN @USEYN ELSE C.USE_YN END))

		--SELECT	DISTINCT 
		--		ORDER_ID = B.ORDER_ID,
		--		COUPON_PUBLISH_ID = C.COUPON_PUBLISH_ID,
		--		USER_ID = A.USER_ID, 
		--		USER_NAME = A.NAME, 
		--		PHONE_NUMBER = A.CELLPHONE_NUMBER, 
		--		WEDDING_DATE = A.WEDDING_DATE, 
		--		JOIN_DATETIME = A.JOIN_DATETIME, --,A.WEDDING_HHMM

		--		-- 유효기간 : 3가지 유형 : 날짜 지정 / 발행일로부터 X일 / 무제한
		--		PUBLISH_END_DATE = CASE WHEN D.PERIOD_METHOD_CODE = 'PMC01' THEN D.PUBLISH_END_DATE -- 날짜 지정
		--								WHEN D.PERIOD_METHOD_CODE = 'PMC02' 
		--									THEN -- 발행일로부터 X일
										
		--										CASE WHEN  D.PUBLISH_PERIOD_CODE = 'PPC01'  THEN 
		--													DATEADD(DD, 5, C.REGIST_DATETIME)		
		--											WHEN  D.PUBLISH_PERIOD_CODE = 'PPC02'   THEN 
		--													DATEADD(DD, 10, C.REGIST_DATETIME)		
		--											WHEN  D.PUBLISH_PERIOD_CODE = 'PPC03'  THEN 
		--													DATEADD(DD, 20, C.REGIST_DATETIME)		
		--											WHEN  D.PUBLISH_PERIOD_CODE = 'PPC04'   THEN 
		--													DATEADD(DD, 30, C.REGIST_DATETIME)		
		--											WHEN  D.PUBLISH_PERIOD_CODE = 'PPC05'    THEN 
		--													DATEADD(DD, 100, C.REGIST_DATETIME)		
		--										END
		--							ELSE '무제한'
		--						  END,

		--		--사용일
		--		USEDATE = C.USE_DATETIME, 
				
		--		--사용여부
		--		USE_YN = C.USE_YN,
				
		--		--회수일
		--		COLLECTIONDATE = C.RETRIEVE_DATETIME,

		--		-- 발급일(회원한테 쿠폰을 발급한 날짜)
		--		REGIST_DATETIME = C.REGIST_DATETIME
		--FROM	BARUNSON.DBO.VW_USER A INNER JOIN 
		--		BARUNSON.DBO.TB_ORDER B ON A.USER_ID = B.USER_ID INNER JOIN 
		--		BARUNSON.DBO.TB_COUPON_PUBLISH C ON A.USER_ID = C.USER_ID INNER JOIN 
		--		BARUNSON.DBO.TB_COUPON D ON C.COUPON_ID = D.COUPON_ID INNER JOIN 
		--		BARUNSON.DBO.TB_ORDER_COUPON_USE E ON B.ORDER_ID = E.ORDER_ID
		--WHERE	DATALENGTH(A.WEDDING_DATE) = 10 AND C.COUPON_ID = @COUPONID AND
		--		(A.NAME LIKE  '%' + @SEARCHTXT + '%' OR  A.USER_ID LIKE  '%' + @SEARCHTXT + '%') AND
		--		(C.USE_YN =  (CASE WHEN @USEYN <> '' THEN @USEYN ELSE C.USE_YN END))

	END ELSE BEGIN

		SELECT	COUPON_PUBLISH_ID = C.COUPON_PUBLISH_ID,
				USER_ID = A.USER_ID, 
				USER_NAME = A.NAME, 
				PHONE_NUMBER = A.CELLPHONE_NUMBER, 
				WEDDING_DATE = A.WEDDING_DATE, 
				JOIN_DATETIME = A.JOIN_DATETIME,
				--사용일
				USEDATE = C.USE_DATETIME, 
				
				--사용여부
				USE_YN = C.USE_YN,
				
				--회수일
				COLLECTIONDATE = C.RETRIEVE_DATETIME,

				-- 유효기간 
				PUBLISH_END_DATE = C.EXPIRATION_DATE,

				-- 발급일(회원한테 쿠폰을 발급한 날짜)
				REGIST_DATETIME = C.REGIST_DATETIME

			FROM	BARUNSON.DBO.VW_USER A INNER JOIN 
					BARUNSON.DBO.TB_COUPON_PUBLISH C ON A.USER_ID = C.USER_ID INNER JOIN 
					BARUNSON.DBO.TB_COUPON D ON C.COUPON_ID = D.COUPON_ID
			WHERE	C.COUPON_ID = @COUPONID AND
					(C.USE_YN =  (CASE WHEN @USEYN <> '' THEN @USEYN ELSE C.USE_YN END))

		--SELECT	DISTINCT 
		--		ORDER_ID = B.ORDER_ID,
		--		COUPON_PUBLISH_ID = C.COUPON_PUBLISH_ID,
		--		USER_ID = A.USER_ID, 
		--		USER_NAME = A.NAME, 
		--		PHONE_NUMBER = A.CELLPHONE_NUMBER, 
		--		WEDDING_DATE = A.WEDDING_DATE, 
		--		JOIN_DATETIME = A.JOIN_DATETIME, --,A.WEDDING_HHMM

		--		-- 유효기간 : 3가지 유형 : 날짜 지정 / 발행일로부터 X일 / 무제한
		--		PUBLISH_END_DATE = CASE WHEN D.PERIOD_METHOD_CODE = 'PMC01' THEN D.PUBLISH_END_DATE -- 날짜 지정
		--								WHEN D.PERIOD_METHOD_CODE = 'PMC02' 
		--									THEN -- 발행일로부터 X일
										
		--										CASE WHEN  D.PUBLISH_PERIOD_CODE = 'PPC01'  THEN 
		--													DATEADD(DD, 5, C.REGIST_DATETIME)		
		--											WHEN  D.PUBLISH_PERIOD_CODE = 'PPC02'   THEN 
		--													DATEADD(DD, 10, C.REGIST_DATETIME)		
		--											WHEN  D.PUBLISH_PERIOD_CODE = 'PPC03'  THEN 
		--													DATEADD(DD, 20, C.REGIST_DATETIME)		
		--											WHEN  D.PUBLISH_PERIOD_CODE = 'PPC04'   THEN 
		--													DATEADD(DD, 30, C.REGIST_DATETIME)		
		--											WHEN  D.PUBLISH_PERIOD_CODE = 'PPC05'    THEN 
		--													DATEADD(DD, 100, C.REGIST_DATETIME)		
		--										END
		--							ELSE '무제한'
		--						  END,

		--		--사용일
		--		USEDATE = C.USE_DATETIME, 
				
		--		--사용여부
		--		USE_YN = C.USE_YN,
				
		--		--회수일
		--		COLLECTIONDATE = C.RETRIEVE_DATETIME,

		--		-- 발급일(회원한테 쿠폰을 발급한 날짜)
		--		REGIST_DATETIME = C.REGIST_DATETIME
		--FROM	BARUNSON.DBO.VW_USER A INNER JOIN 
		--		BARUNSON.DBO.TB_ORDER B ON A.USER_ID = B.USER_ID INNER JOIN 
		--		BARUNSON.DBO.TB_COUPON_PUBLISH C ON A.USER_ID = C.USER_ID INNER JOIN 
		--		BARUNSON.DBO.TB_COUPON D ON C.COUPON_ID = D.COUPON_ID INNER JOIN 
		--		BARUNSON.DBO.TB_ORDER_COUPON_USE E ON B.ORDER_ID = E.ORDER_ID
		--WHERE	DATALENGTH(A.WEDDING_DATE) = 10 AND C.COUPON_ID = @COUPONID AND
		--		(C.USE_YN =  (CASE WHEN @USEYN <> '' THEN @USEYN ELSE C.USE_YN END))

	END


 END ELSE BEGIN

	-- 쿠폰을 발급할 전체 주문자 리스트 정보

	IF @SEARCHTXT IS NOT NULL AND @SEARCHTXT <> '' BEGIN 
	
			SELECT	DISTINCT 
					ORDER_ID = B.ORDER_ID,
					USER_ID = A.USER_ID, 
					USER_NAME = A.NAME, 
					PHONE_NUMBER = A.CELLPHONE_NUMBER, 
					WEDDING_DATE = A.WEDDING_DATE, 
					JOIN_DATETIME = A.JOIN_DATETIME
			FROM	BARUNSON.DBO.VW_USER A INNER JOIN 
					BARUNSON.DBO.TB_ORDER B ON A.USER_ID = B.USER_ID
			WHERE	--DATALENGTH(A.WEDDING_DATE) = 10 AND
					(A.NAME LIKE  '%' + @SEARCHTXT + '%' OR  A.USER_ID LIKE  '%' + @SEARCHTXT + '%') AND
					 B.PAYMENT_STATUS_CODE ='PSC02'

	  END ELSE BEGIN

			SELECT	DISTINCT 
					ORDER_ID = B.ORDER_ID,
					USER_ID = A.USER_ID, 
					USER_NAME = A.NAME, 
					PHONE_NUMBER = A.CELLPHONE_NUMBER, 
					WEDDING_DATE = A.WEDDING_DATE, 
					JOIN_DATETIME = A.JOIN_DATETIME
			FROM	BARUNSON.DBO.VW_USER A INNER JOIN 
					BARUNSON.DBO.TB_ORDER B ON A.USER_ID = B.USER_ID
					WHERE B.PAYMENT_STATUS_CODE ='PSC02'
			--WHERE	DATALENGTH(A.WEDDING_DATE) = 10 

	  END

 END 
GO
