IF OBJECT_ID (N'dbo.SP_S_USER_Invitation_Display_CHECK', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_S_USER_Invitation_Display_CHECK
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_S_USER_Invitation_Display_CHECK]
/***************************************************************
작성자	:	표수현
작성일	:	2020-02-15
DESCRIPTION	:	
SPECIAL LOGIC	:  SP_S_USER_INVITATION_DISPLAY_CHECK 435
******************************************************************
MODIFICATION
******************************************************************
수정일           작업자                DESCRIPTION
==================================================================
******************************************************************/
 @INVITATION_ID	INT = 1
AS

 SET NOCOUNT ON
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

 SELECT WEDDINGYY = B.WEDDINGYY, 
		--WEDDINGMM = B.WEDDINGMM, 
		WEDDINGMM = CASE  @INVITATION_ID WHEN 224436 THEN 12
					ELSE B.WEDDINGMM
					END ,
		WEDDINGDD = B.WEDDINGDD, 
		G.CODE_NAME ,  
		G.CODE,  
		--C.ORDER_DATETIME,
		ORDER_DATETIME = CONVERT(VARCHAR(10), C.ORDER_DATETIME, 120),
		C.PAYMENT_STATUS_CODE,
		B.INVITATION_DISPLAY_YN
 FROM   TB_INVITATION A INNER JOIN 
		TB_INVITATION_DETAIL B ON A.INVITATION_ID = B.INVITATION_ID INNER JOIN 
		TB_ORDER C ON A.ORDER_ID = C.ORDER_ID INNER JOIN 
		TB_ORDER_PRODUCT D ON C.ORDER_ID = D.ORDER_ID  INNER JOIN 
		TB_PRODUCT F ON D.PRODUCT_ID = F.PRODUCT_ID INNER JOIN 
		TB_COMMON_CODE G ON F.PRODUCT_CATEGORY_CODE = G.CODE
WHERE	A.INVITATION_ID = @INVITATION_ID  AND 
		G.CODE_GROUP = 'PRODUCT_CATEGORY_CODE' AND
		C.ORDER_STATUS_CODE = 'OSC01'  AND
		C.PAYMENT_STATUS_CODE = 'PSC02'



GO
