IF OBJECT_ID (N'dbo.SP_SELECT_BEWEDDING_CONTENT_LIST', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_BEWEDDING_CONTENT_LIST
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

EXEC SP_SELECT_BEWEDDING_CONTENT_LIST NULL, 9999, 1, 'REG_DATE', 'ASC', '', ''

*/
CREATE PROCEDURE [dbo].[SP_SELECT_BEWEDDING_CONTENT_LIST]
		@P_SEARCH_VALUE AS VARCHAR(100) = ''
	,	@P_PAGE_SIZE AS INT
	,	@P_PAGE_NUMBER AS INT
	,	@P_ORDER_BY_NAME AS VARCHAR(50)
	,	@P_ORDER_BY_TYPE AS VARCHAR(10)
	,	@P_USE_YN AS VARCHAR(10)
	,	@P_CONTENT_TYPE AS VARCHAR(20)
AS
BEGIN

	SET NOCOUNT ON


	SELECT	*
	FROM	(
				SELECT	ROW_NUMBER() OVER	(
												ORDER BY 
													CASE WHEN @P_ORDER_BY_NAME = 'SORTING_NUM'					THEN C.REG_DATE						ELSE 0 END ASC
												,	C.SORTING_NUM ASC
													
											) AS ROW_NUM
					,	ROW_NUMBER() OVER	(
												ORDER BY 
													CASE WHEN @P_ORDER_BY_NAME = 'SORTING_NUM'					THEN C.REG_DATE						ELSE 0 END DESC
												,	C.SORTING_NUM DESC
													
											) AS ROW_NUM_DESC
					,	*
				FROM	(
							SELECT	 
									BC.CONTENT_SEQ
								,	BC.SOURCE_SEQ
								,	BC.CONTENT_1
								,	BC.CONTENT_2
								,	BC.CONTENT_3
								,	BC.CONTENT_TYPE
								,	BC.IMAGE_TAG
								,	BC.CONTENT_CLICK_CNT
								,	BC.CONTENT_LINK_URL
								,	BC.DEL_YN
								,	BC.INTERNAL_LINK_YORN
								,	BC.LOGO_DISPLAY_YN
								,	BC.LOGO_TYPE
								,   BC.REG_DATE
								,   BC.UPD_DATE
								,	BC.UPD_ID
								,   BC.USE_YN
								,   BS.SOURCE_NAME
								,   BC.SORTING_NUM
							FROM	BEWEDDING_CONTENT BC
								LEFT JOIN BEWEDDING_SOURCE BS ON BC.SOURCE_SEQ = BS.SOURCE_SEQ
							WHERE	1 = 1
							AND    BC.DEL_YN = 'N'
							AND	 --(ISNULL(@P_SEARCH_VALUE,'') = '' OR SP.PARTNER_NAME LIKE '%' + @P_SEARCH_VALUE + '%')
								
									(
											CASE WHEN ISNULL(@P_SEARCH_VALUE,'') = '' THEN '' ELSE BC.CONTENT_3 END LIKE '%' + ISNULL(@P_SEARCH_VALUE,'') + '%'
									)
							AND	 
								
									(
											CASE WHEN ISNULL(@P_USE_YN,'') = '' THEN '' ELSE BC.USE_YN END = @P_USE_YN
									)

							AND	 
								
									(
											CASE WHEN ISNULL(@P_CONTENT_TYPE,'') = '' THEN '' ELSE BC.CONTENT_TYPE END = @P_CONTENT_TYPE
									)

						) C

			) A

	WHERE	1 = 1
	AND		CASE WHEN @P_ORDER_BY_TYPE = 'ASC' THEN A.ROW_NUM ELSE A.ROW_NUM_DESC END > (@P_PAGE_NUMBER - 1) * @P_PAGE_SIZE
	AND		CASE WHEN @P_ORDER_BY_TYPE = 'ASC' THEN A.ROW_NUM ELSE A.ROW_NUM_DESC END <= @P_PAGE_NUMBER * @P_PAGE_SIZE
		
	ORDER BY 
		CASE WHEN @P_ORDER_BY_TYPE = 'ASC' THEN A.ROW_NUM ELSE A.ROW_NUM_DESC END ASC
	
END


--SELECT * FROM BEWEDDING_SOURCE

--SELECT * FROM BEWEDDING_SOURCE_IMAGE

--SELECT * FROM BEWEDDING_CONTENT

--SELECT * FROM BEWEDDING_CONTENT_IMAGE

--SELECT * FROM BEWEDDING_NAVIGATION


--[dbo].[SP_SELECT_BEWEDDING_SOURCE_LIST]
GO
