IF OBJECT_ID (N'dbo.SP_SELECT_SMARTAD_PARTNER_LIST', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_SMARTAD_PARTNER_LIST
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

EXEC SP_SELECT_SMARTAD_PARTNER_LIST NULL, 9999, 1, 'REG_DATE', 'DESC'

*/

CREATE PROCEDURE [dbo].[SP_SELECT_SMARTAD_PARTNER_LIST]
		@P_SEARCH_VALUE AS VARCHAR(100) = ''
	,	@P_SEARCH_USEYN AS CHAR(1) = ''
	,	@P_PAGE_SIZE AS INT
	,	@P_PAGE_NUMBER AS INT
	,	@P_ORDER_BY_NAME AS VARCHAR(50)
	,	@P_ORDER_BY_TYPE AS VARCHAR(10)
AS
BEGIN

	SET NOCOUNT ON


	SELECT	*
	FROM	(
				SELECT	ROW_NUMBER() OVER	(
												ORDER BY 
													CASE WHEN @P_ORDER_BY_NAME = 'REG_DATE'					THEN C.REG_DATE						ELSE 0 END ASC
												,	C.PARTNER_SEQ ASC
													
											) AS ROW_NUM
					,	ROW_NUMBER() OVER	(
												ORDER BY 
													CASE WHEN @P_ORDER_BY_NAME = 'REG_DATE'					THEN C.REG_DATE						ELSE 0 END DESC
												,	C.PARTNER_SEQ DESC
													
											) AS ROW_NUM_DESC
					,	*
				FROM	(
							SELECT	DISTINCT 
									SP.PARTNER_SEQ
								,	SP.PARTNER_ID
								,	SP.PARTNER_NAME
								,	SP.PARTNER_TELEPHONE
								,	SP.PARTNER_CELLPHONE
								,	SP.PARTNER_ADMIN_NAME
								,	SP.PARTNER_ADMIN_POSITION
								,	SP.PARTNER_ADMIN_DEPARTMENT
								,	SP.PARTNER_EMAIL
								,	SP.PARTNER_HOMEPAGE
								,	SP.PARTNER_CONTENT
								,	SP.REG_DATE
								,	SP.UPD_DATE
								,	SP.UPD_ID
								,	SP.USE_YN
								,	SP.USE_ADMIN_ID
								,	SP.PARTNER_PASSWORD
								,   (SELECT COUNT(*) FROM SmartAD_Partner_AD SPA WHERE SPA.PARTNER_SEQ = SP.PARTNER_SEQ) AS AD_CNT
							FROM	SmartAD_Partner SP
							WHERE	1 = 1
							AND		(ISNULL(@P_SEARCH_USEYN,'') = '' OR SP.USE_YN = @P_SEARCH_USEYN  )
							AND	 --(ISNULL(@P_SEARCH_VALUE,'') = '' OR SP.PARTNER_NAME LIKE '%' + @P_SEARCH_VALUE + '%')
								
									(
											CASE WHEN ISNULL(@P_SEARCH_VALUE,'') = '' THEN '' ELSE SP.PARTNER_NAME END LIKE '%' + ISNULL(@P_SEARCH_VALUE,'') + '%'
									)

						) C

			) A

	WHERE	1 = 1
	AND		CASE WHEN @P_ORDER_BY_TYPE = 'ASC' THEN A.ROW_NUM ELSE A.ROW_NUM_DESC END > (@P_PAGE_NUMBER - 1) * @P_PAGE_SIZE
	AND		CASE WHEN @P_ORDER_BY_TYPE = 'ASC' THEN A.ROW_NUM ELSE A.ROW_NUM_DESC END <= @P_PAGE_NUMBER * @P_PAGE_SIZE
		
	ORDER BY 
		CASE WHEN @P_ORDER_BY_TYPE = 'ASC' THEN A.ROW_NUM ELSE A.ROW_NUM_DESC END ASC
	
END



GO
