IF OBJECT_ID (N'dbo.SP_INSERT_CallCenterLog', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_INSERT_CallCenterLog
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- 콜센터 로그 기록 남길지 여부를 서버에서 제어하기 위해 간단한 INSERT 이지만 SP로 만듦
CREATE PROCEDURE [dbo].[SP_INSERT_CallCenterLog]
    @UID VARCHAR(30)
,   @CALLNUM VARCHAR(4)
,   @GUBUN1 VARCHAR(30)
,   @MSG VARCHAR(max)
AS
BEGIN
    
    SET NOCOUNT ON;

    INSERT INTO CallCenterLog (UID, CALLNUM, GUBUN1, MSG) VALUES (@UID, @CALLNUM, @GUBUN1, @MSG)

END
GO
