IF OBJECT_ID (N'dbo.SP_UPDATE_OUTSOURCING_ORDER_MST', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_UPDATE_OUTSOURCING_ORDER_MST
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
  
CREATE PROCEDURE [dbo].[SP_UPDATE_OUTSOURCING_ORDER_MST]  
 @P_OUTSOURCING_ORDER_SEQ      AS INT,  
 @P_VALUE      AS VARCHAR(1000),  
 @P_GUBUN      AS VARCHAR(3)  
AS  
BEGIN  
   
 IF @P_GUBUN = 'M'  
  BEGIN  
   UPDATE OUTSOURCING_ORDER_MST  
   SET MEMO_EX = @P_VALUE  
   WHERE OUTSOURCING_ORDER_SEQ = @P_OUTSOURCING_ORDER_SEQ  
  END  
END  
  
GO
