IF OBJECT_ID (N'dbo.SP_EXEC_COUPON_FOR_SAMPLE_SB', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_EXEC_COUPON_FOR_SAMPLE_SB
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
	--2020.03.12 (바/프)샘플발송완료 후 익일 쿠폰발급
	
	쿠폰 발급 기간 : 2020. 3. 12. ~ 4. 30. (샘플 발송일 기준)
	대상 : 2020년 5월~8월 예식 고객 중 바/프 무료샘플을 수령한 고객(ID)
	혜택 : 샘플 발송 1일 후, 1만원 중복쿠폰 추가 발급 
	EXEC SP_EXEC_COUPON_FOR_SAMPLE_SB

*/
CREATE PROCEDURE [dbo].[SP_EXEC_COUPON_FOR_SAMPLE_SB]

AS
BEGIN

	--커서를 이용하여 해당되는 고객정보를 얻는다.
	DECLARE cur_AutoInsert_For_UID CURSOR FAST_FORWARD
	FOR

	SELECT     
		VUI.UID , CSO.COMPANY_SEQ, CSO.SALES_GUBUN   
	FROM    CUSTOM_SAMPLE_ORDER CSO   JOIN    VW_USER_INFO VUI ON CSO.MEMBER_ID = VUI.UID AND CSO.SALES_GUBUN = VUI.SITE_DIV       
	WHERE   CSO.SALES_GUBUN IN ('SS', 'SB','ST')
	AND     CSO.DELIVERY_DATE >= CONVERT(DATETIME , CONVERT(VARCHAR(10), GETDATE() - 1, 120))
	AND     CSO.DELIVERY_DATE <  CONVERT(DATETIME , CONVERT(VARCHAR(10), GETDATE() , 120)) 
	AND	VUI.WEDDING_DAY >= '2020-05-01' 
	AND	VUI.WEDDING_DAY < '2020-09-01'


	OPEN cur_AutoInsert_For_UID


	DECLARE @USER_ID VARCHAR(100)
	DECLARE @COMPANY_SEQ INT    
	DECLARE @SALES_GUBUN VARCHAR(10) 
	DECLARE @COUPON_CODE	AS VARCHAR(40)    

	FETCH NEXT FROM cur_AutoInsert_For_UID INTO  @USER_ID, @COMPANY_SEQ, @SALES_GUBUN

	WHILE @@FETCH_STATUS = 0

	BEGIN
		
	   IF @SALES_GUBUN = 'SB'  
		BEGIN  
		 SET @COUPON_CODE = '572C-ADAD-4376-A6B0'      
		END  
  
	   ELSE IF @SALES_GUBUN = 'SS'  
		BEGIN  
		 SET @COUPON_CODE = '1A72-2C56-4C0C-8D48'     
		END  

	   ELSE IF @SALES_GUBUN = 'ST'  
		BEGIN  
		 SET @COUPON_CODE = '3097-BF45-402C-9277'     
		END  
				
		-- 쿠폰발급!
		EXEC	SP_EXEC_COUPON_ISSUE_FOR_ONE @COMPANY_SEQ, @SALES_GUBUN, @USER_ID, @COUPON_CODE
		
		FETCH NEXT FROM cur_AutoInsert_For_UID INTO @USER_ID, @COMPANY_SEQ, @SALES_GUBUN
	END


	CLOSE cur_AutoInsert_For_UID
	DEALLOCATE cur_AutoInsert_For_UID

END
GO
