IF OBJECT_ID (N'dbo.SP_BARUNSONMALL_COUPON_INSERT_v2', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_BARUNSONMALL_COUPON_INSERT_v2
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*******************************************************

2019-01-03	제휴쿠폰 추할인율변경 신규쿠폰 추가 발급 정혜련
	
	--BARUNSONAMLL17R_JEHU
	--BARUNSONAMLL15R_JEHU
	--BARUNSONAMLL10R_JEHU

*********************************************************/

CREATE PROCEDURE [dbo].[SP_BARUNSONMALL_COUPON_INSERT_v2]
	--@UID		AS		NVARCHAR(20),
	--@COMPANY_SEQ AS VARCHAR(10), 
	--@CARDBRAND	AS NVARCHAR(3) 
	@ORDER_SEQ AS INT
AS

BEGIN
	SET NOCOUNT ON;

	DECLARE @ResultCNT INT 
	DECLARE @CouponCNT INT 
	DECLARE @ERP_PARTCODE varchar(20)
	DECLARE @coupon_code VARCHAR(20) 

	DECLARE @UID VARCHAR(20) 
	DECLARE @COMPANY_SEQ VARCHAR(10) 
	DECLARE @CARDBRAND VARCHAR(3)

	SELECT @UID = MEMBER_ID, @COMPANY_SEQ= COMPANY_SEQ, @CARDBRAND=(SELECT CARDBRAND FROM S2_CARD WHERE CARD_SEQ = A.CARD_SEQ)  FROM CUSTOM_ORDER A 
	WHERE ORDER_SEQ = @ORDER_SEQ
					
	IF @UID <> '' AND GETDATE() <= '2022-12-31 23:59:59'
	
	-- 발급받을 쿠폰 확인하기
	SELECT TOP 1 @ERP_PARTCODE = ERP_PartCode FROM COMPANY WHERE COMPANY_SEQ = @COMPANY_SEQ 

	SET @COUPON_CODE = 'N'

	IF @ERP_PARTCODE = '390'
		BEGIN
			SELECT @ResultCNT = COUNT(COMPANY_SEQ)
			FROM COMPANY
			WHERE COMPANY_SEQ IN (164,5027,5275,5488,5571,5757,6606,6607,6627,7189,7190,7256,7257,7260,7261,7262,7263,7312,7313,7564,7620,7731,5319,5010,5678)
			AND COMPANY_SEQ = @COMPANY_SEQ

			IF @ResultCNT > 0 
				IF @COMPANY_SEQ = 5319
					BEGIN
						SET @COUPON_CODE = 'BARUNSONAMLL25R_JEHU'
					END
				ELSE
					if @company_seq = 5275 OR @company_seq = 5678
						BEGIN
							SET @COUPON_CODE = 'BARUNSONAMLL18R_JEHU'			
						END
					else
						BEGIN
							SET @COUPON_CODE = 'BARUNSONAMLL17R_JEHU'			
						END
			ELSE
				IF @CARDBRAND ='S'
					BEGIN
						SET @COUPON_CODE = 'BARUNSONAMLL10R_JEHU'
					END
				ELSE
					BEGIN
						SET @COUPON_CODE = 'BARUNSONAMLL15R_JEHU'
					END
		END

	ELSE IF @ERP_PARTCODE = '365'			 
		BEGIN
				IF @CARDBRAND ='S'
					BEGIN
						SET @COUPON_CODE = 'BARUNSONAMLL10R_JEHU'
					END
				ELSE
					BEGIN
						SET @COUPON_CODE = 'BARUNSONAMLL15R_JEHU'
					END
		END		


	IF @COUPON_CODE <> 'N'

		SELECT @CouponCNT = COUNT(coupon_code) 
		FROM S4_MYCOUPON 
		WHERE COUPON_CODE = @COUPON_CODE AND UID = @UID
		
		-- 쿠폰발급
		if 	@CouponCNT = 0
			begin
                    INSERT INTO S4_MYCOUPON (COUPON_CODE, UID, COMPANY_SEQ, ISMYYN, END_DATE)
                    SELECT  COUPON_CODE
                        ,   @UID
                        ,   COMPANY_SEQ
                        ,   'Y'
                        ,   convert(varchar(10), DATEADD(MM,3,GETDATE()), 23)
                    FROM    S4_COUPON
                    WHERE   COUPON_CODE = @COUPON_CODE
									
			end 
	
END
GO
