IF OBJECT_ID (N'dbo.SP_DELIVERY_SAVE_SELECT', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_DELIVERY_SAVE_SELECT
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_DELIVERY_SAVE_SELECT]
	@CODE VARCHAR(20),		--배송사코드 
	@USER_ID  VARCHAR(100)

AS
BEGIN
	
	UPDATE DELIVERY_CODE
	SET USE_YN = CASE WHEN CODE = @CODE THEN 'Y' ELSE 'N' END


	INSERT DELIVERY_REG_LOG(USER_ID, CODE, CODE_NAME, REG_DATE)
	SELECT @USER_ID, CODE, CODE_NAME, GETDATE()
	FROM DELIVERY_CODE
	WHERE CODE = @CODE

END
GO
