IF OBJECT_ID (N'dbo.SP_BARUNSONMALL_COUPON_INSERT_TEST', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_BARUNSONMALL_COUPON_INSERT_TEST
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*******************************************************

2019-01-03	제휴쿠폰 추가 할인율변경 신규쿠폰 추가 발급
 	
	--BARUNSONAMLL17R_JEHU
	--BARUNSONAMLL15R_JEHU
	--BARUNSONAMLL10R_JEHU

	-- 390/365

	select * from company where company_name = '삼성결혼도움방'
	
	select * from company where company_name = '삼성카드오픈웨딩'

*********************************************************/

CREATE PROCEDURE [dbo].[SP_BARUNSONMALL_COUPON_INSERT_TEST]
	@UID		 AS NVARCHAR(40),
	@COMPANY_SEQ AS VARCHAR(10), 
	@CARDBRAND	 AS NVARCHAR(3) 
	
AS

BEGIN
	SET NOCOUNT ON;

	DECLARE @ResultCNT INT 
	DECLARE @CouponCNT INT 
	DECLARE @ERP_PARTCODE varchar(20)
	DECLARE @coupon_code VARCHAR(20) 
	
	DECLARE @ChkCompnayCNT INT 
		
	-- 2021.05.03 제휴몰 할인율 정책 변경
	
	--* 기존 할인율 정책 유지 제휴사 LIST 체크

	SELECT @ChkCompnayCNT = COUNT(company_seq) 
	  FROM company
	 WHERE company_seq IN (7179,7872,7722,6923,7840,7894,8031,2708,7871,5010,7564,2715,7886,7666,5437,7679,7318,7841,7922,7792,6586,7601,6470,7602,7873,7713,5115)
	   AND company_seq = @COMPANY_SEQ

	-- 발급받을 쿠폰 확인하기
	SELECT TOP 1 @ERP_PARTCODE = ERP_PartCode FROM COMPANY WHERE COMPANY_SEQ = @COMPANY_SEQ 

	SET @COUPON_CODE = 'N'


	-- 변경된 할인율 정책으로
	IF @ChkCompnayCNT = 1
		IF @CARDBRAND ='S'
		BEGIN
			SET @COUPON_CODE = 'BARUNSONAMLL10R_JEHU'
		END
		ELSE
		BEGIN
			SET @COUPON_CODE = 'BARUNSONAMLL15R_JEHU'
		END
	ELSE
	BEGIN
		IF @ERP_PARTCODE = '390'	--제휴
		BEGIN
			SELECT @ResultCNT = COUNT(COMPANY_SEQ)
			FROM COMPANY
			WHERE COMPANY_SEQ IN (164,5027,5275,5488,5571,5757,6606,6607,6627,7189,7190,7256,7257,7260,7261,7262,7263,7312,7313,7564,7620,7731,5319,5010,5678,8099, 8116)
			AND COMPANY_SEQ = @COMPANY_SEQ

			IF @ResultCNT > 0 
				IF @COMPANY_SEQ = 5319
				BEGIN
					SET @COUPON_CODE = 'BARUNSONAMLL25R_JEHU'
				END
				ELSE
				BEGIN
					IF @COMPANY_SEQ = 5275 OR @COMPANY_SEQ = 5678
					BEGIN
						SET @COUPON_CODE = 'BARUNSONAMLL18R_JEHU'			
					END
					ELSE IF @COMPANY_SEQ = 8099 -- 소노캄
					BEGIN
						IF @CARDBRAND ='S'
						BEGIN
							SET @COUPON_CODE = 'BARUNSONAMLL15R_JEHU'
						END
						ELSE
						BEGIN
							SET @COUPON_CODE = 'BARUNSONAMLL17R_JEHU'
						END	 
					END ELSE IF  @COMPANY_SEQ = 8116 BEGIN  -- 플랜온웨딩  - 프리미어 10% 디얼디어 10% 제외한 바른손 더카드 15% 설정 원합니다!
							IF @CARDBRAND ='S' OR @CARDBRAND ='D' BEGIN --10%
								SET @COUPON_CODE = 'BARUNSONAMLL10R_JEHU'
							END ELSE BEGIN  --15% 
								SET @COUPON_CODE = 'BARUNSONAMLL15R_JEHU'
							END 
					END ELSE BEGIN
						SET @COUPON_CODE = 'BARUNSONAMLL17R_JEHU'			
					END
				END
			ELSE
			BEGIN
				SET @COUPON_CODE = 'BARUNSONAMLL10R_JEHU'
			END
		END

		ELSE IF @ERP_PARTCODE = '365'	-- 웨딩			 
		BEGIN
			IF @COMPANY_SEQ = 7911 -- 예외(농민신문사) 
				IF @CARDBRAND ='S'
				BEGIN
					SET @COUPON_CODE = 'BARUNSONAMLL10R_JEHU'
				END
				ELSE
				BEGIN
					SET @COUPON_CODE = 'BARUNSONAMLL15R_JEHU'
				END
			ELSE
			BEGIN
				SET @COUPON_CODE = 'BARUNSONAMLL10R_JEHU'
			END
		END
		
		ELSE IF @ERP_PARTCODE = '366'	-- 웨딩(비직영)
		BEGIN
			IF @COMPANY_SEQ = 8114 -- 초록어린이재단
			BEGIN
				SET @COUPON_CODE = 'BARUNSONAMLL10R_JEHU'
			END
			ELSE IF @COMPANY_SEQ = 8115 -- 메리어트호텔
				IF @CARDBRAND ='S'
				BEGIN
					SET @COUPON_CODE = 'BARUNSONAMLL10R_JEHU'
				END
				ELSE
				BEGIN
					SET @COUPON_CODE = 'BARUNSONAMLL17R_JEHU'
				END
			ELSE IF @COMPANY_SEQ = 8138 -- 아크레도
				IF @CARDBRAND ='S'
				BEGIN
					SET @COUPON_CODE = 'BARUNSONAMLL10R_JEHU'
				END
				ELSE
				BEGIN
					SET @COUPON_CODE = 'BARUNSONAMLL15R_JEHU'
				END
			ELSE IF @COMPANY_SEQ = 8153 -- 파스텔무비
			BEGIN
				SET @COUPON_CODE = 'BARUNSONAMLL10R_JEHU'
			END
			ELSE
			BEGIN
				SET @COUPON_CODE = 'BARUNSONAMLL5R_JEHU'
			END
		END
	END

	
	IF @COMPANY_SEQ IN (5010, 5569, 5570, 5678, 6627, 6628) BEGIN  -- 삼성결혼도움방 , 삼성카드오픈웨딩
		
		IF @COMPANY_SEQ IN (5010, 5569, 5570, 5678) BEGIN  --삼성결혼도움방

			IF @CARDBRAND <> 'D' BEGIN --디얼디어 제외
				SET @COUPON_CODE = 'BARUNSONAMLL17R_JEHU'
			END ELSE BEGIN 
				SET @COUPON_CODE = 'BARUNSONAMLL15R_JEHU'
			END 

		END ELSE BEGIN 

			IF @CARDBRAND <> 'D' BEGIN --디얼디어 제외
				SET @COUPON_CODE = 'BARUNSONAMLL17R_JEHU'
			END ELSE BEGIN 
				SET @COUPON_CODE = 'BARUNSONAMLL10R_JEHU'
			END 
		END 
		
	END 

	IF @COMPANY_SEQ = 8155 BEGIN  -- 메이크마이웨딩  - 바른손카드 , 더카드 → 15% 추가할인 / 프리미어 페이퍼 → 10% 추가할인
			IF @CARDBRAND ='S' BEGIN --10%
				SET @COUPON_CODE = 'BARUNSONAMLL10R_JEHU'
			END ELSE IF @CARDBRAND ='B' OR  @CARDBRAND ='C'  BEGIN  --15% 
				SET @COUPON_CODE = 'BARUNSONAMLL15R_JEHU'
			END 
	END


	IF @COUPON_CODE <> 'N'
	BEGIN
			
		SELECT @CouponCNT = COUNT(coupon_code) 
			FROM S4_MYCOUPON 
			WHERE COUPON_CODE = @COUPON_CODE AND UID = @UID
		
		-- 쿠폰발급
		IF 	@CouponCNT = 0
		BEGIN
			INSERT INTO S4_MYCOUPON (COUPON_CODE, UID, COMPANY_SEQ, ISMYYN, END_DATE)
			SELECT COUPON_CODE
				 , @UID
				 , COMPANY_SEQ
				 , 'Y'
				 , convert(varchar(10), DATEADD(MM,3,GETDATE()), 23)
			  FROM S4_COUPON
			 WHERE COUPON_CODE = @COUPON_CODE
		END
	END
	
END
GO
