IF OBJECT_ID (N'dbo.SP_EXEC_DISK_SPACE_ALERT', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_EXEC_DISK_SPACE_ALERT
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

	EXEC SP_EXEC_DISK_SPACE_ALERT '[알림] 211.234.97.144 디스크 용량 초과', '[알림] 211.234.97.144 디스크 용량 초과'

*/

CREATE PROCEDURE [dbo].[SP_EXEC_DISK_SPACE_ALERT]
	@P_MESSAGE	NVARCHAR(2000)
AS

BEGIN
	
	SET NOCOUNT ON;

	--SET @P_MESSAGE = '[테스트]' + @P_MESSAGE
	/* 
	2022-07-29 김광호 아래 내용 주석 처리
	담당자 모두 퇴사 및 이 프로시져 호출여부 확인 불가   
	*/

	/* MMS 
	DECLARE @P_PHONE_SENDER VARCHAR(15)
	SET @P_PHONE_SENDER = '010-5090-4010'	-- 박동혁 팀장

	/* 박동혁 팀장 */
	EXEC SP_EXEC_SMS_OR_MMS_SEND @P_PHONE_SENDER, '010-5090-4010', @P_MESSAGE, @P_MESSAGE

	/* 김현기 대리 */
	EXEC SP_EXEC_SMS_OR_MMS_SEND @P_PHONE_SENDER, '010-4531-8283', @P_MESSAGE, @P_MESSAGE

	/* 차호용 알바 */
	EXEC SP_EXEC_SMS_OR_MMS_SEND @P_PHONE_SENDER, '010-4934-9760', @P_MESSAGE, @P_MESSAGE



	/* EMAIL */
	DECLARE @MAIL_TYPE AS VARCHAR(50)
	DECLARE @FROM_EMAIL AS VARCHAR(100)
	SET @MAIL_TYPE = 'ALERT - ' + CAST(NEWID() AS VARCHAR(36))
	SET @FROM_EMAIL = 'mailman@barunn.net'

	EXEC SP_INSERT_TNEO_QUEUE @MAIL_TYPE, '', @FROM_EMAIL, '박동혁', 'donghyuk.park@barunn.net', @P_MESSAGE, @P_MESSAGE, ''
	EXEC SP_INSERT_TNEO_QUEUE @MAIL_TYPE, '', @FROM_EMAIL, '김현기', 'hyunki.kim@barunn.net', @P_MESSAGE, @P_MESSAGE, ''
	EXEC SP_INSERT_TNEO_QUEUE @MAIL_TYPE, '', @FROM_EMAIL, '차호용', 'hoyong.cha@barunn.net', @P_MESSAGE, @P_MESSAGE, ''
	*/
END
GO
