IF OBJECT_ID (N'dbo.SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


/*

SELECT  *
FROM    VW_USER_INFO
WHERE   UID = 's4guest'

SELECT  *
FROM    VW_USER_INFO
WHERE   DUPINFO = 'MC0GCCqGSIb3DQIJAyEAgQMn9E0TJmup1Yu5+Ws1cmQPM5Io02lOWvzoC0hwn0o='

SELECT  *
FROM    S2_USERINFO
WHERE   UID = 's4guest'

EXEC SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER 'MC0GCCqGSIb3DQIJAyEAgQMn9E0TJmup1Yu5+Ws1cmQPM5Io02lOWvzoC0hwn0o=', 'sharniel', '', '', ''

*/
CREATE PROCEDURE [dbo].[SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER]

    @DUPINFO AS VARCHAR(100)
,   @NEW_ID AS VARCHAR(50)
,   @REFERER_SITE AS VARCHAR(100)
,   @SELECT_SITE AS VARCHAR(100)
,   @SELECT_ID AS VARCHAR(100)

AS
BEGIN
    
    SET NOCOUNT ON;

    DECLARE @UID AS VARCHAR(50)
    DECLARE @SALES_GUBUN AS VARCHAR(50)
	DECLARE @TEMP_STR AS VARCHAR(100)
	DECLARE @REFERER_SALES_GUBUN AS VARCHAR(2)

	SET @REFERER_SITE = ISNULL(@REFERER_SITE, 'SB')



	DECLARE @LOG_MSG VARCHAR(1000)
	SET @LOG_MSG = '시작 - REFERER_SITE : ' + @REFERER_SITE
	-- 전환 진행중 상태를 보기 위한 로그
	--EXEC SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG @DUPINFO, @NEW_ID, 'SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', @LOG_MSG

	IF @REFERER_SITE = '비핸즈카드' BEGIN
		SET @REFERER_SALES_GUBUN = 'SA'
	END ELSE IF @REFERER_SITE = '바른손카드' BEGIN
		SET @REFERER_SALES_GUBUN = 'SB'
	END ELSE IF @REFERER_SITE = '더카드' BEGIN
		SET @REFERER_SALES_GUBUN = 'ST'
	END ELSE IF @REFERER_SITE = '프리미어페이퍼' BEGIN
		SET @REFERER_SALES_GUBUN = 'SS'
	END ELSE IF @REFERER_SITE = '비핸즈카드 제휴' BEGIN
		SET @REFERER_SALES_GUBUN = 'B'
	END ELSE IF @REFERER_SITE = '프리미어페이퍼 제휴' BEGIN
		SET @REFERER_SALES_GUBUN = 'H'
	END ELSE IF @REFERER_SITE = '셀레모' BEGIN
		SET @REFERER_SALES_GUBUN = 'CE'
	END ELSE IF @REFERER_SITE = '비웨딩' BEGIN
		SET @REFERER_SALES_GUBUN = 'BE'
	END
	-- 20210813 표수현 추가 Start
	ELSE IF @REFERER_SITE = '바른손모바일카드' BEGIN
		SET @REFERER_SALES_GUBUN = 'BM'
	END
	-- 20210813 표수현 추가 End
	 -- 20221227 표수현 추가 Start  
	ELSE IF @REFERER_SITE = 'gsauth' BEGIN  
		SET @REFERER_SALES_GUBUN = 'GS'  
	END  
 -- 20221227 표수현 추가 End

	ELSE
	BEGIN
		SET @REFERER_SALES_GUBUN = 'SB'
	END

    IF @SELECT_SITE IN ('B', 'C') 
    BEGIN
    SET @REFERER_SALES_GUBUN = 'B'
    END
 
		-- 20230215 표수현 (비핸즈사이트구분코드로 유입된 경우 REFERER_SALES_GUBUN값으로 대체 
	IF @SELECT_SITE = 'SA' BEGIN
			IF @REFERER_SALES_GUBUN = 'SA' BEGIN 
				SET @SELECT_SITE = 'SB'
			END ELSE BEGIN 
				SET @SELECT_SITE = @REFERER_SALES_GUBUN
			END 
	--	SET @SELECT_SITE = @REFERER_SALES_GUBUN
	END
	----------------------------------------------------------------------------------------------
	-- 경유 사이트 및 선택 사이트 업데이트, 제휴 업데이트
	----------------------------------------------------------------------------------------------
	-- 바른손카드 / 프리미어페이퍼
	UPDATE	S2_USERINFO
	SET		REFERER_SALES_GUBUN = @REFERER_SALES_GUBUN
		,	SELECT_SALES_GUBUN = CAST(@SELECT_SITE AS VARCHAR(2))
		,	SELECT_USER_ID = @SELECT_ID
		,	ISJEHU = CASE WHEN @REFERER_SALES_GUBUN = 'H' AND SITE_DIV IN ( 'SS', 'H' ) THEN 'Y' ELSE ISJEHU END
		,	SITE_DIV = CASE WHEN @REFERER_SALES_GUBUN = 'H' AND SITE_DIV IN ( 'SS', 'H' ) THEN 'H' ELSE SITE_DIV END
	WHERE	DUPINFO = @DUPINFO
	-- 비핸즈카드
	UPDATE	S2_USERINFO_BHANDS
	SET		REFERER_SALES_GUBUN = @REFERER_SALES_GUBUN
		,	SELECT_SALES_GUBUN = CAST(@SELECT_SITE AS VARCHAR(2))
		,	SELECT_USER_ID = @SELECT_ID
		,	ISJEHU = CASE WHEN @REFERER_SALES_GUBUN = 'B' AND SITE_DIV IN ( 'SA', 'B', 'C' ) THEN 'Y' ELSE ISJEHU END
		,	SITE_DIV = CASE WHEN @REFERER_SALES_GUBUN = 'B' AND SITE_DIV IN ( 'SA', 'B', 'C' ) THEN 'B' ELSE SITE_DIV END
	WHERE	DUPINFO = @DUPINFO
	-- 더카드
	UPDATE	S2_USERINFO_THECARD
	SET		REFERER_SALES_GUBUN = @REFERER_SALES_GUBUN
		,	SELECT_SALES_GUBUN = CAST(@SELECT_SITE AS VARCHAR(2))
		,	SELECT_USER_ID = @SELECT_ID
	WHERE	DUPINFO = @DUPINFO







    DECLARE @COMPANY_MST TABLE
    (
		    COMPANY_SEQ INT
        ,   SALES_GUBUN VARCHAR(10)
	)	

    DECLARE @USER_INFO_MST TABLE
   (
            ROW_NUM     INT
		,   UID  VARCHAR(50)
        ,   SALES_GUBUN VARCHAR(10)
	)	

    DECLARE @MAX_CNT AS INT = 0
    DECLARE @i AS INT = 1



    INSERT INTO @USER_INFO_MST (ROW_NUM, UID, SALES_GUBUN)
    SELECT  ROW_NUMBER() OVER(ORDER BY UID ASC, SITE_DIV ASC) AS ROW_NUM
        ,   UID
        ,   CASE
                    WHEN SITE_DIV IN ('SA', 'B', 'C')
                    THEN 'SA|B|C'
                    WHEN SITE_DIV IN ('SS', 'H')
                    THEN 'SS|H'
                    ELSE SITE_DIV
           END AS SALES_GUBUN

    FROM    VW_USER_INFO
    WHERE   1 = 1
    AND     DUPINFO = @DUPINFO
    --AND     ISNULL(INTEGRATION_MEMBER_YORN, 'N') = 'N'

    SET @MAX_CNT =  (
                        SELECT  COUNT(*)
                        FROM    @USER_INFO_MST
                    )



	-- 전환 진행중 상태를 보기 위한 로그
	--EXEC SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG @DUPINFO, @NEW_ID, 'SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', 'WHILE 문 시작 전'



    WHILE @i <= @MAX_CNT
    BEGIN
        
        SELECT  @UID = A.UID
            ,   @SALES_GUBUN = A.SALES_GUBUN
        FROM    @USER_INFO_MST A
        WHERE   A.ROW_NUM = @i

		SET @TEMP_STR = @NEW_ID + ' ' + @UID

		-- 전환 진행중 상태를 보기 위한 로그
		--EXEC SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG @DUPINFO, @TEMP_STR, 'SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', '회원 정보 변경 시작'



        /* 통합 아이디로 회원 정보 변경 */
        IF @SALES_GUBUN = 'SA|B|C'
        BEGIN
            
            INSERT INTO INTEGRATION_MEMBER_SIGN_UP_LOG (SALES_GUBUN, USER_ID, INTEGRATION_USER_ID, USER_TABLE_NAME, REFERER_SITE, SELECT_SITE, SELECT_ID, REFERER_SALES_GUBUN)
            SELECT  SITE_DIV, UID, @NEW_ID, 'S2_USERINFO_BHANDS', @REFERER_SITE, @SELECT_SITE, @SELECT_ID, @REFERER_SALES_GUBUN
            FROM    S2_USERINFO_BHANDS
            WHERE   UID = @UID
            AND     DUPINFO = @DUPINFO

            UPDATE  S2_USERINFO_BHANDS
            SET     INTERGRATION_DATE = GETDATE()
				,   INTEGRATION_MEMBER_YORN = 'Y'
				,	UID = @NEW_ID
				,	INTERGRATION_BEFORE_ID = @UID
                ,   MOD_DATE = GETDATE()
            WHERE   DUPINFO = @DUPINFO

        END

        ELSE IF @SALES_GUBUN = 'ST'
        BEGIN
            
            INSERT INTO INTEGRATION_MEMBER_SIGN_UP_LOG (SALES_GUBUN, USER_ID, INTEGRATION_USER_ID, USER_TABLE_NAME, REFERER_SITE, SELECT_SITE, SELECT_ID, REFERER_SALES_GUBUN)
            SELECT  SITE_DIV, UID, @NEW_ID, 'S2_USERINFO_THECARD', @REFERER_SITE, @SELECT_SITE, @SELECT_ID, @REFERER_SALES_GUBUN
            FROM    S2_USERINFO_THECARD
            WHERE   DUPINFO = @DUPINFO

            UPDATE  S2_USERINFO_THECARD
            SET     INTERGRATION_DATE = GETDATE()
				,   INTEGRATION_MEMBER_YORN = 'Y'
				,	UID = @NEW_ID
				,	INTERGRATION_BEFORE_ID = @UID
                ,   MOD_DATE = GETDATE()
            WHERE   DUPINFO = @DUPINFO



			-- 전환 진행중 상태를 보기 위한 로그
			--EXEC SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG @DUPINFO, @TEMP_STR, 'SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', '더카드 통합주문 테이블 시작 '
			/* 더카드 통합주문 테이블 */
			UPDATE  CUSTOM_ORDER_GROUP
			SET     MEMBER_ID = @NEW_ID
			WHERE   1 = 1
			AND     MEMBER_ID = @UID
			AND     COMPANY_SEQ = 5007



			-- 전환 진행중 상태를 보기 위한 로그
			--EXEC SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG @DUPINFO, @TEMP_STR, 'SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', '더카드 통합주문 테이블 끝, 더카드 장바구니 테이블 시작 '
			/* 더카드 장바구니 테이블 */
			UPDATE  S4_Cart
			SET     CART_OWNER_ID = @NEW_ID
			WHERE   1 = 1
			AND     CART_OWNER_ID = @UID
			AND     COMPANY_SEQ = 5007



			-- 전환 진행중 상태를 보기 위한 로그
			--EXEC SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG @DUPINFO, @TEMP_STR, 'SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', '더카드 장바구니 테이블 끝, 더카드 쿠폰 디테일 테이블 시작 '
			/* 더카드 쿠폰 디테일 테이블 */
			UPDATE  tCouponSub
			SET  UserID = @NEW_ID
			WHERE   1 = 1
			AND    UserID = @UID



			-- 전환 진행중 상태를 보기 위한 로그
			--EXEC SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG @DUPINFO, @TEMP_STR, 'SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', '더카드 쿠폰 디테일 테이블 끝, 더카드 이벤트 게시판 테이블 시작 '
			/* 더카드 이벤트 게시판 테이블 */
			UPDATE  S4_Event_Review_New
			SET     ER_UserId = @NEW_ID
			WHERE   1 = 1
			AND     ER_UserId = @UID
			AND     ER_Company_Seq = 5007



			-- 전환 진행중 상태를 보기 위한 로그
			--EXEC SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG @DUPINFO, @TEMP_STR, 'SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', '더카드 이벤트 게시판 테이블 끝, 더카드 서포터즈 테이블 시작 '
			/* 더카드 서포터즈 테이블 */
			UPDATE  S5_Supporters_User
			SET     SP_UserID = @NEW_ID
			WHERE   1 = 1
			AND     SP_UserID = @UID
			AND     SP_Company_seq = 5007



			-- 전환 진행중 상태를 보기 위한 로그
			--EXEC SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG @DUPINFO, @TEMP_STR, 'SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', '더카드 서포터즈 테이블 테이블 끝'


        END

        ELSE IF @SALES_GUBUN = 'SS|H'
        BEGIN
            
            INSERT INTO INTEGRATION_MEMBER_SIGN_UP_LOG (SALES_GUBUN, USER_ID, INTEGRATION_USER_ID, USER_TABLE_NAME, REFERER_SITE, SELECT_SITE, SELECT_ID, REFERER_SALES_GUBUN)
            SELECT  SITE_DIV, UID, @NEW_ID, 'S2_USERINFO', @REFERER_SITE, @SELECT_SITE, @SELECT_ID, @REFERER_SALES_GUBUN
            FROM    S2_USERINFO
            WHERE   UID = @UID
            AND     DUPINFO = @DUPINFO
            AND     SITE_DIV IN ('SS', 'H')

            UPDATE  S2_USERINFO
            SET     INTERGRATION_DATE = GETDATE()
				,   INTEGRATION_MEMBER_YORN = 'Y'
				,	UID = @NEW_ID
				,	INTERGRATION_BEFORE_ID = @UID
                ,   MOD_DATE = GETDATE()
            WHERE   DUPINFO = @DUPINFO
            AND     SITE_DIV IN ('SS', 'H')

        END

        ELSE IF @SALES_GUBUN = 'SB'
        BEGIN
            
            INSERT INTO INTEGRATION_MEMBER_SIGN_UP_LOG (SALES_GUBUN, USER_ID, INTEGRATION_USER_ID, USER_TABLE_NAME, REFERER_SITE, SELECT_SITE, SELECT_ID, REFERER_SALES_GUBUN)
            SELECT  SITE_DIV, UID, @NEW_ID, 'S2_USERINFO', @REFERER_SITE, @SELECT_SITE, @SELECT_ID, @REFERER_SALES_GUBUN
            FROM    S2_USERINFO
            WHERE   UID = @UID
            AND     DUPINFO = @DUPINFO
            AND     SITE_DIV IN ('SB')

            UPDATE  S2_USERINFO
            SET     INTERGRATION_DATE = GETDATE()
				,   INTEGRATION_MEMBER_YORN = 'Y'
				,	UID = @NEW_ID
				,	INTERGRATION_BEFORE_ID = @UID
                ,   MOD_DATE = GETDATE()
            WHERE   DUPINFO = @DUPINFO
            AND     SITE_DIV IN ('SB')

        END



		-- 전환 진행중 상태를 보기 위한 로그
		--EXEC SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG @DUPINFO, @TEMP_STR, 'SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', '회원 정보 변경 끝'
		

        
        INSERT INTO @COMPANY_MST (COMPANY_SEQ, SALES_GUBUN)
        SELECT  COMPANY_SEQ, SALES_GUBUN
        FROM    COMPANY
        WHERE   1 = 1
        AND     SALES_GUBUN IN  ( SELECT VALUE FROM [dbo].[FN_SPLIT] (@SALES_GUBUN, '|') )



		-- 전환 진행중 상태를 보기 위한 로그
		--EXEC SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG @DUPINFO, @TEMP_STR, 'SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', '청첩장 시작'



        /* 청첩장 */
        UPDATE  CUSTOM_ORDER
        SET     MEMBER_ID = @NEW_ID
        WHERE   1 = 1
        AND     MEMBER_ID = @UID
        AND     SALES_GUBUN IN (SELECT SALES_GUBUN FROM @COMPANY_MST GROUP BY SALES_GUBUN)



		-- 전환 진행중 상태를 보기 위한 로그
		--EXEC SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG @DUPINFO, @TEMP_STR, 'SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', '청첩장 끝, 부가상품 시작'



        /* 부가 상품 */
        UPDATE  CUSTOM_ETC_ORDER
        SET     MEMBER_ID = @NEW_ID
        WHERE   1 = 1
        AND     MEMBER_ID = @UID
        AND     SALES_GUBUN IN (SELECT SALES_GUBUN FROM @COMPANY_MST GROUP BY SALES_GUBUN)


		
		-- 전환 진행중 상태를 보기 위한 로그
		--EXEC SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG @DUPINFO, @TEMP_STR, 'SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', '부가상품 끝, 샘플 시작'



        /* 샘플 */
        UPDATE  CUSTOM_SAMPLE_ORDER
        SET     MEMBER_ID = @NEW_ID
        WHERE   1 = 1
        AND     MEMBER_ID = @UID
        AND     SALES_GUBUN IN (SELECT SALES_GUBUN FROM @COMPANY_MST GROUP BY SALES_GUBUN)



		-- 전환 진행중 상태를 보기 위한 로그
		--EXEC SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG @DUPINFO, @TEMP_STR, 'SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', '샘플 끝, 이용후기 시작'



        /* 이용후기 */
        UPDATE  S2_UserComment
        SET     UID = @NEW_ID
        WHERE   1 = 1
        AND     UID = @UID
        AND     SALES_GUBUN IN (SELECT SALES_GUBUN FROM @COMPANY_MST GROUP BY SALES_GUBUN)



		-- 전환 진행중 상태를 보기 위한 로그
		--EXEC SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG @DUPINFO, @TEMP_STR, 'SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', '이용후기 끝, M청첩장 시작 '



        /* M청첩장 */
        UPDATE  S5_nmCardOrder
        SET     UID = @NEW_ID
        WHERE   1 = 1
        AND     UID = @UID
        AND     COMPANY_SEQ IN (SELECT COMPANY_SEQ FROM @COMPANY_MST GROUP BY COMPANY_SEQ)

        UPDATE  S2_mCardOrder
        SET     UID = @NEW_ID
        WHERE   1 = 1
        AND     UID = @UID
        AND     COMPANY_SEQ IN (SELECT COMPANY_SEQ FROM @COMPANY_MST GROUP BY COMPANY_SEQ)



		-- 전환 진행중 상태를 보기 위한 로그
		--EXEC SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG @DUPINFO, @TEMP_STR, 'SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', 'M청첩장 끝, E청첩장 시작 '


        
        /* E청첩장 */
        UPDATE  S2_eCardOrder
        SET     UID = @NEW_ID
        WHERE   1 = 1
        AND     UID = @UID
        AND     COMPANY_SEQ IN (SELECT COMPANY_SEQ FROM @COMPANY_MST GROUP BY COMPANY_SEQ)



		-- 전환 진행중 상태를 보기 위한 로그
		--EXEC SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG @DUPINFO, @TEMP_STR, 'SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', 'E청첩장 끝, 고객 Q&A 시작 '



        /* 고객 Q&A */
        UPDATE  S2_UserQnA
        SET     MEMBER_ID = @NEW_ID
        WHERE   1 = 1
        AND     MEMBER_ID = @UID
        AND     COMPANY_SEQ IN (SELECT COMPANY_SEQ FROM @COMPANY_MST GROUP BY COMPANY_SEQ)



		-- 전환 진행중 상태를 보기 위한 로그
		--EXEC SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG @DUPINFO, @TEMP_STR, 'SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', '고객 Q&A 끝, 쿠폰 시작 '



        /* 쿠폰 */
        UPDATE  S4_COUPON
        SET     UID = @NEW_ID
        WHERE   1 = 1
        AND     UID = @UID
        AND     COMPANY_SEQ IN (SELECT COMPANY_SEQ FROM @COMPANY_MST GROUP BY COMPANY_SEQ)
        
		UPDATE  S4_MYCOUPON
        SET     UID = @NEW_ID
        WHERE   1 = 1
        AND     UID = @UID
        AND     COMPANY_SEQ IN (SELECT COMPANY_SEQ FROM @COMPANY_MST GROUP BY COMPANY_SEQ)



		-- 전환 진행중 상태를 보기 위한 로그
		--EXEC SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG @DUPINFO, @TEMP_STR, 'SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', '쿠폰 끝, 이벤트 리뷰 시작 '
		/* 이벤트 리뷰 */
        UPDATE  S4_EVENT_REVIEW
        SET     ER_UserId = @NEW_ID
        WHERE   1 = 1
        AND     ER_UserId = @UID
        AND     ER_Company_Seq IN (SELECT COMPANY_SEQ FROM @COMPANY_MST GROUP BY COMPANY_SEQ)

		

		-- 전환 진행중 상태를 보기 위한 로그
		--EXEC SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG @DUPINFO, @TEMP_STR, 'SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', '이벤트 리뷰 끝 '



        DELETE @COMPANY_MST

        SET @i = @i + 1



		-- 전환 진행중 상태를 보기 위한 로그
		--EXEC SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG @DUPINFO, @TEMP_STR, 'SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', 'WHILE 문 루프 마지막 부분'
		


    END



	-- 전환 진행중 상태를 보기 위한 로그
	--EXEC SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG @DUPINFO, @TEMP_STR, 'SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER', 'WHILE 끝 SP_EXEC_TRANSACTION_INFORMATION_ID_TO_INTEGRATION_MEMBER 완료'



END
GO
