IF OBJECT_ID (N'dbo.SP_SELECT_PRINT_DRIFT', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_PRINT_DRIFT
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_SELECT_PRINT_DRIFT]
	@ORDER_SEQ INT = NULL
AS
	BEGIN
		SELECT	A.TITLE, A.IMGFOLDER,A.IMGNAME 
        FROM	CUSTOM_ORDER_PLIST A LEFT OUTER JOIN 
				CUSTOM_ORDER_COPY_PLCCODE B ON A.TITLE= B.TITLE 
        WHERE	A.ORDER_SEQ = @ORDER_SEQ AND 
				PSTATUS>0 AND
				NOT IMGNAME IS NULL AND  
				A.TITLE NOT LIKE '%봉투%' AND  
				A.TITLE NOT LIKE '%기본인쇄'   
	END
GO
