IF OBJECT_ID (N'dbo.SP_INSERT_COMMON_CODE', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_INSERT_COMMON_CODE
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_INSERT_COMMON_CODE]

    @CLSS_CODE      AS VARCHAR(3)
,   @CLSS_NAME      AS VARCHAR(100)
,   @DTL_NAME       AS VARCHAR(100)
,   @DTL_DESC       AS VARCHAR(100)
,   @RMRK_CLMN      AS VARCHAR(100)
,   @USE_YORN       AS CHAR(1)
,   @DISPLAY_YORN   AS CHAR(1)
,   @SORT_NUM       AS INT

AS
BEGIN

DECLARE @DTL_CLSS AS VARCHAR(3)

IF @CLSS_CODE = '' OR NOT(EXISTS(SELECT * FROM COMMON_CODE WHERE CLSS_CODE = @CLSS_CODE))
    BEGIN
    
        SET @CLSS_CODE = CONVERT(VARCHAR(3), RIGHT('000' + CONVERT(VARCHAR(3), (SELECT MAX(CLSS_CODE) + 1 FROM COMMON_CODE)), 3))
        SET @DTL_CLSS = '001'

    END
ELSE
    BEGIN
    
        SET @CLSS_NAME = (SELECT TOP 1 CLSS_NAME FROM COMMON_CODE WHERE CLSS_CODE = @CLSS_CODE)
        SET @DTL_CLSS = CONVERT(VARCHAR(3), RIGHT('000' + CONVERT(VARCHAR(3), (SELECT MAX(DTL_CLSS) + 1 FROM COMMON_CODE WHERE CLSS_CODE = @CLSS_CODE)), 3))
    END

    INSERT INTO COMMON_CODE (CMMN_CODE,LANG_CODE,CLSS_CODE,CLSS_NAME,DTL_CLSS,DTL_NAME,DTL_DESC,RMRK_CLMN,USE_YORN,DISPLAY_YORN,SORT_NUM)
    VALUES (@CLSS_CODE + @DTL_CLSS, 'KR', @CLSS_CODE, @CLSS_NAME, @DTL_CLSS, @DTL_NAME, @DTL_DESC, @RMRK_CLMN, @USE_YORN, @DISPLAY_YORN, @SORT_NUM)

END

GO
