IF OBJECT_ID (N'dbo.up_Select_S4_EventMusic_Reply_Bhands', N'P') IS NOT NULL DROP PROCEDURE dbo.up_Select_S4_EventMusic_Reply_Bhands
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		시스템지원팀, 장형일 과장
-- Create date: 2015-07-24
-- Description:	프론트, 초대 이벤트 참여 리스트, S4_EventMusic_Reply

-- EXEC up_Select_S4_EventMusic_Reply 84, 1, 10
-- =============================================

/*
	EXEC up_Select_S4_EventMusic_Reply 84, 1, 10

	EXEC up_Select_S4_EventMusic_Reply 104, 1, 10, 5001
*/
CREATE proc [dbo].[up_Select_S4_EventMusic_Reply_Bhands]

		@EVENT_SEQ			INT
	,	@PAGE				SMALLINT
	,	@PAGE_SIZE			SMALLINT
	,	@COMPANY_SEQ		INT = 0

AS

SET NOCOUNT ON;

DECLARE @STARTROWNUM SMALLINT, @ENDROWNUM SMALLINT, @TOTALCNT INT


SET @STARTROWNUM = (@PAGE - 1) * @PAGE_SIZE + 1
SET @ENDROWNUM   = @PAGE * @PAGE_SIZE

SELECT	@TOTALCNT = COUNT(SEQ)
FROM	S4_EVENTMUSIC_REPLY S2ER
LEFT JOIN VIEW_USRINFO VU ON VU.UID = S2ER.UID 
WHERE	REG_NUM = @EVENT_SEQ AND SITE_NAME ='비핸즈카드'

SELECT	@TOTALCNT AS TOTALCNT
	,	@TOTALCNT - ROWNUM + 1 AS ROWINDEX
	,	*
FROM 
(
	SELECT	ROW_NUMBER() OVER(ORDER BY S2ER.REG_DATE DESC) AS ROWNUM
		,	S2ER.COMMENT
		,	S2ER.UID
		,	CONVERT(VARCHAR(10), S2ER.REG_DATE, 102) AS REG_DATE
		,	S2ER.UNAME
	FROM	S4_EVENTMUSIC_REPLY S2ER
	LEFT OUTER JOIN VIEW_USRINFO VU
	ON VU.UID = S2ER.UID 
	WHERE	S2ER.REG_NUM = @EVENT_SEQ
	AND SITE_NAME ='비핸즈카드'

) AS T
WHERE	T.ROWNUM BETWEEN @STARTROWNUM AND @ENDROWNUM
GO
