IF OBJECT_ID (N'dbo.SP_INSERT_S4_LOGINIPINFO', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_INSERT_S4_LOGINIPINFO
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

*/

CREATE PROCEDURE [dbo].[SP_INSERT_S4_LOGINIPINFO]
    @COMPANY_SEQ		AS INT
,   @UID				AS VARCHAR(50)
,   @UNAME				AS VARCHAR(100)
,   @UMAIL				AS VARCHAR(50)
,   @IP					AS VARCHAR(15)
,   @REFERER_URL		AS VARCHAR(1000)
,	@DEVICE_TYPE_NAME   AS VARCHAR(20) = 'PC'
,	@SALES_GUBUN		AS VARCHAR(10) = ''
,	@AGENT_TYPE			AS NVARCHAR(800) = ''
	

AS
BEGIN

	IF @SALES_GUBUN = ''
	BEGIN
		
		SET @SALES_GUBUN = ISNULL((SELECT SALES_GUBUN FROM COMPANY WHERE COMPANY_SEQ = @COMPANY_SEQ), 'SA')

	END



    INSERT INTO S4_LOGINIPINFO (COMPANY_SEQ, SALES_GUBUN, UID, UNAME, UMAIL, IP, REFERER_URL, DEVICE_TYPE_NAME, AGENT_TYPE) 
    SELECT  @COMPANY_SEQ
		,	@SALES_GUBUN
        ,   @UID        
        ,   @UNAME      
        ,   @UMAIL      
        ,   @IP         
        ,   @REFERER_URL
		,	@DEVICE_TYPE_NAME
		,   @AGENT_TYPE

END
GO
