IF OBJECT_ID (N'dbo.SP_SELECT_CALL_CENTER_STATUS', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_CALL_CENTER_STATUS
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

	EXEC SP_SELECT_CALL_CENTER_STATUS '2015-08-24', '2015-09-24'

*/

CREATE PROCEDURE [dbo].[SP_SELECT_CALL_CENTER_STATUS]
    @START_DATE AS VARCHAR(10)
,	@END_DATE AS VARCHAR(10)
AS
BEGIN

	SELECT	QNA.QNA_RECEPT_PROCESSING_CNT
		,	SMS.SMS_RECEPT_ASSIGN_CNT
		,	ISNULL(CSLM.CALL_BUSY	, 0) AS CALL_BUSY_VALUE
		,	ISNULL(CSLM.CALL_GOOD	, 0) AS CALL_GOOD_VALUE	
		,	ISNULL(CSLM.QNA_BUSY	, 0) AS QNA_BUSY_VALUE
		,	ISNULL(CSLM.QNA_GOOD	, 0) AS QNA_GOOD_VALUE	
		,	ISNULL(CSLM.SMS_BUSY	, 0) AS SMS_BUSY_VALUE	
		,	ISNULL(CSLM.SMS_GOOD	, 0) AS SMS_GOOD_VALUE

	FROM	(
				SELECT	COUNT(*) AS QNA_RECEPT_PROCESSING_CNT
				FROM	VIEW_USRQNA 
				WHERE	1 = 1
				AND		A_STAT <> 'S4' 
				AND		A_STAT IN ('S1','S2') 
				AND		SALES_GUBUN IN (  'SA' , 'C' , 'SB' , 'ST' , 'SS' , 'B' , 'H' , 'U' , 'D' , 'Q' , 'P' , 'SG' , 'X' , 'XB' , 'G'  ) 
				AND		REG_DT >= @START_DATE + ' 00:00:00' 
				AND		REG_DT <= @END_DATE + ' 23:59:59' 
			) QNA

		,	(
				SELECT	COUNT(*) AS SMS_RECEPT_ASSIGN_CNT
				FROM	INVTMNG.MO_TRAN MT
				JOIN	MANAGE_CODE MC ON MT.MO_NUMBER = MC.CODE AND MC.CODE_TYPE = 'CALL'  
				WHERE	1 = 1
				AND		MT.MO_ACCEPTTIME >= REPLACE(@START_DATE, '-', '') + '000000'
				AND		MT.MO_ACCEPTTIME <= REPLACE(@END_DATE, '-', '') + '235959'
				AND		MT.MO_STATUS = '0' 
			) SMS

		,	(
				SELECT	TOP 1 
						CALL_BUSY
					,	CALL_GOOD
					,	QNA_BUSY
					,	QNA_GOOD
					,	SMS_BUSY
					,	SMS_GOOD
				FROM	CALLCENTER_SIGNAL_LAMP_MST
				WHERE	1 = 1
				ORDER BY REG_DATE DESC
			) CSLM

END

GO
