IF OBJECT_ID (N'dbo.SP_INSERT_INTEGRATION_MEMBER_SIGN_UP_NEW_20230315', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_INSERT_INTEGRATION_MEMBER_SIGN_UP_NEW_20230315
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_INSERT_INTEGRATION_MEMBER_SIGN_UP_NEW_20230315] 
 @AUTHCODE				VARCHAR(100),   
 @CONNINFO				VARCHAR(100),	
 @AUTHTYPE				VARCHAR(100),  
 @USER_ID				VARCHAR(50), 
 @PASSWORD              VARCHAR(16),
 @USER_NAME             VARCHAR(16),
 @EMAIL                 VARCHAR(100),
 @BIRTH                 VARCHAR(10),
 @BIRTH_DIV             CHAR(1),
 @ZIP1                  VARCHAR(3), 
 @ZIP2                  VARCHAR(3), 
 @ADDRESS               VARCHAR(150),
 @ADDRESS_DETAIL        VARCHAR(150), 
 @PHONE1                VARCHAR(4), 
 @PHONE2                VARCHAR(4),
 @PHONE3                VARCHAR(4), 
 @HPHONE1               VARCHAR(4),
 @HPHONE2               VARCHAR(4),   
 @HPHONE3               VARCHAR(4),
 @CHK_SMS				CHAR(1),
 @CHK_MAILSERVICE       CHAR(1),
 @ADDR_FLAG             INT = 0,   
 @CHK_SMEMBERSHIP       CHAR(1) = '', 
 @CHK_SMEMBERSHIP_PER   CHAR(1) = '',   
 @CHK_SMEMBERSHIP_COOP  CHAR(1) = '', 
 @MKT_CHK_FLAG          CHAR(1) = '', 
 @WEDD_YEAR             VARCHAR(4) = '', 
 @WEDD_MONTH            VARCHAR(2) = '', 
 @WEDD_DAY              VARCHAR(2) = '', 
 @WEDD_HOUR             VARCHAR(2) = '',   
 @WEDD_MINUTE           VARCHAR(2) = '',   
 @UGUBUN                CHAR(1)			= '',
 @CHK_DM                CHAR(1)			= '', 
 @WEDD_PGUBUN           CHAR(1)			= '', 
 @GENDER                CHAR(1)			= '',	
 @ORI_BIRTH    		    VARCHAR(8)		= '',	
 @NATIONAL_INFO			CHAR(1) = '', 
 @COMPANY_SEQ           INT = 5001,
 @PASSWORD_ENCRYPT		VARCHAR(200) = '', 
 @CHK_MYOMEE            CHAR(1) = '',   
 @CHK_ILOOMMBERSHIP     CHAR(1) = '',	
 @CHK_LGMEMBERSHIP		CHAR(1)	= '',
 @CHK_CUCKOOSMEMBERSHIP	CHAR(1) = '',
 @CHK_CASAMIAMEMBERSHIP	CHAR(1) = '',
 @CHK_KTMEMBERSHIP	    CHAR(1) = '',
 @WEDD_NAME				NVARCHAR(200) = '',
 @SMEMBERSHIP_PERIOD	CHAR(1) = '',
 @CHK_HYUNDAIMEMBERSHIP CHAR(1) = ''
AS  
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

	DECLARE @NOW datetime;
	Set @NOW = GETDATE();

	BEGIN TRY
		BEGIN
			BEGIN TRANSACTION;      

			SET @PASSWORD_ENCRYPT = CASE WHEN ISNULL(@PASSWORD, '') = '' THEN @PASSWORD_ENCRYPT ELSE CONVERT(VARCHAR(200), PWDENCRYPT(@PASSWORD), 1) END;

			-- 맴버십 가입일 변수 선언
			/* 삼성 맴버십,  롯데렌탈 묘미, 일룸, LG, CUCKOO, 까사미아, KT, 현대백화점 */
			DECLARE @SMEMBERSHI_REG_DATE datetime, @MYOMEE_REG_DATE datetime, @ILOOMMEMBERSHIP_REG_DATE datetime, @LGMEMBERSHIP_REG_DATE datetime,
					@CUCKOOSSHIP_REG_DATE datetime, @CASAMIASHIP_REG_DATE datetime, @KTMEMBERSHIP_REG_DATE datetime, @HYUNDAIMEMBERSHIP_REG_DATE datetime,
					@DB_CHK_SMEMBERSHIP CHAR(1), @DB_CHK_SMEMBERSHIP_PER CHAR(1), @DB_CHK_SMEMBERSHIP_COOP  CHAR(1), 
					@DB_CHK_MYOMEE CHAR(1), @DB_CHK_ILOOMMBERSHIP CHAR(1), @DB_CHK_LGMEMBERSHIP CHAR(1), @DB_CHK_CUCKOOSMEMBERSHIP CHAR(1),
					@DB_CHK_CASAMIAMEMBERSHIP  CHAR(1), @DB_CHK_KTMEMBERSHIP  CHAR(1), @DB_CHK_HYUNDAIMEMBERSHIP  CHAR(1),
					@DB_MKT_CHK_FLAG CHAR(1);

			SELECT	@DB_CHK_SMEMBERSHIP = MAX(CHOICE_AGREEMENT_FOR_SAMSUNG_MEMBERSHIP),
					@DB_CHK_SMEMBERSHIP_PER = MAX(CHOICE_AGREEMENT_FOR_SAMSUNG_CHOICE_PERSONAL_DATA),
					@DB_CHK_SMEMBERSHIP_COOP = MAX(CHOICE_AGREEMENT_FOR_SAMSUNG_THIRDPARTY),
					@SMEMBERSHI_REG_DATE = MIN(SMEMBERSHIP_REG_DATE),

					@DB_CHK_MYOMEE = MAX(CHK_MYOMEE),
					@MYOMEE_REG_DATE = MIN(MYOMEE_REG_DATE),

					@DB_CHK_ILOOMMBERSHIP = MAX(chk_iloommembership),
					@ILOOMMEMBERSHIP_REG_DATE = MIN(ILOOMMEMBERSHIP_REG_DATE), 

					@DB_CHK_LGMEMBERSHIP = MAX(CHK_LGMEMBERSHIP),
					@LGMEMBERSHIP_REG_DATE = MIN(LGMEMBERSHIP_REG_DATE),

					@DB_CHK_CUCKOOSMEMBERSHIP = MAX(CHK_CUCKOOSMEMBERSHIP),
					@CUCKOOSSHIP_REG_DATE = MIN(CUCKOOSSHIP_REG_DATE),

					@DB_CHK_CASAMIAMEMBERSHIP = MAX(CHK_CASAMIAMEMBERSHIP),
					@CASAMIASHIP_REG_DATE = MIN(CASAMIASHIP_REG_DATE),

					@DB_CHK_KTMEMBERSHIP = MAX(CHK_KTMEMBERSHIP),
					@KTMEMBERSHIP_REG_DATE = MIN(KTMEMBERSHIP_REG_DATE),

					@DB_CHK_HYUNDAIMEMBERSHIP = MAX(CHK_HYUNDAIMEMBERSHIP),
					@HYUNDAIMEMBERSHIP_REG_DATE = MIN(HYUNDAIMEMBERSHIP_REG_DATE),

					@DB_MKT_CHK_FLAG = MAX(MKT_CHK_FLAG)
			From	VW_USER_INFO
			Where	DUPINFO = @AUTHCODE;

			DECLARE @SMEMBERSHIP_INFLOW_ROUTE varchar(10);

			IF (@CHK_SMEMBERSHIP is null OR @CHK_SMEMBERSHIP = '')				SET @CHK_SMEMBERSHIP = ISNULL(@DB_CHK_SMEMBERSHIP, 'N');
			IF @CHK_SMEMBERSHIP = 'Y' 
				SET @SMEMBERSHIP_INFLOW_ROUTE = 'JOIN' 
			ELSE 
				SET @SMEMBERSHIP_INFLOW_ROUTE = null;
			IF (@CHK_SMEMBERSHIP_PER is null OR @CHK_SMEMBERSHIP_PER = '')		SET @CHK_SMEMBERSHIP_PER = ISNULL(@DB_CHK_SMEMBERSHIP_PER, 'N');
			IF (@CHK_SMEMBERSHIP_COOP is null OR @CHK_SMEMBERSHIP_COOP = '')	SET @CHK_SMEMBERSHIP_COOP = ISNULL(@DB_CHK_SMEMBERSHIP_COOP, 'N');
			IF (@CHK_MYOMEE is null OR @CHK_MYOMEE = '')						SET @CHK_MYOMEE = ISNULL(@DB_CHK_MYOMEE, 'N');
			IF (@CHK_ILOOMMBERSHIP is null OR @CHK_ILOOMMBERSHIP = '')			SET @CHK_ILOOMMBERSHIP = ISNULL(@DB_CHK_ILOOMMBERSHIP, 'N');
			IF (@CHK_LGMEMBERSHIP is null OR @CHK_LGMEMBERSHIP = '')			SET @CHK_LGMEMBERSHIP = ISNULL(@DB_CHK_LGMEMBERSHIP, 'N');
			IF (@CHK_CUCKOOSMEMBERSHIP is null OR @CHK_CUCKOOSMEMBERSHIP = '')	SET @CHK_CUCKOOSMEMBERSHIP = ISNULL(@DB_CHK_CUCKOOSMEMBERSHIP, 'N');
			IF (@CHK_CASAMIAMEMBERSHIP is null OR @CHK_CASAMIAMEMBERSHIP = '')	SET @CHK_CASAMIAMEMBERSHIP = ISNULL(@DB_CHK_CASAMIAMEMBERSHIP, 'N');
			IF (@CHK_KTMEMBERSHIP is null OR @CHK_KTMEMBERSHIP = '')			SET @CHK_KTMEMBERSHIP = ISNULL(@DB_CHK_KTMEMBERSHIP, 'N');
			IF (@CHK_HYUNDAIMEMBERSHIP is null OR @CHK_HYUNDAIMEMBERSHIP = '')	SET @CHK_HYUNDAIMEMBERSHIP = ISNULL(@DB_CHK_HYUNDAIMEMBERSHIP, 'N');

			IF (@MKT_CHK_FLAG is null OR @MKT_CHK_FLAG = '')					SET @MKT_CHK_FLAG = ISNULL(@DB_MKT_CHK_FLAG, 'N');
			IF @UGUBUN = '' SET @UGUBUN = null;
			IF @CHK_DM = '' SET @CHK_DM = null;
			IF @WEDD_PGUBUN = '' SET @WEDD_PGUBUN = null;

			-- 기존 맴버십 가입일 값이 없고 가입체크했을 경우 오늘날짜 설정
			IF (@SMEMBERSHI_REG_DATE IS NULL AND @CHK_SMEMBERSHIP = 'Y')		SET @SMEMBERSHI_REG_DATE = @NOW;
			IF (@MYOMEE_REG_DATE IS NULL AND @CHK_MYOMEE = 'Y')					SET @MYOMEE_REG_DATE = @NOW;
			IF (@ILOOMMEMBERSHIP_REG_DATE IS NULL AND @CHK_ILOOMMBERSHIP = 'Y') SET @ILOOMMEMBERSHIP_REG_DATE = @NOW;
			IF (@LGMEMBERSHIP_REG_DATE IS NULL AND @CHK_LGMEMBERSHIP = 'Y')		SET @LGMEMBERSHIP_REG_DATE = @NOW;
			IF (@CUCKOOSSHIP_REG_DATE IS NULL AND @CHK_CUCKOOSMEMBERSHIP = 'Y') SET @CUCKOOSSHIP_REG_DATE = @NOW;
			IF (@CASAMIASHIP_REG_DATE IS NULL AND @CHK_CASAMIAMEMBERSHIP = 'Y') SET @CASAMIASHIP_REG_DATE = @NOW;
			IF (@KTMEMBERSHIP_REG_DATE IS NULL AND @CHK_KTMEMBERSHIP = 'Y')		SET @KTMEMBERSHIP_REG_DATE = @NOW;
			IF (@HYUNDAIMEMBERSHIP_REG_DATE IS NULL AND @CHK_HYUNDAIMEMBERSHIP = 'Y') SET @HYUNDAIMEMBERSHIP_REG_DATE = @NOW;

			/* 
				비핸즈카드 수정 등록
				DUPINFO 값은 2017-02-17 13:15:55.980 이후 등록회원부터 유일한 값을 가짐.
			*/
			UPDATE	S2_USERINFO_BHANDS SET
					CONNINFO		= @CONNINFO,
					AUTHTYPE		= @AUTHTYPE,
					[UID]			= @USER_ID,
					PWD				= @PASSWORD_ENCRYPT,
					UNAME			= @USER_NAME,
					UMAIL			= @EMAIL,
					BIRTH           = @BIRTH,
					BIRTH_DIV       = @BIRTH_DIV,
					ZIP1            = @ZIP1,
					ZIP2            = @ZIP2,
					[ADDRESS]       = @ADDRESS,
					ADDR_DETAIL     = @ADDRESS_DETAIL,
					PHONE1          = @PHONE1,
					PHONE2          = @PHONE2,
					PHONE3          = @PHONE3,
					HAND_PHONE1     = @HPHONE1,
					HAND_PHONE2     = @HPHONE2,
					HAND_PHONE3     = @HPHONE3,
					CHK_SMS         = @CHK_SMS,
					CHK_MAILSERVICE = @CHK_MAILSERVICE,
					ADDR_FLAG       = @ADDR_FLAG,
					MKT_CHK_FLAG	= @MKT_CHK_FLAG,
					WEDD_YEAR		= @WEDD_YEAR,
					WEDD_MONTH		= @WEDD_MONTH,
					WEDD_DAY		= @WEDD_DAY,
					WEDD_HOUR		= @WEDD_HOUR,
					WEDD_MINUTE		= @WEDD_MINUTE,
					--UGUBUN			= @UGUBUN,    업데이트하지 않음
					--CHK_DM			= @CHK_DM,
					--WEDD_PGUBUN		= @WEDD_PGUBUN,
					MOD_DATE		= @NOW,
					BIRTHDATE		= @ORI_BIRTH,
					GENDER			= @GENDER,      
					NATIONALINFO	= @NATIONAL_INFO,
					PWD_BACKUP		= @PASSWORD,
					CHK_SMEMBERSHIP				= @CHK_SMEMBERSHIP,         
					SMEMBERSHIP_CHK_FLAG		= @CHK_SMEMBERSHIP,   
					SMEMBERSHIP_REG_DATE		= @SMEMBERSHI_REG_DATE,  
					SMEMBERSHIP_INFLOW_ROUTE	= @SMEMBERSHIP_INFLOW_ROUTE,
					CHK_SMEMBERSHIP_PER			= @CHK_SMEMBERSHIP_PER,  
					CHK_SMEMBERSHIP_COOP		= @CHK_SMEMBERSHIP_COOP,
					SMEMBERSHIP_PERIOD			= @SMEMBERSHIP_PERIOD,
					CHK_MYOMEE					= @CHK_MYOMEE,
					MYOMEE_REG_DATE				= @MYOMEE_REG_DATE,
					CHK_ILOOMMEMBERSHIP			= @CHK_ILOOMMBERSHIP,      
					ILOOMMEMBERSHIP_REG_DATE    = @ILOOMMEMBERSHIP_REG_DATE,
					CHK_LGMEMBERSHIP			= @CHK_LGMEMBERSHIP,
					LGMEMBERSHIP_REG_DATE		= @LGMEMBERSHIP_REG_DATE,
					CHK_CUCKOOSMEMBERSHIP		= @CHK_CUCKOOSMEMBERSHIP,
					CUCKOOSSHIP_REG_DATE		= @CUCKOOSSHIP_REG_DATE,
					CHK_CASAMIAMEMBERSHIP		= @CHK_CASAMIAMEMBERSHIP,
					CASAMIASHIP_REG_DATE		= @CASAMIASHIP_REG_DATE,
					CHK_KTMEMBERSHIP			= @CHK_KTMEMBERSHIP,
					KTMEMBERSHIP_REG_DATE		= @KTMEMBERSHIP_REG_DATE,
					CHK_HYUNDAIMEMBERSHIP		= @CHK_HYUNDAIMEMBERSHIP,
					HYUNDAIMEMBERSHIP_REG_DATE	= @HYUNDAIMEMBERSHIP_REG_DATE,
					WEDD_NAME		= @WEDD_NAME
			WHERE	DUPINFO = @AUTHCODE;

			IF @@ROWCOUNT = 0
			BEGIN
				INSERT INTO S2_USERINFO_BHANDS (DUPINFO, CONNINFO, AUTHTYPE, [UID], PWD, UNAME, UMAIL, SITE_DIV, JUMIN, BIRTH, BIRTH_DIV
					, ZIP1, ZIP2, [ADDRESS], ADDR_DETAIL, PHONE1, PHONE2, PHONE3, HAND_PHONE1, HAND_PHONE2, HAND_PHONE3             
					, CHK_SMS, CHK_MAILSERVICE, ADDR_FLAG, MKT_CHK_FLAG                  
					, WEDD_YEAR, WEDD_MONTH, WEDD_DAY, WEDD_HOUR, WEDD_MINUTE, UGUBUN, CHK_DM, WEDD_PGUBUN
					, INTEGRATION_MEMBER_YORN, INTERGRATION_DATE, MOD_DATE, REG_DATE, USE_YORN
					, BIRTHDATE, GENDER, NATIONALINFO, PWD_BACKUP, WEDD_NAME
					
					, CHK_SMEMBERSHIP, SMEMBERSHIP_CHK_FLAG, SMEMBERSHIP_REG_DATE, SMEMBERSHIP_INFLOW_ROUTE, CHK_SMEMBERSHIP_PER, CHK_SMEMBERSHIP_COOP, SMEMBERSHIP_PERIOD    
					, CHK_MYOMEE, MYOMEE_REG_DATE
					, CHK_ILOOMMEMBERSHIP, ILOOMMEMBERSHIP_REG_DATE    
					, CHK_LGMEMBERSHIP,	LGMEMBERSHIP_REG_DATE
					, CHK_CUCKOOSMEMBERSHIP, CUCKOOSSHIP_REG_DATE
					, CHK_CASAMIAMEMBERSHIP, CASAMIASHIP_REG_DATE
					, CHK_KTMEMBERSHIP, KTMEMBERSHIP_REG_DATE
					, CHK_HYUNDAIMEMBERSHIP, HYUNDAIMEMBERSHIP_REG_DATE
				)
				Values (@AUTHCODE, @CONNINFO, @AUTHTYPE, @USER_ID, @PASSWORD_ENCRYPT, @USER_NAME, @EMAIL, 'SA', '', @BIRTH, @BIRTH_DIV
					, @ZIP1, @ZIP2, @ADDRESS, @ADDRESS_DETAIL, @PHONE1, @PHONE2, @PHONE3, @HPHONE1, @HPHONE2, @HPHONE3
					, @CHK_SMS, @CHK_MAILSERVICE, @ADDR_FLAG, @MKT_CHK_FLAG
					, @WEDD_YEAR, @WEDD_MONTH, @WEDD_DAY, @WEDD_HOUR, @WEDD_MINUTE, @UGUBUN, @CHK_DM, @WEDD_PGUBUN
					, 'Y', @NOW, @NOW, @NOW, 'Y'
					, @ORI_BIRTH, @GENDER, @NATIONAL_INFO, @PASSWORD, @WEDD_NAME

					, @CHK_SMEMBERSHIP, @CHK_SMEMBERSHIP, @SMEMBERSHI_REG_DATE, @SMEMBERSHIP_INFLOW_ROUTE, @CHK_SMEMBERSHIP_PER, @CHK_SMEMBERSHIP_COOP, @SMEMBERSHIP_PERIOD
					, @CHK_MYOMEE, @MYOMEE_REG_DATE
					, @CHK_ILOOMMBERSHIP, @ILOOMMEMBERSHIP_REG_DATE    
					, @CHK_LGMEMBERSHIP,	@LGMEMBERSHIP_REG_DATE
					, @CHK_CUCKOOSMEMBERSHIP, @CUCKOOSSHIP_REG_DATE
					, @CHK_CASAMIAMEMBERSHIP, @CASAMIASHIP_REG_DATE
					, @CHK_KTMEMBERSHIP, @KTMEMBERSHIP_REG_DATE
					, @CHK_HYUNDAIMEMBERSHIP, @HYUNDAIMEMBERSHIP_REG_DATE
				);
			END
    
			/* 
				더카드 수정 등록
				DUPINFO 값은 2021-03-05 14:50:26.670 이후 등록회원부터 유일한 값을 가짐.
			*/
			UPDATE	S2_USERINFO_THECARD SET
					CONNINFO		= @CONNINFO,
					AUTHTYPE		= @AUTHTYPE,
					[UID]			= @USER_ID,
					PWD				= @PASSWORD_ENCRYPT,
					UNAME			= @USER_NAME,
					UMAIL			= @EMAIL,
					BIRTH           = @BIRTH,
					BIRTH_DIV       = @BIRTH_DIV,
					ZIP1            = @ZIP1,
					ZIP2            = @ZIP2,
					[ADDRESS]       = @ADDRESS,
					ADDR_DETAIL     = @ADDRESS_DETAIL,
					PHONE1          = @PHONE1,
					PHONE2          = @PHONE2,
					PHONE3          = @PHONE3,
					HAND_PHONE1     = @HPHONE1,
					HAND_PHONE2     = @HPHONE2,
					HAND_PHONE3     = @HPHONE3,
					CHK_SMS         = @CHK_SMS,
					CHK_MAILSERVICE = @CHK_MAILSERVICE,
					ADDR_FLAG       = @ADDR_FLAG,
					MKT_CHK_FLAG	= @MKT_CHK_FLAG,
					WEDD_YEAR		= @WEDD_YEAR,
					WEDD_MONTH		= @WEDD_MONTH,
					WEDD_DAY		= @WEDD_DAY,
					WEDD_HOUR		= @WEDD_HOUR,
					WEDD_MINUTE		= @WEDD_MINUTE,
					--UGUBUN			= @UGUBUN,  업데이트하지 않음
					--CHK_DM			= @CHK_DM,
					--WEDD_PGUBUN		= @WEDD_PGUBUN,
					MOD_DATE		= @NOW,
					BIRTHDATE		= @ORI_BIRTH,
					GENDER			= @GENDER,      
					NATIONALINFO	= @NATIONAL_INFO,
					PWD_BACKUP		= @PASSWORD,
					CHK_SMEMBERSHIP				= @CHK_SMEMBERSHIP,         
					SMEMBERSHIP_CHK_FLAG		= @CHK_SMEMBERSHIP,   
					SMEMBERSHIP_REG_DATE		= @SMEMBERSHI_REG_DATE,  
					SMEMBERSHIP_INFLOW_ROUTE	= @SMEMBERSHIP_INFLOW_ROUTE,
					CHK_SMEMBERSHIP_PER			= @CHK_SMEMBERSHIP_PER,  
					CHK_SMEMBERSHIP_COOP		= @CHK_SMEMBERSHIP_COOP,
					SMEMBERSHIP_PERIOD			= @SMEMBERSHIP_PERIOD,
					CHK_MYOMEE					= @CHK_MYOMEE,
					MYOMEE_REG_DATE				= @MYOMEE_REG_DATE,
					CHK_ILOOMMEMBERSHIP			= @CHK_ILOOMMBERSHIP,      
					ILOOMMEMBERSHIP_REG_DATE    = @ILOOMMEMBERSHIP_REG_DATE,
					CHK_LGMEMBERSHIP			= @CHK_LGMEMBERSHIP,
					LGMEMBERSHIP_REG_DATE		= @LGMEMBERSHIP_REG_DATE,
					CHK_CUCKOOSMEMBERSHIP		= @CHK_CUCKOOSMEMBERSHIP,
					CUCKOOSSHIP_REG_DATE		= @CUCKOOSSHIP_REG_DATE,
					CHK_CASAMIAMEMBERSHIP		= @CHK_CASAMIAMEMBERSHIP,
					CASAMIASHIP_REG_DATE		= @CASAMIASHIP_REG_DATE,
					CHK_KTMEMBERSHIP			= @CHK_KTMEMBERSHIP,
					KTMEMBERSHIP_REG_DATE		= @KTMEMBERSHIP_REG_DATE,
					CHK_HYUNDAIMEMBERSHIP		= @CHK_HYUNDAIMEMBERSHIP,
					HYUNDAIMEMBERSHIP_REG_DATE	= @HYUNDAIMEMBERSHIP_REG_DATE,
					WEDD_NAME		= @WEDD_NAME
			WHERE	DUPINFO = @AUTHCODE
			AND		SITE_DIV = 'ST';

			IF @@ROWCOUNT = 0
			BEGIN
				INSERT INTO S2_USERINFO_THECARD (DUPINFO, CONNINFO, AUTHTYPE, [UID], PWD, UNAME, UMAIL, SITE_DIV, JUMIN, BIRTH, BIRTH_DIV
					, ZIP1, ZIP2, [ADDRESS], ADDR_DETAIL, PHONE1, PHONE2, PHONE3, HAND_PHONE1, HAND_PHONE2, HAND_PHONE3             
					, CHK_SMS, CHK_MAILSERVICE, ADDR_FLAG, MKT_CHK_FLAG                  
					, WEDD_YEAR, WEDD_MONTH, WEDD_DAY, WEDD_HOUR, WEDD_MINUTE, UGUBUN, CHK_DM, WEDD_PGUBUN
					, INTEGRATION_MEMBER_YORN, INTERGRATION_DATE, MOD_DATE, REG_DATE, USE_YORN
					, BIRTHDATE, GENDER, NATIONALINFO, PWD_BACKUP, WEDD_NAME
					
					, CHK_SMEMBERSHIP, SMEMBERSHIP_CHK_FLAG, SMEMBERSHIP_REG_DATE, SMEMBERSHIP_INFLOW_ROUTE, CHK_SMEMBERSHIP_PER, CHK_SMEMBERSHIP_COOP, SMEMBERSHIP_PERIOD    
					, CHK_MYOMEE, MYOMEE_REG_DATE
					, CHK_ILOOMMEMBERSHIP, ILOOMMEMBERSHIP_REG_DATE    
					, CHK_LGMEMBERSHIP,	LGMEMBERSHIP_REG_DATE
					, CHK_CUCKOOSMEMBERSHIP, CUCKOOSSHIP_REG_DATE
					, CHK_CASAMIAMEMBERSHIP, CASAMIASHIP_REG_DATE
					, CHK_KTMEMBERSHIP, KTMEMBERSHIP_REG_DATE
					, CHK_HYUNDAIMEMBERSHIP, HYUNDAIMEMBERSHIP_REG_DATE
				)
				Values (@AUTHCODE, @CONNINFO, @AUTHTYPE, @USER_ID, @PASSWORD_ENCRYPT, @USER_NAME, @EMAIL, 'ST', '', @BIRTH, @BIRTH_DIV
					, @ZIP1, @ZIP2, @ADDRESS, @ADDRESS_DETAIL, @PHONE1, @PHONE2, @PHONE3, @HPHONE1, @HPHONE2, @HPHONE3
					, @CHK_SMS, @CHK_MAILSERVICE, @ADDR_FLAG, @MKT_CHK_FLAG
					, @WEDD_YEAR, @WEDD_MONTH, @WEDD_DAY, @WEDD_HOUR, @WEDD_MINUTE, @UGUBUN, @CHK_DM, @WEDD_PGUBUN
					, 'Y', @NOW, @NOW, @NOW, 'Y'
					, @ORI_BIRTH, @GENDER, @NATIONAL_INFO, @PASSWORD, @WEDD_NAME

					, @CHK_SMEMBERSHIP, @CHK_SMEMBERSHIP, @SMEMBERSHI_REG_DATE, @SMEMBERSHIP_INFLOW_ROUTE, @CHK_SMEMBERSHIP_PER, @CHK_SMEMBERSHIP_COOP, @SMEMBERSHIP_PERIOD
					, @CHK_MYOMEE, @MYOMEE_REG_DATE
					, @CHK_ILOOMMBERSHIP, @ILOOMMEMBERSHIP_REG_DATE    
					, @CHK_LGMEMBERSHIP,	@LGMEMBERSHIP_REG_DATE
					, @CHK_CUCKOOSMEMBERSHIP, @CUCKOOSSHIP_REG_DATE
					, @CHK_CASAMIAMEMBERSHIP, @CASAMIASHIP_REG_DATE
					, @CHK_KTMEMBERSHIP, @KTMEMBERSHIP_REG_DATE
					, @CHK_HYUNDAIMEMBERSHIP, @HYUNDAIMEMBERSHIP_REG_DATE
				);
			END

		
			/* 
				바른손카드 수정 등록
				DUPINFO 값은 SITE DEV값 BM,SS,SB 으로 중복 값 있음
				바른손: SB
				프리미어페이퍼: SS,H 값있음. 등록은 SS로 함. H는 2016-12-29 15:27:52.177 이후 등록 없기 때문에 무시하도록...
				바른손카드모바일: BM, 추가 테이블 업데이트 

				사이트별 반복시 커서 보다는 반복 변수를 사용.
			*/
			DECLARE @siteidx int, @SiteDiv varchar(3);
			SET @siteidx = 0;
			WHILE(@siteidx < 3)
			BEGIN
				IF @siteidx = 0 SET @SiteDiv = 'SB'
				ELSE IF @siteidx = 1 SET @SiteDiv = 'SS'
				ELSE IF @siteidx = 2 SET @SiteDiv = 'BM'
				ELSE BREAK;

				UPDATE	S2_USERINFO SET
						CONNINFO		= @CONNINFO,
						AUTHTYPE		= @AUTHTYPE,
						[UID]			= @USER_ID,
						PWD				= @PASSWORD_ENCRYPT,
						UNAME			= @USER_NAME,
						UMAIL			= @EMAIL,
						BIRTH           = @BIRTH,
						BIRTH_DIV       = @BIRTH_DIV,
						ZIP1            = @ZIP1,
						ZIP2            = @ZIP2,
						[ADDRESS]       = @ADDRESS,
						ADDR_DETAIL     = @ADDRESS_DETAIL,
						PHONE1          = @PHONE1,
						PHONE2          = @PHONE2,
						PHONE3          = @PHONE3,
						HAND_PHONE1     = @HPHONE1,
						HAND_PHONE2     = @HPHONE2,
						HAND_PHONE3     = @HPHONE3,
						CHK_SMS         = @CHK_SMS,
						CHK_MAILSERVICE = @CHK_MAILSERVICE,
						ADDR_FLAG       = @ADDR_FLAG,
						MKT_CHK_FLAG	= @MKT_CHK_FLAG,
						WEDD_YEAR		= @WEDD_YEAR,
						WEDD_MONTH		= @WEDD_MONTH,
						WEDD_DAY		= @WEDD_DAY,
						WEDD_HOUR		= @WEDD_HOUR,
						WEDD_MINUTE		= @WEDD_MINUTE,
						--UGUBUN			= @UGUBUN,		업데이트하지 않음
						--CHK_DM			= @CHK_DM,
						--WEDD_PGUBUN		= @WEDD_PGUBUN,
						MOD_DATE		= @NOW,
						BIRTHDATE		= @ORI_BIRTH,
						GENDER			= @GENDER,      
						NATIONALINFO	= @NATIONAL_INFO,
						PWD_BACKUP		= @PASSWORD,
						CHK_SMEMBERSHIP				= @CHK_SMEMBERSHIP,         
						SMEMBERSHIP_CHK_FLAG		= @CHK_SMEMBERSHIP,   
						SMEMBERSHIP_REG_DATE		= @SMEMBERSHI_REG_DATE,  
						SMEMBERSHIP_INFLOW_ROUTE	= @SMEMBERSHIP_INFLOW_ROUTE,
						CHK_SMEMBERSHIP_PER			= @CHK_SMEMBERSHIP_PER,  
						CHK_SMEMBERSHIP_COOP		= @CHK_SMEMBERSHIP_COOP,
						SMEMBERSHIP_PERIOD			= @SMEMBERSHIP_PERIOD,
						CHK_MYOMEE					= @CHK_MYOMEE,
						MYOMEE_REG_DATE				= @MYOMEE_REG_DATE,
						CHK_ILOOMMEMBERSHIP			= @CHK_ILOOMMBERSHIP,      
						ILOOMMEMBERSHIP_REG_DATE    = @ILOOMMEMBERSHIP_REG_DATE,
						CHK_LGMEMBERSHIP			= @CHK_LGMEMBERSHIP,
						LGMEMBERSHIP_REG_DATE		= @LGMEMBERSHIP_REG_DATE,
						CHK_CUCKOOSMEMBERSHIP		= @CHK_CUCKOOSMEMBERSHIP,
						CUCKOOSSHIP_REG_DATE		= @CUCKOOSSHIP_REG_DATE,
						CHK_CASAMIAMEMBERSHIP		= @CHK_CASAMIAMEMBERSHIP,
						CASAMIASHIP_REG_DATE		= @CASAMIASHIP_REG_DATE,
						CHK_KTMEMBERSHIP			= @CHK_KTMEMBERSHIP,
						KTMEMBERSHIP_REG_DATE		= @KTMEMBERSHIP_REG_DATE,
						CHK_HYUNDAIMEMBERSHIP		= @CHK_HYUNDAIMEMBERSHIP,
						HYUNDAIMEMBERSHIP_REG_DATE	= @HYUNDAIMEMBERSHIP_REG_DATE,
						WEDD_NAME		= @WEDD_NAME
				WHERE	DUPINFO = @AUTHCODE
				AND		SITE_DIV = @SiteDiv;

				IF @@ROWCOUNT = 0
				BEGIN
					INSERT INTO S2_USERINFO (DUPINFO, CONNINFO, AUTHTYPE, [UID], PWD, UNAME, UMAIL, SITE_DIV, JUMIN, BIRTH, BIRTH_DIV
						, ZIP1, ZIP2, [ADDRESS], ADDR_DETAIL, PHONE1, PHONE2, PHONE3, HAND_PHONE1, HAND_PHONE2, HAND_PHONE3             
						, CHK_SMS, CHK_MAILSERVICE, ADDR_FLAG, MKT_CHK_FLAG                  
						, WEDD_YEAR, WEDD_MONTH, WEDD_DAY, WEDD_HOUR, WEDD_MINUTE, UGUBUN, CHK_DM, WEDD_PGUBUN
						, INTEGRATION_MEMBER_YORN, INTERGRATION_DATE, MOD_DATE, REG_DATE, USE_YORN
						, BIRTHDATE, GENDER, NATIONALINFO, PWD_BACKUP, WEDD_NAME
					
						, CHK_SMEMBERSHIP, SMEMBERSHIP_CHK_FLAG, SMEMBERSHIP_REG_DATE, SMEMBERSHIP_INFLOW_ROUTE, CHK_SMEMBERSHIP_PER, CHK_SMEMBERSHIP_COOP, SMEMBERSHIP_PERIOD    
						, CHK_MYOMEE, MYOMEE_REG_DATE
						, CHK_ILOOMMEMBERSHIP, ILOOMMEMBERSHIP_REG_DATE    
						, CHK_LGMEMBERSHIP,	LGMEMBERSHIP_REG_DATE
						, CHK_CUCKOOSMEMBERSHIP, CUCKOOSSHIP_REG_DATE
						, CHK_CASAMIAMEMBERSHIP, CASAMIASHIP_REG_DATE
						, CHK_KTMEMBERSHIP, KTMEMBERSHIP_REG_DATE
						, CHK_HYUNDAIMEMBERSHIP, HYUNDAIMEMBERSHIP_REG_DATE
					)
					Values (@AUTHCODE, @CONNINFO, @AUTHTYPE, @USER_ID, @PASSWORD_ENCRYPT, @USER_NAME, @EMAIL, @SiteDiv, '', @BIRTH, @BIRTH_DIV
						, @ZIP1, @ZIP2, @ADDRESS, @ADDRESS_DETAIL, @PHONE1, @PHONE2, @PHONE3, @HPHONE1, @HPHONE2, @HPHONE3
						, @CHK_SMS, @CHK_MAILSERVICE, @ADDR_FLAG, @MKT_CHK_FLAG
						, @WEDD_YEAR, @WEDD_MONTH, @WEDD_DAY, @WEDD_HOUR, @WEDD_MINUTE, @UGUBUN, @CHK_DM, @WEDD_PGUBUN
						, 'Y', @NOW, @NOW, @NOW, 'Y'
						, @ORI_BIRTH, @GENDER, @NATIONAL_INFO, @PASSWORD, @WEDD_NAME

						, @CHK_SMEMBERSHIP, @CHK_SMEMBERSHIP, @SMEMBERSHI_REG_DATE, @SMEMBERSHIP_INFLOW_ROUTE, @CHK_SMEMBERSHIP_PER, @CHK_SMEMBERSHIP_COOP, @SMEMBERSHIP_PERIOD
						, @CHK_MYOMEE, @MYOMEE_REG_DATE
						, @CHK_ILOOMMBERSHIP, @ILOOMMEMBERSHIP_REG_DATE    
						, @CHK_LGMEMBERSHIP,	@LGMEMBERSHIP_REG_DATE
						, @CHK_CUCKOOSMEMBERSHIP, @CUCKOOSSHIP_REG_DATE
						, @CHK_CASAMIAMEMBERSHIP, @CASAMIASHIP_REG_DATE
						, @CHK_KTMEMBERSHIP, @KTMEMBERSHIP_REG_DATE
						, @CHK_HYUNDAIMEMBERSHIP, @HYUNDAIMEMBERSHIP_REG_DATE
					);
				END
				SET @siteidx = @siteidx + 1;
			END

			/* 제3자 마케팅 활용 동의 */
			IF @MKT_CHK_FLAG = 'Y' 
			BEGIN
				IF NOT EXISTS( SELECT * FROM S4_EVENT_RAINA WHERE [UID] = @USER_ID AND COMPANY_SEQ = @COMPANY_SEQ ) 
				BEGIN
					INSERT S4_EVENT_RAINA ([UID],COMPANY_SEQ,EVENT_DIV, INFLOW_ROUTE) 
					VALUES (@USER_ID, @COMPANY_SEQ, 'MKEVENT', 'MODIFY')
				END
			END ELSE IF @MKT_CHK_FLAG = 'N' 
			BEGIN
				IF EXISTS( SELECT * FROM S4_EVENT_RAINA WHERE [UID] = @USER_ID AND COMPANY_SEQ = @COMPANY_SEQ ) 
				BEGIN
					DELETE  S4_EVENT_RAINA
					WHERE   [UID] = @USER_ID
					AND     COMPANY_SEQ = @COMPANY_SEQ
				END
			END

			COMMIT TRANSACTION;     
		END
	END TRY
	BEGIN CATCH
		BEGIN
			ROLLBACK TRANSACTION;  
		END
	END CATCH
END
GO
