IF OBJECT_ID (N'dbo.SP_HYUNDAI_DAILY', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_HYUNDAI_DAILY
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*----------------------------------------------------------------------------------------------  
1.Stored Procedure : SP_HYUNDAI_DAILY  
2.관련 Table  : s2_userinfo,HYUNDAI_DAILY_INFO  
3.내용    :현대 백화점 일일 회원가입 정보 보내는 데이터 생성  

-- exec [dbo].[SP_HYUNDAI_DAILY]
-----------------------------------------------------------------------------------------------*/  
CREATE PROCEDURE [dbo].[SP_HYUNDAI_DAILY]  
  
AS  
BEGIN  
  
 -- 1. 전일 현대백화점 신촌점 마케팅동의 일별회원 데이터 CI 값으로 중복제거 후 HYUNDAI_DAILY_INFO 인서트 
	INSERT INTO DBO.HYUNDAI_DAILY_INFO (UID, CONNINFO, UNAME, GENDER, BIRTH_DATE, HAND_PHONE, ZIPCODE, ADDRESS, ADDR_DETAIL,
										UMAIL, WEDDING_DAY, BARUN_REG_SITE, BARUN_REG_DATE, HYUNDAIMEMBERSHIP_REG_DATE, CREATE_DATE)
	SELECT	UID, CONNINFO, UNAME, GENDER, BIRTH_DATE = BIRTH, HAND_PHONE = HAND_PHONE1+HAND_PHONE2+HAND_PHONE3,
			ZIPCODE = ZIP1+ZIP2, ADDRESS, ADDR_DETAIL, UMAIL,
			WEDDING_DAY = REPLACE((SELECT TOP 1 WEDDING_DAY FROM VW_USER_INFO WHERE UID = M.UID),'-',''),
			BARUN_REG_SITE = REFERER_SALES_GUBUN,
			BARUN_REG_DATE = INTERGRATION_DATE,
			HYUNDAIMEMBERSHIP_REG_DATE = HYUNDAIMEMBERSHIP_REG_DATE,
			CREATE_DATE = GETDATE()
	FROM	S2_USERINFO M 
	WHERE 1 = 1
	AND SITE_DIV ='SB'
	AND (CONVERT(VARCHAR(10),HYUNDAIMEMBERSHIP_REG_DATE,120) >= CONVERT(VARCHAR(10),DATEADD(DAY,-1,GETDATE()),120)  
	AND CONVERT(VARCHAR(10),HYUNDAIMEMBERSHIP_REG_DATE,120) < CONVERT(VARCHAR(10),GETDATE(),120)  AND CHK_HYUNDAIMEMBERSHIP = 'Y' ) 
	AND M.HYUNDAIMEMBERSHIP_LEAVE_DATE IS NULL  
	AND NOT EXISTS (SELECT 'N' FROM HYUNDAI_DAILY_INFO WHERE CONNINFO = M.CONNINFO )  
	
END  

  
 -------------------------------------------------------------------------------------------------------    
  -- 마케팅 동의철회  
 -------------------------------------------------------------------------------------------------------    
  
    INSERT INTO HYUNDAI_DAILY_INFO_CANCEL (CANCEL_DT, UID, UNAME,HAND_PHONE, CREATE_DATE )   
	SELECT CONVERT(VARCHAR(10) , DELETE_DATE, 112) CANCLE_DT , DM.UID, DM.UNAME   
			,ISNULL((SELECT TOP 1 HPHONE FROM VW_USER_INFO WHERE UID = DM.UID  ),'000-0000-0000') HAND_PHONE  
			,GETDATE()  
	  FROM SAMSUNG_DELETE_MEMBER DM, HYUNDAI_DAILY_INFO MP  
	  WHERE DM.UID = MP.UID  
	  AND DM.DELETE_DATE >=  CONVERT(VARCHAR(10),GETDATE()-1,120)   AND DM.DELETE_DATE <  CONVERT(VARCHAR(10),GETDATE(),120)     
	  AND DM.DELETE_HYUNDAI ='Y'  
GO
