IF OBJECT_ID (N'dbo.SP_SELECT_VW_USER_INFO_FOR_AGE_AND_GENDER', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_VW_USER_INFO_FOR_AGE_AND_GENDER
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*

SELECT  BIRTHDATE, GENDER, *
FROM    S2_USERINFO
WHERE   UID = 's4guest'

SELECT  *
FROM    VW_USER_INFO
WHERE   UID = 's4guest'

EXEC SP_SELECT_VW_USER_INFO '', 'sharniel@nate.com', 5001

EXEC SP_SELECT_VW_USER_INFO_FOR_AGE_AND_SEX 's4guest', 'ysmguest', 'MC0GCCqGSIb3DQIJAyEAItjeCII7f+cjTKLkoaAz1mlAM+CsYxeUFAONtU2u8UM='

*/
CREATE PROCEDURE [dbo].[SP_SELECT_VW_USER_INFO_FOR_AGE_AND_GENDER]
    
    @UID AS VARCHAR(50)
,   @PWD AS VARCHAR(50)
,   @DUPINFO AS VARCHAR(100)


AS
BEGIN
    

SELECT  BIRTHDATE
    ,   DATEDIFF(YEAR, ISNULL(BIRTHDATE, GETDATE()), GETDATE()) AS AGE
    ,   ISNULL(A.GENDER, 0) AS GENDER

FROM    (
            SELECT  CAST(case when isnull(BIRTHDATE, '') = '' then birth else getdate() end AS DATETIME) AS BIRTHDATE, GENDER
            FROM    S2_USERINFO
            WHERE   UID = @UID
            AND     PWDCOMPARE(@PWD, CONVERT(VARBINARY(200), PWD, 1)) = 1
            AND     DUPINFO = @DUPINFO

            UNION ALL

            SELECT  CAST(case when isnull(BIRTHDATE, '') = '' then birth else getdate() end AS DATETIME) AS BIRTHDATE, GENDER
            FROM    S2_USERINFO_THECARD
            WHERE   UID = @UID
            AND     PWDCOMPARE(@PWD, CONVERT(VARBINARY(200), PWD, 1)) = 1
            AND     DUPINFO = @DUPINFO

            UNION ALL

            SELECT  CAST(case when isnull(BIRTHDATE, '') = '' then birth else getdate() end AS DATETIME) AS BIRTHDATE, GENDER
            FROM    S2_USERINFO_BHANDS
            WHERE   UID = @UID
            AND     PWDCOMPARE(@PWD, CONVERT(VARBINARY(200), PWD, 1)) = 1
            AND     DUPINFO = @DUPINFO
        ) A


END
GO
