IF OBJECT_ID (N'dbo.SP_INSERT_USER_SECESSION', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_INSERT_USER_SECESSION
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

SELECT * FROM S2_USERBYE_SECESSION_CAUSE

*/

CREATE PROCEDURE [dbo].[SP_INSERT_USER_SECESSION]

    @P_DUP_INFO					AS VARCHAR(100)
,   @P_SITE_DIV					AS VARCHAR(10)
,   @P_SECESSION_CAUSE_CODE		AS VARCHAR(100)
,   @P_ETC_COMMENT				AS VARCHAR(500)

AS

-----------------------------------------------------------------------------------------------------------------------
-- Declare Block
-----------------------------------------------------------------------------------------------------------------------
DECLARE @UID VARCHAR(50)

BEGIN

	SELECT @UID = [uid]
	  FROM S2_USERINFO
	 WHERE DupInfo = @P_DUP_INFO

	INSERT INTO S2_USERBYE_SECESSION_CAUSE
	(
				DUP_INFO
			,	UID
			,	SITE_DIV
			,	SECESSION_CAUSE_CODE
			,	ETC_COMMENT
	)

	SELECT	@P_DUP_INFO  
		,	ISNULL((SELECT TOP 1 UID FROM VW_USER_INFO WHERE DUPINFO = @P_DUP_INFO), '')
		,   CASE WHEN ISNULL(@P_SITE_DIV, 'SB') = '' THEN 'SB' ELSE @P_SITE_DIV END
		,   value				
		,   CASE WHEN value = '117007' THEN @P_ETC_COMMENT ELSE '' END
	FROM	ufn_SplitTableForRowNum(@P_SECESSION_CAUSE_CODE, '|')

	

	INSERT INTO S2_USERBYE (UID, REASON_1, REASON_2, REASON_3, REASON_4, REASON_5, REASON_6, REASON_7, REASON_TXT, COMPANY_SEQ, DUPINFO)
	SELECT	UID
		,	'N', 'N', 'N', 'N', 'N', 'N', 'N', ''
		,	CASE 
					WHEN SITE_DIV IN ('SA','B','C') THEN 5006
					WHEN SITE_DIV IN ('ST') THEN 5007
					WHEN SITE_DIV IN ('SB') THEN 5001
					WHEN SITE_DIV IN ('SS', 'H') THEN 5003
					WHEN SITE_DIV IN ('BE') THEN 5012
					ELSE 5006
			END
		,	DUPINFO
	FROM	VW_USER_INFO
	WHERE	DUPINFO = @P_DUP_INFO
	
--	DELETE FROM SAMSUNG_DAILY_INFO WHERE UID IN (SELECT UID FROM VW_USER_INFO WHERE DUPINFO = @P_DUP_INFO);
--	DELETE FROM SAMSUNG_DELETE_MEMBER WHERE UID IN (SELECT UID FROM VW_USER_INFO WHERE DUPINFO = @P_DUP_INFO);
--	DELETE FROM S2_USERINFO_THIRD_PARTY_MARKETING_AGREEMENT WHERE UID IN (SELECT UID FROM VW_USER_INFO WHERE DUPINFO = @P_DUP_INFO);
--	DELETE FROM S4_Event_Raina WHERE UID IN (SELECT UID FROM VW_USER_INFO WHERE DUPINFO = @P_DUP_INFO);
	
	DELETE FROM S2_USERINFO WHERE DupInfo = @P_DUP_INFO
	DELETE FROM S2_USERINFO_BHANDS WHERE DupInfo = @P_DUP_INFO
	DELETE FROM S2_USERINFO_THECARD WHERE DupInfo = @P_DUP_INFO
	DELETE FROM S2_USERINFO_JEHU WHERE UserId = @UID
					
END	

GO
