IF OBJECT_ID (N'dbo.spDownloadResultCheck', N'P') IS NOT NULL DROP PROCEDURE dbo.spDownloadResultCheck
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[spDownloadResultCheck] 
@BS_ID int
AS

IF (SELECT count(*) FROM BS_DOWNLOAD_RESULT WHERE BS_ID=@BS_ID)  = 0  
	INSERT INTO BS_DOWNLOAD_RESULT (BS_ID) VALUES (@BS_ID)
GO
