IF OBJECT_ID (N'dbo.SP_DELETE_MCARD_INVITATION', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_DELETE_MCARD_INVITATION
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

ukliio1

SELECT * FROM MCARD_INVITATION WHERE ORDERERNAME = '엄예지' AND INVITATIONCODE = 'SS2349145' AND INVITATIONID = 14147

SELECT * FROM MCARD_COMMENT WHERE INVITATIONID IN (SELECT INVITATIONID FROM MCARD_INVITATION WHERE ORDERERNAME = '엄예지')

http://celemoerp.bhandscard.com/Service/MCard/DeleteMCardInvitationHandler.ashx?INVITATION_ID=14147&INVITATION_CODE=SS2349145&USER_ID=ukliio1

*/

CREATE PROCEDURE [dbo].[SP_DELETE_MCARD_INVITATION]
	
	@P_INVITATION_ID AS INT
,	@P_INVITATION_CODE AS VARCHAR(10)
,	@P_USER_ID AS VARCHAR(50)
,	@P_ORIGINAL_SITE_ORDER_CODE AS VARCHAR(50)

AS
BEGIN

	SET NOCOUNT ON

	DECLARE @RESULT_SUCCESS AS VARCHAR(50)
	DECLARE @RESULT_MESSAGE AS VARCHAR(200)



	UPDATE	MCARD_INVITATION_FOR_OTHER_SITE
	SET		AVAILABLE_YORN = 'N'
	WHERE	1 = 1
	AND		INVITATIONCODE = @P_INVITATION_CODE	
	AND		ORIGINAL_SITE_ORDER_CODE = @P_ORIGINAL_SITE_ORDER_CODE



	IF EXISTS	(
					SELECT	*
					FROM	MCARD_INVITATION					
					WHERE	1 = 1
					AND		INVITATIONID = @P_INVITATION_ID
					AND		INVITATIONCODE = @P_INVITATION_CODE
					AND		AUTHCODE = @P_USER_ID
				)
	BEGIN

		UPDATE	MCARD_INVITATION 
		SET		DELETEYN = 'Y'
			,	EXPIREYN = 'Y'
		WHERE	1 = 1
		AND		INVITATIONID = @P_INVITATION_ID
		AND		INVITATIONCODE = @P_INVITATION_CODE
		AND		AUTHCODE = @P_USER_ID

		SET @RESULT_SUCCESS = 'Y'
		SET @RESULT_MESSAGE = '삭제 완료'

	END

	ELSE
	BEGIN
		
		SET @RESULT_SUCCESS = 'N'
		SET @RESULT_MESSAGE = '데이타가 없습니다'

	END



	SELECT	@RESULT_SUCCESS AS RESULT_SUCCESS
		,	@RESULT_MESSAGE AS RESULT_MESSAGE

END
GO
