IF OBJECT_ID (N'dbo.SP_SELECT_GREETING_FOR_MCARD_GREETING_LIST_OR_DETAIL', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_GREETING_FOR_MCARD_GREETING_LIST_OR_DETAIL
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*

EXEC SP_SELECT_GREETING_FOR_MCARD_GREETING_LIST_OR_DETAIL 1, 5

*/
CREATE PROCEDURE [dbo].[SP_SELECT_GREETING_FOR_MCARD_GREETING_LIST_OR_DETAIL]
    
	@P_CURRENT_PAGE				AS INT
,	@P_RECORD_PER_PAGE			AS INT
,	@P_GREETING_SEQ				AS INT = null

AS
BEGIN
    

    SET NOCOUNT ON;

	-- 인사말 카테고리 번호
	-- 임시로 30번 사용
	-- 추후에 변경 예정
	DECLARE @GREETING_CATEGORY_SEQ AS INT
	SET @GREETING_CATEGORY_SEQ = @P_GREETING_SEQ

	SELECT	CAST(ROW_NUM AS INT) AS ROW_NUM		--닷넷에서 int64/32 오류로 인해 캐스팅
		,	GREETING_SEQ
		,	GREETING_TITLE
		,	REPLACE(GREETING_CONTENT , '&nbsp;' , ' ') GREETING_CONTENT
		,	GREETING_CATEGORY_SEQ
		,	RECOMMEND_YORN
		,	ISNULL((SELECT COUNT(*) FROM GREETING WHERE ISNULL(DISPLAY_YES_OR_NO, '') = '1' AND GREETING_CATEGORY_SEQ = @GREETING_CATEGORY_SEQ), 0) AS TOTAL_RECORD_CNT
	FROM	(
				SELECT	ROW_NUMBER()OVER(ORDER BY GREETING_SEQ ASC) AS ROW_NUM
					,	GREETING_SEQ
					,	GREETING_NAME AS GREETING_TITLE
					,	GREETING_CONTENT
					,	GREETING_CATEGORY_SEQ
					,	CASE WHEN ISNULL(RECOMEND_YES_OR_NO, '') = '' OR ISNULL(RECOMEND_YES_OR_NO, '2') = 2 THEN 'N' ELSE 'Y' END AS RECOMMEND_YORN
				FROM	GREETING G
				WHERE	1 = 1
				AND		ISNULL(DISPLAY_YES_OR_NO, '') = '1'
				AND		GREETING_CATEGORY_SEQ = @GREETING_CATEGORY_SEQ
			) A
	WHERE	1 = 1
	AND		ROW_NUM >= (@P_CURRENT_PAGE - 1) * @P_RECORD_PER_PAGE + 1
	AND		ROW_NUM <= @P_CURRENT_PAGE * @P_RECORD_PER_PAGE



END
GO
