IF OBJECT_ID (N'dbo.SP_SELECT_COMMON_CODE', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_COMMON_CODE
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

EXEC SP_SELECT_COMMON_CODE '', '', '', '', 'N'

*/

CREATE PROCEDURE [dbo].[SP_SELECT_COMMON_CODE]
    @P_CMMN_CODE			AS VARCHAR(6) = ''
,   @P_CLSS_CODE			AS VARCHAR(3) = ''
,   @P_CLSS_NAME			AS VARCHAR(150) = ''
,   @P_DTL_NAME				AS VARCHAR(150) = ''
,   @P_USE_YORN				AS VARCHAR(1) = ''
,   @P_DISPLAY_YORN			AS VARCHAR(1) = ''
AS
BEGIN

    SELECT  ROW_NUMBER() OVER(ORDER BY SORT_NUM ASC, CMMN_CODE ASC) AS ROW_NUM
		,	CMMN_CODE
		,	LANG_CODE
		,	CLSS_CODE
		,	CLSS_NAME
		,	DTL_CLSS
		,	DTL_NAME
		,	DTL_DESC
		,	RMRK_CLMN
		,	USE_YORN
		,	DISPLAY_YORN
		,	SORT_NUM
		,	REG_DATE
		,	MDF_DATE
    FROM    COMMON_CODE
    WHERE   1 = 1
	AND		(CMMN_CODE = @P_CMMN_CODE OR '' = @P_CMMN_CODE)
	AND		(CLSS_CODE = @P_CLSS_CODE OR '' = @P_CLSS_CODE)
	AND		(CLSS_NAME = @P_CLSS_NAME OR '' = @P_CLSS_NAME)
	AND		(DTL_NAME = @P_DTL_NAME OR '' = @P_DTL_NAME)
	AND		(USE_YORN = @P_USE_YORN OR '' = @P_USE_YORN)
	AND		(DISPLAY_YORN = @P_DISPLAY_YORN OR '' = @P_DISPLAY_YORN)
	
    ORDER BY SORT_NUM ASC, CMMN_CODE ASC

END
GO
