IF OBJECT_ID (N'dbo.UP_SELECT_REVIEW_EVENT_SEARCH2', N'P') IS NOT NULL DROP PROCEDURE dbo.UP_SELECT_REVIEW_EVENT_SEARCH2
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*=============================================
-- AUTHOR:		<AUTHOR,,NAME>
-- CREATE DATE: <CREATE DATE,,>
-- DESCRIPTION:	<DESCRIPTION,,>

--[UP_SELECT_REVIEW_EVENT] 5006,1,15,0,'ER_REGDATE',''
--SELECT TOP 100 * FROM S4_EVENT_REVIEW ORDER BY ER_REGDATE
-- 바른손몰, 프페제휴 포함 
exec UP_SELECT_REVIEW_EVENT_SEARCH2 @company_seq='5000', @sort_desc='ER_Regdate', @ER_Type='0', @page=1, @pagesize=10, @search_cardcode='BH9232'

=================================================*/
CREATE PROCEDURE [dbo].[UP_SELECT_REVIEW_EVENT_SEARCH2]
 @COMPANY_SEQ INT,
 @PAGE INT=1,
 @PAGESIZE INT=15,
 @ER_TYPE INT=0,
 @SORT_DESC NVARCHAR(20),
 @SEARCH_CARDCODE VARCHAR(20)
AS

	SET NOCOUNT ON;
	
	DECLARE	@T_CNT	INT
	DECLARE	@SQL	NVARCHAR(4000)
	DECLARE	@SQL2	NVARCHAR(4000)
	
	IF @COMPANY_SEQ IS NULL OR @COMPANY_SEQ='' BEGIN
			SET @COMPANY_SEQ='1'
	END
	
	BEGIN

		SET @SQL2 = ' SELECT COUNT(ER_IDX) FROM S4_EVENT_REVIEW WITH(NOLOCK) WHERE ER_TYPE='+CONVERT(VARCHAR(2),@ER_TYPE)+' AND ER_Card_Code LIKE ''%'+ @SEARCH_CARDCODE + '%'' AND ER_VIEW=0 '
 
		EXEC (@SQL2)
		--PRINT(@SQL2)

		SET @SQL = 'SELECT TOP '+ CONVERT(VARCHAR(50),@PAGESIZE) +' ER_IDX, ER_COMPANY_SEQ, ER_ORDER_SEQ, ER_TYPE, ER_USERID, ER_REGDATE, ER_RECOM_CNT, '
		SET @SQL = @SQL + ' ISNULL(ER_REVIEW_TITLE, '''') AS ER_REVIEW_TITLE, ISNULL(ER_REVIEW_URL, '''') AS ER_REVIEW_URL , '
		SET @SQL = @SQL + ' ER_REVIEW_STAR, ER_STATUS, ER_VIEW, ER_REVIEW_CONTENT, ER_USERNAME, '
		SET @SQL = @SQL + ' ERA_STATUS, ERA_COUPON_STATUS, ISNULL(ERA_COMMENT,'''') AS ERA_COMMENT, ERA_COUPON_CODE, ISNULL(ERA_COMMENT_CANCEL,'''') AS ERA_COMMENT_CANCEL, '
		SET @SQL = @SQL + ' ISNULL(ER_REVIEW_URL_A, '''') AS ER_REVIEW_URL_A, ISNULL(ER_REVIEW_URL_B, '''') AS ER_REVIEW_URL_B, ISNULL(ER_REVIEW_URL2, '''') AS ER_REVIEW_URL2, '
		SET @SQL = @SQL + ' ER_COMMENT = ISNULL(ER_COMMENT,ER_REVIEW_URL), DEVICE_TYPE, ER_ISPHOTO, '
		SET @SQL = @SQL + ' ISNULL(A.ER_CARD_SEQ, 0) AS ER_CARD_SEQ, '
		SET @SQL = @SQL + ' ISNULL(A.ER_CARD_CODE, '''') AS ER_CARD_CODE, '
		SET @SQL = @SQL + ' ISNULL(C.CARD_IMAGE, '''') AS ER_CARDIMAGE, '
		SET @SQL = @SQL + ' CONCAT(ISNULL(A.ER_CARD_SEQ,''0''), ''^'' , ISNULL(A.ER_CARD_CODE, ''''), ''^'' , ISNULL(C.CARD_IMAGE,'''')) AS CARDCODE_CARDIMAGE, '
		SET @SQL = @SQL + '	FIRST_UPLOAD_PHOTO = ( '
		SET @SQL = @SQL + '							SELECT TOP 1 UPIMG_NAME '
		SET @SQL = @SQL + '							  FROM S4_EVENT_REVIEW_PHOTO WHERE SEQ =  A.ER_IDX ORDER BY 1 '
		SET @SQL = @SQL + '						  ) '
		SET @SQL = @SQL + '  FROM S4_EVENT_REVIEW                    AS A WITH(NOLOCK) '
		SET @SQL = @SQL + '  LEFT OUTER JOIN  S4_EVENT_REVIEW_STATUS AS B WITH(NOLOCK) ON (A.ER_IDX = B.ERA_ER_IDX) '
		SET @SQL = @SQL + '  LEFT OUTER JOIN  S2_CARD                AS C WITH(NOLOCK) ON (A.ER_CARD_SEQ = C.CARD_SEQ) '
		SET @SQL = @SQL + ' WHERE A.ER_TYPE= ' + CONVERT(VARCHAR(2),@ER_TYPE)
		SET @SQL = @SQL + '   AND A.ER_IDX NOT IN (SELECT TOP '+ CONVERT(VARCHAR(50), @PAGESIZE * (@PAGE - 1)) +' ER_IDX FROM S4_EVENT_REVIEW WITH(NOLOCK) WHERE ER_Card_Code LIKE ''%'+ @SEARCH_CARDCODE + '%'' AND ER_VIEW=0 ORDER BY '+@SORT_DESC+' DESC ) '
		SET @SQL = @SQL + '   AND A.ER_Card_Code LIKE ''%'+ @SEARCH_CARDCODE + '%'' AND ER_VIEW=0 ORDER BY '+@SORT_DESC+' DESC'

		EXEC (@SQL)
		--PRINT(@SQL)
	END
GO
