IF OBJECT_ID (N'dbo.sp_kt_daily_list', N'P') IS NOT NULL DROP PROCEDURE dbo.sp_kt_daily_list
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*----------------------------------------------------------------------------------------------
1.STORED PROCEDURE	: SP_KT_DAILY_LIST
2.관련 TABLE		: KT_DAILY_INFO

EXEC [DBO].[SP_KT_DAILY_LIST]  '20220331' '1'

 -- TYPE  1:동의 2:철회
-----------------------------------------------------------------------------------------------*/

CREATE PROCEDURE [dbo].[sp_kt_daily_list]
 @TODAY VARCHAR(15), 
 @TYPE  VARCHAR(1) 
AS

BEGIN

SET NOCOUNT ON
DECLARE @SQL NVARCHAR(2000)

	IF @TYPE = '1'

		BEGIN
			------ 기본정보리스트 ------
			SELECT BB.UNAME
				, (CASE WHEN GENDER = '0' THEN '여' ELSE '남' END ) GENDER
				, BIRTH_DATE	
				, BB.HAND_PHONE, WEDDING_DAY	
				, BB.ZIPCODE + ' ' + BB.ADDRESS + ' ' + BB.ADDR_DETAIL AS ADDRESS_INFO 	
				, CONVERT(VARCHAR(10),BB.BARUN_REG_DATE,112) AS BARUN_REG_DATE
				, CONVERT(VARCHAR(10),BB.KTMEMBERSHIP_REG_DATE,112) AS KTMEMBERSHIP_REG_DATE
				,BB.UMAIL	
			FROM KT_DAILY_INFO BB
			WHERE CONVERT(VARCHAR(10),CREATE_DATE,112)=	@TODAY		
		END	
	ELSE
		BEGIN
			
			SELECT	A.CANCEL_DT, A.HAND_PHONE, A.UNAME, 
					BARUN_REG_DATE = CONVERT(VARCHAR(10),B.BARUN_REG_DATE,112), 
					KTMEMBERSHIP_REG_DATE = CONVERT(VARCHAR(10),B.KTMEMBERSHIP_REG_DATE ,112)
			FROM	KT_DAILY_INFO_CANCEL A INNER JOIN 
					KT_DAILY_INFO B ON A.UID = B.UID 
			WHERE CONVERT(VARCHAR(10),A.CREATE_DATE,112) = @TODAY	

			--SELECT CANCEL_DT, HAND_PHONE, UNAME 
			--FROM KT_DAILY_INFO_CANCEL
			--WHERE CONVERT(VARCHAR(10),CREATE_DATE,112)=	@TODAY	

		END

END

GO
