IF OBJECT_ID (N'dbo.SP_S_WEDDINGMAGAZINE_LIST_TEST', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_S_WEDDINGMAGAZINE_LIST_TEST
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_S_WEDDINGMAGAZINE_LIST_TEST]
/***************************************************************
작성자	:	표수현
작성일	:	2023-02-02
DESCRIPTION	:	웨딩매거진 EXEC SP_S_WEDDINGMAGAZINE_LIST @PAGE_NO=1
SPECIAL LOGIC	: SP_S_WEDDINGMAGAZINE_LIST_TEST 1
******************************************************************
MODIFICATION
******************************************************************
수정일           작업자                DESCRIPTION
==================================================================
******************************************************************/
 @PAGE_NO INT = 1,
 @PAGE_SIZE INT = 10

 AS
	
	 SET NOCOUNT ON  
	-- 1. 메인배너 
	SELECT TOP 3 SEQ, KIND, IMG_URL, LINK_URL, VIEW_YN, TITLE,
				 CONTENTS, VIEW_CNT, REG_DATE, SORTINGNUM, CATEGORY
	FROM WEDDINGMAGAZINE
	WHERE	VIEW_YN = 'Y' AND
			CATEGORY = '1'
	ORDER BY SORTINGNUM ASC

	if OBJECT_ID('#TB_TEMP') IS NOT NULL
	 DROP TABLE #TB_TEMP

	-- 2. 리스트배너
	create TABLE #TB_TEMP (SEQ INT IDENTITY(1,1), NUM INT, KIND VARCHAR(20), IMG_URL VARCHAR(200),
							TITLE VARCHAR(200), CSSCLASS VARCHAR(10))

	INSERT INTO #TB_TEMP(NUM, KIND, IMG_URL, TITLE, CSSCLASS)
	SELECT	TOP 6 SEQ, KIND, IMG_URL, TITLE, 
			 CSSCLASS = (CASE  KIND
									WHEN 'MAGAZINE' THEN 'TYPE02'
									ELSE 'TYPE01'
								  END )
	FROM	CARD_NEWS
	WHERE	VIEW_YN = 'Y'
	ORDER BY SORTINGNUM ASC
	
	INSERT INTO #TB_TEMP(NUM, KIND, IMG_URL, TITLE, CSSCLASS)
	SELECT	TOP 6  SEQ, KIND, IMG_URL, TITLE, 
			 CSSCLASS = 'TYPE03'
	FROM	WEDDINGMAGAZINE
	WHERE	VIEW_YN = 'Y' AND
			CATEGORY = '2'
	ORDER BY SORTINGNUM ASC


	--SELECT SEQ ,
	--		NUM,
	--		KIND,
	--		IMG_URL,
	--		TITLE,
	--		CSSCLASS
	--FROM #TB_TEMP

	SELECT * 
	FROM #TB_TEMP
	ORDER BY SEQ ASC
	--OFFSET (@PAGE_NO-1) * @PAGE_SIZE ROW
	--FETCH NEXT @PAGE_SIZE ROW ONLY
	--FETCH NEXT @PAGE_SIZE + 1 ROW ONLY

	DECLARE @TOTAL_COUNT INT
	DECLARE @TOTAL_PAGE INT

	SELECT @TOTAL_COUNT = COUNT(*)
	FROM	#TB_TEMP 

	SET @TOTAL_PAGE = CEILING(CONVERT(FLOAT,@TOTAL_COUNT) / @PAGE_SIZE)
	
	SELECT TOTAL_PAGE = @TOTAL_PAGE



	 SET NOCOUNT OFF
GO
