IF OBJECT_ID (N'dbo.SP_SELECT_FOOD_TICKET_LIST', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_FOOD_TICKET_LIST
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*

EXEC SP_SELECT_FOOD_TICKET_LIST 'C06|C11', '05', 0

SELECT * FROM S2_CARD WHERE CARD_CODE LIKE '%FS%'

SELECT * FROM S2_CARDSALESSITE WHERE CARD_SEQ IN (SELECT CARD_SEQ FROM S2_CARD WHERE CARD_CODE LIKE '%FS%')

*/
CREATE PROCEDURE [dbo].[SP_SELECT_FOOD_TICKET_LIST]
	@CARD_DIV AS VARCHAR(100)
,	@CARD_CODE_OR_CARD_NAME AS VARCHAR(500)
,	@COMPANY_SEQ AS INT
AS
BEGIN
	
	DECLARE @CARD_DIV_MST TABLE
    (
		CARD_DIV VARCHAR(10)
	)	

	INSERT INTO @CARD_DIV_MST (CARD_DIV)
    SELECT	VALUE 
	FROM	[dbo].[FN_SPLIT] (@CARD_DIV, '|')

    SELECT	
			ROW_NUMBER()OVER(ORDER BY SC.CARD_CODE ASC) AS ROW_NUM
		,	SC.CARD_SEQ
		,	SC.CARD_CODE
		,	SC.CARD_NAME
		,	SC.CARD_IMAGE
		,	CASE WHEN BARUNSONCARD_CARD_SEQ IS NULL THEN 'N' ELSE 'Y' END BARUNSONCARD_YORN
		,	CASE WHEN BHANDSCARD_CARD_SEQ IS NULL THEN 'N' ELSE 'Y' END BHANDSCARD_YORN

	FROM	S2_CARD SC

	LEFT JOIN	(
					SELECT	DISTINCT CARD_SEQ AS BARUNSONCARD_CARD_SEQ
					FROM	S2_CARDSALESSITE
					WHERE	1 = 1
					AND		COMPANY_SEQ = 5001
					AND		ISJUMUN = 1
				) CARD_BARUNSONCARD 
				ON SC.CARD_SEQ = CARD_BARUNSONCARD.BARUNSONCARD_CARD_SEQ

	LEFT JOIN	(
					SELECT	DISTINCT CARD_SEQ AS BHANDSCARD_CARD_SEQ
					FROM	S2_CARDSALESSITE
					WHERE	1 = 1
					AND		COMPANY_SEQ = 5006
					AND		ISJUMUN = 1
				) CARD_BHANDSCARD
				ON SC.CARD_SEQ = CARD_BHANDSCARD.BHANDSCARD_CARD_SEQ

	WHERE	1 = 1
	AND		SC.CARD_DIV IN (SELECT CARD_DIV FROM @CARD_DIV_MST)

	AND		CASE 
					WHEN @COMPANY_SEQ = 5001 THEN BARUNSONCARD_CARD_SEQ 
					WHEN @COMPANY_SEQ = 5006 THEN BHANDSCARD_CARD_SEQ 
					ELSE 0
			END >= @COMPANY_SEQ

	AND		(
					SC.CARD_CODE LIKE '%' + @CARD_CODE_OR_CARD_NAME + '%'
				OR	SC.CARD_NAME LIKE '%' + @CARD_CODE_OR_CARD_NAME + '%'
			)

END
GO
