IF OBJECT_ID (N'dbo.SP_INSERT_S2_USER_DEVICE_TOKEN', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_INSERT_S2_USER_DEVICE_TOKEN
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
S2_USER_TOKEN
*/

CREATE PROCEDURE [dbo].[SP_INSERT_S2_USER_DEVICE_TOKEN]
    @UID							AS VARCHAR(50)
,   @DUPINFO						AS VARCHAR(100)
,   @COMPANY_SEQ					AS INT
,   @SALES_GUBUN					AS VARCHAR(10)
,   @TOKEN							AS VARCHAR(300)
,   @MOBILE_DEVICE_OS_TYPE_CODE		AS VARCHAR(6)
,	@DEVICE_TYPE_NAME				AS VARCHAR(50)
,	@HTTP_USER_AGENT				AS VARCHAR(200)
	

AS
BEGIN
	
	-- IOS 디바이스 토큰은 기기당 1개로 고정되어 있기 떄문에,
	-- 다른 아이디로 로그인 했을 경우,
	-- 기존 아이디의 디바이스 토큰 값을 공백 처리 한다
	IF @MOBILE_DEVICE_OS_TYPE_CODE = '121002' AND @TOKEN <> ''
	BEGIN
		
		UPDATE	S2_USER_DEVICE_TOKEN
		SET		TOKEN = ''
		WHERE	1 = 1
		AND		MOBILE_DEVICE_OS_TYPE_CODE = @MOBILE_DEVICE_OS_TYPE_CODE
		AND		TOKEN = @TOKEN
		AND		UID <> @UID

	END



	IF EXISTS (SELECT * FROM VW_USER_INFO WHERE UID = @UID AND DUPINFO = @DUPINFO)
	BEGIN
		
		IF REPLACE(@TOKEN, ' ', '') <> '' 
		BEGIN

			IF NOT EXISTS (SELECT * FROM S2_USER_DEVICE_TOKEN WHERE UID = @UID AND TOKEN = @TOKEN)
			BEGIN
			
				INSERT INTO S2_USER_DEVICE_TOKEN (
						UID
					,	COMPANY_SEQ
					,	SALES_GUBUN
					,	TOKEN
					,	MOBILE_DEVICE_OS_TYPE_CODE
					,	DEVICE_TYPE_NAME
					,	HTTP_USER_AGENT
				)
				SELECT	@UID
					,	@COMPANY_SEQ
					,	@SALES_GUBUN
					,	@TOKEN
					,	@MOBILE_DEVICE_OS_TYPE_CODE
					,	@DEVICE_TYPE_NAME
					,	@HTTP_USER_AGENT

			END

		END

	END

END
GO
