IF OBJECT_ID (N'dbo.SP_UPDATE_OUTSOURCING_CUSTOM_ETC_ORDER_FOR_RECEIPT', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_UPDATE_OUTSOURCING_CUSTOM_ETC_ORDER_FOR_RECEIPT
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

SELECT * FROM OUTSOURCING_ORDER_MST

*/

CREATE PROC [dbo].[SP_UPDATE_OUTSOURCING_CUSTOM_ETC_ORDER_FOR_RECEIPT]  
    @P_OUTSOURCING_ORDER_SEQS AS VARCHAR(4000)

AS  

BEGIN
    
    DECLARE @T_OUTSOURCING_ORDER_SEQ TABLE
    (
	    OUTSOURCING_ORDER_SEQ int NOT NULL
    )

    INSERT INTO @T_OUTSOURCING_ORDER_SEQ (OUTSOURCING_ORDER_SEQ)
    SELECT * FROM dbo.[ufn_SplitTable](@P_OUTSOURCING_ORDER_SEQS, '|')
	


    /* 접수처리 */
    UPDATE  CUSTOM_ETC_ORDER
    SET     PREPARE_DATE = GETDATE()
        ,   STATUS_SEQ = '10'
    WHERE   ORDER_SEQ IN ( SELECT OUTSOURCING_ORDER_SEQ FROM @T_OUTSOURCING_ORDER_SEQ )



END

GO
