IF OBJECT_ID (N'dbo.SP_AUTO_SELECT_INSERT', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_AUTO_SELECT_INSERT
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

SELECT * FROM S2_CARD_FREE_GIFT
SELECT * FROM S2_CARD_FREE_GIFT_LOG

SELECT  *
FROM    CUSTOM_ORDER_ITEM 
WHERE   ORDER_SEQ = 2180316

DELETE CUSTOM_ORDER_ITEM WHERE ORDER_SEQ = 2180316 AND CARD_SEQ = 35488

EXEC SP_INSERT_FREE_GIFT_TEST 2180316
EXEC SP_INSERT_FREE_GIFT 2180316

*/

CREATE PROCEDURE [dbo].[SP_AUTO_SELECT_INSERT]
AS
BEGIN

/*
DECLARE @ORDER_SEQ AS INT = 0
DECLARE @MAX_CNT AS INT = 0
DECLARE @i AS INT = 1
*/
/*
EXEC SP_AUTO_SELECT_INSERT
*/
/* 
	비핸즈카드 이벤트 - 2015-12-23 00:00:00 ~ 2015-12-23 23:59:59 주문건에 대해서
	travel_packing 지급
*/
INSERT INTO CUSTOM_ORDER_ITEM (ORDER_SEQ, CARD_SEQ, ITEM_TYPE, ITEM_COUNT, ITEM_PRICE, ITEM_SALE_PRICE, DISCOUNT_RATE)

SELECT	CO.ORDER_SEQ
	,	35081
	,	'Z'
	,	1
	,	0
	,	0
	,	0
FROM	CUSTOM_ORDER CO
LEFT JOIN	(
				SELECT	ORDER_SEQ
				FROM	CUSTOM_ORDER_ITEM
				WHERE	1 = 1
				AND		REG_DATE >= '2015-12-23 00:00:00'
				AND		CARD_SEQ = 35081
				GROUP BY ORDER_SEQ
		) COI ON CO.ORDER_SEQ = COI.ORDER_SEQ
WHERE	1 = 1
AND		CO.ORDER_DATE >= '2015-12-23 00:00:00'
AND     CO.ORDER_DATE < '2015-12-24 00:00:00'
AND     CO.SALES_GUBUN = 'SA'
AND     CO.COMPANY_SEQ = '5006' 
AND     CO.STATUS_SEQ IN (1, 6, 7, 8, 9, 10)
AND     CO.ORDER_TYPE IN (1, 6, 7)
AND		COI.ORDER_SEQ IS NULL
AND		CO.LAST_TOTAL_PRICE >= 100000



/* 
	비핸즈카드 이벤트 - 2015-12-23 00:00:00 ~ 2015-12-23 23:59:59 주문건에 대해서
	flower_painting 지급
*/
INSERT INTO CUSTOM_ORDER_ITEM (ORDER_SEQ, CARD_SEQ, ITEM_TYPE, ITEM_COUNT, ITEM_PRICE, ITEM_SALE_PRICE, DISCOUNT_RATE)

SELECT	CO.ORDER_SEQ
	,	35370
	,	'H'
	,	1
	,	0
	,	0
	,	0
FROM	CUSTOM_ORDER CO
LEFT JOIN	(
				SELECT	ORDER_SEQ
				FROM	CUSTOM_ORDER_ITEM
				WHERE	1 = 1
				AND		REG_DATE >= '2015-12-23 00:00:00'
				AND		CARD_SEQ = 35370
				GROUP BY ORDER_SEQ
		) COI ON CO.ORDER_SEQ = COI.ORDER_SEQ
WHERE	1 = 1
AND		CO.ORDER_DATE >= '2015-12-23 00:00:00'
AND     CO.ORDER_DATE < '2015-12-24 00:00:00'
AND     CO.SALES_GUBUN = 'SA'
AND     CO.COMPANY_SEQ = '5006' 
AND     CO.STATUS_SEQ IN (1, 6, 7, 8, 9, 10)
AND     CO.ORDER_TYPE IN (1, 6, 7)
AND		COI.ORDER_SEQ IS NULL
AND		CO.LAST_TOTAL_PRICE >= 100000






/*








SELECT  @MAX_CNT = ISNULL(COUNT(*), 0)

FROM    CUSTOM_ORDER CO 

WHERE   CO.ORDER_DATE >= '2015-12-23 00:00:00'
AND     CO.ORDER_DATE < '2015-12-24 00:00:00'
AND     CO.sales_Gubun = 'SA'
AND     CO.company_seq = '5006' 
AND     CO.STATUS_SEQ = 1
AND     CO.order_type IN (1,6,7)

WHILE @i <= @MAX_CNT
BEGIN

    SELECT  @ORDER_SEQ              = A.ORDER_SEQ
        
    FROM    (
                SELECT  ROW_NUMBER() OVER(ORDER BY ORDER_DATE ASC) AS ROWNUM
                    ,   CO.order_seq AS ORDER_SEQ 
                    ,   ISNULL(CO.last_total_price, 0) AS LAST_TOAL_PRICE 
                    ,   ISNULL(CO.last_total_price, 0) AS LAST_TOAL_PRICE 

                FROM    CUSTOM_ORDER CO 
                WHERE   1 = 1
				AND     CO.ORDER_DATE <= '2015-12-23'
				AND     CO.ORDER_DATE < '2015-12-24'
				AND     CO.sales_Gubun = 'SA'
				AND     CO.company_seq = '5006' 
				AND     CO.STATUS_SEQ = 1
				AND     CO.order_type IN (1,6,7)
            ) A
    WHERE   A.ROWNUM = @i

        
        
    IF NOT EXISTS(SELECT * FROM CUSTOM_ORDER_ITEM WHERE ORDER_SEQ = @ORDER_SEQ AND CARD_SEQ = '35370')
    BEGIN
                
            INSERT INTO CUSTOM_ORDER_ITEM (ORDER_SEQ, CARD_SEQ, ITEM_TYPE, ITEM_COUNT, ITEM_PRICE, ITEM_SALE_PRICE, DISCOUNT_RATE, MEMO1, ADDNUM_PRICE)
		    VALUES (@ORDER_SEQ, '35370', 'H', 1, 0, 0, 0, '', 0)

    END


    IF NOT EXISTS(SELECT * FROM CUSTOM_ORDER_ITEM WHERE ORDER_SEQ = @ORDER_SEQ AND CARD_SEQ = '35081')
    BEGIN
                
            INSERT INTO CUSTOM_ORDER_ITEM (ORDER_SEQ, CARD_SEQ, ITEM_TYPE, ITEM_COUNT, ITEM_PRICE, ITEM_SALE_PRICE, DISCOUNT_RATE, MEMO1, ADDNUM_PRICE)
		    VALUES (@ORDER_SEQ, '35081', 'Z', 1, 0, 0, 0, '', 0)

    END



    SET @i = @i + 1

END
*/


END

GO
