IF OBJECT_ID (N'dbo.SP_SELECT_S2_CARD_ETC', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_S2_CARD_ETC
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
SP_HELPTEXT SP_SELECT_S2_CARD_ETC
EXEC SP_SELECT_S2_CARD_WITH_ERP_STOCK 0, 99999, 0, '', '', '정상판매|단종예정', '', '5001|5006|5007|5003|5008', '', 'N', 9999, 1, 'INVENTORY_AVAILABLE_QTY', 'DESC'

*/
CREATE PROCEDURE [dbo].[SP_SELECT_S2_CARD_ETC]
		@P_CARD_SET_PRICE_MIN AS INT
	,	@P_CARD_SET_PRICE_MAX AS INT
	,	@P_CARD_KIND_SEQ AS INT
	,	@P_CARD_BRAND AS VARCHAR(50)
	,	@P_CARD_CODE_OR_CARD_NAME AS VARCHAR(50)
	,	@P_PRODUCTION_STATUS_NAME AS VARCHAR(200)
	,	@P_SAMPLE_ORDER_AVAILABLE_YORN AS VARCHAR(1)
	,	@P_SITE_SEARCH_VALUE AS VARCHAR(100)
	,	@P_SALES_TYPE AS VARCHAR(10)
	,	@P_MIN_STOCK_UNDER_YORN AS VARCHAR(10)
	,	@P_PAGE_SIZE AS INT
	,	@P_PAGE_NUMBER AS INT
	,	@P_ORDER_BY_NAME AS VARCHAR(50)
	,	@P_ORDER_BY_TYPE AS VARCHAR(10)
AS
BEGIN

	SET NOCOUNT ON

	DECLARE @T_PRODUCTION_STATUS_NAME TABLE ( PRODUCTION_STATUS_NAME VARCHAR(20) )
	DECLARE @T_SITE_SEARCH_VALUE TABLE ( COMPANY_SEQ INT )

	DECLARE @T_PRODUCTION_STATUS_NAME_COUNT AS INT
	DECLARE @T_SITE_SEARCH_VALUE_COUNT AS INT



	INSERT INTO @T_PRODUCTION_STATUS_NAME (PRODUCTION_STATUS_NAME)
	SELECT CAST(VALUE AS VARCHAR(20)) FROM dbo.[ufn_SplitTable] (@P_PRODUCTION_STATUS_NAME, '|')

	INSERT INTO @T_SITE_SEARCH_VALUE (COMPANY_SEQ)
	SELECT CAST(VALUE AS INT) FROM dbo.[ufn_SplitTable] (@P_SITE_SEARCH_VALUE, '|')

	-- 공백을 '' 으로 치환
	UPDATE	@T_PRODUCTION_STATUS_NAME
	SET		PRODUCTION_STATUS_NAME = ''
	WHERE	PRODUCTION_STATUS_NAME = '공백'


	SET @T_PRODUCTION_STATUS_NAME_COUNT = ISNULL((SELECT COUNT(*) FROM @T_PRODUCTION_STATUS_NAME), 0)
	SET @T_PRODUCTION_STATUS_NAME_COUNT = CASE WHEN @T_PRODUCTION_STATUS_NAME_COUNT = 0 THEN 10 ELSE @T_PRODUCTION_STATUS_NAME_COUNT END
	SET @T_SITE_SEARCH_VALUE_COUNT = ISNULL((SELECT COUNT(*) FROM @T_SITE_SEARCH_VALUE), 0)
	SET @T_SITE_SEARCH_VALUE_COUNT = CASE WHEN @T_SITE_SEARCH_VALUE_COUNT = 0 THEN 10 ELSE @T_SITE_SEARCH_VALUE_COUNT END



	SELECT	*
	FROM	(
				SELECT	ROW_NUMBER() OVER	(
												ORDER BY 
													CASE WHEN @P_ORDER_BY_NAME = 'REG_DATE'					THEN C.REG_DATE						ELSE 0 END ASC
												,	CASE WHEN @P_ORDER_BY_NAME = 'DISPLAY_BARUNSONCARD'		THEN C.DISPLAY_BARUNSONCARD			ELSE 0 END ASC
												,	CASE WHEN @P_ORDER_BY_NAME = 'DISPLAY_BHANDSCARD'		THEN C.DISPLAY_BHANDSCARD			ELSE 0 END ASC
												,	CASE WHEN @P_ORDER_BY_NAME = 'DISPLAY_THECARD'			THEN C.DISPLAY_THECARD				ELSE 0 END ASC
												,	CASE WHEN @P_ORDER_BY_NAME = 'DISPLAY_PREMIERPAPER'		THEN C.DISPLAY_PREMIERPAPER			ELSE 0 END ASC
												,	CASE WHEN @P_ORDER_BY_NAME = 'DISPLAY_OUTBOUND'			THEN C.DISPLAY_OUTBOUND				ELSE 0 END ASC
												,	CASE WHEN @P_ORDER_BY_NAME = 'DISPLAY_BARUNSONMALL'	    THEN C.DISPLAY_BARUNSONMALL			ELSE 0 END ASC
												,	C.CARD_SEQ ASC
													
											) AS ROW_NUM
					,	ROW_NUMBER() OVER	(
												ORDER BY 
													CASE WHEN @P_ORDER_BY_NAME = 'REG_DATE'					THEN C.REG_DATE						ELSE 0 END DESC
												,	CASE WHEN @P_ORDER_BY_NAME = 'DISPLAY_BARUNSONCARD'		THEN C.DISPLAY_BARUNSONCARD			ELSE 0 END DESC
												,	CASE WHEN @P_ORDER_BY_NAME = 'DISPLAY_BHANDSCARD'		THEN C.DISPLAY_BHANDSCARD			ELSE 0 END DESC
												,	CASE WHEN @P_ORDER_BY_NAME = 'DISPLAY_THECARD'			THEN C.DISPLAY_THECARD				ELSE 0 END DESC
												,	CASE WHEN @P_ORDER_BY_NAME = 'DISPLAY_PREMIERPAPER'		THEN C.DISPLAY_PREMIERPAPER			ELSE 0 END DESC
												,	CASE WHEN @P_ORDER_BY_NAME = 'DISPLAY_OUTBOUND'			THEN C.DISPLAY_OUTBOUND				ELSE 0 END DESC
												,	CASE WHEN @P_ORDER_BY_NAME = 'DISPLAY_BARUNSONMALL'	    THEN C.DISPLAY_BARUNSONMALL			ELSE 0 END DESC
												,	C.CARD_SEQ DESC
													
											) AS ROW_NUM_DESC
					,	*
				FROM	(
							SELECT	DISTINCT 
									SC.CARD_SEQ
								,	SC.CARD_CODE	
								,	SC.CARD_ERPCODE AS ERP_CODE
								,	SC.CARD_NAME
								,	SC.CARDSET_PRICE AS CARD_SET_PRICE
								,	SC.CARD_PRICE
								,	CASE WHEN ISNULL(SCO.ISSAMPLE, '') = '1' THEN 'Y' ELSE 'N' END AS SAMPLE_ORDER_YORN
								,	CASE WHEN ISNULL(SC.CARD_IMAGE, '') = '' THEN '' ELSE 'HTTP://FILE.BARUNSONCARD.COM/COMMON_IMG/' + SC.CARD_IMAGE END AS CARD_IMAGE_FULL_URL
		
								,	CASE	
											WHEN UPPER(SC.CARDBRAND) = 'A'	THEN '티아라카드'
											WHEN UPPER(SC.CARDBRAND) = 'B'	THEN '바른손카드'
											WHEN UPPER(SC.CARDBRAND) = 'G'	THEN '가랑카드'
											WHEN UPPER(SC.CARDBRAND) = 'H'	THEN '해피카드'
											WHEN UPPER(SC.CARDBRAND) = 'P'	THEN 'W페이퍼'
											WHEN UPPER(SC.CARDBRAND) = 'S'	THEN '프리미어페이퍼'
											WHEN UPPER(SC.CARDBRAND) = 'T'	THEN '티로즈'
											WHEN UPPER(SC.CARDBRAND) = 'W'	THEN '위시메이드'
											WHEN UPPER(SC.CARDBRAND) = 'Y'	THEN '예카드'
											WHEN UPPER(SC.CARDBRAND) = 'N'	THEN '비핸즈카드'
											WHEN UPPER(SC.CARDBRAND) = 'C'	THEN '더카드'
																			ELSE '기타' 
									END AS BRAND_NAME

								,	ISNULL((1 + SCSS_BARUNSONCARD.ISDISPLAY		)				, 0 ) AS DISPLAY_BARUNSONCARD
								,	ISNULL((1 + SCSS_BHANDSCARD.ISDISPLAY		)				, 0 ) AS DISPLAY_BHANDSCARD
								,	ISNULL((1 + SCSS_THECARD.ISDISPLAY			)				, 0 ) AS DISPLAY_THECARD 
								,	ISNULL((1 + SCSS_PREMIERPAPER.ISDISPLAY		)				, 0 ) AS DISPLAY_PREMIERPAPER
								,	ISNULL((1 + SCSS_OUTBOUND.ISDISPLAY			)				, 0 ) AS DISPLAY_OUTBOUND
								,	ISNULL((1 + SCSS_BARUNSONMALL.ISDISPLAY		)				, 0 ) AS DISPLAY_BARUNSONMALL
								,	SC.REGDATE AS REG_DATE

							FROM	S2_CARD SC
							JOIN	S2_CARDKIND SCK ON SC.CARD_SEQ = SCK.CARD_SEQ

							LEFT JOIN	S2_CARDOPTION SCO ON SC.CARD_SEQ = SCO.CARD_SEQ
							LEFT JOIN	S2_CardDetailEtc S2CD ON SC.CARD_SEQ = S2CD.CARD_SEQ
							LEFT JOIN	S2_CARDSALESSITE SCSS_BARUNSONCARD	ON SC.CARD_SEQ = SCSS_BARUNSONCARD.CARD_SEQ		AND SCSS_BARUNSONCARD.COMPANY_SEQ	= 5001
							LEFT JOIN	S2_CARDSALESSITE SCSS_PREMIERPAPER	ON SC.CARD_SEQ = SCSS_PREMIERPAPER.CARD_SEQ		AND SCSS_PREMIERPAPER.COMPANY_SEQ	= 5003
							LEFT JOIN	S2_CARDSALESSITE SCSS_BHANDSCARD	ON SC.CARD_SEQ = SCSS_BHANDSCARD.CARD_SEQ		AND SCSS_BHANDSCARD.COMPANY_SEQ		= 5006
							LEFT JOIN	S2_CARDSALESSITE SCSS_THECARD		ON SC.CARD_SEQ = SCSS_THECARD.CARD_SEQ			AND SCSS_THECARD.COMPANY_SEQ		= 5007
							LEFT JOIN	S2_CARDSALESSITE SCSS_OUTBOUND		ON SC.CARD_SEQ = SCSS_OUTBOUND.CARD_SEQ			AND SCSS_OUTBOUND.COMPANY_SEQ		= 5008
							LEFT JOIN	S2_CARDSALESSITE SCSS_BARUNSONMALL  ON SC.CARD_SEQ = SCSS_BARUNSONMALL.CARD_SEQ		AND SCSS_BARUNSONMALL.COMPANY_SEQ	= 5000

							WHERE	1 = 1
							AND		SC.CARD_DIV IN ( 'C08')
							
							--AND		SC.CARDSET_PRICE >= @P_CARD_SET_PRICE_MIN
							--AND		SC.CARDSET_PRICE < @P_CARD_SET_PRICE_MAX

							AND		CASE WHEN @P_CARD_KIND_SEQ = 0 THEN 0 ELSE SCK.CARDKIND_SEQ END = @P_CARD_KIND_SEQ
							AND		CASE WHEN @P_CARD_BRAND = '' THEN '' ELSE SC.CARDBRAND END = @P_CARD_BRAND

							AND		(
											CASE WHEN @P_CARD_CODE_OR_CARD_NAME = '' THEN '' ELSE SC.CARD_CODE END LIKE '%' + @P_CARD_CODE_OR_CARD_NAME + '%'
										OR	CASE WHEN @P_CARD_CODE_OR_CARD_NAME = '' THEN '' ELSE SC.CARD_NAME END LIKE '%' + @P_CARD_CODE_OR_CARD_NAME + '%'
									)

							AND		CASE	WHEN @P_SAMPLE_ORDER_AVAILABLE_YORN = '' THEN '' 
											ELSE CASE WHEN ISNULL(SCO.ISSAMPLE, '') = '1' THEN '1' ELSE '' END
									END 
									= 
									CASE WHEN @P_SAMPLE_ORDER_AVAILABLE_YORN = 'Y' THEN '1' ELSE '' END

							--AND		SCES.PRODUCTION_STATUS_NAME IN (SELECT PRODUCTION_STATUS_NAME FROM @T_PRODUCTION_STATUS_NAME)

							AND		(
										(
												@T_SITE_SEARCH_VALUE_COUNT < 6
											AND	(
														(SCSS_BARUNSONCARD.COMPANY_SEQ IN (SELECT COMPANY_SEQ FROM @T_SITE_SEARCH_VALUE)	AND CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_BARUNSONCARD.ISJUMUN END = @P_SALES_TYPE)
													OR	(SCSS_PREMIERPAPER.COMPANY_SEQ IN (SELECT COMPANY_SEQ FROM @T_SITE_SEARCH_VALUE)	AND CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_PREMIERPAPER.ISJUMUN END = @P_SALES_TYPE)
													OR	(SCSS_BHANDSCARD.COMPANY_SEQ IN (SELECT COMPANY_SEQ FROM @T_SITE_SEARCH_VALUE)		AND CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_BHANDSCARD.ISJUMUN END = @P_SALES_TYPE)
													OR	(SCSS_THECARD.COMPANY_SEQ IN (SELECT COMPANY_SEQ FROM @T_SITE_SEARCH_VALUE)			AND CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_THECARD.ISJUMUN END = @P_SALES_TYPE)
													OR	(SCSS_OUTBOUND.COMPANY_SEQ IN (SELECT COMPANY_SEQ FROM @T_SITE_SEARCH_VALUE)		AND CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_OUTBOUND.ISJUMUN END = @P_SALES_TYPE)
													OR	(SCSS_BARUNSONMALL.COMPANY_SEQ IN (SELECT COMPANY_SEQ FROM @T_SITE_SEARCH_VALUE)	AND CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_BARUNSONMALL.ISJUMUN END = @P_SALES_TYPE)
												)
										)
										OR
										(
												@T_SITE_SEARCH_VALUE_COUNT >= 6
											AND (
														CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_BARUNSONCARD.ISJUMUN END = @P_SALES_TYPE
													OR  CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_PREMIERPAPER.ISJUMUN END = @P_SALES_TYPE
													OR  CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_BHANDSCARD.ISJUMUN END = @P_SALES_TYPE
													OR  CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_THECARD.ISJUMUN END = @P_SALES_TYPE
													OR  CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_OUTBOUND.ISJUMUN END = @P_SALES_TYPE
													OR  CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_BARUNSONMALL.ISJUMUN END = @P_SALES_TYPE
												)
										)
									)

						) C

			) A

	WHERE	1 = 1
	AND		CASE WHEN @P_ORDER_BY_TYPE = 'ASC' THEN A.ROW_NUM ELSE A.ROW_NUM_DESC END > (@P_PAGE_NUMBER - 1) * @P_PAGE_SIZE
	AND		CASE WHEN @P_ORDER_BY_TYPE = 'ASC' THEN A.ROW_NUM ELSE A.ROW_NUM_DESC END <= @P_PAGE_NUMBER * @P_PAGE_SIZE
		
	ORDER BY 
		CASE WHEN @P_ORDER_BY_TYPE = 'ASC' THEN A.ROW_NUM ELSE A.ROW_NUM_DESC END ASC
	
END


GO
