IF OBJECT_ID (N'dbo.SP_INSERT_TNEO_QUEUE', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_INSERT_TNEO_QUEUE
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

EXEC SP_INSERT_MAIL_MST '차호용', 'sharniel@naver.com'

*/

CREATE PROCEDURE [dbo].[SP_INSERT_TNEO_QUEUE]
	@P_MAIL_TYPE AS VARCHAR(50)
,	@P_SITE_NAME AS VARCHAR(50)
,   @P_FROM_EMAIL AS VARCHAR(100)
,   @P_TO_NAME AS VARCHAR(100)
,   @P_TO_EMAIL AS VARCHAR(100)
,   @P_MAIL_TITLE AS VARCHAR(200)
,   @P_MAIL_FROM AS VARCHAR(MAX)
,   @P_USER_ID AS VARCHAR(50)

AS
BEGIN

	

	IF @P_USER_ID <> ''
	BEGIN
	
		SELECT	@P_TO_NAME = UNAME
			,	@P_TO_EMAIL = UMAIL
		FROM	VW_USER_INFO
		WHERE	1 = 1
		AND		UID = @P_USER_ID

	END 

	/*
	2022-07-29 김광호 TNEO_QUEUE 삽입 중지

	IF NOT EXISTS(SELECT * FROM TNEO_QUEUE WHERE BARID = @P_MAIL_TYPE AND RMAIL = @P_TO_EMAIL AND MTITLE = @P_MAIL_TITLE)
	BEGIN

		INSERT INTO TNEO_QUEUE (BARID, SNAME, SMAIL, RNAME, RMAIL, MTITLE, MCONTENT, MDATE, C_SITE, C_CATEGORY, CARDNO, ORG_DATE) 
		SELECT  
				@P_MAIL_TYPE
			,   @P_SITE_NAME
			,   @P_FROM_EMAIL
    
			,   @P_TO_NAME
			,   @P_TO_EMAIL

			,   @P_MAIL_TITLE
			,   @P_MAIL_FROM
			,   GETDATE()
			,   'M'
			,   'A'
			,   'WEDD'
			,   GETDATE()

	END
	*/

END
GO
