IF OBJECT_ID (N'dbo.SP_INSERT_WEDDINGBOX_EVENT', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_INSERT_WEDDINGBOX_EVENT
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Create date: 2021-08-17
-- Description:	바른손카드 웨딩박스 이벤트

-- EXEC SP_INSERT_WEDDINGBOX_EVENT 's4guest'

--SELECT  count(*) FROM EVT_WEDDINGBOX WHERE REG_DATE >= '2021-08-19' AND UID = 's4guest' 
-- =============================================

CREATE PROCEDURE [dbo].[SP_INSERT_WEDDINGBOX_EVENT]
	@UID								AS VARCHAR(50)
AS
BEGIN
	
	DECLARE		@COUPON_CODE					AS	VARCHAR(50) = ''
	DECLARE		@END_DATE						AS	VARCHAR(50)	= ''
	DECLARE		@MSG							AS	VARCHAR(150) = ''
	DECLARE		@SUBJECT						AS	VARCHAR(50) = ''
	DECLARE		@USERPHONE						AS	VARCHAR(50) = ''
	DECLARE		@COMPANY_NM						AS	VARCHAR(50) = ''
	DECLARE		@SEND_PHONE						AS	VARCHAR(15) = ''
	DECLARE		@SALES_GUBUN					AS	VARCHAR(2) = ''
	DECLARE		@EVENT_Cnt						AS INT
	DECLARE		@RESULT_CODE					AS VARCHAR(1) = ''

	--SET @RESULT_CODE = 'N'

	-- 발급안된 쿠폰번호 검색 후, 쿠폰발급
	SELECT @EVENT_Cnt = count(*) FROM EVT_WEDDINGBOX WHERE REG_DATE >= '2021-08-19' AND UID = @UID 


	IF @EVENT_Cnt = 0 
	
		BEGIN 
			INSERT INTO EVT_WEDDINGBOX (UID,REG_DATE) VALUES (@UID,GETDATE()) 

			SET @RESULT_CODE = 'Y'
		END 

    --SELECT  @RESULT_CODE	AS RESULT_CODE

END
GO
