IF OBJECT_ID (N'dbo.SP_SELECT_MYCOUPON_VIEW', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_MYCOUPON_VIEW
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_SELECT_MYCOUPON_VIEW]
		@P_UID AS VARCHAR(100) = ''    -- I : 진행중, E :만료
		,@P_ADSEQ AS VARCHAR(100) = ''    -- I : 진행중, E :만료
		,@P_COUPONCD AS VARCHAR(100) = ''    -- I : 진행중, E :만료
AS
BEGIN

	SET NOCOUNT ON

	SELECT		SCM.SMARTAD_COUPON_MST_SEQ
			,	SCM.AD_SEQ
			,	SCM.COUPON_NAME 
			,	SCM.COUPON_CD
			,	SCM.START_DATE
			,   SCM.END_DATE
			,	SCM.DISCOUNT_TYPE
			,	SCM.USE_YORN 
			,   SM.REG_DATE
			,	SPA.CONTENT1
			,	SPA.CONTENT2
			,	SPA.CONTENT3
			,   SPAI.IMG_URL
			,	SP.PARTNER_NAME
			,   SM.MYCOUPON_SEQ
			,   SCM.ISSUE_CNT
			,   SPA.PROMOTION_TYPE
			,   SPA.DIRECTION_MSG
			,   SPA.CAUTION_MSG
	FROM	SmartAD_Partner SP
		LEFT JOIN SmartAD_Partner_AD SPA
			ON	SP.PARTNER_SEQ = SPA.PARTNER_SEQ
		LEFT JOIN SmartAD_Partner_AD_IMAGE SPAI
			ON SPA.AD_SEQ = SPAI.AD_SEQ 
        LEFT JOIN SMARTAD_COUPON_MST SCM
			ON SPA.AD_SEQ = SCM.AD_SEQ
		LEFT JOIN SMARTAD_MYCOUPON SM
			ON SCM.SMARTAD_COUPON_MST_SEQ = SM.SMARTAD_COUPON_MST_SEQ
	WHERE	1	=	1
	--AND		SPA.PROMOTION_TYPE = 'S'
	AND		SPAI.IMAGE_TYPE = 'M'
	AND		SCM.USE_YORN = 'Y'
	AND		SM.UID = @P_UID
	AND     SM.AD_SEQ = @P_ADSEQ
	--AND     SM.COUPON_CD = @P_COUPONCD 
END


GO
