IF OBJECT_ID (N'dbo.SP_SELECT_CUSTOM_ORDER_FOR_AUTO_CHOAN_MACHINE_TEST', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_CUSTOM_ORDER_FOR_AUTO_CHOAN_MACHINE_TEST
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*

EXEC SP_SELECT_CUSTOM_ORDER_FOR_AUTO_CHOAN_MACHINE_TEST

select AUTO_CHOAN_STATUS_CODE,AUTO_CHOAN_REG_DATE,STATUS_SEQ,ISCOMPOSE,SRC_COMPOSE_ADMIN_ID,
* from custom_order where order_Seq in (3056181,3056182,3056184,3056188,3056126,3056176,3056179)



update custom_order set STATUS_SEQ = 1,ISCOMPOSE = 0, SRC_COMPOSE_ADMIN_ID = null where order_Seq in (3056181,3056182,3056184,3056188,3056126,3056176,3056179)

select * from manage_code where code_type = 'status_seq'

*/

CREATE PROCEDURE [dbo].[SP_SELECT_CUSTOM_ORDER_FOR_AUTO_CHOAN_MACHINE_TEST]

AS
BEGIN	

	DECLARE @ORDER_SEQ INT
	
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED	
	SET NOCOUNT ON
	SET LOCK_TIMEOUT 2000

	BEGIN TRAN AUTO_CHOAN_MACHINE

		/* 주문일 기준으로 */
		/* 자동 초안 생성중인 상태가 10분 이상 지났다면, 미완료로 변경하고 다시 시도한다. */
		/* 30분 이상 지난 건은 그대로 둔다. */ 	/* 60분 이상 지난 건은 그대로 둔다. */
		UPDATE	CUSTOM_ORDER
		SET		AUTO_CHOAN_STATUS_CODE = '138001'
			,	AUTO_CHOAN_REG_DATE = null
		WHERE	1 = 1
		AND		AUTO_CHOAN_REG_DATE < CONVERT(VARCHAR(19), DATEADD(MINUTE, -10, GETDATE()), 120)
		AND		AUTO_CHOAN_REG_DATE > CONVERT(VARCHAR(19), DATEADD(MINUTE, -30, GETDATE()), 120)
		AND		STATUS_SEQ = 1
		AND		ISCOMPOSE <> '1'
		AND		(SRC_COMPOSE_ADMIN_ID IS NULL OR SRC_COMPOSE_ADMIN_ID = '')
		AND		AUTO_CHOAN_STATUS_CODE = '138101'
		


		SELECT	TOP 1 
				@ORDER_SEQ = A.ORDER_SEQ
		FROM	CUSTOM_ORDER A WITH (HOLDLOCK, ROWLOCK, XLOCK)
		WHERE	1 = 1
		AND		A.ORDER_DATE >= CONVERT(VARCHAR(10), GETDATE() -10, 120) + ' 00:00:00'
		AND		A.STATUS_SEQ = 1
		AND		A.member_id = 's4guest'
		--AND		A.card_seq <> 37283
		AND		(
					(
							A.ISCOMPOSE <> '1'
						AND	ISNULL(A.AUTO_CHOAN_STATUS_CODE, '138001') = '138001' --미완료, , '138901'실패
						AND ISNULL(A.SRC_COMPOSE_ADMIN_ID, '') = ''  --AND	(SRC_COMPOSE_ADMIN_ID IS NULL OR SRC_COMPOSE_ADMIN_ID = '') 
					)
					OR
					(
						ISNULL(A.AUTO_CHOAN_STATUS_CODE, '138001') = '138002'	
					)
					OR
					(
							A.ISCOMPOSE <> '1'
						AND	ISNULL(A.AUTO_CHOAN_STATUS_CODE, '') = '138901'   --'138901'실패
						AND ISNULL(A.SRC_COMPOSE_ADMIN_ID, '') = ''  --AND	(SRC_COMPOSE_ADMIN_ID IS NULL OR SRC_COMPOSE_ADMIN_ID = '') 
						AND A.Order_seq IN (	SELECT L.order_seq FROM AUTO_CHOAN_LOG L
												WHERE L.SUB_LOCATION = 'Critical' AND L.order_seq= A.order_seq
												GROUP BY L.order_seq
												HAVING COUNT(*) < 3
													AND DATEADD( MI, 10, MAX(L.REG_DATE) ) < GETDATE()  --실패건은 10분뒤 재실행하고 총3번 실행할수 있음.
											)
					)
					
				)	
		--AND A.order_Seq in (3056181,3056182,3056184,3056188,3056126,3056176,3056179)
		ORDER BY ORDER_DATE ASC





		IF @ORDER_SEQ IS NOT NULL
			BEGIN

				UPDATE	CUSTOM_ORDER WITH (ROWLOCK, XLOCK)
				SET		AUTO_CHOAN_STATUS_CODE = '138101'
					,	AUTO_CHOAN_REG_DATE = GETDATE()
				WHERE	ORDER_SEQ = @ORDER_SEQ

				SELECT	@ORDER_SEQ AS ORDER_SEQ

			END

		ELSE
			BEGIN
			
				SELECT	0 AS ORDER_SEQ

			END

	COMMIT TRAN AUTO_CHOAN_MACHINE

END
GO
