IF OBJECT_ID (N'dbo.SP_SELECT_S5_NMCARD_IMAGE_INFO', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_S5_NMCARD_IMAGE_INFO
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

EXEC SP_SELECT_S5_NMCARD_IMAGE_INFO 's4guests4guest'

*/

CREATE PROCEDURE [dbo].[SP_SELECT_S5_NMCARD_IMAGE_INFO]
	@MCARD_ADDRESS AS VARCHAR(50)
AS
BEGIN

	SELECT	IMG_LG.ORDER_SEQ
		,	CONVERT(VARCHAR(10), ISNULL(IMG_LG.FILEINDEX, 0))		AS LG_IMAGE_FILE_INDEX
		,	ISNULL(IMG_LG.FILENAME, '')								AS LG_IMAGE_FILE_NAME
		,	CONVERT(VARCHAR(10),ISNULL(IMG_LG.IMAGESIZEW, 0))		AS LG_IMAGE_SIZE_WIDTH
		,	CONVERT(VARCHAR(10),ISNULL(IMG_LG.IMAGESIZEH, 0))		AS LG_IMAGE_SIZE_HEIGHT

		,	CASE 
					WHEN IMG_MD.FILEINDEX IS NULL		THEN	CONVERT(VARCHAR(10), ISNULL(IMG_LG.FILEINDEX, 0)) 
					WHEN IMG_MD.FILEINDEX IS NOT NULL	THEN	CONVERT(VARCHAR(10), ISNULL(IMG_MD.FILEINDEX, 0))
			END AS MD_IMAGE_FILE_INDEX
		,	CASE 
					WHEN IMG_MD.FILEINDEX IS NULL		THEN	ISNULL(IMG_LG.FILENAME, '') 
					WHEN IMG_MD.FILEINDEX IS NOT NULL	THEN	ISNULL(IMG_MD.FILENAME, '')	
			END AS MD_IMAGE_FILE_NAME
		,	CONVERT(VARCHAR(10),ISNULL(IMG_LG.IMAGESIZEW, 0))		AS MD_IMAGE_SIZE_WIDTH
		,	CONVERT(VARCHAR(10),ISNULL(IMG_LG.IMAGESIZEH, 0))		AS MD_IMAGE_SIZE_HEIGHT

		,	CONVERT(VARCHAR(10),ISNULL(IMG_SM.FILEINDEX, 0))		AS SM_IMAGE_FILE_INDEX
		,	ISNULL(IMG_SM.FILENAME, '')								AS SM_IMAGE_FILE_NAME
		,	CONVERT(VARCHAR(10),ISNULL(IMG_SM.IMAGESIZEW, 0))		AS SM_IMAGE_SIZE_WIDTH
		,	CONVERT(VARCHAR(10),ISNULL(IMG_SM.IMAGESIZEH, 0))		AS SM_IMAGE_SIZE_HEIGHT

	FROM	S5_NMCARDIMAGEINFO IMG_LG
	JOIN	S5_NMCARDIMAGEINFO IMG_SM ON IMG_LG.ORDER_SEQ = IMG_SM.ORDER_SEQ AND IMG_LG.FILEINDEX = IMG_SM.FILEINDEX
	LEFT JOIN	S5_NMCARDIMAGEINFO IMG_MD ON IMG_LG.ORDER_SEQ = IMG_MD.ORDER_SEQ AND IMG_LG.FILEINDEX = IMG_MD.FILEINDEX AND IMG_MD.FILETYPE = 6

	WHERE	1 = 1
	AND		IMG_LG.FILETYPE = 1
	AND		IMG_SM.FILETYPE = 2
	AND		IMG_LG.ORDER_SEQ IN ( SELECT ORDER_SEQ FROM S5_NMCARDORDER WHERE ADDR = @MCARD_ADDRESS )

END



GO
