IF OBJECT_ID (N'dbo.SP_INSERT_EVT_REGIST_GIFT', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_INSERT_EVT_REGIST_GIFT
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
  
/*  
  
바른손 가입혜택 이벤트 프로시저
2019.08.13 정혜련

EXEC [SP_INSERT_EVT_REGIST_GIFT] 2836954 , 5001
 
*/  
  
CREATE PROCEDURE [dbo].[SP_INSERT_EVT_REGIST_GIFT]  
    @ORDER_SEQ                  AS INT
   , @COMPANY_SEQ				AS INT
AS  
BEGIN  
  
DECLARE @FREE_GIFT_SEQ AS INT = 0  
DECLARE @FREE_GIFT_CARD_SEQ AS INT = 0  
DECLARE @FREE_GIFT_ITEM_TYPE AS VARCHAR(2) = ''  
DECLARE @TOTAL_QTY AS INT = 0  
DECLARE @UID AS VARCHAR(50) = ''  
DECLARE @FREE_GIFT_TARGET_YORN AS CHAR(1) = ''  
DECLARE @LIMIT_DELIVERY_REGION_STR AS VARCHAR(500) = ''  
DECLARE @LIMIT_DELIVERY_GU_STR AS VARCHAR(500) = ''  
DECLARE @LIMIT_CARD_BRAND AS VARCHAR(50) = ''  
DECLARE @ORDER_CARD_SEQ AS INT  
  
DECLARE @MAX_CNT AS INT = 0  
DECLARE @i AS INT = 1  
  
DECLARE @EVENT_REPLY_CNT AS INT = 0  
DECLARE @SALES_GUBUN AS VARCHAR(50) = ''  
DECLARE @MEMBER_ID AS VARCHAR(50) = ''  
DECLARE @FLOW AS INT = 0;  
DECLARE @ORDER_CNT AS INT = 0  

   
   -- 예외적으로 USE_YORN = 'N' 처리한다
    SELECT  @FREE_GIFT_SEQ              = A.FREE_GIFT_SEQ  
        ,   @FREE_GIFT_CARD_SEQ         = A.FREE_GIFT_CARD_SEQ  
        ,   @UID                        = A.UID  
        ,   @LIMIT_DELIVERY_REGION_STR  = A.LIMIT_DELIVERY_REGION_STR  
		,   @LIMIT_DELIVERY_GU_STR		= A.LIMIT_DELIVERY_GU_STR  
        ,   @FREE_GIFT_ITEM_TYPE        = A.FREE_GIFT_ITEM_TYPE  
        ,   @LIMIT_CARD_BRAND           = A.LIMIT_CARD_BRAND  
        ,   @ORDER_CARD_SEQ             = A.CARD_SEQ  
    FROM    (  
                SELECT  ROW_NUMBER() OVER(ORDER BY REG_DATE ASC) AS ROWNUM  
                    ,   ISNULL(SCFG.FREE_GIFT_SEQ, 0) AS FREE_GIFT_SEQ  
                    ,   ISNULL(SCFG.CARD_SEQ, 0) AS FREE_GIFT_CARD_SEQ  
                    ,   ISNULL(CO.MEMBER_ID, '') AS UID  
                    ,   ISNULL(SCFG.LIMIT_DELIVERY_REGION_STR, '') AS LIMIT_DELIVERY_REGION_STR  
                    ,   ISNULL(SCFG.LIMIT_DELIVERY_GU_STR, '') AS LIMIT_DELIVERY_GU_STR  
                    ,   ISNULL(SCFG.ITEM_TYPE, '') AS FREE_GIFT_ITEM_TYPE  
                    ,   ISNULL(SCFG.LIMIT_CARD_BRAND, '') AS LIMIT_CARD_BRAND  
                    ,   ISNULL(CO.CARD_SEQ, 0) AS CARD_SEQ  
                FROM    S2_CARD_FREE_GIFT SCFG  
                JOIN    CUSTOM_ORDER CO				   
                 ON CO.SALES_GUBUN IN (SELECT value FROM dbo.[ufn_SplitTable] (SCFG.SALES_GUBUN, '|'))  
                  AND     SCFG.START_DATE <= GETDATE()  
                  AND     SCFG.END_DATE >= GETDATE()  
                  AND     SCFG.USE_YORN = 'N'  
                  AND     SCFG.QTY > 0
				  AND	  SCFG.FREE_GIFT_SEQ IN (90,91,92)
                  AND (SCFG.LIMIT_ORDER_TYPE_STR = '' or CHARINDEX(CO.ORDER_TYPE, SCFG.LIMIT_ORDER_TYPE_STR, 1 ) > 0)  
				JOIN	evt_mem_regist_gift E
				 ON SCFG.CARD_SEQ = E.gift_card_seq
				 AND CO.MEMBER_ID = E.UID
				 AND E.company_seq = @COMPANY_SEQ
				 AND E.give_Date IS NULL 
				 AND E.end_Date >= GETDATE()
	       WHERE   1 = 1  
                AND     CO.ORDER_SEQ = @ORDER_SEQ  
                AND     CO.UP_ORDER_SEQ IS NULL  
                AND     ISNULL(SCFG.LIMIT_ORDER_PRICE, 0) <= ISNULL(CO.SETTLE_PRICE, 0)  
                AND     ISNULL(SCFG.LIMIT_ORDER_COUNT, 0) <= ISNULL(CO.ORDER_COUNT, 0)  
            ) A  
   
	if @FREE_GIFT_CARD_SEQ > 0 
	BEGIN

		IF NOT EXISTS(SELECT * FROM CUSTOM_ORDER_ITEM WHERE ORDER_SEQ = @ORDER_SEQ AND CARD_SEQ = @FREE_GIFT_CARD_SEQ)  
		BEGIN     
      
				INSERT INTO CUSTOM_ORDER_ITEM (ORDER_SEQ, CARD_SEQ, ITEM_TYPE, ITEM_COUNT, ITEM_PRICE, ITEM_SALE_PRICE, DISCOUNT_RATE, MEMO1, ADDNUM_PRICE)  
				VALUES (@ORDER_SEQ, @FREE_GIFT_CARD_SEQ, @FREE_GIFT_ITEM_TYPE, 1, 0, 0, 0, '', 0)  
  
				INSERT INTO S2_CARD_FREE_GIFT_LOG (FREE_GIFT_SEQ, CARD_SEQ, ORDER_SEQ, UID)  
				VALUES (@FREE_GIFT_SEQ, @FREE_GIFT_CARD_SEQ, @ORDER_SEQ, @UID)  
  
				UPDATE  S2_CARD_FREE_GIFT  
				SET     QTY = QTY - 1  
				WHERE   FREE_GIFT_SEQ = @FREE_GIFT_SEQ  

				UPDATE  evt_mem_regist_gift
				SET give_Date = GETDATE()
					, ORDER_SEQ = @ORDER_SEQ
				WHERE UID = @UID
				AND gift_card_seq = @FREE_GIFT_CARD_SEQ 
			  
		END  
	END

END  
  
GO
