IF OBJECT_ID (N'dbo.SP_DELETE_SELECT_OUTSOURCING_ORDER_MST', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_DELETE_SELECT_OUTSOURCING_ORDER_MST
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_DELETE_SELECT_OUTSOURCING_ORDER_MST]
    @P_OUTSOURCING_ORDER_SEQ      AS VARCHAR(4000)

AS
BEGIN
	create table #temp 
	(
		idx int identity(1,1),
		order_no int
	)

	declare @i int, @max int, @OUTSOURCING_ORDER_SEQ int
	insert into #temp (order_no)
	select VALUE from dbo.FN_SPLIT(@P_OUTSOURCING_ORDER_SEQ, ',') 

	SET @i = 0;
	Select @max = count(*) from #temp
	select * from #temp
	select @max

	while (@i <= @max)
	BEGIN
		Select @OUTSOURCING_ORDER_SEQ = order_no from #temp where idx = @i

		INSERT INTO OUTSOURCING_ORDER_MST_BACK_DATA (ORDER_STATUS_CODE,ORDER_TYPE_CODE,ORDER_SUB_TYPE_CODE,ORDER_SEQ,SITE_TYPE_CODE,ERP_PART_TYPE_CODE,CARD_CODE
													 ,ORDER_NAME,ORDER_QTY,PAPER_TYPE_NAME,PAPER_SIZE,PAGES_PER_SHEET_VALUE,PRINT_LOSS_VALUE,BOTH_SIDE_YORN,OSI_YORN
													 ,CUTOUT_YORN,GLOSSY_YORN,PRESS_YORN,FOIL_TYPE_NAME,LASER_CUT_YORN,REQUESTOR_NAME,COMPANY_TYPE_CODE,DELIVERY_TYPE_CODE
													 ,PRINT_FILE_URL,IMAGE_FILE_URL,RECEIPT_DATE,REG_DATE,MEMO,EXPECT_DATE,EDGE_YORN,EDGE_COLOR,PRINT_CHASU,OUTSOURCING_ORDER_SEQ_BACK)
		SELECT ORDER_STATUS_CODE,ORDER_TYPE_CODE,ORDER_SUB_TYPE_CODE,ORDER_SEQ,SITE_TYPE_CODE,ERP_PART_TYPE_CODE,CARD_CODE
			   ,ORDER_NAME,ORDER_QTY,PAPER_TYPE_NAME,PAPER_SIZE,PAGES_PER_SHEET_VALUE,PRINT_LOSS_VALUE,BOTH_SIDE_YORN,OSI_YORN
			   ,CUTOUT_YORN,GLOSSY_YORN,PRESS_YORN,FOIL_TYPE_NAME,LASER_CUT_YORN,REQUESTOR_NAME,COMPANY_TYPE_CODE,DELIVERY_TYPE_CODE
			   ,PRINT_FILE_URL,IMAGE_FILE_URL,RECEIPT_DATE,REG_DATE,MEMO,EXPECT_DATE,EDGE_YORN,EDGE_COLOR,PRINT_CHASU,@OUTSOURCING_ORDER_SEQ FROM OUTSOURCING_ORDER_MST WHERE OUTSOURCING_ORDER_SEQ = @OUTSOURCING_ORDER_SEQ

		DELETE OUTSOURCING_ORDER_MST WHERE OUTSOURCING_ORDER_SEQ = @OUTSOURCING_ORDER_SEQ

		SET @i = @i + 1
	END

	drop table #temp
END

GO
