IF OBJECT_ID (N'dbo.SP_DELETE_MCARD_COMMENT', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_DELETE_MCARD_COMMENT
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

ukliio1

SELECT * FROM MCARD_INVITATION WHERE ORDERERNAME = '엄예지' AND INVITATIONCODE = 'SS2349145' AND INVITATIONID = 14147

SELECT * FROM MCARD_COMMENT WHERE INVITATIONID IN (SELECT INVITATIONID FROM MCARD_INVITATION WHERE ORDERERNAME = '엄예지')

http://celemoerp.bhandscard.com/Service/MCard/DeleteMCardCommentHandler.ashx?INVITATION_ID=14147&INVITATION_CODE=SS2349145&USER_ID=ukliio1&DELETE_ALL_YORN=Y

*/

CREATE PROCEDURE [dbo].[SP_DELETE_MCARD_COMMENT]
	
	@P_INVITATION_ID AS INT
,	@P_INVITATION_CODE AS VARCHAR(10)
,	@P_COMMENT_ID AS INT
,	@P_USER_ID AS VARCHAR(50)
,	@P_DELETE_ALL_YORN AS VARCHAR(1)

AS
BEGIN

	SET NOCOUNT ON

	DECLARE @RESULT_SUCCESS AS VARCHAR(50)
	DECLARE @RESULT_MESSAGE AS VARCHAR(200)



	IF EXISTS	(
					SELECT	MC.COMMENTID
					FROM	MCARD_INVITATION MI
					JOIN	MCARD_COMMENT MC ON MI.INVITATIONID = MC.INVITATIONID AND MI.INVITATIONCODE = MC.INVITATIONCODE
					WHERE	1 = 1
					AND		MI.INVITATIONID = @P_INVITATION_ID
					AND		MI.INVITATIONCODE = @P_INVITATION_CODE
					AND		MI.AUTHCODE = @P_USER_ID
					AND		CASE WHEN @P_DELETE_ALL_YORN = 'Y' THEN 0 ELSE MC.COMMENTID END
							=
							CASE WHEN @P_DELETE_ALL_YORN = 'Y' THEN 0 ELSE @P_COMMENT_ID END
				)
	BEGIN

		DELETE 
		FROM	MCARD_COMMENT 
		WHERE	1 = 1
		AND		COMMENTID IN	(
									SELECT	MC.COMMENTID
									FROM	MCARD_INVITATION MI
									JOIN	MCARD_COMMENT MC ON MI.INVITATIONID = MC.INVITATIONID AND MI.INVITATIONCODE = MC.INVITATIONCODE
									WHERE	1 = 1
									AND		MI.INVITATIONID = @P_INVITATION_ID
									AND		MI.INVITATIONCODE = @P_INVITATION_CODE
									AND		MI.AUTHCODE = @P_USER_ID
									AND		CASE WHEN @P_DELETE_ALL_YORN = 'Y' THEN 0 ELSE MC.COMMENTID END
											=
											CASE WHEN @P_DELETE_ALL_YORN = 'Y' THEN 0 ELSE @P_COMMENT_ID END
	
								)

		SET @RESULT_SUCCESS = 'Y'
		SET @RESULT_MESSAGE = '삭제 완료'

	END

	ELSE
	BEGIN
		
		SET @RESULT_SUCCESS = 'N'
		SET @RESULT_MESSAGE = '데이타가 없습니다'

	END



	SELECT	@RESULT_SUCCESS AS RESULT_SUCCESS
		,	@RESULT_MESSAGE AS RESULT_MESSAGE

END
GO
