IF OBJECT_ID (N'dbo.SP_SELECT_VW_USER_INFO', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_VW_USER_INFO
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*

EXEC SP_SELECT_VW_USER_INFO 'sharniel', 'sharniel@nate.com', ''

*/
CREATE PROCEDURE [dbo].[SP_SELECT_VW_USER_INFO]
    
    @UID AS VARCHAR(50)
,   @PWD AS VARCHAR(50)
,   @DUPINFO AS VARCHAR(100)


AS
BEGIN
    
    SELECT  TOP 1 *
    FROM    VW_USER_INFO
    WHERE   UID = @UID
    AND     PWDCOMPARE(@PWD, CONVERT(VARBINARY(200), PWD, 1)) = 1
    AND     DUPINFO = @DUPINFO

END
GO
