IF OBJECT_ID (N'dbo.SP_SELECT_SAMPLE_ORDER_CONVERSION_RATE_FOR_WEDD_TEST', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_SAMPLE_ORDER_CONVERSION_RATE_FOR_WEDD_TEST
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

EXEC SP_SELECT_SAMPLE_ORDER_CONVERSION_RATE_FOR_CUSTOM_ORDER '2016-07', '2017-10', ''

*/
CREATE PROCEDURE [dbo].[SP_SELECT_SAMPLE_ORDER_CONVERSION_RATE_FOR_WEDD_TEST]
		@P_START_DATE AS VARCHAR(7)
	,	@P_END_DATE AS VARCHAR(7)
	,	@P_SALES_GUBUN AS VARCHAR(100)
AS
BEGIN

	SET NOCOUNT ON

	DECLARE @T_MONTH TABLE
    (
		[MONTH] VARCHAR(7)
	)	

	INSERT INTO @T_MONTH ([MONTH])

	SELECT	CONVERT(VARCHAR(7), DATEADD(D, NUMBER, @P_START_DATE + '-01'), 120) [MONTH]
	FROM	MASTER..SPT_VALUES
	WHERE	TYPE = 'P' 
	AND		NUMBER <= DATEDIFF(D, @P_START_DATE + '-01', CONVERT(VARCHAR(4), DATEADD(YEAR, 1, SUBSTRING(@P_END_DATE, 1, 4)), 120) + '-12-01')
	GROUP BY CONVERT(VARCHAR(7), DATEADD(D,NUMBER,@P_START_DATE + '-01'), 120)

	

	SET @P_SALES_GUBUN = CASE WHEN @P_SALES_GUBUN = 'SB|SA|ST|SS|B' THEN '' ELSE @P_SALES_GUBUN END



	SELECT	A.SAMPLE_DELIVERY_DATE	AS SampleDeliveryMonth
		,	T.MONTH					AS ConversionMonth
		,	MAX(CASE WHEN A.CUSTOM_WEDDING_DATE = T.MONTH THEN A.WEDDING_INVITATION_QNT ELSE 0 END)	AS WeddingInvitationCount
		,	SUM(A.SAMPLE_ORDER_QNT)																		AS SampleCount
		,	ROUND(1.0 * MAX(CASE WHEN A.CUSTOM_WEDDING_DATE = T.MONTH THEN A.WEDDING_INVITATION_QNT ELSE 0 END) / SUM(A.SAMPLE_ORDER_QNT) * 100, 2) AS Rate

	FROM	(
				SELECT	CSOCO.SAMPLE_DELIVERY_DATE
					,	CSOCO.CUSTOM_WEDDING_DATE
					,	SUM(CSOCO.WEDDING_INVITATION_QNT)	AS WEDDING_INVITATION_QNT
					,	SUM(CSOCO.SAMPLE_ORDER_QNT)			AS SAMPLE_ORDER_QNT
				FROM	(
							SELECT	CSO.SAMPLE_ORDER_SEQ
								,	MAX(CONVERT(VARCHAR(7), CSO.DELIVERY_DATE, 120))		AS SAMPLE_DELIVERY_DATE
								,	MAX(CONVERT(VARCHAR(7), VUI.WEDDING_DAY, 120))			AS CUSTOM_WEDDING_DATE
								,	1														AS WEDDING_INVITATION_QNT
								,	1														AS SAMPLE_ORDER_QNT
							FROM	CUSTOM_SAMPLE_ORDER CSO
							JOIN	VW_USER_INFO VUI
								ON	CSO.MEMBER_ID = VUI.UID
							WHERE	1 = 1
							AND		CSO.STATUS_SEQ = 12

							AND		('' = '' OR CSO.SALES_GUBUN IN (SELECT VALUE FROM DBO.FN_SPLIT('', '|')))
							AND		CSO.DELIVERY_DATE >= '2016-07' + '-01 00:00:00'
							AND		CSO.DELIVERY_DATE < DATEADD(MM, 1, '2017-07' + '-01 00:00:00')

							GROUP BY CSO.SAMPLE_ORDER_SEQ
						) CSOCO
				GROUP BY CSOCO.SAMPLE_DELIVERY_DATE, CSOCO.CUSTOM_WEDDING_DATE
			) A
	LEFT
	JOIN	@T_MONTH T ON 1 = 1

	GROUP BY A.SAMPLE_DELIVERY_DATE, T.MONTH
	ORDER BY A.SAMPLE_DELIVERY_DATE ASC, T.MONTH ASC



END
GO
