IF OBJECT_ID (N'dbo.SP_INSERT_MARKETING_AGREEMENT_LOG', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_INSERT_MARKETING_AGREEMENT_LOG
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_INSERT_MARKETING_AGREEMENT_LOG]
	@P_USER_ID VARCHAR(20),
	@P_AGREEMENT_DATA VARCHAR(100)

AS
BEGIN
	
	/* 기존 동의 로그 갱신 */
	UPDATE MGL SET
		MGL.REG_DATE = 
			CASE 
				WHEN YN = 'Y' AND MGL.REG_DATE IS NULL THEN GETDATE() 
				ELSE MGL.REG_DATE
			END
	FROM S4_MARKETING_AGREEMENT_LOG AS MGL
		INNER JOIN (
			SELECT substring(value,0,CHARINDEX(':',value)) AS MARKETING_TYPE_CODE, 
				RIGHT(value,1) AS YN
			FROM dbo.[ufn_SplitTable] (@P_AGREEMENT_DATA, '|')
		) AS A
			ON MGL.MARKETING_TYPE_CODE = A.MARKETING_TYPE_CODE
				AND MGL.UID = @P_USER_ID ;

	/* 신규 동의 로그 등록 */
	INSERT INTO S4_MARKETING_AGREEMENT_LOG (
		UID,
		SALES_GUBUN,
		MARKETING_TYPE_CODE,
		REG_DATE
	)
	SELECT
		@P_USER_ID AS UID,
		(SELECT SELECT_SALES_GUBUN FROM S2_USERINFO_THECARD WHERE UID = @P_USER_ID) AS SALES_GUBUN,
		MARKETING_TYPE_CODE,
		CASE 
			WHEN YN = 'Y' THEN GETDATE()
			ELSE NULL
		END AS REG_DATE
	FROM (
			SELECT substring(value,0,CHARINDEX(':',value)) AS MARKETING_TYPE_CODE, 
				RIGHT(value,1) AS YN
			FROM dbo.[ufn_SplitTable] (@P_AGREEMENT_DATA, '|')
		) AS A
	WHERE MARKETING_TYPE_CODE NOT IN (
		SELECT
			MARKETING_TYPE_CODE
		FROM S4_MARKETING_AGREEMENT_LOG
		where UID = @P_USER_ID
	);
	
END
GO
