IF OBJECT_ID (N'dbo.sp_DacomSMS', N'P') IS NOT NULL DROP PROCEDURE dbo.sp_DacomSMS
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

EXEC sp_DacomSMS '010-8973-8286', '1644-0708', '테스트입니다~'

*/
CREATE PROCEDURE [dbo].[sp_DacomSMS]
	@RECV_PNUM 	VARCHAR(20),
	@SEND_PNUM 	VARCHAR(20),
	@MSG 	VARCHAR(160)
AS
BEGIN

	EXEC SP_EXEC_SMS_OR_MMS_SEND @SEND_PNUM, @RECV_PNUM, '', @MSG, '', '기타', 'SP_DACOMSMS', '', 0, ''	

END
GO
