IF OBJECT_ID (N'dbo.SP_INSERT_S2_CARD_FREE_FOOD_TICKET_MST', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_INSERT_S2_CARD_FREE_FOOD_TICKET_MST
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*

EXEC SP_SELECT_FOOD_TICKET_LIST 'C06|C11', '', 5001

SELECT * FROM S2_CARD WHERE CARD_CODE LIKE '%FS%'

SELECT * FROM S2_CARDSALESSITE WHERE CARD_SEQ IN (SELECT CARD_SEQ FROM S2_CARD WHERE CARD_CODE LIKE '%FS%')

*/
CREATE PROCEDURE [dbo].[SP_INSERT_S2_CARD_FREE_FOOD_TICKET_MST]
	@SEQ			AS INT
,	@CARD_SEQ		AS INT
,	@COMPANY_SEQ	AS INT
,	@START_DATE		AS VARCHAR(10)
,	@END_DATE		AS VARCHAR(10)
,	@USE_JEHU_YORN	AS VARCHAR(1)
,	@USE_YORN		AS VARCHAR(1)
AS
BEGIN
	
	IF @SEQ > 0
	BEGIN
		
		UPDATE	S2_CARD_FREE_FOOD_TICKET_MST
		SET		CARD_SEQ		= @CARD_SEQ		
			,	COMPANY_SEQ		= @COMPANY_SEQ	
			,	START_DATE		= @START_DATE		
			,	END_DATE		= @END_DATE		
			,	USE_JEHU_YORN	= @USE_JEHU_YORN	
			,	USE_YORN		= @USE_YORN		
		WHERE   SEQ = @SEQ

	END

	ELSE
	BEGIN

		INSERT INTO S2_CARD_FREE_FOOD_TICKET_MST (
				CARD_SEQ
			,	COMPANY_SEQ
			,	START_DATE
			,	END_DATE
			,	USE_JEHU_YORN
			,	USE_YORN
		)
		SELECT	@CARD_SEQ		
			,	@COMPANY_SEQ	
			,	@START_DATE		
			,	@END_DATE		
			,	@USE_JEHU_YORN	
			,	@USE_YORN		

	END

END
GO
