IF OBJECT_ID (N'dbo.SP_SELECT_OUTSOURCING_CARD_PRINT_INFO_FOR_GROUP', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_OUTSOURCING_CARD_PRINT_INFO_FOR_GROUP
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

EXEC SP_SELECT_OUTSOURCING_CARD_PRINT_INFO_FOR_GROUP 'PAPER_NAME'

*/

CREATE PROCEDURE [dbo].[SP_SELECT_OUTSOURCING_CARD_PRINT_INFO_FOR_GROUP]
    @TYPE_CODE          AS NVARCHAR(50)

AS
BEGIN
    
    IF @TYPE_CODE = 'PAPER_NAME'
        BEGIN

            SELECT PAPER_NAME FROM [erpdb.bhandscard.com].[XERP].dbo.VW_CARD_PRINT_INFO_WITH_WEPOD GROUP BY PAPER_NAME

        END
    ELSE IF @TYPE_CODE = 'PAPER_SIZE'
        BEGIN

            SELECT CHILDITEMSPEC AS PAPER_SIZE FROM [erpdb.bhandscard.com].[XERP].dbo.VW_CARD_PRINT_INFO_WITH_WEPOD GROUP BY CHILDITEMSPEC

        END


END

GO
