IF OBJECT_ID (N'dbo.select_WOrder_Call', N'P') IS NOT NULL DROP PROCEDURE dbo.select_WOrder_Call
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE    PROCEDURE [dbo].[select_WOrder_Call]
    @P_HPHONE AS VARCHAR(20)
AS
BEGIN
	
	SET @P_HPHONE = REPLACE(@P_HPHONE,'-','')
	
	Declare @PhonNo VARCHAR(20)
	Set @PhonNo = dbo.FN_GET_PHONENO_ADDHYPHEN(@P_HPHONE)

	SELECT	ORDER_SEQ
	FROM	CUSTOM_ORDER 
	WHERE	ORDER_SEQ > 2350000
	AND	   (ORDER_HPHONE = @PhonNo Or ORDER_HPHONE = @P_HPHONE)
	
END
GO
