IF OBJECT_ID (N'dbo.SP_SELECT_S2_CARD_FOR_SALES', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_S2_CARD_FOR_SALES
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

EXEC SP_SELECT_S2_CARD_FOR_SALES 'C06', 5001, 1, 'N', 'N'

EXEC SP_SELECT_S2_CARD_FOR_SALES 'C06', 5001, 1, 'N', 'N'

*/

CREATE PROCEDURE [dbo].[SP_SELECT_S2_CARD_FOR_SALES]
		@CARD_DIV AS VARCHAR(100)
	,	@COMPANY_SEQ AS INT
	,	@JUMUN_STATUS AS INT
	,	@FREE_FOOD_TICKET_INCLUDE_YORN AS CHAR(1)
	,	@FREE_FOOD_TICKET_ONLY_YORN AS CHAR(1)
AS

	
	SET NOCOUNT ON;

	DECLARE @CARD_DIV_MST TABLE
    (
		CARD_DIV VARCHAR(10)
	)	

	INSERT INTO @CARD_DIV_MST (CARD_DIV)
    SELECT	VALUE 
	FROM	[dbo].[FN_SPLIT] (@CARD_DIV, '|')



	SELECT  SCSS.CARD_SEQ
		,	SC.CARD_NAME
		,	SC.CARDSET_PRICE
		,	SC.CARD_PRICE
		,	SC.CARD_IMAGE

    FROM    S2_CARDSALESSITE SCSS
    JOIN    S2_CARD SC ON SCSS.CARD_SEQ = SC.CARD_SEQ
	
	WHERE   1 = 1
	AND		SC.CARD_DIV IN (SELECT CARD_DIV FROM @CARD_DIV_MST)
	AND		SCSS.COMPANY_SEQ = @COMPANY_SEQ 
	AND		SCSS.ISJUMUN = @JUMUN_STATUS

	AND		1 = CASE 
						WHEN @FREE_FOOD_TICKET_INCLUDE_YORN = 'Y'
						THEN 1
						WHEN @FREE_FOOD_TICKET_INCLUDE_YORN = 'N'
						THEN  
								CASE 
										WHEN 
												NOT EXISTS	(
													SELECT	1 
													FROM	S2_CARD_FREE_FOOD_TICKET_MST SCFFTM 
													WHERE	SCFFTM.COMPANY_SEQ = @COMPANY_SEQ 
													AND		CONVERT(VARCHAR(8), SCFFTM.START_DATE, 112) <= CONVERT(VARCHAR(8), GETDATE(), 112)
													AND		CONVERT(VARCHAR(8), SCFFTM.END_DATE, 112) >= CONVERT(VARCHAR(8), GETDATE(), 112)
													AND		SCFFTM.USE_YORN = 'Y' 
													AND		SCFFTM.CARD_SEQ = SCSS.CARD_SEQ
												)
										THEN 1
								END
				END

	AND		1 = CASE 
						WHEN @FREE_FOOD_TICKET_ONLY_YORN = 'N'
						THEN 1
						WHEN @FREE_FOOD_TICKET_INCLUDE_YORN = 'Y'
						THEN  
								CASE 
										WHEN 
												EXISTS	(
													SELECT	1 
													FROM	S2_CARD_FREE_FOOD_TICKET_MST SCFFTM 
													WHERE	SCFFTM.COMPANY_SEQ = @COMPANY_SEQ 
													AND		CONVERT(VARCHAR(8), SCFFTM.START_DATE, 112) <= CONVERT(VARCHAR(8), GETDATE(), 112)
													AND		CONVERT(VARCHAR(8), SCFFTM.END_DATE, 112) >= CONVERT(VARCHAR(8), GETDATE(), 112)
													AND		SCFFTM.USE_YORN = 'Y' 
													AND		SCFFTM.CARD_SEQ = SCSS.CARD_SEQ
												)
										THEN 1
								END
				END
    
	ORDER BY SC.CARD_PRICE, SC.CARD_NAME, SC.CARD_DIV
GO
