IF OBJECT_ID (N'dbo.SP_EXEC_COUPON_ISSUE', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_EXEC_COUPON_ISSUE
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*

    http://www.barunsoncard.com/event/event_coupon_issue_for_celemo.asp?company_seq=5001&uid=s4guest
    
    SELECT * FROM S4_COUPON WHERE COMPANY_SEQ = 5001 AND ISRECYCLE = 'Y' ORDER BY REG_DATE DESC

    --INSERT INTO S4_COUPON (COUPON_CODE, COMPANY_SEQ, UID, REG_DATE, DISCOUNT_TYPE, DISCOUNT_VALUE, LIMIT_PRICE, ISYN, COUPON_DESC, ISRECYCLE, ISWEDDINGCOUPON, ISJEHU, ITEM_TYPE, COUPON_TYPE_CODE)
    --VALUES ('BRSP5000CELEMO', 5001, '', GETDATE(), 'P', '5000', '0', 'Y', '셀레모 이벤트 5,000원 할인쿠폰', 'Y', 'Y', 'N', 'W1', '114001')


    SELECT * FROM S4_EVENTMUSIC_REPLY WHERE REG_NUM = 92 AND UID = 's4guest'
    SELECT * FROM S4_MYCOUPON WHERE UID = 's4guest' ORDER BY REG_DATE DESC



    DELETE S4_EVENTMUSIC_REPLY WHERE REG_NUM = 92 AND UID = 's4guest'
    DELETE S4_MYCOUPON WHERE UID = 's4guest' AND COUPON_CODE = 'BRSP5000CELEMO'
    

    BRSR10SP140721

    DECLARE @RESULT_CODE AS VARCHAR(4)
    EXEC SP_EXEC_COUPON_ISSUE 5001, 's4guest', 'BRSR10SP140721', 5001, '2015-09-12', @RESULT_CODE OUTPUT
    SELECT @RESULT_CODE

*/
CREATE PROCEDURE [dbo].[SP_EXEC_COUPON_ISSUE]
    @COMPANY_SEQ AS INT
,   @USER_ID AS VARCHAR(50)
,   @COUPON_CODE AS VARCHAR(50)
,   @COUPON_COMPANY_SEQ AS INT
,   @END_DATE AS DATETIME
AS
BEGIN
    
    SET NOCOUNT ON;

    DECLARE @RESULT_CODE AS VARCHAR(4)

    IF EXISTS( SELECT TOP 1 * FROM S4_COUPON WHERE COUPON_CODE = @COUPON_CODE AND COMPANY_SEQ = @COUPON_COMPANY_SEQ )
    BEGIN
        
        IF NOT EXISTS( SELECT TOP 1 * FROM S4_MYCOUPON WHERE COUPON_CODE = @COUPON_CODE AND COMPANY_SEQ = @COMPANY_SEQ AND UID = @USER_ID )
        BEGIN
            
            INSERT INTO S4_MYCOUPON (COUPON_CODE, UID, COMPANY_SEQ, ISMYYN, END_DATE, REG_DATE)
            VALUES ( @COUPON_CODE, @USER_ID, @COMPANY_SEQ, 'Y', @END_DATE, GETDATE() )

            SET @RESULT_CODE = '0000'

        END

        ELSE
        BEGIN
            
            SET @RESULT_CODE = '1000'

        END

    END

    ELSE
    BEGIN
        
        SET @RESULT_CODE = '2000'

    END



    SELECT  @RESULT_CODE AS RESULT_CODE



END
GO
