IF OBJECT_ID (N'dbo.SP_SELECT_ADMIN_LST_FOR_LOGIN', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_ADMIN_LST_FOR_LOGIN
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_SELECT_ADMIN_LST_FOR_LOGIN]
    @P_USER_ID AS VARCHAR(30)
,   @P_USER_PW AS VARCHAR(30)

AS
BEGIN

DECLARE
    @R_MSG AS NVARCHAR(200)
,   @R_RESULT AS INT
,   @R_USER_NAME AS NVARCHAR(200)	
,   @R_USER_GRADE AS INT
,   @R_COMPANY_TYPE_CODE AS VARCHAR(6)

    SET @R_USER_NAME = ''

	IF (EXISTS(SELECT * FROM ADMIN_LST WHERE ADMIN_ID = @P_USER_ID AND NSTATE = 1))
	BEGIN
		IF (EXISTS(SELECT * FROM ADMIN_LST WHERE ( ADMIN_ID = @P_USER_ID AND ADMIN_PASSWD = @P_USER_PW ) AND NSTATE = 1))
		BEGIN
			SET @R_RESULT = 1
			SET @R_MSG = ''

			SELECT	@R_USER_NAME = ADMIN_NAME
                ,   @R_USER_GRADE = ADMIN_LEVEL
                ,   @R_COMPANY_TYPE_CODE = ISNULL(COMPANY_TYPE_CODE, '107000')
			FROM	ADMIN_LST 
			WHERE	ADMIN_ID = @P_USER_ID AND ADMIN_PASSWD = @P_USER_PW

		END

		ELSE
		BEGIN
			SET @R_RESULT = -1
			SET @R_MSG = '비밀번호를 잘못 입력하셨습니다.'
		END
	END

	ELSE
	BEGIN
		SET @R_RESULT = -1
		SET @R_MSG = '아이디를 잘못 입력하셨습니다.'
	END



	SELECT	@R_MSG AS MSG
		,	@R_RESULT AS RESULT
		,	@R_USER_NAME AS USER_NAME
        ,   @P_USER_ID AS USER_ID
        ,   @R_USER_GRADE AS USER_GRADE
        ,   @R_COMPANY_TYPE_CODE AS COMPANY_TYPE_CODE

END
GO
