IF OBJECT_ID (N'dbo.SP_DELETE_OUTSOURCING_ORDER_MST', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_DELETE_OUTSOURCING_ORDER_MST
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_DELETE_OUTSOURCING_ORDER_MST]
    @P_OUTSOURCING_ORDER_SEQ      AS INT

AS
BEGIN

    DELETE OUTSOURCING_ORDER_MST WHERE OUTSOURCING_ORDER_SEQ = @P_OUTSOURCING_ORDER_SEQ

END

GO
