IF OBJECT_ID (N'dbo.SP_SELECT_BEWEDDING_SOURCE_LIST', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_BEWEDDING_SOURCE_LIST
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

EXEC SP_SELECT_BEWEDDING_SOURCE_LIST NULL, 9999, 1, 'REG_DATE', 'DESC'

*/
CREATE PROCEDURE [dbo].[SP_SELECT_BEWEDDING_SOURCE_LIST]
		@P_SEARCH_VALUE AS VARCHAR(100) = ''
	,	@P_PAGE_SIZE AS INT
	,	@P_PAGE_NUMBER AS INT
	,	@P_ORDER_BY_NAME AS VARCHAR(50)
	,	@P_ORDER_BY_TYPE AS VARCHAR(10)
AS
BEGIN

	SET NOCOUNT ON


	SELECT	*
	FROM	(
				SELECT	ROW_NUMBER() OVER	(
												ORDER BY 
													CASE WHEN @P_ORDER_BY_NAME = 'REG_DATE'					THEN C.REG_DATE						ELSE 0 END ASC
												,	C.SOURCE_SEQ ASC
													
											) AS ROW_NUM
					,	ROW_NUMBER() OVER	(
												ORDER BY 
													CASE WHEN @P_ORDER_BY_NAME = 'REG_DATE'					THEN C.REG_DATE						ELSE 0 END DESC
												,	C.SOURCE_SEQ DESC
													
											) AS ROW_NUM_DESC
					,	*
				FROM	(
							SELECT	 
									BS.SOURCE_SEQ
								,	BS.SOURCE_CODE
								,	BS.SOURCE_NAME
								,	BS.REG_DATE
								,	BS.UPD_DATE
								,	BS.UPD_ID
								,   BS.USE_YN
								,   (SELECT COUNT(*) FROM BEWEDDING_CONTENT BC WHERE BC.SOURCE_SEQ = BS.SOURCE_SEQ) AS CONTENT_CNT
								,   (SELECT COUNT(*) FROM BEWEDDING_SOURCE_IMAGE BSI WHERE BSI.SOURCE_SEQ = BS.SOURCE_SEQ) AS SOURCE_LOGOIMG_CNT
							FROM	BEWEDDING_SOURCE BS
							WHERE	1 = 1
							AND	 --(ISNULL(@P_SEARCH_VALUE,'') = '' OR SP.PARTNER_NAME LIKE '%' + @P_SEARCH_VALUE + '%')
								
									(
											CASE WHEN ISNULL(@P_SEARCH_VALUE,'') = '' THEN '' ELSE BS.SOURCE_NAME END LIKE '%' + ISNULL(@P_SEARCH_VALUE,'') + '%'
									)

						) C

			) A

	WHERE	1 = 1
	AND		CASE WHEN @P_ORDER_BY_TYPE = 'ASC' THEN A.ROW_NUM ELSE A.ROW_NUM_DESC END > (@P_PAGE_NUMBER - 1) * @P_PAGE_SIZE
	AND		CASE WHEN @P_ORDER_BY_TYPE = 'ASC' THEN A.ROW_NUM ELSE A.ROW_NUM_DESC END <= @P_PAGE_NUMBER * @P_PAGE_SIZE
		
	ORDER BY 
		CASE WHEN @P_ORDER_BY_TYPE = 'ASC' THEN A.ROW_NUM ELSE A.ROW_NUM_DESC END ASC
	
END


GO
