IF OBJECT_ID (N'dbo.SP_SELECT_OUTSOURCING_ORDER_MST_FOR_LIST_AND_PARAM_ORDER_SEQS', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_OUTSOURCING_ORDER_MST_FOR_LIST_AND_PARAM_ORDER_SEQS
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
/*

EXEC SP_SELECT_OUTSOURCING_ORDER_MST_FOR_LIST_AND_PARAM_ORDER_SEQS '2141291|2144272|2143992'

SELECT * FROM VW_OUTSOURCING_ORDER_MST



*/

CREATE PROCEDURE [dbo].[SP_SELECT_OUTSOURCING_ORDER_MST_FOR_LIST_AND_PARAM_ORDER_SEQS]
	
	@p_outsourcing_order_seqs varchar(4000)

AS
BEGIN
    
	DECLARE @T_OUTSOURCING_ORDER_SEQ TABLE
    (
	    OUTSOURCING_ORDER_SEQ int NOT NULL
    )

	INSERT INTO @T_OUTSOURCING_ORDER_SEQ (OUTSOURCING_ORDER_SEQ)
    SELECT * FROM dbo.[ufn_SplitTable](@p_outsourcing_order_seqs, '|')

    SELECT  ROW_NUMBER() OVER(ORDER BY VW_OOM.REG_DATE ASC) AS ROW_NUM
		,	VW_OOM.OUTSOURCING_ORDER_SEQ
		,	VW_OOM.ORDER_SEQ
		,	VW_OOM.CARD_CODE
		,	VW_OOM.ORDER_NAME
		,	VW_OOM.PRINT_FILE_URL
		,	VW_OOM.FOIL_TYPE_NAME
    FROM    VW_OUTSOURCING_ORDER_MST AS VW_OOM
	JOIN	@T_OUTSOURCING_ORDER_SEQ T_OS ON VW_OOM.OUTSOURCING_ORDER_SEQ = T_OS.OUTSOURCING_ORDER_SEQ

    ORDER BY VW_OOM.REG_DATE DESC

END
GO
