IF OBJECT_ID (N'dbo.SP_VW_COUPON_USER_LIST', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_VW_COUPON_USER_LIST
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

EXEC SP_VW_COUPON_USER_LIST 's4guest'

*/
CREATE PROCEDURE [dbo].[SP_VW_COUPON_USER_LIST]
    
    @P_UID			AS VARCHAR(50)
,   @P_COMPANY_SEQS AS VARCHAR(50) = ''

AS
BEGIN
	


	SELECT	CM.COUPON_MST_SEQ                   AS CouponMstSeq
		,	CD.COUPON_DETAIL_SEQ				AS CouponDetailSeq
		,	CI.COUPON_ISSUE_SEQ					AS CouponIssueSeq
		,	CD.COUPON_CODE						AS CouponCode
		,	CI.UID								AS Uid
		,	CI.COMPANY_SEQ						AS CompanySeq
		,	CASE WHEN CI.SALES_GUBUN = 'SB' THEN '바른손' 
				 WHEN CI.SALES_GUBUN = 'SA' THEN '비핸즈' 
				 WHEN CI.SALES_GUBUN = 'ST' THEN '더카드' 
				 WHEN CI.SALES_GUBUN = 'SS' THEN '프리미어' 
				 ELSE  '바른손몰' 
				 END 		AS Site
		,	CI.ACTIVE_YN						AS ActiveYN
		,	ISNULL(CONVERT(VARCHAR(10), CI.END_DATE, 120), '')		AS EndDate
		,	ISNULL(CONVERT(VARCHAR(10), CI.REG_DATE, 120), '없음')		AS RegDate
		,	CM.EXPIRY_TYPE					
		,	CM.EXPIRY_CUSTOM_VALUE
		,	CONVERT(VARCHAR(10), CM.EXPIRY_START_DATE, 120) AS EXPIRY_START_DATE
		,	CONVERT(VARCHAR(10), CM.EXPIRY_END_DATE, 120) AS EXPIRY_END_DATE
		,	CM.COUPON_NAME						AS CouponName
		,	CM.COUPON_DESC						AS CouponDesc
		,	CM.COUPON_GROUP_CODE
		,	CM.COUPON_TYPE_CODE
		,	CM.ORDER_TYPE_CODE
		,	CM.DUP_COUPON_ALLOW_YN
		,	CM.AD_COUPON_ALLOW_YN
		,	CM.ADD_COUPON_ALLOW_YN
		,	CM.ORDER_APPLY_TYPE
		,	CM.DOWNLOAD_KIND
		,	CM.DOWNLOAD_KIND_ETC_CODE
		,	CM.DOWNLOAD_USER_GB
		,	CM.USE_PLACE
		,	CM.USE_DEVICE
		,	CM.DISCOUNT_VALUE					AS DiscountValue
		,	CM.DISCOUNT_FIXED_RATE_TYPE			AS DiscountFixedRateType
		,	CM.DISCOUNT_MAX_AMT					AS DiscountMaxAmt
		,	CM.ORDER_AMT						AS OrderAmt
		,	CM.ORDER_CNT						AS OrderCnt
		,	CM.CARD_ORDER_CNT
		,	CM.STATUS_ACTIVE_YN

	FROM	COUPON_MST CM
	JOIN	COUPON_DETAIL CD ON CM.COUPON_MST_SEQ = CD.COUPON_MST_SEQ
	JOIN	COUPON_ISSUE CI ON CD.COUPON_DETAIL_SEQ = CI.COUPON_DETAIL_SEQ

	WHERE	1 = 1
	AND		CI.UID = @P_UID
    AND     (
                    @P_COMPANY_SEQS = ''
                OR  CI.COMPANY_SEQ IN (SELECT VALUE FROM FN_SPLIT(@P_COMPANY_SEQS, '|'))
            )

END
GO
