IF OBJECT_ID (N'dbo.SP_INSERT_EVENT_MUSIC_REPLY', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_INSERT_EVENT_MUSIC_REPLY
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

SELECT * FROM S4_EVENTMUSIC_REPLY

*/

CREATE PROCEDURE [dbo].[SP_INSERT_EVENT_MUSIC_REPLY]
    @REG_NUM AS INT
,   @COMPANY_SEQ AS INT
,   @SALES_GUBUN AS VARCHAR(2)
,   @USER_ID AS VARCHAR(50)
,   @USER_NAME AS VARCHAR(50)
,   @USER_EMAIL AS VARCHAR(50)
,   @COMMENT AS VARCHAR(1000)

AS
BEGIN
    
    SET NOCOUNT ON;

    DECLARE @RESULT_CODE AS VARCHAR(4)

    IF NOT EXISTS(SELECT TOP 1 * FROM S4_EVENTMUSIC_REPLY WHERE REG_NUM = @REG_NUM AND UID = @USER_ID AND company_seq = @COMPANY_SEQ)
    BEGIN
        
        IF @USER_ID <> '' AND @USER_NAME = '' 
        BEGIN

            SELECT  TOP 1
                    @USER_NAME = uname
                ,   @USER_EMAIL = umail
            FROM    VW_USER_INFO
            WHERE   1 = 1
            AND     site_div = @SALES_GUBUN
            AND     UID = @USER_ID

        END



        INSERT INTO S4_EVENTMUSIC_REPLY (COMPANY_SEQ, REG_NUM, UID, UNAME, UMAIL, COMMENT, REG_DATE)
        VALUES (@COMPANY_SEQ, @REG_NUM, @USER_ID, @USER_NAME, @USER_EMAIL, @COMMENT, GETDATE())

        SET @RESULT_CODE = '0000'

    END

    ELSE
    BEGIN
        
        SET @RESULT_CODE = '1000'

    END



    SELECT @RESULT_CODE AS RESULT_CODE



END

GO
