IF OBJECT_ID (N'dbo.SP_REPORT_CHOAN_COST_BY_MONTHLY', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_REPORT_CHOAN_COST_BY_MONTHLY
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

EXEC SP_REPORT_CHOAN_COST_BY_MONTHLY '2017-07-01'

*/

CREATE PROCEDURE [dbo].[SP_REPORT_CHOAN_COST_BY_MONTHLY]
		@P_START_DATE		AS VARCHAR(10)
AS
BEGIN



		SELECT	'ALBA' + CAST(A.CHOAN_ID AS VARCHAR(10))								AS AlbaID
		,	A.INVITATION_CNT															AS InvitationCnt
		,	A.THANKS_CNT																AS ThanksCnt
		,	0 																			AS DigitalCnt
		,	0 																			AS MapCnt
		,	A.TOTAL_CNT																	AS TotalCnt
		,	A.CHOAN_TOTAL_PRICE															AS ChoanTotalPrice
		,	0 																			AS MapTotalPrice
		,	A.ADD_TOTAL_PRICE															AS AddTotalPrice
		,	A.CHOAN_TOTAL_PRICE + A.ADD_TOTAL_PRICE										AS TotalPrice
		,	0 																			AS TroublePrice
		,	CAST(ROUND((A.CHOAN_TOTAL_PRICE + A.ADD_TOTAL_PRICE) * 0.967, -1) AS INT)	AS LastTotalPrice
	FROM	(
				SELECT	A.CHOAN_ID
					,	SUM(A.INVITATION_CNT) AS INVITATION_CNT
					,	SUM(A.THANKS_CNT) AS THANKS_CNT
					,	SUM(A.MAP_CNT) AS MAP_CNT
					,	SUM(A.INVITATION_CNT) + SUM(A.THANKS_CNT) AS TOTAL_CNT
					,	(SUM(A.INVITATION_CNT) * 1000) + (SUM(A.THANKS_CNT) * 500) AS CHOAN_TOTAL_PRICE
					,	SUM(A.MAP_CNT) * 200 AS MAP_TOTAL_PRICE
					,	CASE 
								WHEN SUM(A.INVITATION_CNT) + SUM(A.THANKS_CNT) >= 1500 THEN 200000
								WHEN SUM(A.INVITATION_CNT) + SUM(A.THANKS_CNT) < 1500 AND SUM(A.INVITATION_CNT) + SUM(A.THANKS_CNT) >= 1000 THEN 150000
								WHEN SUM(A.INVITATION_CNT) + SUM(A.THANKS_CNT) < 1000 AND SUM(A.INVITATION_CNT) + SUM(A.THANKS_CNT) >= 700 THEN 100000
								WHEN SUM(A.INVITATION_CNT) + SUM(A.THANKS_CNT) < 700 AND SUM(A.INVITATION_CNT) + SUM(A.THANKS_CNT) >= 500 THEN 50000
								ELSE 0 
						END AS ADD_TOTAL_PRICE
				FROM	(
							SELECT
									CASE WHEN A.ORDER_TYPE IN (1,3,4,5,6,7) THEN 1 ELSE 0 END AS INVITATION_CNT
								,	CASE WHEN A.ORDER_TYPE = 2 THEN 1 ELSE 0 END AS THANKS_CNT
								,	CASE WHEN A.ORDER_TYPE IN (1,3,4,5,6,7) AND ISNULL(B.WEDD_IDX, 0) = 0 THEN 1 ELSE 0 END AS MAP_CNT
								,	A.STATUS_SEQ
								,	A.SETTLE_STATUS
								,	A.SRC_CONFIRM_DATE
								,	A.SRC_COMPOSE_ADMIN_ID
								,	CAST(REPLACE(A.SRC_COMPOSE_ADMIN_ID, 'ALBA', '') AS INT) AS CHOAN_ID
							FROM	CUSTOM_ORDER A
							JOIN	CUSTOM_ORDER_WEDDINFO B ON A.ORDER_SEQ = B.ORDER_SEQ
							WHERE	SRC_CONFIRM_DATE >= @P_START_DATE + ' 00:00:00'
							AND		SRC_CONFIRM_DATE < DATEADD( MONTH, 1, @P_START_DATE + ' 00:00:00' )
							AND		A.SRC_COMPOSE_ADMIN_ID LIKE 'ALBA%'
							AND		A.SRC_COMPOSE_MOD_ADMIN_ID = A.SRC_COMPOSE_ADMIN_ID
							AND		STATUS_SEQ >= 9
							AND		SETTLE_STATUS = 2
						) A
				GROUP BY A.CHOAN_ID
			) A
	ORDER BY A.CHOAN_ID ASC



END
GO
