IF OBJECT_ID (N'dbo.SP_UPDATE_SMARTAD_AD_USEYORN', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_UPDATE_SMARTAD_AD_USEYORN
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

-- EXEC SP_UPDATE_SMARTAD_AD_USEYORN '1', 'N'

-- SELECT * FROM SmartAD_Partner_AD

*/

CREATE PROCEDURE [dbo].[SP_UPDATE_SMARTAD_AD_USEYORN]
		@P_CHECK_VALUE AS VARCHAR(100) = ''    -- I : 진행중, E :만료
		,@P_CHECK_TYPE AS CHAR(1)
		,@P_UPD_ID AS VARCHAR(50) = ''
AS
BEGIN

	SET NOCOUNT ON


	DECLARE @T_AD_SEQ TABLE ( AD_SEQ VARCHAR(20) )

	INSERT INTO @T_AD_SEQ (AD_SEQ)
	SELECT VALUE FROM dbo.[ufn_SplitTable] (@P_CHECK_VALUE, '|')
	
	--정보갱신
	UPDATE SmartAD_Partner_AD
	SET DISPLAY_YN = @P_CHECK_TYPE
	    ,UPD_ID = @P_UPD_ID
		,UPD_DATE = GETDATE()
	WHERE AD_SEQ IN (
						SELECT AD_SEQ FROM  @T_AD_SEQ 
					)
	

END


GO
