IF OBJECT_ID (N'dbo.SP_DELETE_S4_MD_CHOICE', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_DELETE_S4_MD_CHOICE
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_DELETE_S4_MD_CHOICE]
    @SEQS AS VARCHAR(4000)
AS
BEGIN

    DECLARE @T_SEQS TABLE
    (
		SEQ int
	)
	
	INSERT INTO @T_SEQS (SEQ)
    SELECT CAST(value AS INT) FROM dbo.[ufn_SplitTable] (@SEQS, '|')

    DELETE
    FROM    S4_MD_CHOICE
    WHERE   SEQ IN (SELECT SEQ FROM @T_SEQS)

END
GO
