IF OBJECT_ID (N'dbo.SP_SELECT_OUTSOURCING_SAMPLE_FOR_LIST_PREMIER', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_OUTSOURCING_SAMPLE_FOR_LIST_PREMIER
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
/*

EXEC SP_SELECT_OUTSOURCING_SAMPLE_FOR_LIST_PREMIER '', '1', '', '2016-05-01', '2016-05-30',''

*/

CREATE PROCEDURE [dbo].[SP_SELECT_OUTSOURCING_SAMPLE_FOR_LIST_PREMIER]
    @P_COMPANY_TYPE_CODE AS VARCHAR(200)
,   @P_SEARCH_TYPE_CODE AS VARCHAR(200)
,   @P_SEARCH_VALUE AS VARCHAR(200)
,   @P_START_DATE AS VARCHAR(20)
,   @P_END_DATE AS VARCHAR(20)
,   @P_EXCEL_ORDER_MST_SEQS AS VARCHAR(2000) = ''
AS
BEGIN

	declare @strOneMoreCardSeqs VARCHAR(4000)
	declare @strBeniCardSeqs VARCHAR(4000)
	declare @strCardSeqs VARCHAR(4000)

	DECLARE @GB VARCHAR(10) = 'PR'

	--SELECT @strOneMoreCardSeqs = RMRK_CLMN FROM COMMON_CODE
	--WHERE CMMN_CODE = @P_COMPANY_TYPE_CODE

	--SELECT @strBeniCardSeqs = RMRK_CLMN FROM COMMON_CODE
	--WHERE CMMN_CODE = @P_COMPANY_TYPE_CODE
	
	IF  @P_COMPANY_TYPE_CODE = '107010'  --원모어띵
		BEGIN
			SET @GB = @GB + '0'
		END
	ELSE IF @P_COMPANY_TYPE_CODE = '107011'   --제이플레져
		BEGIN
			SET @GB = @GB + '1'
		END
	ELSE IF @P_COMPANY_TYPE_CODE = '107013'   --페니클레
		BEGIN
			SET @GB = @GB + '2'
		END
	
	--SELECT * FROM COMMON_CODE WHERE CMMN_CODE = '107101'
	--SELECT * FROM S2_CARD WHERE CARD_SEQ IN ('35829','33921')
	

    SELECT  ROW_NUMBER() OVER(ORDER BY A.REQUEST_DATE ASC) AS ROW_NUM
		--,   A.* 
		, A.sample_order_seq
		, CASE WHEN A.STATUS_SEQ = 12 THEN '배송완료' ELSE '배송준비중' END AS STATUS_SEQ
		, A.MEMBER_ID
		, A.MEMBER_NAME
		, '1000' AS SETTLE_PRICE
		, B.CARD_SEQ
		, B.CARD_PRICE
		, A.REQUEST_DATE
    FROM    CUSTOM_SAMPLE_ORDER AS A
		LEFT OUTER JOIN CUSTOM_SAMPLE_ORDER_ITEM AS B
			ON A.sample_order_seq = B.SAMPLE_ORDER_SEQ
		INNER JOIN S2_CARD C
			ON B.CARD_SEQ = C.Card_Seq
    WHERE   1 = 1
    AND  A.REQUEST_DATE >= @P_START_DATE + ' 00:00:00'
    AND  A.REQUEST_DATE < CONVERT(VARCHAR(10), DATEADD(DAY, 1, CAST(@P_END_DATE AS DATETIME)), 120) + ' 00:00:00'
	AND  A.SALES_GUBUN IN ('SS','H')
	AND  A.STATUS_SEQ = 12
	AND  C.Card_Code LIKE @GB + '%'
		--B.CARD_SEQ IN ( SELECT * FROM [dbo].[ufn_SplitTable] (@strCardSeqs, '|') )
	AND ( 
			ISNULL(@P_EXCEL_ORDER_MST_SEQS, '') = '' OR  A.sample_order_seq IN ( SELECT * FROM [dbo].[ufn_SplitTable] (@P_EXCEL_ORDER_MST_SEQS, '|') )
		)
		 
    ORDER BY A.REQUEST_DATE DESC


END

GO
