IF OBJECT_ID (N'dbo.SP_UPDATE_S4_EVENT_INSTALL_FOR_REFERER', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_UPDATE_S4_EVENT_INSTALL_FOR_REFERER
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

*/

CREATE PROCEDURE [dbo].[SP_UPDATE_S4_EVENT_INSTALL_FOR_REFERER]
    @COMPANY_SEQ    AS INT
,   @UID            AS VARCHAR(50)
,   @REFERER_URL    AS VARCHAR(1000)

AS
BEGIN
    


    DECLARE @FAVORITE_INSTALL_YORN AS CHAR(1) = 'N'
    DECLARE @DESKTOP_INSTALL_YORN AS CHAR(1) = 'N'

    SELECT  @FAVORITE_INSTALL_YORN = ISNULL(FAVORITE_INSTALL, 'N')
        ,   @DESKTOP_INSTALL_YORN = ISNULL(DESKTOP_INSTALL , 'N')
    FROM    S4_EVENT_INSTALL 
    WHERE   COMPANY_SEQ = @COMPANY_SEQ 
    AND     UID = @UID

    IF @REFERER_URL = 'favorite' AND @FAVORITE_INSTALL_YORN = 'Y'
    BEGIN
        
        UPDATE  S4_EVENT_INSTALL 
        SET     FAVORITE_CNT = FAVORITE_CNT + 1 
        WHERE   COMPANY_SEQ = @COMPANY_SEQ
        AND     UID = @UID

    END

    IF @REFERER_URL = 'shortcut' AND @DESKTOP_INSTALL_YORN = 'Y'
    BEGIN
        
        UPDATE  S4_EVENT_INSTALL 
        SET     DESKTOP_CNT = DESKTOP_CNT + 1 
        WHERE   COMPANY_SEQ = @COMPANY_SEQ
        AND     UID = @UID

    END



END
GO
