IF OBJECT_ID (N'dbo.SP_INSERT_TNEO_QUEUE_v2', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_INSERT_TNEO_QUEUE_v2
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
  
/*  
  
EXEC SP_INSERT_MAIL_MST '차호용', 'sharniel@naver.com'  
  
*/  
  
CREATE PROCEDURE [dbo].[SP_INSERT_TNEO_QUEUE_v2]  
 @P_MAIL_TYPE AS VARCHAR(50)  
, @P_SITE_NAME AS VARCHAR(50)  
,   @P_FROM_EMAIL AS VARCHAR(100)  
,   @P_TO_NAME AS VARCHAR(100)  
,   @P_TO_EMAIL AS VARCHAR(100)  
,   @P_MAIL_TITLE AS VARCHAR(200)  
,   @P_MAIL_FROM AS VARCHAR(MAX)  
,   @P_USER_ID AS VARCHAR(50)  
  
AS  
BEGIN  
  
 IF @P_USER_ID <> ''  
 BEGIN  
   
  SELECT @P_TO_NAME = UNAME  
   , @P_TO_EMAIL = UMAIL  
  FROM VW_USER_INFO  
  WHERE 1 = 1  
  AND  UID = @P_USER_ID  
  
 END   


 DECLARE @SMS_PHONE     AS VARCHAR(20)
 DECLARE @SMS_MSG       AS VARCHAR(200)
 DECLARE @EMAIL         AS VARCHAR(100)
 DECLARE @EMAIL_SENDER  AS VARCHAR(50)
 DECLARE @EMAIL_TITLE   AS VARCHAR(50)
 DECLARE @EMAIL_MSG     AS VARCHAR(8000)
    
 DECLARE @SMS_NEW_MSG  AS VARCHAR(200)
 DECLARE @RECEIVE_EMAIL AS VARCHAR(200)
    
 SELECT TOP 1  @SMS_PHONE = SMS_PHONE    
            ,   @SMS_MSG = SMS_MSG    
            ,   @EMAIL_SENDER = EMAIL_SENDER    
            ,   @EMAIL = EMAIL    
            ,   @EMAIL_TITLE = EMAIL_TITLE    
            ,   @EMAIL_MSG = EMAIL_MSG     
 FROM    WEDD_MAIL     
 --WHERE id = '112'
 WHERE   SALES_GUBUN = @P_SITE_NAME     
 AND     DIV = '회원가입'
 AND     USE_YORN = 'Y'    
    
 SET @EMAIL_MSG = REPLACE(@EMAIL_MSG, ':::uid:::', @P_USER_ID)    
 SET @EMAIL_MSG = REPLACE(@EMAIL_MSG, ':::uname:::', @P_TO_NAME)    

  
  
  /*
	2022-07-29 김광호 TNEO_QUEUE 삽입 중지
	 IF NOT EXISTS(SELECT * FROM TNEO_QUEUE WHERE BARID = @P_MAIL_TYPE AND RMAIL = @P_TO_EMAIL AND MTITLE = @P_MAIL_TITLE)  
	 BEGIN  
  
	  INSERT INTO TNEO_QUEUE (BARID, SNAME, SMAIL, RNAME, RMAIL, MTITLE, MCONTENT, MDATE, C_SITE, C_CATEGORY, CARDNO, ORG_DATE)   
	  SELECT    
		@P_MAIL_TYPE  
	   ,   @EMAIL_SENDER  
	   ,   @P_FROM_EMAIL  
	   ,   @P_TO_NAME  
	   ,   @P_TO_EMAIL  
	   ,   @P_MAIL_TITLE  
	   ,   @EMAIL_MSG  
	   ,   GETDATE()  
	   ,   'M'  
	   ,   'A'  
	   ,   'WEDD'  
	   ,   GETDATE()  
  
	 END  
  */
END
GO
