IF OBJECT_ID (N'dbo.SP_SELECT_MAIN_POPUP_YN', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_MAIN_POPUP_YN
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_SELECT_MAIN_POPUP_YN]
/***********************************************
구매후기 팝업창 노출 조건
조건 1 : 청첩장 구매한 고객
조건 2 : 구매후기 작성하지 않은 고객

노출 기준
기준 1 : 청첩장 주문일 기준 7일 뒤 노출
기준 2 : 바른손몰 메인에서만 노출


샘플후기 팝업창 노출 조건 
조건 1 : 샘플 구매한 고객
조건 2 : 샘플후기 작성하지 않은 고객

노출 기준
기준 1 : 샘플 주문일 기준 3일 뒤 노출
기준 2 : 바른손몰 메인에서만 노출
************************************************/
	@UID VARCHAR(50),
	@COMPANY_SEQ INT = 0
AS
BEGIN

	SET NOCOUNT ON

	IF @UID is null or @UID = '' 
	  BEGIN
		SELECT SAMPLEPOPUPYN = 0 , REVIEWPOPUPYN = 0
	  END
	ELSE
	  BEGIN
		DECLARE @SAMPLEPOPUPYN int
		DECLARE @REVIEWPOPUPYN int

		-- 샘플후기 

		SELECT @SAMPLEPOPUPYN = COUNT(1) --SETTLE_DATE--, CONVERT(VARCHAR(10),  DATEADD(DAY, 7, SETTLE_DATE), 120), CONVERT(VARCHAR(10),  GETDATE(), 120) 
		FROM (
				SELECT  REQUEST_DATE = MAX(REQUEST_DATE) FROM CUSTOM_SAMPLE_ORDER 
				WHERE	COMPANY_SEQ = @COMPANY_SEQ AND
						MEMBER_ID=  @UID AND 
						(STATUS_SEQ = 4 OR STATUS_SEQ = 12 )AND  
						MEMBER_ID NOT IN (SELECT CONVERT(VARCHAR(50), ER_USERID) [UID] FROM S4_EVENT_REVIEW  WHERE ER_USERID = @UID) --결재완료
			 ) TB 
		WHERE CONVERT(VARCHAR(10), GETDATE(), 120) >= CONVERT(VARCHAR(10), DATEADD(DAY, 3, TB.REQUEST_DATE), 120)

		-- 구매후기 
		SELECT  @REVIEWPOPUPYN = COUNT(1)  --ORDER_DATE--, CONVERT(VARCHAR(10),  DATEADD(DAY, 7, ORDER_DATE), 120)--, CONVERT(VARCHAR(10),  GETDATE(), 120) 
		FROM (
				SELECT  ORDER_DATE = MAX(ORDER_DATE) FROM CUSTOM_ORDER 
				WHERE	COMPANY_SEQ = @COMPANY_SEQ AND
						MEMBER_ID=  @UID AND 
						SETTLE_STATUS = 2  AND 
						MEMBER_ID NOT IN (SELECT UID FROM S2_USERCOMMENT  WHERE  UID = @UID) --  결재완료
			 ) TB 
		WHERE CONVERT(VARCHAR(10), GETDATE(), 120)  >=  CONVERT(VARCHAR(10),  DATEADD(DAY, 7, TB.ORDER_DATE), 120)

		IF @UID = 'S4GUEST' BEGIN 
	
			SELECT SAMPLEPOPUPYN = @SAMPLEPOPUPYN , REVIEWPOPUPYN = @REVIEWPOPUPYN
	
		END ELSE BEGIN 
	
			SELECT SAMPLEPOPUPYN = @SAMPLEPOPUPYN , REVIEWPOPUPYN = @REVIEWPOPUPYN

		END 
	  END
	
END

GO
