IF OBJECT_ID (N'dbo.SP_SELECT_PARTS_WITH_ERP_STOCK', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_PARTS_WITH_ERP_STOCK
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

EXEC SP_SELECT_CARD_PART 'B01','', 50, 1, 'REG_DATE', 'DESC'
EXEC SP_SELECT_PARTS_WITH_ERP_STOCK 'B01','', 200, 1, 'REG_DATE', 'DESC', '정상판매|단종예정|발주대기|폐기대상|폐기|공백', '', ''
EXEC SP_SELECT_PARTS_WITH_ERP_STOCK 'B01','', 200, 1, 'REG_DATE', 'DESC', '폐기대상|폐기', '', ''
EXEC SP_SELECT_PARTS_WITH_ERP_STOCK 'B01','', 100, 1, 'REG_DATE', 'DESC', '', '', ''
*/

CREATE PROCEDURE [dbo].[SP_SELECT_PARTS_WITH_ERP_STOCK]
		@P_CARD_DIV AS VARCHAR(50)
	,	@P_CARD_CODE_OR_CARD_NAME AS VARCHAR(50)
	,	@P_PAGE_SIZE AS INT
	,	@P_PAGE_NUMBER AS INT
	,	@P_ORDER_BY_NAME AS VARCHAR(50)
	,	@P_ORDER_BY_TYPE AS VARCHAR(10)
    ,	@P_PRODUCTION_STATUS_NAME AS VARCHAR(200)
	,	@P_SITE_SEARCH_VALUE AS VARCHAR(100)
	,	@P_SALES_TYPE AS VARCHAR(10)


AS
BEGIN

	SET NOCOUNT ON
	
    DECLARE @T_PRODUCTION_STATUS_NAME TABLE ( PRODUCTION_STATUS_NAME VARCHAR(20) )
	DECLARE @T_SITE_SEARCH_VALUE TABLE ( COMPANY_SEQ INT )

	DECLARE @T_PRODUCTION_STATUS_NAME_COUNT AS INT
	DECLARE @T_SITE_SEARCH_VALUE_COUNT AS INT



	INSERT INTO @T_PRODUCTION_STATUS_NAME (PRODUCTION_STATUS_NAME)
	SELECT CAST(VALUE AS VARCHAR(20)) FROM dbo.[ufn_SplitTable] (@P_PRODUCTION_STATUS_NAME, '|')

	INSERT INTO @T_SITE_SEARCH_VALUE (COMPANY_SEQ)
	SELECT CAST(VALUE AS INT) FROM dbo.[ufn_SplitTable] (@P_SITE_SEARCH_VALUE, '|')

	-- 공백을 '' 으로 치환
	UPDATE	@T_PRODUCTION_STATUS_NAME
	SET		PRODUCTION_STATUS_NAME = ''
	WHERE	PRODUCTION_STATUS_NAME = '공백'


	SET @T_PRODUCTION_STATUS_NAME_COUNT = ISNULL((SELECT COUNT(*) FROM @T_PRODUCTION_STATUS_NAME), 0)
	SET @T_PRODUCTION_STATUS_NAME_COUNT = CASE WHEN @T_PRODUCTION_STATUS_NAME_COUNT = 0 THEN 10 ELSE @T_PRODUCTION_STATUS_NAME_COUNT END
    SET @T_SITE_SEARCH_VALUE_COUNT = ISNULL((SELECT COUNT(*) FROM @T_SITE_SEARCH_VALUE), 0)
	SET @T_SITE_SEARCH_VALUE_COUNT = CASE WHEN @T_SITE_SEARCH_VALUE_COUNT = 0 THEN 10 ELSE @T_SITE_SEARCH_VALUE_COUNT END

    --select * from @T_PRODUCTION_STATUS_NAME


	SELECT	*
	FROM	(
				SELECT	ROW_NUMBER() OVER	(
												ORDER BY 
													CASE WHEN @P_ORDER_BY_NAME = 'REG_DATE'					THEN C.REG_DATE						ELSE 0 END ASC
												,	C.CARD_SEQ ASC
													
											) AS ROW_NUM
					,	ROW_NUMBER() OVER	(
												ORDER BY 
													CASE WHEN @P_ORDER_BY_NAME = 'REG_DATE'					THEN C.REG_DATE						ELSE 0 END DESC
												,	C.CARD_SEQ DESC
													
											) AS ROW_NUM_DESC
					,	*
				FROM	(
							SELECT	DISTINCT 
									SC.CARD_SEQ
								,	SC.CARD_CODE
								,	SC.Card_ERPCode AS CARD_ERP_CODE	
								,	SC.CARD_NAME
								,	SC.CARDSET_PRICE AS CARD_SET_PRICE
								,	SC.CARD_PRICE
								,	CASE WHEN ISNULL(SC.CARD_IMAGE, '') = '' THEN '' ELSE 'HTTP://FILE.BARUNSONCARD.COM/COMMON_IMG/' + SC.CARD_IMAGE END AS CARD_IMAGE_FULL_URL
								,	SC.REGDATE AS REG_DATE
								,	ISNULL(SC.CARDFACTORY_PRICE,0) AS CARDFACTORY_PRICE
								,	ISNULL(SCES.PRODUCTION_STATUS_NAME							, '') AS ERP_PRODUCTION_STATUS_NAME	
                                ,   ISNULL(SCES.CARD_TYPE_NAME,'') AS CARD_TYPE_NAME	
								,	ISNULL((1 + SCSS_BARUNSONCARD.ISDISPLAY		), 0) AS DISPLAY_BARUNSONCARD
								,	ISNULL((1 + SCSS_BHANDSCARD.ISDISPLAY		), 0) AS DISPLAY_BHANDSCARD
								,	ISNULL((1 + SCSS_THECARD.ISDISPLAY			), 0) AS DISPLAY_THECARD 
								,	ISNULL((1 + SCSS_PREMIERPAPER.ISDISPLAY		), 0) AS DISPLAY_PREMIERPAPER
								,	ISNULL((1 + SCSS_BARUNSONMALL.ISDISPLAY		), 0) AS DISPLAY_BARUNSONMALL
								,	ISNULL((1 + SCSS_OUTBOUND.ISDISPLAY			), 0) AS DISPLAY_OUTBOUND
								,	SC.CARD_DIV
								,	(SELECT code_value FROM MANAGE_CODE WHERE code_type = 'card_div' AND code = SC.CARD_DIV) AS CARD_TYPE
								,	ISNULL((SELECT code_value FROM MANAGE_CODE WHERE code_type = 'cardbrand' AND code = SC.CardBrand),'') AS CARD_BRAND
								
								,	ISNULL(SC.CARD_HSIZE, 0) AS CARD_HSIZE
								,	ISNULL(SC.CARD_WSIZE, 0) AS CARD_WSIZE
								,	CASE WHEN ISNULL(CD.ENVCHARGE, '0') = '1' THEN 'Y' ELSE 'N' END AS ENVCHARGE
								
								,	ISNULL(CD.CARD_TEXT_PREMIER, '') AS CARD_TEXT_PREMIER
								,	ISNULL(SC.FPRINT_YORN, 'N') AS FPRINT_YORNFPRINT_YORN
								
							FROM	S2_CARD SC
							LEFT JOIN S2_CARDDETAIL AS CD ON SC.CARD_SEQ = CD.CARD_SEQ
   							LEFT JOIN	S2_CARD_ERP_STOCK SCES ON SC.CARD_CODE = SCES.CARD_CODE AND SC.CARD_ERPCODE = SCES.CARD_CODE_ERP
							--JOIN	S2_CARDKIND SCK ON SC.CARD_SEQ = SCK.CARD_SEQ
							LEFT JOIN	S2_CARDSALESSITE SCSS_BARUNSONCARD	ON SC.CARD_SEQ = SCSS_BARUNSONCARD.CARD_SEQ		AND SCSS_BARUNSONCARD.COMPANY_SEQ = 5001
							LEFT JOIN	S2_CARDSALESSITE SCSS_PREMIERPAPER	ON SC.CARD_SEQ = SCSS_PREMIERPAPER.CARD_SEQ		AND SCSS_PREMIERPAPER.COMPANY_SEQ = 5003
							LEFT JOIN	S2_CARDSALESSITE SCSS_BHANDSCARD	ON SC.CARD_SEQ = SCSS_BHANDSCARD.CARD_SEQ		AND SCSS_BHANDSCARD.COMPANY_SEQ = 5006
							LEFT JOIN	S2_CARDSALESSITE SCSS_THECARD		ON SC.CARD_SEQ = SCSS_THECARD.CARD_SEQ			AND SCSS_THECARD.COMPANY_SEQ = 5007
							LEFT JOIN	S2_CARDSALESSITE SCSS_BARUNSONMALL  ON SC.CARD_SEQ = SCSS_BARUNSONMALL.CARD_SEQ		AND SCSS_BARUNSONMALL.COMPANY_SEQ = 5000
							LEFT JOIN	S2_CARDSALESSITE SCSS_OUTBOUND		ON SC.CARD_SEQ = SCSS_OUTBOUND.CARD_SEQ			AND SCSS_OUTBOUND.COMPANY_SEQ = 5008

							WHERE	1 = 1
							--AND		SC.CARD_GROUP IN ( 'I' )
                            AND     SC.DISPLAY_YORN = 'Y'
							AND		SC.CardBrand <> 'X'
							AND		(
										    CASE WHEN @P_CARD_DIV = 'C05' THEN  SC.Card_Div else '' end  IN (SELECT value from dbo.FN_SPLIT('C05,C07', ','))
										OR	CASE WHEN @P_CARD_DIV = 'C06' THEN  SC.Card_Div else '' end  IN (SELECT value from dbo.FN_SPLIT('C01,C02,C06,C09,C10,C11', ',') )
										OR  SC.Card_Div IN (@P_CARD_DIV)
									)

							AND		(
											CASE WHEN ISNULL(@P_CARD_CODE_OR_CARD_NAME, '') = '' THEN '' ELSE SC.CARD_DIV END  NOT IN ('A01','A03')  AND SC.CARD_CODE LIKE '%' + @P_CARD_CODE_OR_CARD_NAME + '%'
										OR	CASE WHEN ISNULL(@P_CARD_CODE_OR_CARD_NAME, '') = '' THEN '' ELSE SC.CARD_NAME END LIKE '%' + @P_CARD_CODE_OR_CARD_NAME + '%'
									)
                            AND     (
                                            @P_PRODUCTION_STATUS_NAME = ''
                                        OR  ( 
                                                SCES.PRODUCTION_STATUS_NAME IN (SELECT PRODUCTION_STATUS_NAME FROM @T_PRODUCTION_STATUS_NAME)
                                                OR CASE WHEN @P_PRODUCTION_STATUS_NAME = '정상판매|단종예정|발주대기|폐기대상|폐기|공백' THEN  SCES.PRODUCTION_STATUS_NAME
                                                        WHEN @P_PRODUCTION_STATUS_NAME = '공백' THEN  SCES.PRODUCTION_STATUS_NAME 
                                                        ELSE '' 
                                                   END IS NULL
                                            )      
                                     --   OR  SCES.PRODUCTION_STATUS_NAME is null
                                    )
                            --봉투, 봉투라이닝 
							AND		(
										(
												@T_SITE_SEARCH_VALUE_COUNT < 6
											AND	(
														(SCSS_BARUNSONCARD.COMPANY_SEQ IN (SELECT COMPANY_SEQ FROM @T_SITE_SEARCH_VALUE)	AND CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_BARUNSONCARD.ISJUMUN END = @P_SALES_TYPE)
													OR	(SCSS_PREMIERPAPER.COMPANY_SEQ IN (SELECT COMPANY_SEQ FROM @T_SITE_SEARCH_VALUE)	AND CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_PREMIERPAPER.ISJUMUN END = @P_SALES_TYPE)
													OR	(SCSS_BHANDSCARD.COMPANY_SEQ IN (SELECT COMPANY_SEQ FROM @T_SITE_SEARCH_VALUE)		AND CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_BHANDSCARD.ISJUMUN END = @P_SALES_TYPE)
													OR	(SCSS_THECARD.COMPANY_SEQ IN (SELECT COMPANY_SEQ FROM @T_SITE_SEARCH_VALUE)			AND CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_THECARD.ISJUMUN END = @P_SALES_TYPE)
													OR	(SCSS_BARUNSONMALL.COMPANY_SEQ IN (SELECT COMPANY_SEQ FROM @T_SITE_SEARCH_VALUE)	AND CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_BARUNSONMALL.ISJUMUN END = @P_SALES_TYPE)
												)
										)
										OR
										(
												@T_SITE_SEARCH_VALUE_COUNT >= 6
											AND (
														CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_BARUNSONCARD.ISJUMUN END = @P_SALES_TYPE
													OR  CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_PREMIERPAPER.ISJUMUN END = @P_SALES_TYPE
													OR  CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_BHANDSCARD.ISJUMUN END = @P_SALES_TYPE
													OR  CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_THECARD.ISJUMUN END = @P_SALES_TYPE
													OR  CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_OUTBOUND.ISJUMUN END = @P_SALES_TYPE
													OR  CASE WHEN @P_SALES_TYPE = '' THEN '' ELSE SCSS_BARUNSONMALL.ISJUMUN END = @P_SALES_TYPE
												)
										)
									)
						) C

			) A

	WHERE	1 = 1
	AND		CASE WHEN @P_ORDER_BY_TYPE = 'ASC' THEN A.ROW_NUM ELSE A.ROW_NUM_DESC END > (@P_PAGE_NUMBER - 1) * @P_PAGE_SIZE
	AND		CASE WHEN @P_ORDER_BY_TYPE = 'ASC' THEN A.ROW_NUM ELSE A.ROW_NUM_DESC END <= @P_PAGE_NUMBER * @P_PAGE_SIZE
		
	ORDER BY 
		CASE WHEN @P_ORDER_BY_TYPE = 'ASC' THEN A.ROW_NUM ELSE A.ROW_NUM_DESC END ASC
	
END


GO
