IF OBJECT_ID (N'dbo.SP_HELPCOLUMNNAMEWITHCOMMA', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_HELPCOLUMNNAMEWITHCOMMA
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_HELPCOLUMNNAMEWITHCOMMA]
       @TABLENAME VARCHAR(1024)
AS
BEGIN
       DECLARE @TMP TABLE (ISEQ INT IDENTITY(1, 1), COLUMN_NAME VARCHAR(1024));
       DECLARE @IMAX INT, @IMIN INT, @RESULT VARCHAR(2048);
 
       INSERT INTO @TMP (COLUMN_NAME)
       SELECT COLUMN_NAME
       FROM INFORMATION_SCHEMA.COLUMNS
       WHERE TABLE_NAME = @TABLENAME
       ORDER BY ORDINAL_POSITION;
 
       SELECT @IMAX = MAX(ISEQ), @IMIN = MIN(ISEQ) FROM @TMP;
 
       SELECT @RESULT = COLUMN_NAME FROM @TMP WHERE ISEQ = @IMIN;
 
       SET @IMIN = @IMIN + 1;
 
       WHILE @IMAX >= @IMIN
       BEGIN
             SELECT @RESULT = @RESULT + ', ' + COLUMN_NAME
             FROM @TMP
             WHERE ISEQ = @IMIN;
 
             SET @IMIN = @IMIN + 1;
       END
 
       SELECT @RESULT;
END;
GO
