IF OBJECT_ID (N'dbo.SP_SELECT_BARUNSONCARD_USERCOMMENTINFO', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_BARUNSONCARD_USERCOMMENTINFO
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--exec SP_SELECT_BARUNSONCARD_USERCOMMENTINFO 5001,''    
CREATE PROCEDURE [dbo].[SP_SELECT_BARUNSONCARD_USERCOMMENTINFO]    
      @COMPANY_SEQ INT  
    , @CARD_SEQ INT    
AS    
BEGIN       

    SELECT
            A.TOTAL AS Total
        ,   A.SCORE AS Score
        ,   CASE WHEN A.TOTAL > 0 THEN A.SCORE / A.TOTAL ELSE 0 END AvgScore
    FROM
    (
        SELECT 
                COUNT(*) AS TOTAL
                , ISNULL( SUM(SUC.SCORE), 0) AS SCORE
        FROM    S2_USERCOMMENT SUC
        WHERE   1 = 1
        AND     SUC.COMPANY_SEQ = @COMPANY_SEQ
        AND     SUC.CARD_SEQ = @CARD_SEQ          
    ) A

END      
GO
