IF OBJECT_ID (N'dbo.SP_EVENT_WEDDINGCAFE_COUPON', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_EVENT_WEDDINGCAFE_COUPON
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
	CREATE DATE	:	2021-11-02
	DESCRIPTION	:	이벤트 웨딩까페 샘플 후기 쿠폰 발급
					기간 20220314 ~ 20220429
	EXEC SP_EVENT_WEDDINGCAFE_COUPON 'S4GUEST';
	BSLECELLE5000 2021 르셀르 웨딩카페쿠폰
	BSDESKER5000 데스커까페쿠폰
	WEDDCAFE5000 웨딩까페쿠폰


*/
CREATE PROCEDURE [dbo].[SP_EVENT_WEDDINGCAFE_COUPON]
		@UID	AS VARCHAR(100)
AS
BEGIN
	
    SET NOCOUNT ON;

	DECLARE	@EVTCNT AS INT = 0	
	DECLARE @COUPONCNT AS INT = 0		

	-- 쿠폰 발급여부 확인 (WEDDCAFE5000)
	SELECT @COUPONCNT = COUNT(*) FROM S4_MYCOUPON WHERE UID = @UID AND COUPON_CODE ='WEDDCAFE5000'

	IF @COUPONCNT = 0 BEGIN
			
			SELECT @EVTCNT = COUNT(*) FROM S4_EVENT_REVIEW WHERE ER_REVIEW_URL LIKE '%CAFE%' AND ER_USERID = @UID AND  ER_REGDATE >= CONVERT(VARCHAR, GETDATE(), 120) AND ER_REGDATE < CONVERT(VARCHAR, GETDATE()+1, 120)

			IF @EVTCNT > 0  BEGIN
				INSERT INTO S4_MYCOUPON (COUPON_CODE, UID, COMPANY_SEQ , ISMYYN, END_DATE, REG_DATE) VALUES ('WEDDCAFE5000', @UID, 5006 , 'Y','2022-12-31' , GETDATE())
				--INSERT INTO S4_MYCOUPON (COUPON_CODE, UID, COMPANY_SEQ , ISMYYN, END_DATE, REG_DATE) VALUES ('WEDDCAFE5000', @UID, 5006 , 'Y','2022-05-31' , GETDATE())
			END					
		END

END


GO
