IF OBJECT_ID (N'dbo.SP_MD_GIFT_EVENT_CHANEL_ISSUE_CHECK', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_MD_GIFT_EVENT_CHANEL_ISSUE_CHECK
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		황새롬
-- Create date: 2017-09-29
-- Description:	바/비/더 사은품 or 쿠폰 이벤트 (옥승D)
/*

EXEC SP_MD_GIFT_EVENT_CHANEL_ISSUE_CHECK 2542561, 'arar000'

EXEC SP_MD_GIFT_EVENT_CHANEL_ISSUE_CHECK 2542099, 's4guest' 

SELECT * FROM MD_GIFT_EVENT_CHANEL

SELECT * FROM CUSTOM_ORDER_ITEM WHERE ORDER_SEQ = 2542396
SELECT settle_status, * FROM CUSTOM_ORDER WHERE ORDER_SEQ = 2542396

*/
-- =============================================

CREATE PROCEDURE [dbo].[SP_MD_GIFT_EVENT_CHANEL_ISSUE_CHECK]
	@ORDER_SEQ							AS INT
,	@UID								AS VARCHAR(50)
AS
BEGIN
	
    SET NOCOUNT ON;

	/* 사은품 아이템 삭제 */
	IF EXISTS	(
					SELECT	*
					FROM	CUSTOM_ORDER_ITEM
					WHERE	1 = 1
					AND		ORDER_SEQ = @ORDER_SEQ
					AND		CARD_SEQ IN (36432,36433,36434,36435,36440,36441)
				)
		BEGIN

			/* 아이템 수량 증가 */
			UPDATE	MD_GIFT_EVENT_CHANEL
			SET		REMAIN_CNT = REMAIN_CNT + 1
			WHERE	CARD_SEQ IN (SELECT CARD_SEQ FROM CUSTOM_ORDER_ITEM WHERE ORDER_SEQ = @ORDER_SEQ AND CARD_SEQ IN (36432,36433,36434,36435,36440,36441))

			/* 아이템 삭제 */
			DELETE CUSTOM_ORDER_ITEM WHERE ORDER_SEQ = @ORDER_SEQ AND CARD_SEQ IN (36432,36433,36434,36435,36440,36441)

		END

	/* 쿠폰 삭제 */
	IF EXISTS	(
					SELECT	*
					FROM	COUPON_ISSUE
					WHERE	UID = @UID
					AND		COUPON_DETAIL_SEQ = 40857
				)
		BEGIN
			
			DELETE COUPON_ISSUE WHERE UID = @UID AND COUPON_DETAIL_SEQ = 40857

		END

	/* 결제 완료건 중에 사은품 또는 쿠폰 받은 내역이 있는지 체크 */
	DECLARE @GIFT_ISSUE_YORN AS VARCHAR(1)
	SET @GIFT_ISSUE_YORN = ISNULL
							(	
								(
									SELECT	MAX(YORN)
									FROM	(
												SELECT	'Y' YORN
												FROM	CUSTOM_ORDER CO
												JOIN	CUSTOM_ORDER_ITEM COI ON CO.ORDER_SEQ = COI.ORDER_SEQ
												WHERE	1 = 1
												AND		CO.SETTLE_STATUS = 2
												AND		CO.UP_ORDER_SEQ IS NULL
												AND		CO.MEMBER_ID = @UID
												AND		COI.CARD_SEQ IN (36432,36433,36434,36435,36440,36441)
					
												UNION ALL
					
												SELECT	'Y'
												FROM	COUPON_ISSUE
												WHERE	UID = @UID
												AND		COUPON_DETAIL_SEQ = 40857
											) A
								)
							, 'N')
	
	/* 청첩장만 오픈 */
	IF EXISTS	(
					SELECT	*
					FROM	CUSTOM_ORDER
					WHERE	1 = 1
					AND		ORDER_SEQ = @ORDER_SEQ
					AND		ORDER_TYPE IN (1,6,7)
					AND		UP_ORDER_SEQ IS NULL
					AND		@GIFT_ISSUE_YORN = 'N'
				)
		BEGIN
			
			SET @GIFT_ISSUE_YORN = 'N'

		END
	ELSE
		BEGIN
			
			SET @GIFT_ISSUE_YORN = 'Y'

		END

	IF CONVERT(VARCHAR(10), GETDATE(), 112) > '20171031'
	BEGIN	
		SET @GIFT_ISSUE_YORN = 'Y'
	END

	/* 사은품 및 쿠폰 받았는지 여부 */
	SELECT	@GIFT_ISSUE_YORN AS GIFT_ISSUE_YORN
		,	(SELECT REMAIN_CNT FROM MD_GIFT_EVENT_CHANEL WHERE CARD_CODE = 'CECE16004') AS CECE_CNT
		,	(SELECT REMAIN_CNT FROM MD_GIFT_EVENT_CHANEL WHERE CARD_CODE = 'CEJA16002') AS CEJA_CNT
		,	(SELECT REMAIN_CNT FROM MD_GIFT_EVENT_CHANEL WHERE CARD_CODE = 'CEKI16001') AS CEKI_CNT
		,	(SELECT REMAIN_CNT FROM MD_GIFT_EVENT_CHANEL WHERE CARD_CODE = 'CEWA15006') AS CEWA_CNT
		,	(SELECT REMAIN_CNT FROM MD_GIFT_EVENT_CHANEL WHERE CARD_CODE = 'VB002') AS VB002_CNT
		,	(SELECT REMAIN_CNT FROM MD_GIFT_EVENT_CHANEL WHERE CARD_CODE = 'PHOTOCARD_FRAME') AS FRAME_CNT			

END
GO
