IF OBJECT_ID (N'dbo.WSP_S_REVIEW_EVENT_LIST', N'P') IS NOT NULL DROP PROCEDURE dbo.WSP_S_REVIEW_EVENT_LIST
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*=============================================  
작성자   : 표수현  
작성일   : 2020-11-11  
INPUT PARAMETER  :  
OUTPUT PARAMETER :  
TABLE   :  
DESCRIPTION  : 특정회원의 샘플주문리스트 조회 및 특정 회원의 샘플후기 리스트 조회( 바른손몰, 프페제휴 포함 )  
SPECIAL LOGIC  :  
EXEC WSP_S_REVIEW_EVENT_LIST @구분 = '1' , @ER_USERID = 's4guest'  
EXEC WSP_S_REVIEW_EVENT_LIST @구분 = '2' , @ER_USERID = 's4guest'  
=================================================*/  
CREATE PROCEDURE [dbo].[WSP_S_REVIEW_EVENT_LIST]  
 @구분 CHAR(1) = NULL,  
 @ER_USERID VARCHAR(40) = NULL,  
 @ER_TYPE INT = 0,
 @COMPANY_SEQ INT = 0  
AS  
 BEGIN  
   
 SET NOCOUNT ON  
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED  
    
 IF @구분 = '1' BEGIN -- 특정회원의 샘플주문리스트 조회  
  
   SELECT DISTINCT   
    ORDER_SEQ = A.SAMPLE_ORDER_SEQ ,  
    ORDER_DATE = REQUEST_DATE,  
    STATUS_SEQ,  
    SETTLE_PRICE,  
    SETTLE_METHOD,PG_TID,   
    DACOM_TID,   
    PG_SHOPID = PG_MERTID,  
    PG_RESULTINFO,  
    PG_RESULTINFO2,  
    SETTLE_DATE,  
    DELIVERY_DATE,  
    DELIVERY_COM,  
    DELIVERY_CODE = DELIVERY_CODE_NUM    
  FROM CUSTOM_SAMPLE_ORDER A WITH(NOLOCK) LEFT OUTER JOIN   
    CUSTOM_SAMPLE_ORDER_ITEM B WITH(NOLOCK) ON A.SAMPLE_ORDER_SEQ = B.SAMPLE_ORDER_SEQ LEFT OUTER JOIN   
    S2_CARD C WITH(NOLOCK) ON C.CARD_SEQ = B.CARD_SEQ   
  WHERE MEMBER_ID = @ER_USERID AND   
   STATUS_SEQ = 12 AND   
   COMPANY_SEQ = @COMPANY_SEQ
  
 END ELSE BEGIN   
    
  SELECT  ER_IDX,   
    ER_COMPANY_SEQ,   
    ER_ORDER_SEQ,   
    ER_TYPE,   
    ER_USERID,   
    ER_REGDATE,  
    ER_RECOM_CNT,  
    ER_REVIEW_TITLE = ISNULL(ER_REVIEW_TITLE, ''''),   
    ER_REVIEW_URL = ISNULL(ER_REVIEW_URL, ''''),   
    ER_REVIEW_STAR,   
    ER_STATUS,   
    ER_VIEW,   
    ER_REVIEW_CONTENT,   
    ER_USERNAME,   
    ERA_STATUS,   
    ERA_COUPON_STATUS,   
    ERA_COMMENT = ISNULL(ERA_COMMENT,''''),   
    ERA_COMMENT_CANCEL = ERA_COUPON_CODE, ISNULL(ERA_COMMENT_CANCEL,''''),   
    ER_REVIEW_URL_A = ISNULL(ER_REVIEW_URL_A, ''''),   
    ER_REVIEW_URL_B = ISNULL(ER_REVIEW_URL_B, ''''),   
    ER_REVIEW_URL2 = ISNULL(ER_REVIEW_URL2, ''''),  
    ER_COMMENT = ISNULL(ER_COMMENT,ER_REVIEW_URL),  
    DEVICE_TYPE,  
    ER_ISPHOTO,  
    ER_CARD_SEQ = CASE WHEN ISNULL(ER_CARD_SEQ,0) = 0   
          THEN (   
            SELECT TOP 1 A.CARD_SEQ FROM CUSTOM_SAMPLE_ORDER_ITEM A LEFT OUTER JOIN S2_CARD B ON A.CARD_SEQ = B.CARD_SEQ    
            WHERE A.SAMPLE_ORDER_SEQ=  ER_ORDER_SEQ     
           )   
          ELSE ER_CARD_SEQ   
          END,   
    ER_CARD_CODE = CASE WHEN ER_CARD_CODE = '0000'  
         THEN  (   
           SELECT TOP 1 B.CARD_CODE FROM CUSTOM_SAMPLE_ORDER_ITEM A LEFT OUTER JOIN S2_CARD B ON A.CARD_SEQ = B.CARD_SEQ    
           WHERE A.SAMPLE_ORDER_SEQ=  ER_ORDER_SEQ     
           )    
         ELSE ER_CARD_CODE   
         END ,   
    ER_CARDIMAGE = ISNULL(    
           (    
            SELECT  B.CARD_IMAGE  FROM CUSTOM_SAMPLE_ORDER_ITEM A LEFT OUTER JOIN S2_CARD B ON A.CARD_SEQ = B.CARD_SEQ    
            WHERE A.SAMPLE_ORDER_SEQ=  ER_ORDER_SEQ  AND B.CARD_SEQ = ER_CARD_SEQ   
           ),   
           (   
            SELECT TOP 1 B.CARD_IMAGE FROM CUSTOM_SAMPLE_ORDER_ITEM A LEFT OUTER JOIN S2_CARD B ON A.CARD_SEQ = B.CARD_SEQ   
            WHERE A.SAMPLE_ORDER_SEQ=  ER_ORDER_SEQ     
           )    
           ),   
    CARDCODE_CARDIMAGE = (   
          SELECT TOP 1 CONCAT(A.CARD_SEQ ,'^' , B.CARD_CODE , '^' , B.CARD_IMAGE ) FROM CUSTOM_SAMPLE_ORDER_ITEM A LEFT OUTER JOIN S2_CARD B ON A.CARD_SEQ = B.CARD_SEQ   
          WHERE A.SAMPLE_ORDER_SEQ=  ER_ORDER_SEQ    
          ) ,
	FIRST_UPLOAD_PHOTO = (SELECT TOP 1 UPIMG_NAME  FROM S4_EVENT_REVIEW_PHOTO WHERE SEQ =  A.ER_IDX ORDER BY 1 ) 
			
    FROM S4_EVENT_REVIEW AS A WITH(NOLOCK) LEFT OUTER JOIN    
      S4_EVENT_REVIEW_STATUS AS B WITH(NOLOCK) ON A.ER_IDX = B.ERA_ER_IDX JOIN   
      COMPANY AS C ON A.ER_COMPANY_SEQ = C.COMPANY_SEQ   
    WHERE ER_TYPE = @ER_TYPE AND    
       C.SALES_GUBUN IN ('B','C','H') AND   
       ER_USERID = @ER_USERID AND   
       ER_VIEW = 0   
    ORDER BY ER_REGDATE DESC  
    
  END  
 END  
  
GO
