IF OBJECT_ID (N'dbo.UP_INSERT_REVIEW3_NEW_MOBILE', N'P') IS NOT NULL DROP PROCEDURE dbo.UP_INSERT_REVIEW3_NEW_MOBILE
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*******************************************************************    
작성자  : 표수현    
  
작성일  : 2020-10-15    
  
DESCRIPTION : 샘플 후기 모바일 등록 

ER_view -> 전시 / 0 -> 비노출 / 1

inflow_route -> PC OR NULL / Mobile

ER_isPhoto  1 -> text / 포토  - 0

********************************************************************    
수정일   작업자  DESCRIPTION        
********************************************************************/ 
CREATE PROCEDURE [dbo].[UP_INSERT_REVIEW3_NEW_MOBILE]
	@COMPANY_SEQ	INT,
	@ORDER_SEQ		INT,
	@CARD_SEQ		INT,
	@CARD_CODE		NVARCHAR(20),
	@REVIEWS_TITLE	NVARCHAR(150),
	@REVIEWS_URL	NVARCHAR(250),
    @REVIEWS_URL2	NVARCHAR(250),
	@REVIEWS_URL3	NVARCHAR(250),
	@SCORE			INT,
	@CONTENT		NTEXT,
	@USERID			NVARCHAR(20),
	@ER_TYPE		INT,
	@USER_NAME		NVARCHAR(20),
	@REVIEWS_URL_A	NVARCHAR(250),
	@REVIEWS_URL_B	NVARCHAR(250),	
	@IMG_NAME1		VARCHAR(60),
	@UPIMG_NAME1	VARCHAR(60),
	@IMG_NAME2		VARCHAR(60),
	@UPIMG_NAME2	VARCHAR(60),
	@IMG_NAME3		VARCHAR(60),
	@UPIMG_NAME3	VARCHAR(60),
	@IMG_NAME4		VARCHAR(60),
	@UPIMG_NAME4	VARCHAR(60),
	@IMG_NAME5		VARCHAR(60),
	@UPIMG_NAME5	VARCHAR(60),
	@RESULT			INT=0 OUTPUT
AS
 BEGIN

 SET NOCOUNT ON;
 --BEGIN TRAN
			
			DECLARE @ID	INT;
			DECLARE @EXIST_CNT INT;


			IF @COMPANY_SEQ = '5001' OR @COMPANY_SEQ = '5007'
				BEGIN
					SELECT @EXIST_CNT = COUNT(*) FROM S4_EVENT_REVIEW WHERE ER_REVIEW_URL = @REVIEWS_URL AND ER_COMPANY_SEQ = @COMPANY_SEQ
				END
			ELSE
				BEGIN
					SELECT @EXIST_CNT = COUNT(*) FROM S4_EVENT_REVIEW WHERE ER_REVIEW_URL = @REVIEWS_URL AND ER_COMPANY_SEQ = @COMPANY_SEQ
				END

			IF @EXIST_CNT = 0 BEGIN

					DECLARE @사진첨부여부 CHAR = '1'

					IF @IMG_NAME1 <> '' OR 	@IMG_NAME2 <> '' OR @IMG_NAME3 <> '' OR  @IMG_NAME4 <> '' OR  @IMG_NAME5 <> '' BEGIN
						SET @사진첨부여부 = '0'
					END

					/*리뷰 기본정보 등록*/
    				INSERT INTO S4_EVENT_REVIEW (ER_COMPANY_SEQ, ER_ORDER_SEQ, ER_TYPE, ER_CARD_SEQ, ER_CARD_CODE, ER_USERID, ER_ISPHOTO, ER_REVIEW_TITLE, ER_REVIEW_URL, ER_REVIEW_URL2, ER_REVIEW_URL3, ER_Comment,/*ER_REVIEW_CONTENT*/
												 ER_REVIEW_STAR, ER_USERNAME, ER_REVIEW_URL_A, ER_REVIEW_URL_B,inflow_route) 
    				VALUES 
    				(@COMPANY_SEQ, @ORDER_SEQ, @ER_TYPE, @CARD_SEQ, @CARD_CODE, @USERID, @사진첨부여부, @REVIEWS_TITLE, @REVIEWS_URL, @REVIEWS_URL2, @REVIEWS_URL3, @CONTENT, @SCORE, @USER_NAME, @REVIEWS_URL_A, @REVIEWS_URL_B, 'mobile')
    		
    				SET @ID = SCOPE_IDENTITY()
    		
    				INSERT INTO S4_EVENT_REVIEW_STATUS(ERA_ER_IDX) VALUES (@ID)
		
					-- 이미지 파일명 저장
					IF @IMG_NAME1 <> '' BEGIN	
							INSERT S4_EVENT_REVIEW_PHOTO (seq, IMG_NAME, UPIMG_NAME) VALUES (@ID,@IMG_NAME1,@UPIMG_NAME1)
					END

					IF @IMG_NAME2 <> ''	BEGIN
							INSERT S4_EVENT_REVIEW_PHOTO (seq, IMG_NAME, UPIMG_NAME) VALUES (@ID,@IMG_NAME2,@UPIMG_NAME2)
					END 

					IF @IMG_NAME3 <> '' BEGIN
							INSERT S4_EVENT_REVIEW_PHOTO (seq, IMG_NAME, UPIMG_NAME) VALUES (@ID,@IMG_NAME3,@UPIMG_NAME3)
					END 

					IF @IMG_NAME4 <> '' BEGIN
							INSERT S4_EVENT_REVIEW_PHOTO (seq, IMG_NAME, UPIMG_NAME) VALUES (@ID,@IMG_NAME4,@UPIMG_NAME4)
					END 

					IF @IMG_NAME5 <> '' BEGIN
							INSERT S4_EVENT_REVIEW_PHOTO (seq, IMG_NAME, UPIMG_NAME) VALUES (@ID,@IMG_NAME5,@UPIMG_NAME5)
					END 		
					
					SET @RESULT = '0'
					SET @RESULT = @@ERROR
					--IF (@RESULT <> 0) GOTO PROBLEM
					--COMMIT TRAN


					--PROBLEM:
					--IF (@RESULT <> 0) BEGIN
					--	ROLLBACK TRAN
					--END
			END ELSE BEGIN
				SET @RESULT = '9'
				--SET @RESULT = '동일한 URL이 존재합니다.'
			END

			RETURN @RESULT

END

GO
