IF OBJECT_ID (N'dbo.SP_UPDATE_CUSTOM_ORDER_FOR_AUTO_CHOAN_UPLOAD_CODE', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_UPDATE_CUSTOM_ORDER_FOR_AUTO_CHOAN_UPLOAD_CODE
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_UPDATE_CUSTOM_ORDER_FOR_AUTO_CHOAN_UPLOAD_CODE]    
    @ORDER_SEQ              AS INT    
,   @AUTO_CHOAN_UPLOAD_CODE AS VARCHAR(6)    
AS    
    
BEGIN    
      
    UPDATE  CUSTOM_ORDER     
    SET     AUTO_CHOAN_UPLOAD_CODE = @AUTO_CHOAN_UPLOAD_CODE    
        ,   AUTO_CHOAN_UPLOAD_REG_DATE = GETDATE()  
    WHERE   ORDER_SEQ = @ORDER_SEQ    
  
    

    UPDATE  CUSTOM_ORDER
    SET     STATUS_SEQ = 7
        ,   SRC_COMPOSE_ADMIN_ID = 'admin'
        ,   SRC_COMPOSE_DATE = GETDATE()
    WHERE   1 = 1
    AND     ORDER_SEQ = @ORDER_SEQ
    AND     MEMBER_ID = 's4guest'

    --SELECT  CC.AUTO_CHOAN_REGISTER_YORN  
    --FROM    CUSTOM_ORDER CO  
    --JOIN    S2_CARD SC ON CO.CARD_SEQ = SC.CARD_SEQ  
    --LEFT  
    --JOIN    S2_CARDCORELTEMPLATEINFO SCCTI ON SC.CARD_CODE = SCCTI.CARD_CODE  
    --JOIN    CARD_COREL CC ON CC.CARD_CODE = CASE WHEN SCCTI.CARD_CODE IS NOT NULL THEN SCCTI.CARD_CODE ELSE SC.CARD_ERPCODE END  
    --WHERE   1 = 1
    --AND     ORDER_SEQ = @ORDER_SEQ  
    
END
GO
