IF OBJECT_ID (N'dbo.SP_INSERT_CALLCENTER_SIGNAL_LAMP_MST', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_INSERT_CALLCENTER_SIGNAL_LAMP_MST
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

SELECT * FROM CALLCENTER_SIGNAL_LAMP_MST

*/

CREATE PROCEDURE [dbo].[SP_INSERT_CALLCENTER_SIGNAL_LAMP_MST]

    @CONNECTION_RATE_GOOD_VALUE     AS INT
,   @CONNECTION_RATE_BUSY_VALUE     AS INT
,   @QNA_GOOD_VALUE					AS INT
,   @QNA_BUSY_VALUE					AS INT
,   @SMS_GOOD_VALUE					AS INT
,   @SMS_BUSY_VALUE					AS INT

AS
BEGIN

	INSERT INTO CALLCENTER_SIGNAL_LAMP_MST
	(
				CALL_GOOD
			,	CALL_BUSY
			,	QNA_GOOD
			,	QNA_BUSY
			,	SMS_GOOD
			,	SMS_BUSY
	)

	SELECT	    @CONNECTION_RATE_GOOD_VALUE 
			,   @CONNECTION_RATE_BUSY_VALUE 
			,   @QNA_GOOD_VALUE				
			,   @QNA_BUSY_VALUE				
			,   @SMS_GOOD_VALUE				
			,   @SMS_BUSY_VALUE		
			
END		
GO
