IF OBJECT_ID (N'dbo.UP_INSERT_REVIEW_BRSMOBILE_NEW', N'P') IS NOT NULL DROP PROCEDURE dbo.UP_INSERT_REVIEW_BRSMOBILE_NEW
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- AUTHOR:		<AUTHOR,,NAME>
-- CREATE DATE: <CREATE DATE,,>
-- DESCRIPTION:	<DESCRIPTION,,>

-- UP_INSERT_REVIEW_TEST 5000, 12345, 0, 0000, '제목', 'REVIEWS_URL', 5, 'SAMPLE', 'PHS4125', 0,'박형승','REVIEWS_URL_A','REVIEWS_URL_B' 
-- =============================================
CREATE PROCEDURE [dbo].[UP_INSERT_REVIEW_BRSMOBILE_NEW]
	-- ADD THE PARAMETERS FOR THE STORED PROCEDURE HERE
	@COMPANY_SEQ		INT,
	@ORDER_SEQ			INT,
	@CARD_SEQ			INT,
	@CARD_CODE			NVARCHAR(20),
	@REVIEWS_TITLE		NVARCHAR(150),
	@REVIEWS_URL		NVARCHAR(250),
	@SCORE				INT,
	@CONTENT			NTEXT,
	@USERID				NVARCHAR(20),
	@ER_TYPE			INT,
	@USER_NAME			NVARCHAR(20),
	@REVIEWS_URL_A		NVARCHAR(250),
	@REVIEWS_URL_B		NVARCHAR(250),
	@EMAIL				VARCHAR(100)
AS
BEGIN
	-- SET NOCOUNT ON ADDED TO PREVENT EXTRA RESULT SETS FROM
	-- INTERFERING WITH SELECT STATEMENTS.

	SET NOCOUNT ON;
	BEGIN TRAN
			
		DECLARE @ID	INT;
		DECLARE @EXIST_CNT INT;
		DECLARE @RESULT INT

		SELECT @EXIST_CNT = COUNT(*) FROM S4_EVENT_REVIEW WHERE ER_REVIEW_URL = @REVIEWS_URL AND ER_COMPANY_SEQ = @COMPANY_SEQ

		IF @EXIST_CNT = 0
			BEGIN
			
				/*리뷰 기본정보 등록*/
    			INSERT INTO S4_EVENT_REVIEW (ER_COMPANY_SEQ, ER_ORDER_SEQ, ER_TYPE, ER_CARD_SEQ, ER_CARD_CODE, ER_USERID, ER_REVIEW_TITLE, ER_REVIEW_URL, ER_REVIEW_CONTENT, ER_REVIEW_STAR, ER_USERNAME, ER_REVIEW_URL_A, ER_REVIEW_URL_B, INFLOW_ROUTE, 
				ER_EMAIL) 
    			VALUES 
    			(@COMPANY_SEQ, @ORDER_SEQ, @ER_TYPE, @CARD_SEQ, @CARD_CODE, @USERID, @REVIEWS_TITLE, @REVIEWS_URL, @CONTENT, @SCORE, @USER_NAME, @REVIEWS_URL_A, @REVIEWS_URL_B, 'MOBILE', @EMAIL)
    		
    			SET @ID = SCOPE_IDENTITY()
    			
				IF @USERID = '' BEGIN   

				    INSERT INTO S4_EVENT_REVIEW_STATUS(ERA_ER_IDX, ERA_STATUS, ERA_COMMENT_CANCEL) VALUES (@ID, 2, '회원가입 전환 후 재승인 요청을 클릭해 주세요.')  
		
				END ELSE BEGIN 
		
					INSERT INTO S4_EVENT_REVIEW_STATUS(ERA_ER_IDX) VALUES (@ID)
		
				END 
    			
				SET @RESULT = '0'
				SET @RESULT = @@ERROR
				IF (@RESULT <> 0) GOTO PROBLEM
				COMMIT TRAN


				PROBLEM:
				IF (@RESULT <> 0) BEGIN
					ROLLBACK TRAN
				END
			END
		ELSE
			BEGIN
				SET @RESULT = '9'
				--SET @RESULT = '동일한 URL이 존재합니다.'
			END
			
			RETURN @RESULT

END

GO
