IF OBJECT_ID (N'dbo.SP_INSERT_S5_NMCARD_BOARD', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_INSERT_S5_NMCARD_BOARD
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

SELECT * FROM S5_nmCARDORDER WHERE ADDr= 's4guests4guest'

EXEC SP_SELECT_S5_NMCARD_BOARD 0, 's4guests4guest', 1, 5

*/

CREATE PROCEDURE [dbo].[SP_INSERT_S5_NMCARD_BOARD]
	@ORDER_SEQ				AS INT
,	@GUEST_BOARD_NAME		AS VARCHAR(20)
,	@GUEST_BOARD_MESSAGE	AS NVARCHAR(500)
,	@IP						AS NVARCHAR(50)
,	@HTTP_USER_AGENT		AS NVARCHAR(500)

AS
BEGIN

	INSERT INTO S5_NMCARDBOARD (ORDER_SEQ, NAME, CONTENTS, IP, HTTP_USER_AGENT, REGDATE)
	VALUES (
			@ORDER_SEQ
		,	@GUEST_BOARD_NAME
		,	@GUEST_BOARD_MESSAGE
		,	@IP
		,	@HTTP_USER_AGENT
		,	GETDATE()
	)

END

GO
