IF OBJECT_ID (N'dbo.PROC_CLOSESAMPLE_NEW2', N'P') IS NOT NULL DROP PROCEDURE dbo.PROC_CLOSESAMPLE_NEW2
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PROC_CLOSESAMPLE_NEW2]
 @ORDER_SEQ INT
AS
BEGIN

    SET NOCOUNT ON;

    DECLARE @DELIVERY_COMPANY_SHORT_NAME AS VARCHAR(10)
	DECLARE @DEL_CODE VARCHAR(100)
    SET @DELIVERY_COMPANY_SHORT_NAME = 'LT'

	EXEC [DBO].[SP_CJ_DELEVERY_NEW] 'CUSTOM_SAMPLE_ORDER|',@ORDER_SEQ, 0, @DELIVERY_COMPANY_SHORT_NAME, @DEL_CODE OUTPUT


   


END






GO
