IF OBJECT_ID (N'dbo.SP_SEARCH_PROCEDURE', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SEARCH_PROCEDURE
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_SEARCH_PROCEDURE]

	@P_SEARCH_VALUE AS VARCHAR(MAX)

AS
BEGIN

	SELECT	ROUTINE_NAME 
    FROM	INFORMATION_SCHEMA.ROUTINES
    WHERE	1 = 1
	AND		ROUTINE_DEFINITION LIKE '%' + @P_SEARCH_VALUE + '%'
    AND		ROUTINE_TYPE = 'PROCEDURE'
    ORDER BY ROUTINE_NAME

END
GO
