IF OBJECT_ID (N'dbo.UP_PACKING_EXPECTED_DATE', N'P') IS NOT NULL DROP PROCEDURE dbo.UP_PACKING_EXPECTED_DATE
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UP_PACKING_EXPECTED_DATE]
	@ORDER_SEQ		INT,
	@PACKING_EXPECTED_DATE VARCHAR(10)
AS
BEGIN
	SET NOCOUNT ON;
	
	UPDATE CUSTOM_ORDER
	SET PACKING_EXPECTED_DATE = @PACKING_EXPECTED_DATE
	WHERE ORDER_SEQ = @ORDER_SEQ
END

GO
