IF OBJECT_ID (N'dbo.SP_SEARCH_ALL_DELIVERY_STOP', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SEARCH_ALL_DELIVERY_STOP
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_SEARCH_ALL_DELIVERY_STOP]
	@GUBUN CHAR(1) = NULL,
	@SEARCHDATE1 VARCHAR(10) = NULL,
	@SEARCHDATE2 VARCHAR(10) = NULL,
	@ORDERSEQ	INT = NULL
AS
	IF @ORDERSEQ = '' BEGIN SET @ORDERSEQ = 0 END 


	IF @GUBUN = 'A' BEGIN -- 청첩장

		IF @ORDERSEQ > 0 BEGIN
					
				SELECT	ORDER_SEQ = A.ORDER_SEQ,
						ZIP = C.ZIP ,  
						ADDR = B.ADDR, 
						ADDR_DETAIL  = B.ADDR_DETAIL 
				FROM	CUSTOM_ORDER A INNER JOIN 
						DELIVERY_INFO AS B ON A.ORDER_SEQ = B.ORDER_SEQ INNER JOIN 
						DELIVERY_STOP_ZIPCODE C ON B.ZIP = C.ZIP      
				WHERE	C.GUBUN = @GUBUN AND 
						A.SETTLE_STATUS = 2  AND 
						CONVERT(VARCHAR(10), ORDER_DATE, 120)  BETWEEN	@SEARCHDATE1 AND  @SEARCHDATE2 AND
						A.ORDER_SEQ = @ORDERSEQ 

				ORDER BY  A.ORDER_SEQ DESC

		END ELSE BEGIN 

				SELECT	ORDER_SEQ = A.ORDER_SEQ,
						ZIP = C.ZIP ,  
						ADDR = B.ADDR, 
						ADDR_DETAIL  = B.ADDR_DETAIL 
				FROM	CUSTOM_ORDER A INNER JOIN 
						DELIVERY_INFO AS B ON A.ORDER_SEQ = B.ORDER_SEQ INNER JOIN 
						DELIVERY_STOP_ZIPCODE C ON B.ZIP = C.ZIP      
				WHERE	C.GUBUN = @GUBUN AND 
						A.SETTLE_STATUS = 2  AND 
						CONVERT(VARCHAR(10), ORDER_DATE, 120)   BETWEEN	@SEARCHDATE1 AND  @SEARCHDATE2 
				ORDER BY  A.ORDER_SEQ DESC

		END 

	END ELSE IF  @GUBUN = 'B' BEGIN  -- 샘플
		
		IF  @ORDERSEQ > 0 BEGIN

				SELECT	ORDER_SEQ = A.SAMPLE_ORDER_SEQ,  
						ZIP = B.ZIP , 
						ADDR = A.MEMBER_ADDRESS, 
						ADDR_DETAIL = A.MEMBER_ADDRESS_DETAIL
				FROM	CUSTOM_SAMPLE_ORDER A INNER JOIN 
						DELIVERY_STOP_ZIPCODE B ON A.MEMBER_ZIP = B.ZIP
				WHERE	B.GUBUN = @GUBUN AND		
						A.DELIVERY_CHANGO = '1' AND		
						A.STATUS_SEQ >= 1 AND  
						CONVERT(VARCHAR(10), A.REQUEST_DATE, 120)  BETWEEN	@SEARCHDATE1 AND  @SEARCHDATE2 AND
						 A.SAMPLE_ORDER_SEQ = @ORDERSEQ
				ORDER BY A.SAMPLE_ORDER_SEQ DESC 

		END ELSE BEGIN 
		 
				SELECT	ORDER_SEQ = A.SAMPLE_ORDER_SEQ,  
						ZIP = B.ZIP , 
						ADDR = A.MEMBER_ADDRESS, 
						ADDR_DETAIL = A.MEMBER_ADDRESS_DETAIL
				FROM	CUSTOM_SAMPLE_ORDER A INNER JOIN 
						DELIVERY_STOP_ZIPCODE B ON A.MEMBER_ZIP = B.ZIP
				WHERE	B.GUBUN = @GUBUN AND		
						A.DELIVERY_CHANGO = '1' AND		
						A.STATUS_SEQ >= 1 AND  
						CONVERT(VARCHAR(10), A.REQUEST_DATE, 120) BETWEEN	@SEARCHDATE1 AND  @SEARCHDATE2 
				ORDER BY A.SAMPLE_ORDER_SEQ DESC 


		END 

	END ELSE BEGIN 

		IF @ORDERSEQ > 0 BEGIN  -- 부가상품

				SELECT	ORDER_SEQ = A.ORDER_SEQ , 
						ZIP = A.RECV_ZIP,  
						ADDR = A.RECV_ADDRESS,
						ADDR_DETAIL = A.RECV_ADDRESS_DETAIL
				FROM	CUSTOM_ETC_ORDER AS A INNER JOIN 
						COMPANY AS B ON A.COMPANY_SEQ = B.COMPANY_SEQ INNER JOIN 
						DELIVERY_STOP_ZIPCODE C ON C.ZIP = A.RECV_ZIP  LEFT OUTER JOIN 
						MANAGE_CODE D ON A.SALES_GUBUN = D.CODE AND D.CODE_TYPE = 'SALES_GUBUN'   
				WHERE	A.STATUS_SEQ >= 1 AND  
						C.GUBUN = @GUBUN AND 
						CONVERT(VARCHAR(10), A.ORDER_DATE, 120)  BETWEEN @SEARCHDATE1 AND  @SEARCHDATE2 AND
						A.ORDER_SEQ = @ORDERSEQ
 				ORDER BY A.ORDER_SEQ DESC 


		END ELSE BEGIN 

				SELECT	ORDER_SEQ = ORDER_SEQ , 
						ZIP = A.RECV_ZIP,  
						ADDR = A.RECV_ADDRESS,
						ADDR_DETAIL = A.RECV_ADDRESS_DETAIL
				FROM	CUSTOM_ETC_ORDER AS A INNER JOIN 
						COMPANY AS B ON A.COMPANY_SEQ = B.COMPANY_SEQ INNER JOIN 
						DELIVERY_STOP_ZIPCODE C ON C.ZIP = A.RECV_ZIP  LEFT OUTER JOIN 
						MANAGE_CODE D ON A.SALES_GUBUN = D.CODE AND D.CODE_TYPE = 'SALES_GUBUN'   
				WHERE	A.STATUS_SEQ >= 1 AND  
						C.GUBUN = @GUBUN AND 
						CONVERT(VARCHAR(10), A.ORDER_DATE, 120)  BETWEEN @SEARCHDATE1 AND  @SEARCHDATE2 
 				ORDER BY A.ORDER_SEQ DESC 

		END 


	END 
GO
