IF OBJECT_ID (N'dbo.SP_EXEC_COUPON_CALC_FOR_CO_TEST', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_EXEC_COUPON_CALC_FOR_CO_TEST
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

EXEC SP_EXEC_COUPON_CALC_FOR_CO 's4guest', 2472827, '', ''


100,000

기본 쿠폰 1 : 10%    10,000   체크
기본 쿠폰 1 : 5%      5,000
기본 쿠폰 1 : 15%    15,000


중복 쿠폰 1 : 10%    10,000   9,000
중복 쿠폰 1 : 5%      5,000
중복 쿠폰 1 : 15%    15,000



AD 쿠폰 1 : 10%      10,000
AD 쿠폰 1 : 5%        5,000
AD 쿠폰 1 : 15%      15,000



추카 쿠폰 1 : 10%    옵션금액을 대상으로 함
추카 쿠폰 1 : 5%     옵션금액을 대상으로 함
추카 쿠폰 1 : 15%    옵션금액을 대상으로 함

SELECT TOP 100 * FROM VW_COUPON_CALC_FOR_CO_TEST

*/
CREATE PROCEDURE [dbo].[SP_EXEC_COUPON_CALC_FOR_CO_TEST]
    
    @P_UID									AS VARCHAR(50)
,	@P_ORDER_SEQ							AS INT
,	@P_SELECTED_COUPON_ISSUE_SEQ_LIST		AS VARCHAR(100) = ''
,	@P_VERIFICATION_COUPON_ISSUE_SEQ_LIST	AS VARCHAR(100) = ''
,	@P_DEVICE_TYPE							AS VARCHAR(100) = 'P'

AS
BEGIN
    


	/* 기본쿠폰, 중복쿠폰1, 중복쿠폰2는 하나만 선택할 수 있다. */
	/* 추가쿠폰은 복수선택이 가능하지만, COUPON_SERVICE_TYPE_CODE가 같은건 하나만 선택할 수 있다. */
	/* 기본쿠폰, 중복쿠폰1, 중복쿠폰2 는 ORDER_PRICE만 할인한다. */
	/* 추가쿠폰은 ORDER_PRICE를 제외한 옵션 금액을 할인한다 */

	/* 중복쿠폰1의 대상금액 =  (대상금액 - 기본쿠폰 할인금액)  */
	/* 중복쿠폰2의 대상금액 =  (대상금액 - 기본쿠폰 할인금액 - 중복쿠폰1 할인금액)  */



	/* 중복쿠폰 1과 중복쿠폰 2의 할인금액을 계산하기 위해서   */
	/* 선택된 기본쿠폰과 중복쿠폰 1 의 할인된 금액을 가져온다 */
	DECLARE @FIRST_COUPON_ORDER_PRICE	AS INT
		,	@SECOND_COUPON_ORDER_PRICE	AS INT

	DECLARE @FIRST_DUP_COUPON_ALLOW_YN	AS VARCHAR(1)
		,	@FIRST_AD_COUPON_ALLOW_YN	AS VARCHAR(1)

	DECLARE @SECOND_DUP_COUPON_ALLOW_YN	AS VARCHAR(1)
		,	@SECOND_AD_COUPON_ALLOW_YN	AS VARCHAR(1)
	
	/* 기본쿠폰 할인금액 */
	SELECT	@FIRST_COUPON_ORDER_PRICE	= ISNULL(DISCOUNT_ORDER_PRICE, 0)
		,	@FIRST_DUP_COUPON_ALLOW_YN	= ISNULL(DUP_COUPON_ALLOW_YN, 'N')
		,	@FIRST_AD_COUPON_ALLOW_YN	= ISNULL(AD_COUPON_ALLOW_YN, 'N')

	FROM	VW_COUPON_CALC_FOR_CO_TEST
	WHERE	1 = 1
	AND		UID					= @P_UID
	AND		ORDER_SEQ			= @P_ORDER_SEQ
	--AND		(
	--				COUPON_DETAIL_SEQ	IN ( SELECT VALUE FROM FN_SPLIT(@P_SELECTED_COUPON_ISSUE_SEQ_LIST, '|')) 
	--			OR	COUPON_DETAIL_SEQ	IN ( SELECT VALUE FROM FN_SPLIT(@P_VERIFICATION_COUPON_ISSUE_SEQ_LIST, '|'))  
	--		)

	AND		(
					COUPON_ISSUE_SEQ	IN ( SELECT VALUE FROM FN_SPLIT(@P_SELECTED_COUPON_ISSUE_SEQ_LIST, '|')) 
				OR	COUPON_ISSUE_SEQ	IN ( SELECT VALUE FROM FN_SPLIT(@P_VERIFICATION_COUPON_ISSUE_SEQ_LIST, '|'))  
			)

	AND		COUPON_TYPE_CODE	IN ('131001')

	/* 중복쿠폰 1 할인금액 */
	SELECT	@SECOND_COUPON_ORDER_PRICE = 
			CASE 
					WHEN	DISCOUNT_FIXED_RATE_TYPE = 'W' 
					THEN	
							CASE 
									WHEN	DISCOUNT_TARGET_ORDER_PRICE - @FIRST_COUPON_ORDER_PRICE - DISCOUNT_VALUE <= 0 
									THEN	CASE 
													WHEN	DISCOUNT_TARGET_ORDER_PRICE - @FIRST_COUPON_ORDER_PRICE > DISCOUNT_MAX_AMT 
													THEN	DISCOUNT_MAX_AMT 
													ELSE	
															CASE WHEN DISCOUNT_TARGET_ORDER_PRICE - @FIRST_COUPON_ORDER_PRICE <= 0 THEN 0 ELSE DISCOUNT_TARGET_ORDER_PRICE - @FIRST_COUPON_ORDER_PRICE END
											END
									ELSE	CASE
													WHEN	DISCOUNT_VALUE > DISCOUNT_MAX_AMT
													THEN	DISCOUNT_MAX_AMT
													ELSE	DISCOUNT_VALUE
											END
							END
					ELSE	
							CASE 
									WHEN	(DISCOUNT_TARGET_ORDER_PRICE - @FIRST_COUPON_ORDER_PRICE) * (1.0 * DISCOUNT_VALUE / 100) > DISCOUNT_MAX_AMT
									THEN	DISCOUNT_MAX_AMT
									ELSE	(DISCOUNT_TARGET_ORDER_PRICE - @FIRST_COUPON_ORDER_PRICE) * (1.0 * DISCOUNT_VALUE / 100)
							END
			END
		,	@SECOND_DUP_COUPON_ALLOW_YN	= ISNULL(DUP_COUPON_ALLOW_YN, 'N')
		,	@SECOND_AD_COUPON_ALLOW_YN	= ISNULL(AD_COUPON_ALLOW_YN, 'N')

	FROM	VW_COUPON_CALC_FOR_CO_TEST
	WHERE	1 = 1
	AND		UID					= @P_UID
	AND		ORDER_SEQ			= @P_ORDER_SEQ
	--AND		(
	--				COUPON_DETAIL_SEQ	IN ( SELECT VALUE FROM FN_SPLIT(@P_SELECTED_COUPON_ISSUE_SEQ_LIST, '|')) 
	--			OR	COUPON_DETAIL_SEQ	IN ( SELECT VALUE FROM FN_SPLIT(@P_VERIFICATION_COUPON_ISSUE_SEQ_LIST, '|'))  
	--		)

	AND		(
					COUPON_ISSUE_SEQ	IN ( SELECT VALUE FROM FN_SPLIT(@P_SELECTED_COUPON_ISSUE_SEQ_LIST, '|')) 
				OR	COUPON_ISSUE_SEQ	IN ( SELECT VALUE FROM FN_SPLIT(@P_VERIFICATION_COUPON_ISSUE_SEQ_LIST, '|'))  
			)

	AND		COUPON_TYPE_CODE	IN ('131002')




	SELECT	*
	FROM	(

				SELECT	ORDER_SEQ
					,	ISNULL(UP_ORDER_SEQ, 0) AS UP_ORDER_SEQ
					,	UID
					,	COMPANY_SEQ
					,	SALES_GUBUN
					,	ORDER_TYPE
					,	COUPON_ISSUE_SEQ
					,	COUPON_DETAIL_SEQ
					,	COUPON_NAME
					,	COUPON_TYPE_CODE
					,	COUPON_SERVICE_TYPE_CODE
					,	COUPON_SERVICE_TYPE_NAME
					,	DUP_COUPON_ALLOW_YN
					,	AD_COUPON_ALLOW_YN
					,	ADD_COUPON_ALLOW_YN
					,	CARD_SEQ
					,	ORDER_COUNT
					,	LAST_TOTAL_PRICE
					,	USE_DEVICE
					,	DISCOUNT_FIXED_RATE_TYPE
					,	DISCOUNT_VALUE
					,	DISCOUNT_MAX_AMT
					,	ORDER_PRICE
					,	FTICKET_PRICE
					,	GUESTBOOK_PRICE
					,	LINING_ENV_PRICE
					,	PRINT_PRICE
					,	EMBO_PRICE
					,	JEBON_PRICE
					,	ENVINSERT_PRICE
					,	EXPRESS_SHIPPING_PRICE
					,	DELIVERY_PRICE

					,	DISCOUNT_TARGET_ORDER_PRICE			AS DISCOUNT_TARGET_ORDER_PRICE_ORG
					,	DISCOUNT_TARGET_ORDER_PRICE_TEMP	AS DISCOUNT_TARGET_ORDER_PRICE
					,	DISCOUNT_TARGET_FTICKET_PRICE
					,	DISCOUNT_TARGET_GUESTBOOK_PRICE
					,	DISCOUNT_TARGET_LINING_ENV_PRICE
					
					,	DISCOUNT_TARGET_FLOWER_PRICE
					,	DISCOUNT_TARGET_SEALING_PRICE
					, 	DISCOUNT_TARGET_ENVSPECIAL_PRICE
					,	DISCOUNT_TARGET_RIBBON_PRICE
					,	DISCOUNT_TARGET_PAPERCOVER_PRICE
					
					,	DISCOUNT_TARGET_PRINT_PRICE
					,	DISCOUNT_TARGET_EMBO_PRICE
					,	DISCOUNT_TARGET_JEBON_PRICE
					,	DISCOUNT_TARGET_ENVINSERT_PRICE
					,	DISCOUNT_TARGET_DELIVERY_PRICE
					,	DISCOUNT_TARGET_EXPRESS_SHIPPING_PRICE

					,	CASE 
								WHEN	COUPON_TYPE_CODE IN ('131001', '131002', '131003')
								THEN
										CASE 
												WHEN	DISCOUNT_FIXED_RATE_TYPE = 'W' 
												THEN	
														CASE 
																WHEN	DISCOUNT_TARGET_ORDER_PRICE_TEMP - DISCOUNT_VALUE <= 0 
																THEN	CASE 
																				WHEN	DISCOUNT_TARGET_ORDER_PRICE_TEMP > DISCOUNT_MAX_AMT AND DISCOUNT_MAX_AMT > 0
																				THEN	DISCOUNT_MAX_AMT 
																				ELSE	CASE WHEN DISCOUNT_TARGET_ORDER_PRICE_TEMP <= 0 THEN 0 ELSE DISCOUNT_TARGET_ORDER_PRICE_TEMP END
																		END
																ELSE	CASE
																				WHEN	DISCOUNT_VALUE > DISCOUNT_MAX_AMT AND DISCOUNT_MAX_AMT > 0
																				THEN	DISCOUNT_MAX_AMT
																				ELSE	DISCOUNT_VALUE
																		END
														END
												ELSE	
														CASE 
																WHEN	DISCOUNT_TARGET_ORDER_PRICE_TEMP * (1.0 * DISCOUNT_VALUE / 100) > DISCOUNT_MAX_AMT AND DISCOUNT_MAX_AMT > 0
																THEN	DISCOUNT_MAX_AMT
																ELSE	DISCOUNT_TARGET_ORDER_PRICE_TEMP * (1.0 * DISCOUNT_VALUE / 100)
														END
										END
								ELSE 0
						END AS DISCOUNT_ORDER_PRICE
					,	DISCOUNT_FTICKET_PRICE
					,	DISCOUNT_GUESTBOOK_PRICE
					,	DISCOUNT_LINING_ENV_PRICE
					
					, 	DISCOUNT_FLOWER_PRICE
					,	DISCOUNT_SEALING_STICKER_PRICE
					,	DISCOUNT_ENVSPECIAL_PRICE
					,	DISCOUNT_RIBBON_PRICE
					,	DISCOUNT_PAPERCOVER_PRICE
					
					,	DISCOUNT_PRINT_PRICE
					,	DISCOUNT_EMBO_PRICE
					,	DISCOUNT_JEBON_PRICE
					,	DISCOUNT_ENVINSERT_PRICE
					,	DISCOUNT_DELIVERY_PRICE
					,	DISCOUNT_EXPRESS_SHIPPING_PRICE

					,		CASE 
									WHEN	COUPON_TYPE_CODE IN ('131001', '131002', '131003')
									THEN
											CASE 
													WHEN	DISCOUNT_FIXED_RATE_TYPE = 'W' 
													THEN	
															CASE 
																	WHEN	DISCOUNT_TARGET_ORDER_PRICE_TEMP - DISCOUNT_VALUE <= 0 
																	THEN	CASE 
																					WHEN	DISCOUNT_TARGET_ORDER_PRICE_TEMP > DISCOUNT_MAX_AMT AND DISCOUNT_MAX_AMT > 0
																					THEN	DISCOUNT_MAX_AMT 
																					ELSE	CASE WHEN DISCOUNT_TARGET_ORDER_PRICE_TEMP <= 0 THEN 0 ELSE DISCOUNT_TARGET_ORDER_PRICE_TEMP END 
																			END
																	ELSE	CASE
																					WHEN	DISCOUNT_VALUE > DISCOUNT_MAX_AMT AND DISCOUNT_MAX_AMT > 0
																					THEN	DISCOUNT_MAX_AMT
																					ELSE	DISCOUNT_VALUE
																			END
															END
													ELSE	
															CASE 
																	WHEN	DISCOUNT_TARGET_ORDER_PRICE_TEMP * (1.0 * DISCOUNT_VALUE / 100) > DISCOUNT_MAX_AMT AND DISCOUNT_MAX_AMT > 0
																	THEN	DISCOUNT_MAX_AMT
																	ELSE	DISCOUNT_TARGET_ORDER_PRICE_TEMP * (1.0 * DISCOUNT_VALUE / 100)
															END
											END
									ELSE 0
							END
						+	DISCOUNT_FTICKET_PRICE
						+	DISCOUNT_GUESTBOOK_PRICE
						+	DISCOUNT_LINING_ENV_PRICE
						
						+ 	DISCOUNT_FLOWER_PRICE
						+	DISCOUNT_SEALING_STICKER_PRICE
						+	DISCOUNT_ENVSPECIAL_PRICE
						+	DISCOUNT_RIBBON_PRICE
						+	DISCOUNT_PAPERCOVER_PRICE
						
						+	DISCOUNT_PRINT_PRICE
						+	DISCOUNT_EMBO_PRICE
						+	DISCOUNT_JEBON_PRICE
						+	DISCOUNT_ENVINSERT_PRICE
						+	DISCOUNT_DELIVERY_PRICE
						+	DISCOUNT_EXPRESS_SHIPPING_PRICE
						AS DISCOUNT_TOTAL_PRICE

				FROM	(
							SELECT	*

								,	CASE 
											WHEN
													DISCOUNT_TARGET_ORDER_PRICE
													-	(
															CASE 
																	WHEN		(COUPON_TYPE_CODE = '131002' AND @FIRST_DUP_COUPON_ALLOW_YN = 'Y') 
																			OR	(COUPON_TYPE_CODE = '131003' AND @FIRST_AD_COUPON_ALLOW_YN = 'Y') 
																	THEN		@FIRST_COUPON_ORDER_PRICE 
																	ELSE		0 
															END
														)
													- (CASE WHEN COUPON_TYPE_CODE = '131003' AND @SECOND_AD_COUPON_ALLOW_YN = 'Y' THEN @SECOND_COUPON_ORDER_PRICE ELSE 0 END)
													<= 0
											THEN	0
											ELSE	DISCOUNT_TARGET_ORDER_PRICE
													-- 중복쿠폰 1은 ORDER_PRICE에서 기본쿠폰의 할인금액을 제외한 금액을 대상으로 한다
													-	(
															CASE 
																	WHEN		(COUPON_TYPE_CODE = '131002' AND @FIRST_DUP_COUPON_ALLOW_YN = 'Y') 
																			OR	(COUPON_TYPE_CODE = '131003' AND @FIRST_AD_COUPON_ALLOW_YN = 'Y') 
																	THEN		@FIRST_COUPON_ORDER_PRICE 
																	ELSE		0 
															END
														)
													-- 중복쿠폰 2는 ORDER_PRICE에서 기본쿠폰 및 중복쿠폰 1의 할인금액을 제외한 금액을 대상으로 한다
													- (CASE WHEN COUPON_TYPE_CODE = '131003' AND @SECOND_AD_COUPON_ALLOW_YN = 'Y' THEN @SECOND_COUPON_ORDER_PRICE ELSE 0 END)
									END
									AS DISCOUNT_TARGET_ORDER_PRICE_TEMP

							FROM	VW_COUPON_CALC_FOR_CO_TEST
							WHERE	1 = 1
							AND		UID = @P_UID
							AND		ORDER_SEQ = @P_ORDER_SEQ

							-- 사용 가능 디바이스
							AND		(
											USE_DEVICE = 'A'
										OR	USE_DEVICE = @P_DEVICE_TYPE
										OR  ISNULL(@P_DEVICE_TYPE, '') = ''
									)

							-- 최종 검증을 위한 조건식
							-- 해당 쿠폰 리스트만 가져온다
							AND		(		
											@P_VERIFICATION_COUPON_ISSUE_SEQ_LIST = '' 
										--OR	(		
										--			@P_VERIFICATION_COUPON_ISSUE_SEQ_LIST <> '' 
										--		AND COUPON_DETAIL_SEQ IN ( SELECT VALUE FROM FN_SPLIT(@P_VERIFICATION_COUPON_ISSUE_SEQ_LIST, '|')) 
										--	)

										OR	(		
													@P_VERIFICATION_COUPON_ISSUE_SEQ_LIST <> '' 
												AND COUPON_ISSUE_SEQ IN ( SELECT VALUE FROM FN_SPLIT(@P_VERIFICATION_COUPON_ISSUE_SEQ_LIST, '|')) 
											)

									)
						) A
			) A
	WHERE	1 = 1

	-- 할인금액이 0보다 큰 쿠폰만 가져온다
	AND		A.DISCOUNT_TOTAL_PRICE > 0

	ORDER BY COUPON_TYPE_CODE ASC



END

GO
