IF OBJECT_ID (N'dbo.SP_EXEC_GENERATE_MCARD_INVITATION_CODE_FOR_OTHER_SITE', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_EXEC_GENERATE_MCARD_INVITATION_CODE_FOR_OTHER_SITE
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*

DELETE MCARD_INVITATION_FOR_OTHER_SITE

SELECT * FROM MCARD_INVITATION_FOR_OTHER_SITE

EXEC SP_EXEC_GENERATE_MCARD_INVITATION_CODE_FOR_OTHER_SITE 'CE', '2016102613440817541', 'test'

http://celemoerp.bhandscard.com/Service/MCard/GenerateMcardInvitationCodeHandler.ashx?SITE_CODE=CE&ORIGINAL_SITE_ORDER_CODE=CE2016102613440817541&USER_ID=test

*/
CREATE PROCEDURE [dbo].[SP_EXEC_GENERATE_MCARD_INVITATION_CODE_FOR_OTHER_SITE]
    
    @P_SITE_CODE AS VARCHAR(10)
,	@P_ORIGINAL_SITE_ORDER_CODE AS VARCHAR(50)
,	@P_USER_ID AS VARCHAR(50)
,	@P_USER_NAME AS VARCHAR(50)
,	@P_HPHONE AS VARCHAR(13)

AS
BEGIN
    
	SET NOCOUNT ON


	DECLARE @RESULT_INVITATION_CODE AS VARCHAR(10)

	IF NOT EXISTS(SELECT * FROM MCARD_INVITATION_FOR_OTHER_SITE WHERE ORIGINAL_SITE_ORDER_CODE = @P_ORIGINAL_SITE_ORDER_CODE AND SITE_CODE = @P_SITE_CODE AND USER_ID = @P_USER_ID)
	BEGIN
		
		INSERT INTO MCARD_INVITATION_FOR_OTHER_SITE (SITE_CODE, ORIGINAL_SITE_ORDER_CODE, INVITATIONCODE, USER_ID, USER_NAME, HPHONE, AVAILABLE_YORN)
		SELECT	@P_SITE_CODE
			,	@P_ORIGINAL_SITE_ORDER_CODE
			,	''
			,	@P_USER_ID
			,	@P_USER_NAME
			,	@P_HPHONE
			,	'Y'


		UPDATE	MCARD_INVITATION_FOR_OTHER_SITE
		SET		INVITATIONCODE = SITE_CODE + RIGHT('0000000' + CAST(SEQ AS VARCHAR(7)), 7)
		WHERE	1 = 1
		AND		ORIGINAL_SITE_ORDER_CODE = @P_ORIGINAL_SITE_ORDER_CODE
		AND		SITE_CODE = @P_SITE_CODE
		AND		USER_ID = @P_USER_ID

	END



	SELECT TOP 1 * 
	FROM	MCARD_INVITATION_FOR_OTHER_SITE 
	WHERE	1 = 1
	AND		ORIGINAL_SITE_ORDER_CODE = @P_ORIGINAL_SITE_ORDER_CODE
	AND		SITE_CODE = @P_SITE_CODE
	AND		USER_ID = @P_USER_ID

END
GO
