IF OBJECT_ID (N'dbo.SP_EXEC_CUSTOM_SAMPLE_ORDER_ITEM_FOR_PRICE', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_EXEC_CUSTOM_SAMPLE_ORDER_ITEM_FOR_PRICE
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*

EXEC SP_EXEC_CUSTOM_SAMPLE_ORDER_ITEM_FOR_PRICE 5001, 's4guest', '35583,35792,35462,35437', 0, 'LIST'
EXEC SP_EXEC_CUSTOM_SAMPLE_ORDER_ITEM_FOR_PRICE 5001, 's4guest', '35583,35792,35462,35437', 0, 'SUM'

*/
CREATE PROCEDURE [dbo].[SP_EXEC_CUSTOM_SAMPLE_ORDER_ITEM_FOR_PRICE]
    @P_COMPANY_SEQ		AS INT				/* 사이트 시퀀스 */
,   @P_USER_ID			AS VARCHAR(50)		/* 아이디 */
,   @P_CARD_SEQ_LIST	AS VARCHAR(500)		/* ',' 으로 합쳐진 CARD_SEQ를 받는다 */
,   @P_ORDER_SEQ		AS VARCHAR(50)		/* 주문번호 */
,	@P_RESULT_TYPE		AS VARCHAR(10)		/* LIST : 카드들의 금액을 리스트 형태로 리턴, SUM : 모든 금액을 리턴 */

AS
BEGIN

    SET NOCOUNT ON;	
	
	DECLARE @DELIVERY_PRICE AS INT    
	DECLARE @ORDER_SEQ AS INT

	SET @ORDER_SEQ = CASE WHEN ISNUMERIC(@P_ORDER_SEQ) = 0 THEN 0 ELSE CAST(@P_ORDER_SEQ AS INT) END


	/* 주문 내역이 있다면, 배송비는 3,000원 */

	IF @P_USER_ID = ''
	
	BEGIN
	
		SET @DELIVERY_PRICE = 3000

    IF @ORDER_SEQ > 0 
		BEGIN
			
				IF @P_RESULT_TYPE = 'LIST' 
					BEGIN

						SELECT	A.CARD_SEQ
							,	B.CARD_CODE
							,	B.CARD_NAME
							,	ISNULL(A.CARD_PRICE, 0) AS CARD_PRICE
							,	B.CARD_IMAGE 
							,	@DELIVERY_PRICE AS DELIVERY_PRICE
						FROM	CUSTOM_SAMPLE_ORDER_ITEM A 
						JOIN	S2_CARD B ON A.CARD_SEQ = B.CARD_SEQ 
						WHERE	SAMPLE_ORDER_SEQ = @ORDER_SEQ

					END

				ELSE
					BEGIN
					
						SELECT	SUM(ISNULL(A.CARD_PRICE, 0)) + @DELIVERY_PRICE	AS TOTAL_PRICE
							,	SUM(ISNULL(A.CARD_PRICE, 0))					AS CARD_PRICE
							,	@DELIVERY_PRICE									AS DELIVERY_PRICE
						FROM	CUSTOM_SAMPLE_ORDER_ITEM A 
						JOIN	S2_CARD B ON A.CARD_SEQ = B.CARD_SEQ 
						WHERE	SAMPLE_ORDER_SEQ = @ORDER_SEQ

					END

			END

		ELSE
			BEGIN
			
				IF @P_RESULT_TYPE = 'LIST' 
					BEGIN

						SELECT	CARD_SEQ
							,	CARD_CODE
							,	CARD_NAME
							,	CAST(0 AS INT) AS CARD_PRICE
							,	CARD_IMAGE 
							,	@DELIVERY_PRICE AS DELIVERY_PRICE
						FROM	S2_CARD 
						WHERE	CARD_SEQ IN (SELECT VALUE FROM FN_SPLIT(REPLACE(@P_CARD_SEQ_LIST, ' ', ''), ','))

					END
				ELSE
					BEGIN
					
						SELECT	CAST(SUM(0) AS INT) + @DELIVERY_PRICE	AS TOTAL_PRICE
							,	CAST(SUM(0) AS INT)						AS CARD_PRICE
							,	@DELIVERY_PRICE																									AS DELIVERY_PRICE
						FROM	S2_CARD 
						WHERE	CARD_SEQ IN (SELECT VALUE FROM FN_SPLIT(REPLACE(@P_CARD_SEQ_LIST, ' ', ''), ','))

					END

			END	
	END
	-- 회원
	ELSE
	
	
	BEGIN
		BEGIN
			SET @DELIVERY_PRICE = ISNULL(
											(
												SELECT	3000
												FROM	CUSTOM_SAMPLE_ORDER 
												WHERE	1 = 1
												AND		STATUS_SEQ >= 4 
												AND		STATUS_SEQ <> 5 
												AND		BUY_CONF='1' 
												AND		MEMBER_ID = @P_USER_ID 
												AND		COMPANY_SEQ = @P_COMPANY_SEQ 
												AND		MEMBER_ID <> 'thesnssample'
											), 0
										)

		END 
	


    IF @ORDER_SEQ > 0 
		BEGIN
			
			IF @P_RESULT_TYPE = 'LIST' 
				BEGIN

					SELECT	A.CARD_SEQ
						,	B.CARD_CODE
						,	B.CARD_NAME
						,	ISNULL(A.CARD_PRICE, 0) AS CARD_PRICE
						,	B.CARD_IMAGE 
						,	@DELIVERY_PRICE AS DELIVERY_PRICE
					FROM	CUSTOM_SAMPLE_ORDER_ITEM A 
					JOIN	S2_CARD B ON A.CARD_SEQ = B.CARD_SEQ 
					WHERE	SAMPLE_ORDER_SEQ = @ORDER_SEQ

				END

			ELSE
				BEGIN
					
					SELECT	SUM(ISNULL(A.CARD_PRICE, 0)) + @DELIVERY_PRICE	AS TOTAL_PRICE
						,	SUM(ISNULL(A.CARD_PRICE, 0))					AS CARD_PRICE
						,	@DELIVERY_PRICE									AS DELIVERY_PRICE
					FROM	CUSTOM_SAMPLE_ORDER_ITEM A 
					JOIN	S2_CARD B ON A.CARD_SEQ = B.CARD_SEQ 
					WHERE	SAMPLE_ORDER_SEQ = @ORDER_SEQ

				END

		END

	ELSE
		BEGIN
			
			IF @P_RESULT_TYPE = 'LIST' 
				BEGIN

					SELECT	CARD_SEQ
						,	CARD_CODE
						,	CARD_NAME
						,	CAST(CASE WHEN @DELIVERY_PRICE > 0 THEN ISNULL(CARD_PRICE, 0) * 0.4 ELSE 0 END AS INT) AS CARD_PRICE
						,	CARD_IMAGE 
						,	@DELIVERY_PRICE AS DELIVERY_PRICE
					FROM	S2_CARD 
					WHERE	CARD_SEQ IN (SELECT VALUE FROM FN_SPLIT(REPLACE(@P_CARD_SEQ_LIST, ' ', ''), ','))

				END
			ELSE
				BEGIN
					
					SELECT	CAST(SUM(CASE WHEN @DELIVERY_PRICE > 0 THEN ISNULL(CARD_PRICE, 0) * 0.4 ELSE 0 END) AS INT) + @DELIVERY_PRICE	AS TOTAL_PRICE
						,	CAST(SUM(CASE WHEN @DELIVERY_PRICE > 0 THEN ISNULL(CARD_PRICE, 0) * 0.4 ELSE 0 END) AS INT)						AS CARD_PRICE
						,	@DELIVERY_PRICE																									AS DELIVERY_PRICE
					FROM	S2_CARD 
					WHERE	CARD_SEQ IN (SELECT VALUE FROM FN_SPLIT(REPLACE(@P_CARD_SEQ_LIST, ' ', ''), ','))

				END

		END
	END

END
GO
