IF OBJECT_ID (N'dbo.SP_EXEC_SAMSUNG_MEMBERSHIP_SIGN_UP', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_EXEC_SAMSUNG_MEMBERSHIP_SIGN_UP
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*


*/
CREATE PROCEDURE [dbo].[SP_EXEC_SAMSUNG_MEMBERSHIP_SIGN_UP]
	@P_USER_ID AS VARCHAR(50)

AS
BEGIN
    
    SET NOCOUNT ON;

	UPDATE	S2_USERINFO
	SET		CHK_SMEMBERSHIP = 'Y'
		,	SMEMBERSHIP_REG_DATE = GETDATE()
		,	CHK_SMEMBERSHIP_PER = 'Y'
		,	CHK_SMEMBERSHIP_COOP = 'Y'
		,	SMEMBERSHIP_INFLOW_ROUTE = 'JOIN'
		,	SMEMBERSHIP_CHK_FLAG = 'Y'
	WHERE	UID = @P_USER_ID

	UPDATE	S2_USERINFO_THECARD
	SET		CHK_SMEMBERSHIP = 'Y'
		,	SMEMBERSHIP_REG_DATE = GETDATE()
		,	CHK_SMEMBERSHIP_PER = 'Y'
		,	CHK_SMEMBERSHIP_COOP = 'Y'
		,	SMEMBERSHIP_INFLOW_ROUTE = 'JOIN'
		,	SMEMBERSHIP_CHK_FLAG = 'Y'
	WHERE	UID = @P_USER_ID

	UPDATE	S2_USERINFO_BHANDS
	SET		CHK_SMEMBERSHIP = 'Y'
		,	SMEMBERSHIP_REG_DATE = GETDATE()
		,	CHK_SMEMBERSHIP_PER = 'Y'
		,	CHK_SMEMBERSHIP_COOP = 'Y'
		,	SMEMBERSHIP_INFLOW_ROUTE = 'JOIN'
		,	SMEMBERSHIP_CHK_FLAG = 'Y'
	WHERE	UID = @P_USER_ID

END
GO
