IF OBJECT_ID (N'dbo.SP_UPDATE_CUSTOM_ORDER_FOR_AUTO_CHOAN_STATUS_CODE', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_UPDATE_CUSTOM_ORDER_FOR_AUTO_CHOAN_STATUS_CODE
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_UPDATE_CUSTOM_ORDER_FOR_AUTO_CHOAN_STATUS_CODE]
    @ORDER_SEQ              AS INT
,   @AUTO_CHOAN_STATUS_CODE AS VARCHAR(6)
AS

BEGIN
    
    UPDATE  CUSTOM_ORDER 
    SET     AUTO_CHOAN_STATUS_CODE = @AUTO_CHOAN_STATUS_CODE 
    WHERE   ORDER_SEQ = @ORDER_SEQ

END
GO
