IF OBJECT_ID (N'dbo.SP_SELECT_S2_NEWS', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SELECT_S2_NEWS
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

SELECT * FROM S2_News

*/

CREATE PROCEDURE [dbo].[SP_SELECT_S2_NEWS]
    @SEQ AS INT
AS
BEGIN

    SELECT  *
        ,   ISNULL((SELECT TOP 1 CMMN_CODE FROM COMMON_CODE WHERE CLSS_CODE = '112' AND DTL_NAME = CATEGORY), '') AS CATEGORY_TYPE_CODE
    FROM    S2_NEWS
    WHERE   SEQ = @SEQ

END

GO
