IF OBJECT_ID (N'dbo.SP_SAMPLEBOOK_SELECT_ORDERITEM_LIST', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_SAMPLEBOOK_SELECT_ORDERITEM_LIST
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_SAMPLEBOOK_SELECT_ORDERITEM_LIST]
	@ORDER_SEQ INT

AS
BEGIN

	SELECT B.Card_Seq
		, C.Card_Code
		, ISNULL(B.SampleBook_ID, '') AS SampleBookID
		, CASE WHEN B.SampleBook_Status >= 15 THEN '●' ELSE '' END AS ReturnStatus
		, CASE WHEN B.SampleBook_Status >= 16 THEN '●' ELSE '' END AS StockStatus

	FROM CUSTOM_ETC_ORDER A
	JOIN CUSTOM_ETC_ORDER_ITEM B ON A.order_seq = B.order_seq
	LEFT JOIN S2_Card C ON B.card_seq = C.card_seq
	LEFT JOIN SampleBook S ON B.SampleBook_ID = S.SampleBook_ID
	WHERE A.order_seq = @ORDER_SEQ
	ORDER BY B.SEQ


END

GO
