IF OBJECT_ID (N'dbo.proc_CloseCopy_cancel', N'P') IS NOT NULL DROP PROCEDURE dbo.proc_CloseCopy_cancel
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[proc_CloseCopy_cancel]
	@ORDER_SEQ INT
--,@RSLT TINYINT OUTPUT
AS
BEGIN
	--DECLARE @DELIVERY_COMPANY_SHORT_NAME VARCHAR(2)
	--SELECT @DELIVERY_COMPANY_SHORT_NAME = CODE FROM DELIVERY_CODE WHERE USE_YN = 'Y' 
	
	--IF @DELIVERY_COMPANY_SHORT_NAME = 'CJ' BEGIN 
		
	--	UPDATE CJ_DELCODE SET ISUSE='0' WHERE CODE IN (SELECT DELIVERY_CODE_NUM FROM DELIVERY_INFO_DELCODE WHERE ORDER_SEQ = @ORDER_SEQ)

	--END ELSE BEGIN 
	
	--	UPDATE LT_DELCODE SET ISUSE='0' WHERE CODE IN (SELECT DELIVERY_CODE_NUM FROM DELIVERY_INFO_DELCODE WHERE ORDER_SEQ = @ORDER_SEQ)

	--END 
	--사용하는 송장코드를 원상복귀
    IF GETDATE() >= '2015-08-03 00:00:00'
        BEGIN

	        UPDATE CJ_DELCODE SET ISUSE='0' WHERE CODE IN (SELECT DELIVERY_CODE_NUM FROM DELIVERY_INFO_DELCODE WHERE ORDER_SEQ = @ORDER_SEQ)

        END
    ELSE
        BEGIN

            UPDATE CJ_DELCODE SET ISUSE='0' WHERE CODE IN (SELECT DELIVERY_CODE_NUM FROM DELIVERY_INFO_DELCODE WHERE ORDER_SEQ = @ORDER_SEQ)

        END
	
	--주문/송장 테이블에서 삭제
	DELETE FROM DELIVERY_INFO_DELCODE WHERE ORDER_SEQ=@ORDER_SEQ
	UPDATE DELIVERY_INFO SET DELIVERY_CODE_NUM='',DELIVERY_COM='' WHERE ORDER_SEQ = @ORDER_SEQ
		
	--마감시간 반영
	UPDATE CUSTOM_ORDER SET SRC_CLOSECOPY_DATE=NULL WHERE ORDER_SEQ=@ORDER_SEQ


END
GO
