IF OBJECT_ID (N'dbo.SP_UPDATE_SMARTAD_PARTNER', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_UPDATE_SMARTAD_PARTNER
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

-- EXEC SP_UPDATE_SMARTAD_PARTNER '1'

-- SELECT * FROM SmartAD_Partner

*/

CREATE PROCEDURE [dbo].[SP_UPDATE_SMARTAD_PARTNER]
		@P_CHECK_VALUE AS VARCHAR(100) = ''    -- I : 진행중, E :만료
		, @P_UPD_ID AS VARCHAR(50) = ''    -- I : 진행중, E :만료
AS
BEGIN

	SET NOCOUNT ON


	DECLARE @T_PARTNER_SEQ TABLE ( PARTNER_SEQ VARCHAR(20) )

	INSERT INTO @T_PARTNER_SEQ (PARTNER_SEQ)
	SELECT VALUE FROM dbo.[ufn_SplitTable] (@P_CHECK_VALUE, '|')
	
	--정보갱신
	UPDATE SmartAD_Partner
	SET USE_YN = 'Y', USE_ADMIN_ID = @P_UPD_ID, UPD_DATE = GETDATE()
	WHERE PARTNER_SEQ IN (
							SELECT PARTNER_SEQ FROM  @T_PARTNER_SEQ 
						)
	

END


GO
