IF OBJECT_ID (N'dbo.SP_REPORT_MARKETING_AGREE_BY_ALL', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_REPORT_MARKETING_AGREE_BY_ALL
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_REPORT_MARKETING_AGREE_BY_ALL]
	@P_START_DATE AS NVARCHAR(10),
	@P_END_DATE AS NVARCHAR(10)
AS
BEGIN

	SELECT	A.SITE_DIV AS RegisterSalesGubun
		,	CASE 
				WHEN A.SITE_DIV = 'SB' THEN '바른손카드'
				WHEN A.SITE_DIV = 'SA' THEN '비핸즈카드'
				WHEN A.SITE_DIV = 'ST' THEN '더카드'
				WHEN A.SITE_DIV = 'SS' THEN '프리미어페이퍼'
				WHEN A.SITE_DIV = 'B' THEN '바른손몰'
				WHEN A.SITE_DIV = 'CE' THEN '셀레모'
				WHEN A.SITE_DIV = 'BE' THEN '비웨딩'
				WHEN A.SITE_DIV IS NULL THEN '합계'
				ELSE ''
			END AS RegisterSalesGubunSiteName
		,	SUM(A.SIGN_UP_COUNT) AS SignUpCnt
		,	SUM(THIRD_PARTY_COMMUNICATION_COUNT) AS ThirdPartyCommunicationCnt
		,	SUM(THIRD_PARTY_INSURANCE_COUNT) AS ThirdPartyInsuranceCnt		
		,	ISNULL(SUM(SMEMBERSHIP_COUNT),0) AS SamsungMembershipCnt
		,	ISNULL(SUM(IMEMBERSHIP_COUNT),0) AS IloomMembershipCnt
		,	SUM(THIRD_PARTY_SHINHAN_COUNT) AS ThirdPartyShinhanCnt
		, 	ISNULL(SUM(LGMEMBERSHIP_COUNT), 0) AS LgMembershipCnt

		,	CASE 
					WHEN SUM(A.SIGN_UP_COUNT) > 0 THEN CAST(ROUND(100.0 * SUM(THIRD_PARTY_COMMUNICATION_COUNT) / SUM(A.SIGN_UP_COUNT), 1) AS NUMERIC(12, 1))
					ELSE 0 
			END AS ThirdPartyCommunicationRate

		,	CASE 
					WHEN SUM(A.SIGN_UP_COUNT) > 0 THEN CAST(ROUND(100.0 * SUM(THIRD_PARTY_INSURANCE_COUNT) / SUM(A.SIGN_UP_COUNT), 1) AS NUMERIC(12, 1)) 
					ELSE 0
			END AS ThirdPartyInsuranceRate

		,	CASE 
					WHEN SUM(A.SIGN_UP_COUNT) > 0 THEN CAST(ROUND(100.0 * ISNULL(SUM(SMEMBERSHIP_COUNT),0) / SUM(A.SIGN_UP_COUNT), 1) AS NUMERIC(12, 1)) 
					ELSE 0
			END AS SamsungMembershipRate
		,	CASE 
					WHEN SUM(A.SIGN_UP_COUNT) > 0 THEN CAST(ROUND(100.0 * ISNULL(SUM(IMEMBERSHIP_COUNT),0) / SUM(A.SIGN_UP_COUNT), 1) AS NUMERIC(12, 1)) 
					ELSE 0
			END AS IloomMembershipRate
			
		,	CASE 
					WHEN SUM(A.SIGN_UP_COUNT) > 0 THEN CAST(ROUND(100.0 * SUM(THIRD_PARTY_SHINHAN_COUNT) / SUM(A.SIGN_UP_COUNT), 1) AS NUMERIC(12, 1)) 
					ELSE 0
			END AS ThirdPartyShinhanRate
		,	CASE 
					WHEN SUM(A.SIGN_UP_COUNT) > 0 THEN CAST(ROUND(100.0 * ISNULL(SUM(LGMEMBERSHIP_COUNT),0) / SUM(A.SIGN_UP_COUNT), 1) AS NUMERIC(12, 1)) 
					ELSE 0
			END AS LgMembershipRate

	FROM	(

				SELECT	CASE 
							WHEN ISNULL(SELECT_SALES_GUBUN, '') = '' THEN 
								CASE WHEN ISNULL(REFERER_SALES_GUBUN, 'SB') IN ('B', 'H', 'C') THEN 'B' ELSE ISNULL(REFERER_SALES_GUBUN, 'SB') END
							ELSE 
								CASE WHEN ISNULL(SELECT_SALES_GUBUN, 'SB') IN ('B', 'H', 'C') THEN 'B' ELSE ISNULL(SELECT_SALES_GUBUN, 'SB') END
						END AS SITE_DIV
					,	SUM(CASE WHEN INTERGRATION_DATE >= @P_START_DATE + ' 00:00:00' AND INTERGRATION_DATE < CONVERT(VARCHAR(10), DATEADD(DAY, 1, @P_END_DATE), 120) + ' 00:00:00' THEN 1 ELSE 0 END) AS SIGN_UP_COUNT
					,	SUM(CASE WHEN INTERGRATION_DATE >= @P_START_DATE + ' 00:00:00' AND INTERGRATION_DATE < CONVERT(VARCHAR(10), DATEADD(DAY, 1, @P_END_DATE), 120) + ' 00:00:00' AND ISNULL(SUT.MKT_CHK_FLAG, 'N') = 'Y' AND TP.THIRD_PARTY_COMMUNICATION = 1 AND dbo.fn_datediff(TP.THIRD_PARTY_COMMUNICATION_DT, SUT.INTERGRATION_DATE) < 5  THEN 1 ELSE 0 END) THIRD_PARTY_COMMUNICATION_COUNT
					,	SUM(CASE WHEN INTERGRATION_DATE >= @P_START_DATE + ' 00:00:00' AND INTERGRATION_DATE < CONVERT(VARCHAR(10), DATEADD(DAY, 1, @P_END_DATE), 120) + ' 00:00:00' AND ISNULL(SUT.MKT_CHK_FLAG, 'N') = 'Y' AND TP.THIRD_PARTY_INSURANCE = 1 AND dbo.fn_datediff( TP.THIRD_PARTY_INSURANCE_DT, SUT.INTERGRATION_DATE) < 5 THEN 1 ELSE 0 END) THIRD_PARTY_INSURANCE_COUNT
					,	SUM(CASE WHEN INTERGRATION_DATE >= @P_START_DATE + ' 00:00:00' AND INTERGRATION_DATE < CONVERT(VARCHAR(10), DATEADD(DAY, 1, @P_END_DATE), 120) + ' 00:00:00' AND ISNULL(SUT.MKT_CHK_FLAG, 'N') = 'Y' AND TP.THIRD_PARTY_SHINHAN = 1 AND dbo.fn_datediff( TP.THIRD_PARTY_SHINHAN_DT, SUT.INTERGRATION_DATE) < 5 THEN 1 ELSE 0 END) THIRD_PARTY_SHINHAN_COUNT
			
				FROM	S2_USERINFO_THECARD SUT
				LEFT 
				JOIN	(
							SELECT	UID
								,	ISNULL(MAX(CASE WHEN MARKETING_TYPE_CODE = '119001' THEN 1 ELSE 0 END), 0) AS THIRD_PARTY_COMMUNICATION
								,   MAX(CASE WHEN MARKETING_TYPE_CODE = '119001' THEN REG_DATE ELSE 0 END) AS THIRD_PARTY_COMMUNICATION_DT
								,	ISNULL(MAX(CASE WHEN MARKETING_TYPE_CODE = '119005' THEN 1 ELSE 0 END), 0) AS THIRD_PARTY_INSURANCE 
								,	MAX(CASE WHEN MARKETING_TYPE_CODE = '119005' THEN REG_DATE ELSE 0 END) AS THIRD_PARTY_INSURANCE_DT
								,	ISNULL(MAX(CASE WHEN MARKETING_TYPE_CODE = '119006' THEN 1 ELSE 0 END), 0) AS THIRD_PARTY_SHINHAN 
								,	MAX(CASE WHEN MARKETING_TYPE_CODE = '119006' THEN REG_DATE ELSE 0 END) AS THIRD_PARTY_SHINHAN_DT
							FROM	S2_USERINFO_THIRD_PARTY_MARKETING_AGREEMENT
							GROUP BY UID
						) TP ON SUT.UID = TP.UID

				WHERE	1 = 1
				AND		INTEGRATION_MEMBER_YORN = 'Y'

				and sut.birth <> '' and sut.birth is not null and  sut.birth <> '' and len(sut.birth) = 10

				GROUP BY 
						CASE 
							WHEN ISNULL(SELECT_SALES_GUBUN, '') = '' THEN 
								CASE WHEN ISNULL(REFERER_SALES_GUBUN, 'SB') IN ('B', 'H', 'C') THEN 'B' ELSE ISNULL(REFERER_SALES_GUBUN, 'SB') END
							ELSE 
								CASE WHEN ISNULL(SELECT_SALES_GUBUN, 'SB') IN ('B', 'H', 'C') THEN 'B' ELSE ISNULL(SELECT_SALES_GUBUN, 'SB') END
						END

			) A
	LEFT 
	JOIN	(
				SELECT	CASE WHEN SITE_DIV IN ('B', 'H', 'C') THEN 'B' ELSE SITE_DIV END AS SITE_DIV
					,	COUNT(*) AS WITHDRAWAL_COUNT 
				FROM	S2_USERBYE_SECESSION_CAUSE  USC 
				WHERE	1 = 1
				AND		REG_DATE >= @P_START_DATE + ' 00:00:00'
				AND		REG_DATE < CONVERT(VARCHAR(10), DATEADD(DAY, 1, @P_END_DATE), 120) + ' 00:00:00'

				GROUP BY CASE WHEN SITE_DIV IN ('B', 'H', 'C') THEN 'B' ELSE SITE_DIV END
			) AS WITHDRAWAL ON CASE WHEN A.SITE_DIV IN ('B', 'H', 'C') THEN 'B' ELSE A.SITE_DIV END = WITHDRAWAL.SITE_DIV
	LEFT 
	JOIN	(	
		SELECT
				CASE 
					WHEN ISNULL(SELECT_SALES_GUBUN, '') = '' THEN 
						CASE WHEN ISNULL(REFERER_SALES_GUBUN, 'SB') IN ('B', 'H', 'C') THEN 'B' ELSE ISNULL(REFERER_SALES_GUBUN, 'SB') END
					ELSE 
						CASE WHEN ISNULL(SELECT_SALES_GUBUN, 'SB') IN ('B', 'H', 'C') THEN 'B' ELSE ISNULL(SELECT_SALES_GUBUN, 'SB') END
				END AS SITE_DIV,
		count(1) SMEMBERSHIP_COUNT
		from S2_UserInfo_TheCard as uit
			left outer join EVENT_MARKETING_AGREEMENT ema
				on uit.uid = ema.uid
		where chk_smembership = 'Y'
			and ema.uid is null
			and convert(varchar(10), uit.reg_date, 120) = convert(varchar(10), uit.smembership_reg_date, 120)
			and uit.reg_date >= @P_START_DATE + ' 00:00:00' and uit.reg_date <= @P_END_DATE + ' 23:59:59'
			and (uit.smembership_leave_date is null or (uit.smembership_leave_date is not null and convert(varchar(10), uit.smembership_leave_date, 120) > convert(varchar(10), uit.smembership_reg_date, 120)))

		GROUP BY 
				CASE 
					WHEN ISNULL(SELECT_SALES_GUBUN, '') = '' THEN 
						CASE WHEN ISNULL(REFERER_SALES_GUBUN, 'SB') IN ('B', 'H', 'C') THEN 'B' ELSE ISNULL(REFERER_SALES_GUBUN, 'SB') END
					ELSE 
						CASE WHEN ISNULL(SELECT_SALES_GUBUN, 'SB') IN ('B', 'H', 'C') THEN 'B' ELSE ISNULL(SELECT_SALES_GUBUN, 'SB') END
				END
			) AS SM_CNT ON CASE WHEN A.SITE_DIV IN ('B', 'H', 'C') THEN 'B' ELSE A.SITE_DIV END = SM_CNT.SITE_DIV
	LEFT 
	JOIN	(	
		SELECT
				CASE 
					WHEN ISNULL(SELECT_SALES_GUBUN, '') = '' THEN 
						CASE WHEN ISNULL(REFERER_SALES_GUBUN, 'SB') IN ('B', 'H', 'C') THEN 'B' ELSE ISNULL(REFERER_SALES_GUBUN, 'SB') END
					ELSE 
						CASE WHEN ISNULL(SELECT_SALES_GUBUN, 'SB') IN ('B', 'H', 'C') THEN 'B' ELSE ISNULL(SELECT_SALES_GUBUN, 'SB') END
				END AS SITE_DIV,
		count(1) LGMEMBERSHIP_COUNT
		from S2_UserInfo_TheCard as a
			left outer join EVENT_MARKETING_AGREEMENT ema
				on a.uid = ema.uid
		where chk_lgmembership = 'Y'
			and ema.uid is null
			and convert(varchar(10), a.reg_date, 120) = convert(varchar(10), a.lgmembership_reg_date, 120)
			and a.reg_date >= @P_START_DATE + ' 00:00:00' AND a.reg_date < CONVERT(VARCHAR(10), DATEADD(DAY, 1, @P_END_DATE), 120) + ' 00:00:00'
		GROUP BY 
				CASE 
					WHEN ISNULL(SELECT_SALES_GUBUN, '') = '' THEN 
						CASE WHEN ISNULL(REFERER_SALES_GUBUN, 'SB') IN ('B', 'H', 'C') THEN 'B' ELSE ISNULL(REFERER_SALES_GUBUN, 'SB') END
					ELSE 
						CASE WHEN ISNULL(SELECT_SALES_GUBUN, 'SB') IN ('B', 'H', 'C') THEN 'B' ELSE ISNULL(SELECT_SALES_GUBUN, 'SB') END
				END
			) AS LG_CNT ON CASE WHEN A.SITE_DIV IN ('B', 'H', 'C') THEN 'B' ELSE A.SITE_DIV END = LG_CNT.SITE_DIV			
	LEFT 
	JOIN	(	
		SELECT
				CASE 
					WHEN ISNULL(SELECT_SALES_GUBUN, '') = '' THEN 
						CASE WHEN ISNULL(REFERER_SALES_GUBUN, 'SB') IN ('B', 'H', 'C') THEN 'B' ELSE ISNULL(REFERER_SALES_GUBUN, 'SB') END
					ELSE 
						CASE WHEN ISNULL(SELECT_SALES_GUBUN, 'SB') IN ('B', 'H', 'C') THEN 'B' ELSE ISNULL(SELECT_SALES_GUBUN, 'SB') END
				END AS SITE_DIV,
		count(1) IMEMBERSHIP_COUNT
		from S2_UserInfo_TheCard as a
			left outer join EVENT_MARKETING_AGREEMENT ema
				on a.uid = ema.uid
		where chk_iloommembership = 'Y'
			and ema.uid is null
			and convert(varchar(10), a.reg_date, 120) = convert(varchar(10), a.iloommembership_reg_date, 120)
			and a.reg_date >= @P_START_DATE + ' 00:00:00' AND a.reg_date < CONVERT(VARCHAR(10), DATEADD(DAY, 1, @P_END_DATE), 120) + ' 00:00:00'
		GROUP BY 
				CASE 
					WHEN ISNULL(SELECT_SALES_GUBUN, '') = '' THEN 
						CASE WHEN ISNULL(REFERER_SALES_GUBUN, 'SB') IN ('B', 'H', 'C') THEN 'B' ELSE ISNULL(REFERER_SALES_GUBUN, 'SB') END
					ELSE 
						CASE WHEN ISNULL(SELECT_SALES_GUBUN, 'SB') IN ('B', 'H', 'C') THEN 'B' ELSE ISNULL(SELECT_SALES_GUBUN, 'SB') END
				END

			) AS IM_CNT ON CASE WHEN A.SITE_DIV IN ('B', 'H', 'C') THEN 'B' ELSE A.SITE_DIV END = IM_CNT.SITE_DIV		
	GROUP BY A.SITE_DIV	WITH ROLLUP 
	ORDER BY	
			CASE 
				WHEN A.SITE_DIV = 'SB' THEN 1 
				WHEN A.SITE_DIV = 'SA' THEN 2
				WHEN A.SITE_DIV = 'ST' THEN 3 
				WHEN A.SITE_DIV = 'SS' THEN 4 
				WHEN A.SITE_DIV = 'B' THEN 5 
				WHEN A.SITE_DIV = 'CE' THEN 6 
				WHEN A.SITE_DIV = 'BE' THEN 7 
				WHEN A.SITE_DIV IS NULL THEN 8
				ELSE 1 
			END ASC
			;


END
GO
