IF OBJECT_ID (N'dbo.UP_SELECT_REVIEW_EVENT_MOBILE_COMMENT', N'P') IS NOT NULL DROP PROCEDURE dbo.UP_SELECT_REVIEW_EVENT_MOBILE_COMMENT
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*=============================================  
작성자   : 표수현  
작성일   : 2020-11-11  
INPUT PARAMETER  :  
OUTPUT PARAMETER :  
TABLE   :  
DESCRIPTION  : 바른손몰 모바일에서 샘플후기 제목 클릭시 내용 + 사진 뿌려주는 기능
SPECIAL LOGIC  :   
=================================================*/ 
CREATE PROCEDURE [dbo].[UP_SELECT_REVIEW_EVENT_MOBILE_COMMENT]  
	@SEQ				INT=1
 AS
 
 BEGIN
	SET NOCOUNT ON;

	SELECT IMG_NAME, UPIMG_NAME 
	FROM S4_EVENT_REVIEW_PHOTO  
	WHERE SEQ = @SEQ 


	SELECT ER_COMMENT = ISNULL(ER_COMMENT, ER_REVIEW_URL)
	FROM  S4_EVENT_REVIEW
	WHERE ER_IDX = @SEQ 

	SELECT ER_REVIEW_URL
	FROM  S4_EVENT_REVIEW
	WHERE ER_IDX = @SEQ 

 END
GO
