IF OBJECT_ID (N'dbo.SP_EXEC_ALBA_CHOAN_DOWNLOAD', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_EXEC_ALBA_CHOAN_DOWNLOAD
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*

EXEC SP_EXEC_ALBA_CHOAN_DOWNLOAD 'admin', 50, 50, 50

*/
CREATE PROCEDURE [dbo].[SP_EXEC_ALBA_CHOAN_DOWNLOAD]    
    @P_ALBA_ID							AS VARCHAR(50)
,	@P_WEDDING_INVITATION_COUNT			AS INT
,	@P_THANKS_INVITATION_COUNT			AS INT
,	@P_DIGITAL_WEDDING_INVITATION_COUNT	AS INT

AS
BEGIN
		
	SET NOCOUNT ON;

	DECLARE @WEDDING_INVITATION_DOWNLOADED_COUNT			AS INT = 0
	DECLARE @THANKS_INVITATION_DOWNLOADED_COUNT				AS INT = 0
	DECLARE @DIGITAL_WEDDING_INVITATION_DOWNLOADED_COUNT	AS INT = 0
	DECLARE @NOW_DATE AS VARCHAR = CONVERT(VARCHAR(10), GETDATE(), 120)

	/* 청첩장 */
	IF @P_WEDDING_INVITATION_COUNT > 0
		BEGIN

			UPDATE	CUSTOM_ORDER
			SET		SRC_COMPOSE_ADMIN_ID = @P_ALBA_ID
				,	SRC_COMPOSE_MOD_ADMIN_ID = @P_ALBA_ID
				,	PG_CALDATE = @NOW_DATE
			WHERE	1 = 1
			AND		ORDER_SEQ IN	(
										SELECT	CO.ORDER_SEQ
										FROM	CUSTOM_ORDER CO
										JOIN	S2_CARDVIEW SCV ON CO.CARD_SEQ = SCV.CARD_SEQ
										JOIN	CARD_COREL CC ON SCV.CARD_CODE = CC.CARD_CODE
										LEFT 
										JOIN	CUSTOM_ORDER_WEDDINFO COW ON CO.ORDER_SEQ = COW.ORDER_SEQ
										WHERE	1 = 1
										AND		DATEDIFF(MM, CO.ORDER_DATE, GETDATE()) <= 2
										AND     STATUS_SEQ = 1
										AND     CO.ISSPECIAL NOT IN ('1', '2')
										AND     CO.SRC_COMPOSE_ADMIN_ID IS NULL
										AND     CO.UP_ORDER_SEQ IS NULL
										AND     CO.ISCOREL = '1'
										AND     CO.LAST_TOTAL_PRICE < 300000
										AND     CO.SALES_GUBUN NOT IN ('G', 'X', 'SS', 'H')
										AND     CO.ORDER_TYPE IN ('1', '3', '5')
										AND     CO.ISCOLORINPAPER = 0
										AND     CC.ISALBADOWN = '1'
										AND     (COW.FTYPE IS NULL OR COW.FTYPE <> '5')
										AND		((CO.COMPANY_SEQ = 5007 AND CO.SETTLE_STATUS = 2) OR CO.COMPANY_SEQ <> 5007)
										ORDER BY CO.ORDER_DATE ASC
										OFFSET 0 ROWS
										FETCH NEXT @P_WEDDING_INVITATION_COUNT ROWS ONLY
									)

			SET @WEDDING_INVITATION_DOWNLOADED_COUNT = @@ROWCOUNT

		END


	
	/* 감사장 */
	IF @P_THANKS_INVITATION_COUNT > 0
		BEGIN

			UPDATE	CUSTOM_ORDER
			SET		SRC_COMPOSE_ADMIN_ID = @P_ALBA_ID
				,	SRC_COMPOSE_MOD_ADMIN_ID = @P_ALBA_ID
				,	PG_CALDATE = @NOW_DATE
			WHERE	1 = 1
			AND		ORDER_SEQ IN	(
										SELECT	CO.ORDER_SEQ
										FROM	CUSTOM_ORDER CO
										JOIN	S2_CARDVIEW SCV ON CO.CARD_SEQ = SCV.CARD_SEQ
										JOIN	CARD_COREL CC ON SCV.CARD_CODE = CC.CARD_CODE
										LEFT 
										JOIN	CUSTOM_ORDER_WEDDINFO COW ON CO.ORDER_SEQ = COW.ORDER_SEQ
										WHERE	1 = 1
										AND		DATEDIFF(MM, CO.ORDER_DATE, GETDATE()) <= 2
										AND     STATUS_SEQ = 1
										AND     CO.ISSPECIAL NOT IN ('1', '2')
										AND     CO.SRC_COMPOSE_ADMIN_ID IS NULL
										AND     CO.UP_ORDER_SEQ IS NULL
										AND     CO.ISCOREL = '1'
										AND		CC.INNER_WORK_YORN = 'N'
										AND     CO.LAST_TOTAL_PRICE < 300000
										AND     CO.SALES_GUBUN NOT IN ('G', 'X', 'SS', 'H')
										AND     CO.ORDER_TYPE IN ('2')
										AND     CO.ISCOLORINPAPER = 0
										AND     CC.ISALBADOWN = '1'
										AND     (COW.FTYPE IS NULL OR COW.FTYPE <> '5')
										AND		((CO.COMPANY_SEQ = 5007 AND CO.SETTLE_STATUS = 2) OR CO.COMPANY_SEQ <> 5007)
										ORDER BY CO.ORDER_DATE ASC
										OFFSET 0 ROWS
										FETCH NEXT @P_THANKS_INVITATION_COUNT ROWS ONLY
									)

			SET @THANKS_INVITATION_DOWNLOADED_COUNT = @@ROWCOUNT

		END



	/* 디지털 청첩장 */
	IF @P_DIGITAL_WEDDING_INVITATION_COUNT > 0
		BEGIN

			UPDATE	CUSTOM_ORDER
			SET		SRC_COMPOSE_ADMIN_ID = @P_ALBA_ID
				,	SRC_COMPOSE_MOD_ADMIN_ID = @P_ALBA_ID
				,	PG_CALDATE = @NOW_DATE
			WHERE	1 = 1
			AND		ORDER_SEQ IN	(
										SELECT	CO.ORDER_SEQ
										FROM	CUSTOM_ORDER CO
										JOIN	S2_CARDVIEW SCV ON CO.CARD_SEQ = SCV.CARD_SEQ
										JOIN	CARD_COREL CC ON SCV.CARD_CODE = CC.CARD_CODE
										LEFT 
										JOIN	CUSTOM_ORDER_WEDDINFO COW ON CO.ORDER_SEQ = COW.ORDER_SEQ
										WHERE	1 = 1
										AND		DATEDIFF(MM, CO.ORDER_DATE, GETDATE()) <= 2
										AND     STATUS_SEQ = 1
										AND     CO.ISSPECIAL NOT IN ('1', '2')
										AND     CO.SRC_COMPOSE_ADMIN_ID IS NULL
										AND     CO.UP_ORDER_SEQ IS NULL
										AND     CO.ISCOREL = '1'
										AND     CO.LAST_TOTAL_PRICE < 300000
										AND     CO.SALES_GUBUN NOT IN ('G', 'X', 'SS', 'H')
										AND     CO.ORDER_TYPE IN ('6')
                                        AND     CO.SETTLE_STATUS = 2
										AND     CO.ISCOLORINPAPER = 0
										AND     CC.ISALBADOWN = '1'
										AND     (COW.FTYPE IS NULL OR COW.FTYPE <> '5')
										AND		((CO.COMPANY_SEQ = 5007 AND CO.SETTLE_STATUS = 2) OR CO.COMPANY_SEQ <> 5007)
										ORDER BY CO.ORDER_DATE ASC
										OFFSET 0 ROWS
										FETCH NEXT @P_DIGITAL_WEDDING_INVITATION_COUNT ROWS ONLY
									)

			SET @DIGITAL_WEDDING_INVITATION_DOWNLOADED_COUNT = @@ROWCOUNT

		END
		


	SELECT	@WEDDING_INVITATION_DOWNLOADED_COUNT  			AS WEDDING_INVITATION_DOWNLOADED_COUNT
		,	@THANKS_INVITATION_DOWNLOADED_COUNT				AS THANKS_INVITATION_DOWNLOADED_COUNT
		,	@DIGITAL_WEDDING_INVITATION_DOWNLOADED_COUNT	AS DIGITAL_WEDDING_INVITATION_DOWNLOADED_COUNT

END
GO
