IF OBJECT_ID (N'dbo.SP_INSERT_S2_USERINFO_THIRD_PARTY_MARKETING_AGREEMENT', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_INSERT_S2_USERINFO_THIRD_PARTY_MARKETING_AGREEMENT
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

EXEC SP_INSERT_S2_USERINFO_THIRD_PARTY_MARKETING_AGREEMENT 'sharniel1', '119001,119002'

*/

CREATE PROCEDURE [dbo].[SP_INSERT_S2_USERINFO_THIRD_PARTY_MARKETING_AGREEMENT]

    @P_UID						AS VARCHAR(50)
,   @P_MARKETING_TYPE_CODE		AS VARCHAR(100)

AS
BEGIN

	IF @P_MARKETING_TYPE_CODE <> ''
	BEGIN



		INSERT INTO S2_USERINFO_THIRD_PARTY_MARKETING_AGREEMENT (UID, MARKETING_TYPE_CODE, USE_YORN)

		SELECT	@P_UID
			,	MTC.VALUE
			,	'Y'
		FROM	ufn_SplitTableForRowNum(@P_MARKETING_TYPE_CODE, ',') MTC
		JOIN	COMMON_CODE CC ON MTC.VALUE = CC.CMMN_CODE

		WHERE	MTC.VALUE NOT IN (
			
			-- 중복 가입 방지용
			SELECT	MARKETING_TYPE_CODE
			FROM	S2_USERINFO_THIRD_PARTY_MARKETING_AGREEMENT
			WHERE	UID = @P_UID
			GROUP BY MARKETING_TYPE_CODE
		)
		


		UPDATE	S2_USERINFO
		SET		mkt_chk_flag = 'Y'
		WHERE	UID = @P_UID

		UPDATE	S2_USERINFO_BHANDS
		SET		mkt_chk_flag = 'Y'
		WHERE	UID = @P_UID

		UPDATE	S2_USERINFO_THECARD
		SET		mkt_chk_flag = 'Y'
		WHERE	UID = @P_UID

	END
				
END		

GO
