IF OBJECT_ID (N'dbo.SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG', N'P') IS NOT NULL DROP PROCEDURE dbo.SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_INSERT_BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG]

    @P_DUPINFO		AS VARCHAR(100)
,   @P_ID			AS VARCHAR(100)
,   @P_STEP			AS VARCHAR(100)
,   @P_STEP_DESC	AS VARCHAR(MAX)


AS
BEGIN



INSERT INTO BARUNN_INTEGRATE_USER_CHANGE_PROGRESS_LOG	(
																DUPINFO
															,	ID
															,	STEP
															,	STEP_DESC
														)
VALUES	(
				@P_DUPINFO	
			,	@P_ID		
			,	@P_STEP		
			,	@P_STEP_DESC	
		)



END

GO
