IF OBJECT_ID (N'dbo.V_LMS_HIST_SD', N'V') IS NOT NULL DROP View dbo.V_LMS_HIST_SD
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[V_LMS_HIST_SD]
AS
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 2 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       LMS_MSG, SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_LMS_HIST_SD_01(READPAST)
UNION ALL
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 2 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       LMS_MSG, SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_LMS_HIST_SD_02(READPAST)
UNION ALL
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 2 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       LMS_MSG, SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_LMS_HIST_SD_03(READPAST)
UNION ALL
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 2 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       LMS_MSG, SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_LMS_HIST_SD_04(READPAST)
UNION ALL
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 2 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       LMS_MSG, SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_LMS_HIST_SD_05(READPAST)
UNION ALL
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 2 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       LMS_MSG, SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_LMS_HIST_SD_06(READPAST)
UNION ALL
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 2 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       LMS_MSG, SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_LMS_HIST_SD_07(READPAST)
UNION ALL
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 2 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       LMS_MSG, SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_LMS_HIST_SD_08(READPAST)
UNION ALL
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 2 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       LMS_MSG, SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_LMS_HIST_SD_09(READPAST)
UNION ALL
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 2 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       LMS_MSG, SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_LMS_HIST_SD_10(READPAST)
UNION ALL
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 2 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       LMS_MSG, SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_LMS_HIST_SD_11(READPAST)
UNION ALL
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 2 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       LMS_MSG, SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_LMS_HIST_SD_12(READPAST);
GO
