IF OBJECT_ID (N'dbo.V_MMS_HIST_SD', N'V') IS NOT NULL DROP View dbo.V_MMS_HIST_SD
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[V_MMS_HIST_SD]
AS
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 3 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       MMS_MSG,IMAGE_PATH_01, IMAGE_PATH_02, IMAGE_PATH_03, AUDIO_PATH, VIDEO_PATH,
       SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_MMS_HIST_SD_01(READPAST)
UNION ALL
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 3 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       MMS_MSG,IMAGE_PATH_01, IMAGE_PATH_02, IMAGE_PATH_03, AUDIO_PATH, VIDEO_PATH,
       SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_MMS_HIST_SD_02(READPAST)
UNION ALL
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 3 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       MMS_MSG,IMAGE_PATH_01, IMAGE_PATH_02, IMAGE_PATH_03, AUDIO_PATH, VIDEO_PATH,
       SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_MMS_HIST_SD_03(READPAST)
UNION ALL
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 3 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       MMS_MSG,IMAGE_PATH_01, IMAGE_PATH_02, IMAGE_PATH_03, AUDIO_PATH, VIDEO_PATH,
       SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_MMS_HIST_SD_04(READPAST)
UNION ALL
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 3 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       MMS_MSG,IMAGE_PATH_01, IMAGE_PATH_02, IMAGE_PATH_03, AUDIO_PATH, VIDEO_PATH,
       SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_MMS_HIST_SD_05(READPAST)
UNION ALL
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 3 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       MMS_MSG,IMAGE_PATH_01, IMAGE_PATH_02, IMAGE_PATH_03, AUDIO_PATH, VIDEO_PATH,
       SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_MMS_HIST_SD_06(READPAST)
UNION ALL
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 3 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       MMS_MSG,IMAGE_PATH_01, IMAGE_PATH_02, IMAGE_PATH_03, AUDIO_PATH, VIDEO_PATH,
       SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_MMS_HIST_SD_07(READPAST)
UNION ALL
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 3 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       MMS_MSG,IMAGE_PATH_01, IMAGE_PATH_02, IMAGE_PATH_03, AUDIO_PATH, VIDEO_PATH,
       SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_MMS_HIST_SD_08(READPAST)
UNION ALL
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 3 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       MMS_MSG,IMAGE_PATH_01, IMAGE_PATH_02, IMAGE_PATH_03, AUDIO_PATH, VIDEO_PATH,
       SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_MMS_HIST_SD_09(READPAST)
UNION ALL
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 3 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       MMS_MSG,IMAGE_PATH_01, IMAGE_PATH_02, IMAGE_PATH_03, AUDIO_PATH, VIDEO_PATH,
       SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_MMS_HIST_SD_10(READPAST)
UNION ALL
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 3 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       MMS_MSG,IMAGE_PATH_01, IMAGE_PATH_02, IMAGE_PATH_03, AUDIO_PATH, VIDEO_PATH,
       SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_MMS_HIST_SD_11(READPAST)
UNION ALL
SELECT MSG_KEY, IN_TIME, SERVICE_CODE, 3 AS MSG_TYPE, CALLEE_NO, CALLBACK_NO, CALLBACK_URL, SUBJECT,
       MMS_MSG,IMAGE_PATH_01, IMAGE_PATH_02, IMAGE_PATH_03, AUDIO_PATH, VIDEO_PATH,
       SAVE_TIME, SEND_TIME, RESULT_TIME, DELIVERY_TIME, PROC_RESULT, ORDER_FLAG,
       TR_SECT, USER_VAR, USER_INT
  FROM T_MMS_HIST_SD_12(READPAST);
GO
