IF OBJECT_ID (N'dbo.view_cardRank', N'V') IS NOT NULL DROP View dbo.view_cardRank
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[view_cardRank]
AS
SELECT   TOP 50 CARD_SEQ, SALES_RANKING
FROM      dbo.CARD
WHERE   (CARD_GROUP = '1') AND (DISPLAY_YES_OR_NO = '1')
ORDER BY SALES_RANKING
GO
