IF OBJECT_ID (N'dbo.VIEW_DELIVERYLST_TEST', N'V') IS NOT NULL DROP View dbo.VIEW_DELIVERYLST_TEST
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VIEW_DELIVERYLST_TEST]
AS

SELECT  'W' AS OTYPE, A.ORDER_SEQ, A.SALES_GUBUN, A.COMPANY_SEQ, D .COMPANY_NAME, 
		A.SRC_SEND_DATE AS DELIVERY_DATE, B.NAME AS RECV_NAME, B.ADDR + ' ' + ISNULL(B.ADDR_DETAIL, '') 
		AS RECV_ADDRESS, C.DELIVERY_COM, C.DELIVERY_CODE_NUM AS DELIVERY_CODE, 
		--D.ERP_PARTCODE, 
		ERP_PARTCODE = CASE WHEN D.ERP_PARTCODE IS NULL AND D.SALES_GUBUN = 'P'
								THEN 'P' 
							WHEN  D.ERP_PARTCODE IS NULL AND D.SALES_GUBUN = 'Q'
								THEN 'Q' 
						ELSE D.ERP_PARTCODE
						END,
		A.SRC_PACKING_DATE AS PACKING_DATE
FROM	CUSTOM_ORDER A INNER JOIN
		DELIVERY_INFO B ON A.ORDER_SEQ = B.ORDER_SEQ, DELIVERY_INFO_DELCODE C, COMPANY D
WHERE	B.ID = C.DELIVERY_ID AND A.COMPANY_SEQ = D .COMPANY_SEQ AND C.DELIVERY_COM IN ('HJ', 'CJ') AND 
        B.DELIVERY_METHOD = 1
UNION ALL

SELECT  'S' AS OTYPE, SAMPLE_ORDER_SEQ AS ORDER_SEQ, A.SALES_GUBUN, A.COMPANY_SEQ, B.COMPANY_NAME, 
               DELIVERY_DATE, MEMBER_NAME AS RECV_NAME, MEMBER_ADDRESS + ' ' + MEMBER_ADDRESS_DETAIL AS RECV_ADDRESS, 
               DELIVERY_COM, DELIVERY_CODE_NUM AS DELIVERY_CODE, 
			   --B.ERP_PARTCODE, 
			     ERP_PARTCODE = CASE WHEN B.ERP_PARTCODE IS NULL AND B.SALES_GUBUN = 'P'
									THEN 'P' 
								WHEN  B.ERP_PARTCODE IS NULL AND B.SALES_GUBUN = 'Q'
									THEN 'Q' 
								ELSE B.ERP_PARTCODE
								END,
			   PREPARE_DATE AS PACKING_DATE
FROM     CUSTOM_SAMPLE_ORDER A INNER JOIN
               COMPANY B ON A.COMPANY_SEQ = B.COMPANY_SEQ
WHERE  DELIVERY_COM IN ( 'HJ' , 'CJ' )

UNION ALL

SELECT  'E' AS OTYPE, ORDER_SEQ, A.SALES_GUBUN, A.COMPANY_SEQ, B.COMPANY_NAME, DELIVERY_DATE, RECV_NAME, 
               ISNULL(RECV_ADDRESS, '') + ' ' + ISNULL(RECV_ADDRESS_DETAIL, '') AS RECV_ADDRESS, DELIVERY_COM, DELIVERY_CODE, 
			   --B.ERP_PARTCODE, 
			    ERP_PARTCODE = CASE WHEN B.ERP_PARTCODE IS NULL AND B.SALES_GUBUN = 'P'
									THEN 'P' 
								WHEN  B.ERP_PARTCODE IS NULL AND B.SALES_GUBUN = 'Q'
									THEN 'Q' 
								ELSE B.ERP_PARTCODE
								END,

               PREPARE_DATE AS PACKING_DATE
FROM     CUSTOM_ETC_ORDER A INNER JOIN
               COMPANY B ON A.COMPANY_SEQ = B.COMPANY_SEQ
WHERE  DELIVERY_COM IN ( 'HJ' , 'CJ' )



--SELECT  'W' AS OTYPE, A.ORDER_SEQ, A.SALES_GUBUN, A.COMPANY_SEQ, D .COMPANY_NAME, 
--               A.SRC_SEND_DATE AS DELIVERY_DATE, B.NAME AS RECV_NAME, B.ADDR + ' ' + ISNULL(B.ADDR_DETAIL, '') 
--               AS RECV_ADDRESS, C.DELIVERY_COM, C.DELIVERY_CODE_NUM AS DELIVERY_CODE, D .ERP_PARTCODE, 
--               A.SRC_PACKING_DATE AS PACKING_DATE
--FROM     CUSTOM_ORDER A INNER JOIN
--               DELIVERY_INFO B ON A.ORDER_SEQ = B.ORDER_SEQ, DELIVERY_INFO_DELCODE C, COMPANY D
--WHERE  B.ID = C.DELIVERY_ID AND A.COMPANY_SEQ = D .COMPANY_SEQ AND C.DELIVERY_COM IN ( 'HJ' , 'CJ' ) AND 
--               B.DELIVERY_METHOD = 1
--UNION ALL

--SELECT  'S' AS OTYPE, SAMPLE_ORDER_SEQ AS ORDER_SEQ, A.SALES_GUBUN, A.COMPANY_SEQ, B.COMPANY_NAME, 
--               DELIVERY_DATE, MEMBER_NAME AS RECV_NAME, MEMBER_ADDRESS + ' ' + MEMBER_ADDRESS_DETAIL AS RECV_ADDRESS, 
--               DELIVERY_COM, DELIVERY_CODE_NUM AS DELIVERY_CODE, B.ERP_PARTCODE, PREPARE_DATE AS PACKING_DATE
--FROM     CUSTOM_SAMPLE_ORDER A INNER JOIN
--               COMPANY B ON A.COMPANY_SEQ = B.COMPANY_SEQ
--WHERE  DELIVERY_COM IN ( 'HJ' , 'CJ' )

--UNION ALL

--SELECT  'E' AS OTYPE, ORDER_SEQ, A.SALES_GUBUN, A.COMPANY_SEQ, B.COMPANY_NAME, DELIVERY_DATE, RECV_NAME, 
--               ISNULL(RECV_ADDRESS, '') + ' ' + ISNULL(RECV_ADDRESS_DETAIL, '') AS RECV_ADDRESS, DELIVERY_COM, DELIVERY_CODE, B.ERP_PARTCODE, 
--               PREPARE_DATE AS PACKING_DATE
--FROM     CUSTOM_ETC_ORDER A INNER JOIN
--               COMPANY B ON A.COMPANY_SEQ = B.COMPANY_SEQ
--WHERE  DELIVERY_COM IN ( 'HJ' , 'CJ' )
GO
