SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

    
	
/*
2020-03-03
order_price ->> order_total_price 로 할인 변경 

*/    

ALTER VIEW [dbo].[VW_COUPON_CALC_FOR_CO]    
AS    
SELECT  ORDER_SEQ
        , UP_ORDER_SEQ
        , UID
        , COMPANY_SEQ
        , SALES_GUBUN
        , ORDER_TYPE
        , COUPON_ISSUE_SEQ
        , COUPON_DETAIL_SEQ
        , COUPON_NAME
        , COUPON_TYPE_CODE
        , COUPON_SERVICE_TYPE_CODE
        , COUPON_SERVICE_TYPE_NAME
        , DUP_COUPON_ALLOW_YN
        , AD_COUPON_ALLOW_YN
        , ADD_COUPON_ALLOW_YN
        , CARD_SEQ
        , ORDER_COUNT
        , LAST_TOTAL_PRICE
        , USE_DEVICE
        , DISCOUNT_FIXED_RATE_TYPE
        , DISCOUNT_VALUE
        , DISCOUNT_MAX_AMT
        , ISNULL(CAST(ORDER_PRICE_TEMP AS INT), 0) AS ORDER_PRICE
        , ISNULL(CAST(FTICKET_PRICE_TEMP AS INT), 0) AS FTICKET_PRICE
        , ISNULL(CAST(GUESTBOOK_PRICE_TEMP AS INT), 0) AS GUESTBOOK_PRICE
        , ISNULL(CAST(LINING_ENV_PRICE_TEMP AS INT), 0) AS LINING_ENV_PRICE
        , ISNULL(CAST(PRINT_PRICE_TEMP AS INT), 0) AS PRINT_PRICE
        , ISNULL(CAST(EMBO_PRICE_TEMP AS INT), 0) AS EMBO_PRICE
        , ISNULL(CAST(JEBON_PRICE_TEMP AS INT), 0) AS JEBON_PRICE
        , ISNULL(CAST(ENVINSERT_PRICE_TEMP AS INT), 0) AS ENVINSERT_PRICE
        , ISNULL(CAST(EXPRESS_SHIPPING_PRICE_TEMP AS INT), 0) AS EXPRESS_SHIPPING_PRICE
        , ISNULL(CAST(LININGJAEBON_PRICE_TEMP AS INT), 0) AS LININGJAEBON_PRICE
        , ISNULL(CAST(DELIVERY_PRICE_TEMP AS INT), 0) AS DELIVERY_PRICE
        , ISNULL(CAST(DISCOUNT_TARGET_ORDER_PRICE_TEMP AS INT), 0) AS DISCOUNT_TARGET_ORDER_PRICE
        , ISNULL(CAST(DISCOUNT_TARGET_FTICKET_PRICE_TEMP AS INT), 0) AS DISCOUNT_TARGET_FTICKET_PRICE
        , ISNULL(CAST(DISCOUNT_TARGET_GUESTBOOK_PRICE_TEMP AS INT), 0) AS DISCOUNT_TARGET_GUESTBOOK_PRICE
        , ISNULL(CAST(DISCOUNT_TARGET_LINING_ENV_PRICE_TEMP AS INT), 0) AS DISCOUNT_TARGET_LINING_ENV_PRICE

        , ISNULL(CAST(DISCOUNT_TARGET_FLOWER_PRICE_TEMP AS INT), 0) AS DISCOUNT_TARGET_FLOWER_PRICE
        , ISNULL(CAST(DISCOUNT_TARGET_SEALING_PRICE_TEMP AS INT), 0) AS DISCOUNT_TARGET_SEALING_PRICE
        , ISNULL(CAST(DISCOUNT_TARGET_ENVSPECIAL_PRICE_TEMP AS INT), 0) AS DISCOUNT_TARGET_ENVSPECIAL_PRICE
        , ISNULL(CAST(DISCOUNT_TARGET_RIBBON_PRICE_TEMP AS INT), 0) AS DISCOUNT_TARGET_RIBBON_PRICE
        , ISNULL(CAST(DISCOUNT_TARGET_PAPERCOVER_PRICE_TEMP AS INT), 0) AS DISCOUNT_TARGET_PAPERCOVER_PRICE

        , ISNULL(CAST(DISCOUNT_TARGET_PRINT_PRICE_TEMP AS INT), 0) AS DISCOUNT_TARGET_PRINT_PRICE
        , ISNULL(CAST(DISCOUNT_TARGET_EMBO_PRICE_TEMP AS INT), 0) AS DISCOUNT_TARGET_EMBO_PRICE
        , ISNULL(CAST(DISCOUNT_TARGET_JEBON_PRICE_TEMP AS INT), 0) AS DISCOUNT_TARGET_JEBON_PRICE
        , ISNULL(CAST(DISCOUNT_TARGET_ENVINSERT_PRICE_TEMP AS INT), 0) AS DISCOUNT_TARGET_ENVINSERT_PRICE
        , ISNULL(CAST(DISCOUNT_TARGET_DELIVERY_PRICE_TEMP AS INT), 0) AS DISCOUNT_TARGET_DELIVERY_PRICE
        , ISNULL(CAST(DISCOUNT_TARGET_EXPRESS_SHIPPING_PRICE_TEMP AS INT), 0) AS DISCOUNT_TARGET_EXPRESS_SHIPPING_PRICE
        , ISNULL(CAST(DISCOUNT_TARGET_LININGJAEBON_PRICE_TEMP AS INT), 0) AS DISCOUNT_TARGET_LININGJAEBON_PRICE
        , ISNULL(CAST(CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_ORDER_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_ORDER_PRICE_TEMP END AS NUMERIC(29, 6)), 0) AS DISCOUNT_ORDER_PRICE
        , ISNULL(CAST(CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_FTICKET_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_FTICKET_PRICE_TEMP END AS NUMERIC(29, 6)), 0) AS DISCOUNT_FTICKET_PRICE
        , ISNULL(CAST(CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_GUESTBOOK_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_GUESTBOOK_PRICE_TEMP END AS NUMERIC(29, 6)), 0) AS DISCOUNT_GUESTBOOK_PRICE
        , ISNULL(CAST(CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_LINING_ENV_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_LINING_ENV_PRICE_TEMP END AS NUMERIC(29, 6)), 0) AS DISCOUNT_LINING_ENV_PRICE
        
        , ISNULL(CAST(CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_FLOWER_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_FLOWER_PRICE_TEMP END AS NUMERIC(29, 6)), 0) AS DISCOUNT_FLOWER_PRICE
        , ISNULL(CAST(CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_SEALING_STICKER_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_SEALING_STICKER_PRICE_TEMP END AS NUMERIC(29, 6)), 0) AS DISCOUNT_SEALING_STICKER_PRICE
        , ISNULL(CAST(CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_ENVSPECIAL_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_ENVSPECIAL_PRICE_TEMP END AS NUMERIC(29, 6)), 0) AS DISCOUNT_ENVSPECIAL_PRICE
        , ISNULL(CAST(CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_RIBBON_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_RIBBON_PRICE_TEMP END AS NUMERIC(29, 6)), 0) AS DISCOUNT_RIBBON_PRICE
        , ISNULL(CAST(CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_PAPERCOVER_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_PAPERCOVER_PRICE_TEMP END AS NUMERIC(29, 6)), 0) AS DISCOUNT_PAPERCOVER_PRICE
        
        , ISNULL(CAST(CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_PRINT_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_PRINT_PRICE_TEMP END AS NUMERIC(29, 6)), 0) AS DISCOUNT_PRINT_PRICE
        , ISNULL(CAST(CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_EMBO_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_EMBO_PRICE_TEMP END AS NUMERIC(29, 6)), 0) AS DISCOUNT_EMBO_PRICE
        , ISNULL(CAST(CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_JEBON_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_JEBON_PRICE_TEMP END AS NUMERIC(29, 6)), 0) AS DISCOUNT_JEBON_PRICE
        , ISNULL(CAST(CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_ENVINSERT_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_ENVINSERT_PRICE_TEMP END AS NUMERIC(29, 6)), 0) AS DISCOUNT_ENVINSERT_PRICE
        , ISNULL(CAST(CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_DELIVERY_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_DELIVERY_PRICE_TEMP END AS NUMERIC(29, 6)), 0) AS DISCOUNT_DELIVERY_PRICE
        , ISNULL(CAST(CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_EXPRESS_SHIPPING_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_EXPRESS_SHIPPING_PRICE_TEMP END AS NUMERIC(29, 6)), 0) AS DISCOUNT_EXPRESS_SHIPPING_PRICE
		, ISNULL(CAST(CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_LININGJAEBON_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_LININGJAEBON_PRICE_TEMP END AS NUMERIC(29, 6)), 0) AS DISCOUNT_LININGJAEBON_PRICE
        
        , ISNULL(CAST(CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_ORDER_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_ORDER_PRICE_TEMP END 
                + CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_FTICKET_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_FTICKET_PRICE_TEMP END 
                + CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_GUESTBOOK_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_GUESTBOOK_PRICE_TEMP END 
                + CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_LINING_ENV_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_LINING_ENV_PRICE_TEMP END 
                
                + CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_FLOWER_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_FLOWER_PRICE_TEMP END
                + CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_SEALING_STICKER_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_SEALING_STICKER_PRICE_TEMP END
                + CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_ENVSPECIAL_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_ENVSPECIAL_PRICE_TEMP END
                + CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_RIBBON_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_RIBBON_PRICE_TEMP END
                + CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_PAPERCOVER_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_PAPERCOVER_PRICE_TEMP END
                
                + CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_PRINT_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_PRINT_PRICE_TEMP END 
                + CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_EMBO_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_EMBO_PRICE_TEMP END 
                + CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_JEBON_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_JEBON_PRICE_TEMP END 
                + CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_ENVINSERT_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_ENVINSERT_PRICE_TEMP END 
                + CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_DELIVERY_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_DELIVERY_PRICE_TEMP END 
                + CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_EXPRESS_SHIPPING_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_EXPRESS_SHIPPING_PRICE_TEMP END AS NUMERIC(29, 6)), 0) 
				+ CASE WHEN DISCOUNT_MAX_AMT > 0 AND DISCOUNT_LININGJAEBON_PRICE_TEMP > DISCOUNT_MAX_AMT THEN DISCOUNT_MAX_AMT ELSE DISCOUNT_LININGJAEBON_PRICE_TEMP END 
                
               AS DISCOUNT_TOTAL_PRICE  

FROM (
        SELECT  CO.order_seq AS ORDER_SEQ
                , MAX(CO.up_order_seq) AS UP_ORDER_SEQ
                , MAX(CI.UID) AS UID
                , MAX(CO.company_seq) AS COMPANY_SEQ
                , MAX(CO.sales_Gubun) AS SALES_GUBUN
                , MAX(CO.order_type) AS ORDER_TYPE
                , MAX(CI.COUPON_ISSUE_SEQ) AS COUPON_ISSUE_SEQ
                , CI.COUPON_DETAIL_SEQ
                , MAX(CM.COUPON_NAME) AS COUPON_NAME
                , MAX(CM.COUPON_TYPE_CODE) AS COUPON_TYPE_CODE
                , MIN(CA_SERVICE.CMMN_CODE) AS COUPON_SERVICE_TYPE_CODE
                , MAX
                (
                    CASE 
                        WHEN CO.ORDER_TYPE IN (1, 6, 7) AND CC_SERVICE.CMMN_CODE = '131001' THEN '청첩장' 
                        WHEN CO.ORDER_TYPE IN (2) AND CC_SERVICE.CMMN_CODE = '131002' THEN '감사장' 
                        WHEN CO.ORDER_TYPE IN (3) AND CC_SERVICE.CMMN_CODE = '131003' THEN '초대장' 
                        ELSE CC_SERVICE.DTL_NAME 
                    END
                ) AS COUPON_SERVICE_TYPE_NAME
                , MAX(CM.DUP_COUPON_ALLOW_YN) AS DUP_COUPON_ALLOW_YN
                , MAX(CM.AD_COUPON_ALLOW_YN) AS AD_COUPON_ALLOW_YN
                , MAX(CM.ADD_COUPON_ALLOW_YN) AS ADD_COUPON_ALLOW_YN
                , MAX(CO.card_seq) AS CARD_SEQ
                , MAX(CO.order_count) AS ORDER_COUNT
                , MAX(CO.last_total_price) AS LAST_TOTAL_PRICE
                , MAX(CM.USE_DEVICE) AS USE_DEVICE
                , MAX(CM.DISCOUNT_FIXED_RATE_TYPE) AS DISCOUNT_FIXED_RATE_TYPE
                , MAX(CM.DISCOUNT_VALUE) AS DISCOUNT_VALUE
                , MAX(CM.DISCOUNT_MAX_AMT) AS DISCOUNT_MAX_AMT
                , MAX(CO.order_total_price) AS ORDER_PRICE_TEMP
                , MAX(CO.fticket_price) AS FTICKET_PRICE_TEMP
                , MAX(CO.guestbook_price) AS GUESTBOOK_PRICE_TEMP
                , MAX(ISNULL(COI.item_sale_price, 0)) AS LINING_ENV_PRICE_TEMP
                , MAX(CO.print_price) AS PRINT_PRICE_TEMP
                , MAX(CO.embo_price) AS EMBO_PRICE_TEMP
                , MAX(CO.jebon_price) AS JEBON_PRICE_TEMP
                , MAX(CO.envInsert_price) AS ENVINSERT_PRICE_TEMP
                , MAX
                (
                    CASE 
                        WHEN CO.ISSPECIAL = 1 
                        THEN (CASE WHEN ETC_PRICE > 35000 THEN 35000 ELSE ETC_PRICE END) 
                        ELSE 0 
                    END
                ) AS EXPRESS_SHIPPING_PRICE_TEMP
				, MAX(CO.LININGJAEBON_PRICE) AS LININGJAEBON_PRICE_TEMP
                , MAX(CO.delivery_price) AS DELIVERY_PRICE_TEMP
                , MAX(CASE WHEN CA_SERVICE.CMMN_CODE IN ('133001', '133002', '133003') THEN CO.order_total_price ELSE 0 END) AS DISCOUNT_TARGET_ORDER_PRICE_TEMP
                , MAX(CASE WHEN CA_SERVICE.CMMN_CODE = '134001' THEN CO.FTICKET_PRICE ELSE 0 END) AS DISCOUNT_TARGET_FTICKET_PRICE_TEMP
                , MAX(CASE WHEN CA_SERVICE.CMMN_CODE = '134002' THEN CO.GUESTBOOK_PRICE ELSE 0 END) AS DISCOUNT_TARGET_GUESTBOOK_PRICE_TEMP
                , MAX(CASE WHEN CA_SERVICE.CMMN_CODE = '134003' THEN ISNULL(CAST(COI.ITEM_SALE_PRICE AS INT), 0) ELSE 0 END) AS DISCOUNT_TARGET_LINING_ENV_PRICE_TEMP

                , MAX(CASE WHEN CA_SERVICE.CMMN_CODE = '134004' THEN CO.flower_price ELSE 0 END) AS DISCOUNT_TARGET_FLOWER_PRICE_TEMP
                , MAX(CASE WHEN CA_SERVICE.CMMN_CODE = '134005' THEN CO.sealing_sticker_price ELSE 0 END) AS DISCOUNT_TARGET_SEALING_PRICE_TEMP
                , MAX(CASE WHEN CA_SERVICE.CMMN_CODE = '134006' THEN CO.EnvSpecial_price ELSE 0 END) AS DISCOUNT_TARGET_ENVSPECIAL_PRICE_TEMP
                , MAX(CASE WHEN CA_SERVICE.CMMN_CODE = '134007' THEN CO.ribbon_price ELSE 0 END) AS DISCOUNT_TARGET_RIBBON_PRICE_TEMP
                , MAX(CASE WHEN CA_SERVICE.CMMN_CODE = '134008' THEN CO.paperCover_price ELSE 0 END) AS DISCOUNT_TARGET_PAPERCOVER_PRICE_TEMP

                , MAX(CASE WHEN CA_SERVICE.CMMN_CODE = '135001' THEN CO.PRINT_PRICE ELSE 0 END) AS DISCOUNT_TARGET_PRINT_PRICE_TEMP
                , MAX(CASE WHEN CA_SERVICE.CMMN_CODE = '135002' THEN CO.EMBO_PRICE ELSE 0 END) AS DISCOUNT_TARGET_EMBO_PRICE_TEMP
                , MAX(CASE WHEN CA_SERVICE.CMMN_CODE IN ('135003','135005') THEN CO.JEBON_PRICE ELSE 0 END) AS DISCOUNT_TARGET_JEBON_PRICE_TEMP
                , MAX(CASE WHEN CA_SERVICE.CMMN_CODE = '135004' THEN CO.ENVINSERT_PRICE ELSE 0 END) AS DISCOUNT_TARGET_ENVINSERT_PRICE_TEMP
                , MAX(CASE WHEN CA_SERVICE.CMMN_CODE = '135006' THEN CO.DELIVERY_PRICE ELSE 0 END) AS DISCOUNT_TARGET_DELIVERY_PRICE_TEMP
                , MAX(
                    CASE 
                        WHEN CA_SERVICE.CMMN_CODE = '135007' AND CO.ISSPECIAL = 1 
                        THEN CASE WHEN ETC_PRICE > 35000 THEN 35000 ELSE ETC_PRICE END 
                        ELSE 0 
                    END
                    ) AS DISCOUNT_TARGET_EXPRESS_SHIPPING_PRICE_TEMP
				, MAX(CASE WHEN CA_SERVICE.CMMN_CODE = '135010' THEN CO.LININGJAEBON_PRICE ELSE 0 END) AS DISCOUNT_TARGET_LININGJAEBON_PRICE_TEMP
                
                , MAX(
                    CASE 
                        WHEN CA_SERVICE.CMMN_CODE IN ('133001', '133002', '133003')   
                        THEN 
                            CASE 
                            WHEN CM.DISCOUNT_FIXED_RATE_TYPE = 'W' THEN CASE WHEN CO.order_total_price - CM.DISCOUNT_VALUE <= 0 THEN CO.order_total_price ELSE CM.DISCOUNT_VALUE END 
                            ELSE CO.order_total_price * (1.0 * CM.DISCOUNT_VALUE / 100) 
                            END 
                        ELSE 0 
                    END
                    ) AS DISCOUNT_ORDER_PRICE_TEMP
                , MAX(
                    CASE 
                        WHEN CA_SERVICE.CMMN_CODE = '134001' 
                        THEN 
                        CASE 
                            WHEN CM.DISCOUNT_FIXED_RATE_TYPE = 'W' THEN CASE WHEN CO.FTICKET_PRICE - CM.DISCOUNT_VALUE <= 0 THEN CO.FTICKET_PRICE ELSE CM.DISCOUNT_VALUE END 
                            ELSE CO.FTICKET_PRICE * (1.0 * CM.DISCOUNT_VALUE / 100) END 
                        ELSE 0 
                        END
                    ) AS DISCOUNT_FTICKET_PRICE_TEMP
                , MAX(
                    CASE 
                        WHEN CA_SERVICE.CMMN_CODE = '134002' 
                        THEN 
                        CASE 
                            WHEN CM.DISCOUNT_FIXED_RATE_TYPE = 'W' THEN CASE WHEN CO.GUESTBOOK_PRICE - CM.DISCOUNT_VALUE <= 0 THEN CO.GUESTBOOK_PRICE ELSE CM.DISCOUNT_VALUE END 
							ELSE CO.GUESTBOOK_PRICE * (1.0 * CM.DISCOUNT_VALUE / 100) END 
                        ELSE 0 
                        END
                    ) AS DISCOUNT_GUESTBOOK_PRICE_TEMP
                , MAX(
                    CASE 
                        WHEN CA_SERVICE.CMMN_CODE = '134003' 
                        THEN 
                        CASE 
                            WHEN CM.DISCOUNT_FIXED_RATE_TYPE = 'W' THEN CASE WHEN ISNULL(COI.ITEM_SALE_PRICE, 0) - CM.DISCOUNT_VALUE <= 0 THEN ISNULL(COI.ITEM_SALE_PRICE, 0) ELSE CM.DISCOUNT_VALUE END 
                            ELSE ISNULL(COI.ITEM_SALE_PRICE, 0) * (1.0 * CM.DISCOUNT_VALUE / 100) END 
                        ELSE 0 
                        END
                    ) AS DISCOUNT_LINING_ENV_PRICE_TEMP
                            
                , MAX(
                    CASE
                      	WHEN CA_SERVICE.CMMN_CODE = '134004'
                      	THEN
                      		CASE 
                      			WHEN CM.DISCOUNT_FIXED_RATE_TYPE = 'W' THEN CASE WHEN CO.FLOWER_PRICE - CM.DISCOUNT_VALUE <= 0 THEN CO.FLOWER_PRICE ELSE CM.DISCOUNT_VALUE END
                      			ELSE CO.FLOWER_PRICE * (1.0 * CM.DISCOUNT_VALUE / 100) END
                      		ELSE 0
                      	END
                    ) AS DISCOUNT_FLOWER_PRICE_TEMP
                , MAX(
                    CASE
                      	WHEN CA_SERVICE.CMMN_CODE = '134005'
                      	THEN
                      		CASE 
                      			WHEN CM.DISCOUNT_FIXED_RATE_TYPE = 'W' THEN CASE WHEN CO.sealing_sticker_price - CM.DISCOUNT_VALUE <= 0 THEN CO.sealing_sticker_price ELSE CM.DISCOUNT_VALUE END
                      			ELSE CO.sealing_sticker_price * (1.0 * CM.DISCOUNT_VALUE / 100) END
                      		ELSE 0
                      	END
                    ) AS DISCOUNT_SEALING_STICKER_PRICE_TEMP
                , MAX(
                    CASE
                      	WHEN CA_SERVICE.CMMN_CODE = '134006'
                      	THEN
                      		CASE 
                      			WHEN CM.DISCOUNT_FIXED_RATE_TYPE = 'W' THEN CASE WHEN CO.EnvSpecial_Price - CM.DISCOUNT_VALUE <= 0 THEN CO.EnvSpecial_Price ELSE CM.DISCOUNT_VALUE END
                      			ELSE CO.EnvSpecial_Price * (1.0 * CM.DISCOUNT_VALUE / 100) END
                      		ELSE 0
                      	END
                    ) AS DISCOUNT_ENVSPECIAL_PRICE_TEMP
                , MAX(
                    CASE
                      	WHEN CA_SERVICE.CMMN_CODE = '134007'
                      	THEN
                      		CASE 
                      			WHEN CM.DISCOUNT_FIXED_RATE_TYPE = 'W' THEN CASE WHEN CO.ribbon_price - CM.DISCOUNT_VALUE <= 0 THEN CO.ribbon_price ELSE CM.DISCOUNT_VALUE END
                      			ELSE CO.ribbon_price * (1.0 * CM.DISCOUNT_VALUE / 100) END
                      		ELSE 0
                      	END
                    ) AS DISCOUNT_RIBBON_PRICE_TEMP
                , MAX(
                    CASE
                      	WHEN CA_SERVICE.CMMN_CODE = '134008'
                      	THEN
                      		CASE 
                      			WHEN CM.DISCOUNT_FIXED_RATE_TYPE = 'W' THEN CASE WHEN CO.paperCover_price - CM.DISCOUNT_VALUE <= 0 THEN CO.paperCover_price ELSE CM.DISCOUNT_VALUE END
                      			ELSE CO.paperCover_price * (1.0 * CM.DISCOUNT_VALUE / 100) END
                      		ELSE 0
                      	END
                    ) AS DISCOUNT_PAPERCOVER_PRICE_TEMP
                      
                      		
                      		
                , MAX(
					CASE 
                        WHEN CA_SERVICE.CMMN_CODE = '135001' 
                        THEN 
                        CASE 
                            WHEN CM.DISCOUNT_FIXED_RATE_TYPE = 'W' THEN CASE WHEN CO.PRINT_PRICE - CM.DISCOUNT_VALUE <= 0 THEN CO.PRINT_PRICE ELSE CM.DISCOUNT_VALUE END 
                            ELSE CO.PRINT_PRICE * (1.0 * CM.DISCOUNT_VALUE / 100) END 
                        ELSE 0 
                        END
                    ) AS DISCOUNT_PRINT_PRICE_TEMP
                , MAX(
                    CASE 
                        WHEN CA_SERVICE.CMMN_CODE = '135002' 
                        THEN 
                        CASE 
                            WHEN CM.DISCOUNT_FIXED_RATE_TYPE = 'W' THEN CASE WHEN CO.EMBO_PRICE - CM.DISCOUNT_VALUE <= 0 THEN CO.EMBO_PRICE ELSE CM.DISCOUNT_VALUE END 
                            ELSE CO.EMBO_PRICE * (1.0 * CM.DISCOUNT_VALUE / 100) END 
                        ELSE 0 
                        END
                    ) AS DISCOUNT_EMBO_PRICE_TEMP
                , MAX(
                    CASE 
                        WHEN CA_SERVICE.CMMN_CODE IN ('135003','135005') 
                        THEN 
                        CASE 
                            WHEN CM.DISCOUNT_FIXED_RATE_TYPE = 'W' THEN CASE WHEN CO.JEBON_PRICE - CM.DISCOUNT_VALUE <= 0 THEN CO.JEBON_PRICE ELSE CM.DISCOUNT_VALUE END 
                            ELSE CO.JEBON_PRICE * (1.0 * CM.DISCOUNT_VALUE / 100) END 
                        ELSE 0 
                        END
                    ) AS DISCOUNT_JEBON_PRICE_TEMP
                , MAX(
                    CASE 
                        WHEN CA_SERVICE.CMMN_CODE = '135004' 
                        THEN 
                        CASE 
                            WHEN CM.DISCOUNT_FIXED_RATE_TYPE = 'W' THEN CASE WHEN CO.ENVINSERT_PRICE - CM.DISCOUNT_VALUE <= 0 THEN CO.ENVINSERT_PRICE ELSE CM.DISCOUNT_VALUE END 
                            ELSE CO.ENVINSERT_PRICE * (1.0 * CM.DISCOUNT_VALUE / 100) END 
                        ELSE 0 
                        END
                    ) AS DISCOUNT_ENVINSERT_PRICE_TEMP
                , MAX(
                    CASE 
                        WHEN CA_SERVICE.CMMN_CODE = '135006' 
                        THEN 
                        CASE 
                            WHEN CM.DISCOUNT_FIXED_RATE_TYPE = 'W' THEN CASE WHEN CO.DELIVERY_PRICE - CM.DISCOUNT_VALUE <= 0 THEN CO.DELIVERY_PRICE ELSE CM.DISCOUNT_VALUE END 
                            ELSE CO.DELIVERY_PRICE * (1.0 * CM.DISCOUNT_VALUE / 100) END 
                        ELSE 0 
                        END
                    ) AS DISCOUNT_DELIVERY_PRICE_TEMP
                , MAX(
                    CASE 
                        WHEN CA_SERVICE.CMMN_CODE = '135007' AND CO.ISSPECIAL = 1 
                        THEN 
                        CASE 
                            WHEN CM.DISCOUNT_FIXED_RATE_TYPE = 'W' THEN CASE WHEN (CASE WHEN ETC_PRICE > 35000 THEN 35000 ELSE ETC_PRICE END) - CM.DISCOUNT_VALUE <= 0 THEN (CASE WHEN ETC_PRICE > 35000 THEN 35000 ELSE ETC_PRICE END) ELSE CM.DISCOUNT_VALUE END 
                            ELSE (CASE WHEN ETC_PRICE > 35000 THEN 35000 ELSE ETC_PRICE END) * (1.0 * CM.DISCOUNT_VALUE / 100) END 
                        ELSE 0 
                        END
                    ) AS DISCOUNT_EXPRESS_SHIPPING_PRICE_TEMP  
				, MAX(
                    CASE 
                        WHEN CA_SERVICE.CMMN_CODE = '135010' --라이닝봉투삽입
                        THEN 
                        CASE 
                            WHEN CM.DISCOUNT_FIXED_RATE_TYPE = 'W' THEN CASE WHEN CO.LININGJAEBON_PRICE - CM.DISCOUNT_VALUE <= 0 THEN CO.LININGJAEBON_PRICE ELSE CM.DISCOUNT_VALUE END 
                            ELSE CO.LININGJAEBON_PRICE * (1.0 * CM.DISCOUNT_VALUE / 100) END 
                        ELSE 0 
                        END
                    ) AS DISCOUNT_LININGJAEBON_PRICE_TEMP
                
        FROM     dbo.COUPON_ISSUE AS CI   
            INNER JOIN dbo.COUPON_DETAIL AS CD ON CD.COUPON_DETAIL_SEQ = CI.COUPON_DETAIL_SEQ   
            INNER JOIN dbo.COUPON_MST AS CM ON CM.COUPON_MST_SEQ = CD.COUPON_MST_SEQ   
            INNER JOIN dbo.COUPON_APPLY_SERVICE AS CA_SERVICE ON CM.COUPON_MST_SEQ = CA_SERVICE.COUPON_MST_SEQ   
            INNER JOIN dbo.COMMON_CODE AS CC_SERVICE ON CA_SERVICE.CMMN_CODE = CC_SERVICE.CMMN_CODE   
            INNER JOIN dbo.COUPON_APPLY_SITE AS CA_SITE ON CM.COUPON_MST_SEQ = CA_SITE.COUPON_MST_SEQ AND CA_SITE.COMPANY_SEQ = CI.COMPANY_SEQ   
            INNER JOIN dbo.custom_order AS CO ON CO.member_id = CI.UID   
            LEFT OUTER JOIN dbo.COUPON_APPLY_CARD AS CA_CARD ON CM.COUPON_MST_SEQ = CA_CARD.COUPON_MST_SEQ   
            LEFT OUTER JOIN dbo.custom_order_item AS COI ON COI.order_seq = CO.order_seq AND COI.item_type = 'D'  
            LEFT JOIN (   
							SELECT A.Card_Seq, A.Card_Code  
							, C.COUPON_APPLY_CARD_SEQ, C.COUPON_MST_SEQ, C.CARD_ALLOW_YN  
							FROM S2_card A   
							LEFT JOIN COUPON_APPLY_CARD C ON A.CARD_SEQ = C.Card_Seq  
							WHERE A.Card_Div = 'A01'           
						) AS CA_CARD_V2 ON CO.card_seq = CA_CARD_V2.CARD_SEQ AND CM.COUPON_MST_SEQ = ISNULL(CA_CARD_V2.COUPON_MST_SEQ, '')  
  
        WHERE	(CA_SERVICE.CLSS_CODE NOT IN ('132')) 
		AND		(CM.STATUS_ACTIVE_YN = 'Y') 
		AND		(CI.ACTIVE_YN = 'Y')   
        AND		(CM.ORDER_TYPE_CODE LIKE '%137001%' 
					AND CO.order_type IN (1, 6, 7) 
					OR	CM.ORDER_TYPE_CODE LIKE '%137002%' AND CO.order_type IN (2) 
					OR  CM.ORDER_TYPE_CODE LIKE '%137003%' AND CO.order_type IN (3))   
        AND		(CA_CARD.CARD_SEQ IS NULL 
					OR	CA_CARD.CARD_SEQ IS NOT NULL 
					AND CA_CARD.CARD_ALLOW_YN = 'Y' 
					AND CO.card_seq = CA_CARD.CARD_SEQ 
					OR	CA_CARD.CARD_SEQ IS NOT NULL 
					AND CA_CARD.CARD_ALLOW_YN = 'N' 
					AND CO.card_seq <> CA_CARD.CARD_SEQ)   
        AND		ISNULL(CA_CARD_V2.CARD_ALLOW_YN, 'Y') = 'Y'  
        AND		(CO.sales_Gubun = 'SB' AND	CA_SITE.COMPANY_SEQ = 5001 
					OR  CO.sales_Gubun = 'SA' AND CA_SITE.COMPANY_SEQ = 5006 
					OR  CO.sales_Gubun = 'ST' AND CA_SITE.COMPANY_SEQ = 5007 
					OR	CO.sales_Gubun = 'SS' AND CA_SITE.COMPANY_SEQ = 5003 
					OR	CO.sales_Gubun IN ('B', 'C', 'H') AND CA_SITE.COMPANY_SEQ = 5000) 
		AND		(CM.EXPIRY_TYPE = 'A' OR	CM.EXPIRY_TYPE = 'P' 
					AND (CM.EXPIRY_START_DATE IS NULL	OR	CM.EXPIRY_START_DATE <= GETDATE()) 
					AND (CM.EXPIRY_END_DATE IS NULL		OR  CM.EXPIRY_END_DATE >= GETDATE()) 
				OR  CM.EXPIRY_TYPE = 'V' 
					AND CI.END_DATE >= GETDATE()) 
		AND		(CM.ORDER_AMT = 0	OR	CO.order_total_price >= CM.ORDER_AMT) 
		AND		(CM.ORDER_CNT = 0	OR	CO.order_count >= CM.ORDER_CNT) 
		AND		(CM.ORDER_APPLY_TYPE = 'ALL' OR	CM.ORDER_APPLY_TYPE = 'ORG' 
					AND CO.up_order_seq IS NULL OR  CM.ORDER_APPLY_TYPE = 'ADD' 
					AND CO.up_order_seq IS NOT NULL
				)  
        GROUP BY CO.order_seq, CI.COUPON_DETAIL_SEQ
	) AS COUPON  
  
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[40] 4[20] 2[20] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "COUPON"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 136
               Right = 413
            End
            DisplayFlags = 280
            TopColumn = 0
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VW_COUPON_CALC_FOR_CO'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=1 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VW_COUPON_CALC_FOR_CO'
GO
