IF OBJECT_ID (N'dbo.VW_User_QNA', N'V') IS NOT NULL DROP View dbo.VW_User_QNA
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/* 빠른손에서만 사용하는 고객QA*/    
CREATE VIEW [dbo].[VW_User_QNA]    
AS    
	SELECT 
		QNA_ID = QA_IID,
		COMPANY_SEQ = COMPANY_SEQ,
		SALES_GUBUN = SALES_GUBUN,
		ORDER_ID = ORDER_SEQ,    
		NAME = MEMBER_NAME,  
		USERID = MEMBER_ID, 
		EMAIL = E_MAIL,
		TITLE = Q_TITLE,    
		CONTENT = Q_CONTENT, 
		PHONE_NUMBER = TEL_NO,
		UPFILE_1 = ISNULL(USER_UPFILE1, ''),
		REGIST_DATETIME = REG_DT,    
		ANSWER_CONTENT = A_CONTENT,    
		ANSWER_DATETIME = A_DT,    
		ADMIN_NAME = A_ID,
		--ADMIN_NAME = (SELECT TOP 1 ADMIN_NAME FROM VW_ADMIN WHERE ADMIN_ID = A_ID ),
		ADMIN_UPFILE1 = ADMIN_UPFILE1,
		STAT = A_STAT
	FROM BAR_SHOP1.DBO.S2_USERQNA(NOLOCK)
	WHERE COMPANY_SEQ = 8070
		AND SALES_GUBUN = 'BM'

GO
