IF OBJECT_ID (N'dbo.VW_User', N'V') IS NOT NULL DROP View dbo.VW_User
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_User]
AS

-- -- SELECT *  FROM  BARUNSON.DBO.VW_USER WHERE USER_ID =  'VYRUDAKS12'
--  SELECT TOP 1 CODE_VALUE, CODE FROM BAR_SHOP1.DBO.MANAGE_CODE WHERE CODE_TYPE = 'SALES_GUBUN' AND USE_YORN = 'Y' AND CODE = 'ST'

 SELECT USER_ID, 
		PHONE_NUMBER = PHONE,
		NAME = UNAME,
		CELLPHONE_NUMBER = HPHONE, 
		CASE WHEN LEFT(WEDDING_DATE, 1) = '-' THEN '1900-01-01' ELSE WEDDING_DATE END WEDDING_DATE, 
		WEDDINGCARD_ORDER_YN = CASE WHEN ORDER_YN IS NULL THEN 'N' ELSE ORDER_YN END,
		JOIN_DATETIME = GETDATE(),
		EMAIL,
		REGIST_USER_ID ='',
		REGIST_DATETIME = REGIST_DATETIME,
		REGIST_IP = '',
		UPDATE_USER_ID = '',
		UPDATE_DATETIME = NULL,
		UPDATE_IP = NULL,
		DELETE_USER_ID = '',
		DELETE_DATETIME = NULL,
		DELETE_IP	 = '',
		DUPINFO,
		PWD,
		 -- M은 모바일초대장 사이트에서, 이외는 청첩장 사이트(바,비,더,프,몰)에서 가입한 회원
		REFERER_SALES_GUBUN = (
								SELECT CASE WHEN CODE = 'BM' THEN 'M' 
											WHEN CODE = 'SB' THEN '바' 
											WHEN CODE = 'SA' THEN '비' 
											WHEN CODE = 'ST' THEN '더' 
											WHEN CODE = 'SS' THEN '프' 
											WHEN CODE = 'B' THEN '몰' 
								ELSE '' END
								FROM (
										SELECT TOP 1 CODE FROM BAR_SHOP1.DBO.MANAGE_CODE 
										WHERE CODE_TYPE = 'SALES_GUBUN' 
											  AND USE_YORN = 'Y' 
											  AND CODE = REFERER_SALES_GUBUN
									 ) TB
								),
		--REFERER_SALES_GUBUN = (
		--						SELECT CASE WHEN CODE = 'BM' THEN 'M' ELSE  'F' END -- M은 모바일초대장 사이트에서, F는 청첩장 사이트에서 가입한 회원
		--						FROM (
		--								SELECT TOP 1 CODE FROM BAR_SHOP1.DBO.MANAGE_CODE 
		--								WHERE CODE_TYPE = 'SALES_GUBUN' AND 
		--									  USE_YORN = 'Y' AND 
		--									  CODE = REFERER_SALES_GUBUN
		--							 ) TB
		--					),
		MAX(CARD_CODE) CARD_CODE,
		--REFERER_SALES_GUBUN = (SELECT TOP 1 CODE FROM BAR_SHOP1.DBO.MANAGE_CODE WHERE CODE_TYPE = 'SALES_GUBUN' AND USE_YORN = 'Y' AND CODE = REFERER_SALES_GUBUN),
		CASE WHEN INTEGRATION_MEMBER_YORN IS NULL THEN 'N' ELSE INTEGRATION_MEMBER_YORN END INTEGRATION_MEMBER_YORN
 FROM
	 (
	   SELECT USER_ID = UID,
			  PHONE = PHONE1 + PHONE2 + PHONE3, 
			  UNAME = UNAME,
			  HPHONE = HAND_PHONE1 + HAND_PHONE2 + HAND_PHONE3,  
			  WEDDING_DATE = ISNULL(WEDD_YEAR, '') + '-' + RIGHT('0' + ISNULL(WEDD_MONTH, ''), 2) + '-' + RIGHT('0' + ISNULL(WEDD_DAY, ''), 2) + '-' + ISNULL(wedd_hour,'') + '-' +  ISNULL(wedd_minute,'') ,
			  EMAIL = UMAIL,
			  REGIST_DATETIME = REG_DATE,
			  DUPINFO = DUPINFO ,
			  PWD =  PWD,
			  REFERER_SALES_GUBUN = REFERER_SALES_GUBUN,
			  INTEGRATION_MEMBER_YORN = INTEGRATION_MEMBER_YORN
	   FROM BAR_SHOP1.DBO.S2_USERINFO_THECARD  U
	   WHERE SITE_DIV = 'ST' OR (UID = 'rany919' or UID = 'savagecat')
	    --WHERE SITE_DIV = 'ST'
    ) AS A 
	LEFT JOIN (
		SELECT MEMBER_ID, 
			CARD_CODE = B.CARD_CODE, 
			CASE WHEN COUNT(1) >= 0 THEN 'Y' ELSE 'N' END  AS ORDER_YN
		FROM BAR_SHOP1.DBO.CUSTOM_ORDER A INNER JOIN 
			 BAR_SHOP1.DBO.S2_CARD B ON A.CARD_SEQ = B.CARD_SEQ
		WHERE STATUS_SEQ > 9
		GROUP BY MEMBER_ID, B.CARD_CODE	
	) AS B
		ON A.USER_ID = B.MEMBER_ID

GROUP BY USER_ID, 
		PHONE,
		UNAME,
		HPHONE, 
		WEDDING_DATE, 
		EMAIL,
		REGIST_DATETIME,
		DUPINFO,
		PWD,
		REFERER_SALES_GUBUN,
		INTEGRATION_MEMBER_YORN,
		ORDER_YN

GO
