IF OBJECT_ID (N'dbo.FN_GET_EXPECTED_DELIVERY_DATE', N'FN') IS NOT NULL OR 
	OBJECT_ID (N'dbo.FN_GET_EXPECTED_DELIVERY_DATE', N'FS') IS NOT NULL OR 
	OBJECT_ID (N'dbo.FN_GET_EXPECTED_DELIVERY_DATE', N'FT') IS NOT NULL OR 
	OBJECT_ID (N'dbo.FN_GET_EXPECTED_DELIVERY_DATE', N'IF') IS NOT NULL OR 
	OBJECT_ID (N'dbo.FN_GET_EXPECTED_DELIVERY_DATE', N'TF') IS NOT NULL 
BEGIN
    DROP FUNCTION dbo.FN_GET_EXPECTED_DELIVERY_DATE
END
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*

SELECT  dbo.FN_GET_EXPECTED_DELIVERY_DATE(4132248)
up_select_expected_deliverydate_new_ 4132248
*/

CREATE FUNCTION [dbo].[FN_GET_EXPECTED_DELIVERY_DATE]    
(
	@order_seq INT
)
RETURNS VARCHAR(20)
AS        
BEGIN
	DECLARE @SendDateWEEKDAY VARCHAR(20)
	SELECT @SendDateWEEKDAY = SendDateWEEKDAY FROM dbo.FN_GET_Days_of_making_cards(@order_seq)

	RETURN @SendDateWEEKDAY
END



GO