IF OBJECT_ID (N'dbo.FN_CR_LF_TAB_SPACE_REMOVE', N'FN') IS NOT NULL OR 
	OBJECT_ID (N'dbo.FN_CR_LF_TAB_SPACE_REMOVE', N'FS') IS NOT NULL OR 
	OBJECT_ID (N'dbo.FN_CR_LF_TAB_SPACE_REMOVE', N'FT') IS NOT NULL OR 
	OBJECT_ID (N'dbo.FN_CR_LF_TAB_SPACE_REMOVE', N'IF') IS NOT NULL OR 
	OBJECT_ID (N'dbo.FN_CR_LF_TAB_SPACE_REMOVE', N'TF') IS NOT NULL 
BEGIN
    DROP FUNCTION dbo.FN_CR_LF_TAB_SPACE_REMOVE
END
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE  FUNCTION [dbo].[FN_CR_LF_TAB_SPACE_REMOVE] (@ARG VARCHAR(8000), @REMOVE_TAB_YORN AS CHAR(1) = 'N', @REMOVE_SPACE_YORN AS CHAR(1) = 'N')
RETURNS VARCHAR(8000)
AS
BEGIN 

DECLARE  @RESULT_VALUE VARCHAR(5000)

SET @RESULT_VALUE = @ARG

SET @RESULT_VALUE = REPLACE(@RESULT_VALUE, CHAR(13) + CHAR(10), '')
SET @RESULT_VALUE = REPLACE(REPLACE(@RESULT_VALUE, CHAR(10), ''), CHAR(13), '')


IF @REMOVE_TAB_YORN = 'Y'
BEGIN

    SET @RESULT_VALUE = REPLACE(@RESULT_VALUE, CHAR(9), '')

END

IF @REMOVE_SPACE_YORN = 'Y'
BEGIN

    SET @RESULT_VALUE = REPLACE(@RESULT_VALUE, ' ', '')

END

RETURN @RESULT_VALUE

END
GO
