IF OBJECT_ID (N'dbo.AFN_THREEPARTNAME', N'FN') IS NOT NULL OR 
	OBJECT_ID (N'dbo.AFN_THREEPARTNAME', N'FS') IS NOT NULL OR 
	OBJECT_ID (N'dbo.AFN_THREEPARTNAME', N'FT') IS NOT NULL OR 
	OBJECT_ID (N'dbo.AFN_THREEPARTNAME', N'IF') IS NOT NULL OR 
	OBJECT_ID (N'dbo.AFN_THREEPARTNAME', N'TF') IS NOT NULL 
BEGIN
    DROP FUNCTION dbo.AFN_THREEPARTNAME
END
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[AFN_THREEPARTNAME](

    @object_id INT,

    @database_id INT

)

RETURNS NVARCHAR(1000)

AS

BEGIN

    RETURN (QUOTENAME(DB_NAME(@database_id)) + '.'

          + QUOTENAME(OBJECT_SCHEMA_NAME(@object_id, @database_id))

          + '.' + QUOTENAME(OBJECT_NAME(@object_id, @database_id)));

END
GO
